### ISSUE TITLE
Custom formatter overwrite the existed

### ISSUE THREAD

**Issue by erguotou520** [kazupon/vue-i18n#100]

**Comment by kazupon** [comment]
You can use the `Vue.config. i18nFormatter`.
See [doc](https://kazupon.github.io/vue-i18n/formatting.html#registering-a-custom-formatter)
Please see together default format implementation. (sorry, poor formatting docs) ;)
https://github.com/kazupon/vue-i18n/blob/dev/src/format.js

**Comment by erguotou520** [comment]
I mean if I use `Vue.config.i18nFormatter` to custom a new formatter, the existed `list formatting` and `named formatting` will be overwrited. I think this api should be designed as a pipe or a middleware. I'm not sure if I described clearly?

**Comment by kazupon** [comment]
This feature is implemented with user.
https://github.com/kazupon/vue-i18n/commit/2748eb45704c4d055fb6241748cf04da1cf4c1c2

Certainly, As you pointed out, we should probably be designed with middleware. 🤔 
If you have a good idea, could you proposal to us  with concrete descriptions please?

**Comment by erguotou520** [comment]
I think the api should be like:
```
Vue.config.registeFormatter((text, next) => {
  // handle text replace or something else
  next(handledText)
})
```
or
```
Vue.i18n.customFormatter.pipe(function(text) => { return handledText }).pipe(() => {})
```
This is just my imagine.

**Comment by kazupon** [comment]
release v6.0.0
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0

**Comment by erguotou520** [comment]
Nice work!

**Comment by guyaumetremblay** [comment]
Hi @kazupon . Sorry to write on a closed issue but I don't find how v6 deliver this requested feature. I tried to implement a new formater as per the documentation but it still override the others. Thanks in advance!

**Comment by kevrousso** [comment]
Same issue here, still overwrites the others. I am left having to copy-paste the entirety of [format.js](https://github.com/kazupon/vue-i18n/blob/dev/src/format.js) and add my own conditions to the parse function which is not ideal.
