### ISSUE TITLE
Can I use with Vue 3 preview?

### ISSUE THREAD

**Issue by bakbuz** [kazupon/vue-i18n#1004]
Hello

I have a problem. How can I use with Vue 3 preview? Is support it?

Sincerely
Thanks

**Comment by exoego** [comment]
Yes, try https://github.com/intlify/vue-i18n-next which is going to be a next version of vue-i18n.

vue-i18n 8.x is not compatible with Vue 3.

**Comment by bakbuz** [comment]
> Yes, try https://github.com/intlify/vue-i18n-next which is going to be a next version of vue-i18n.
> 
> vue-i18n 8.x is not compatible with Vue 3.

That's worked. Thanks.
