### ISSUE TITLE
  There are no commands defined in the "vue-i18n" namespace.

### ISSUE THREAD

**Issue by shahidkarimi** [kazupon/vue-i18n#1014]
When I clone my app to another location on the same server, I am getting this error.
I cleared and cleaned the cache reinstalled dependencies multiple times but still no luck.
This seems to be a new issue that needs to be fixed.

**Comment by kazupon** [comment]
Could you provide minimum reproduction codes, please?

**Comment by kazupon** [comment]
close due to in-activity
