### ISSUE TITLE
Warnings for missing translation in the parent component test

### ISSUE THREAD

**Issue by alexandrastrekalova** [kazupon/vue-i18n#1016]
When testing a parent component some warnings are generated that translation for a key in the child component can not be found: `"Value of key 'logout' is not a string!"`

Here is what the component looks like:
```
<Dashboard>
  <PageWithHeader>
    {{ $t('logout') }}
  </PageWithHeader>
</Dashboard>

```

The translation for the key `logout` is defined in the PageWithHeader component.
Same warnings are thrown on the console when the Dashboard component is rendered. In the test for PageWithHeader no warnings are thrown. I can disable the warnings with `silentTranslationWarn: true` in the index.js, then there are no warnings in the browser console.

However, I don't know how I can disable them in the Dashboard.spec.js. Or may be there is a better option how to change the test setup, so that the parent component does not throw any warnings?

Here is the test setup portion for i18n:

```
import VueI18n from 'vue-i18n';
const localVue = createLocalVue();
localVue.use(VueI18n);

```
### vue & vue-i18n version
8.18.2

**Comment by kazupon** [comment]
Did you try to use `vue-i18n-jest`?
https://github.com/intlify/vue-i18n-jest

**Comment by kazupon** [comment]
close due to in-activity
