### ISSUE TITLE
$d 00:00:00 to 24:00:00

### ISSUE THREAD

**Issue by mengjianrong** [kazupon/vue-i18n#1022]
![image](https://user-images.githubusercontent.com/52148134/96562525-725d4480-12f3-11eb-9967-efee60df267f.png)
![image](https://user-images.githubusercontent.com/52148134/96562569-8012ca00-12f3-11eb-8d52-fd1c2552ab34.png)
![image](https://user-images.githubusercontent.com/52148134/96562626-8d2fb900-12f3-11eb-9266-4e61ef28bb7f.png)

我需要的是2020-12-12 00:00:00，而不是24:00:00，这个如何设置

**Comment by exoego** [comment]
Closing as issue description not satisfying our contribution guideline.

Could you follow the gudlines and reopen the issue?

> https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md#general-guidelines
> Thanks for understanding that English is used as a shared language in this repository. Maintainers do not use machine translation to avoid miscommunication due to error in translation. If description of issue / PR are written in non-English languages, those may be closed.

**Comment by dxyqqs** [comment]
@mengjianrong https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle
