### ISSUE TITLE
Component locales can't be translated by Vue.t

### ISSUE THREAD

**Issue by erguotou520** [kazupon/vue-i18n#103]
In the case of using locales in `filters`, the component locales can't be translated by `Vue.t` and in `filter` function the `this` variable is not the `vm`

**Comment by Tinoooo** [comment]
I have the exact same problem. I temporarily solved the problem by adding ``` Vue.prototype.t = Vue.t; ``` right after ```Vue.use(require('vue-i18n'));```

**Comment by kazupon** [comment]
In component translation, You can use `$t` vue instance method.

**Comment by erguotou520** [comment]
But in some case (like `filter`) it can't access the `vm`

**Comment by kazupon** [comment]
`Vue.t` is global function, I don't assume that it's used with filter.
Also, Vue will not support filter feature in the future.
I recommend that you avoid with using computed props.

**Comment by erguotou520** [comment]
`computed` props works well for certain variable, and it can't pass variables. So in `list computed` case, the filter is better I think.
