### ISSUE TITLE
String formatting - loop and condition

### ISSUE THREAD

**Issue by EitanYarimi** [kazupon/vue-i18n#1038]
Is there a way or will be in the future for list formatting can accept a list that i can manipulate or loop on?

for example a resource file that using handlesbar for templating:

i18n.translations.en = {
'MISSING_ERROR':
          'for which you have omitted to provide data.<br>' +
 "in period {{offsetAtPeriod}} {{#isEqual offsetAtAmort 'RESEC'}}resec step{{else}}step{{/isEqual}} {{offsetAtStep}}, " +
          'Traceback: {{#each callerVarsChain}}{{#unless @first}}→{{/unless}}{{this}}{{/each}}.',
}

**Comment by kazupon** [comment]
The message format syntax that can be handled by vue-i18n will not include the if or for statement syntax.
vue-i18n-next (vue-i18n@v9) will still use the current message format for the most same.
https://vue-i18n-next.intlify.dev/essentials/syntax.html 

In vue-i18n currently stable version, you can use message functions
https://kazupon.github.io/vue-i18n/guide/messages.html#message-function
