### ISSUE TITLE
Multilingual best practice for SAP?

### ISSUE THREAD

**Issue by JaxonDvl** [kazupon/vue-i18n#104]
Hello, I'm new to VueJS. I'm trying to make a SAP website with multilingual support. I'm using this helper plugin [Vue-I18n](https://github.com/kazupon/vue-i18n) . Based on this example [vue-i18n/example/locale/src/App.vue](https://github.com/kazupon/vue-i18n/blob/dev/example/locale/src/App.vue) works so far so good. However how can I extend this to have the language available to multiple components (pages)? Do I really need to use a store for this, from Vuex?

For example if I use it from another component I get this: `[Vue warn]: Property or method "langs" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`

Thanks.

**Comment by kazupon** [comment]
I recommend you use the component locale.
https://kazupon.github.io/vue-i18n/component.html

The component locales can compose reusable component for translation.

>[Vue warn]: Property or method "langs" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

Can you provide the repro codes (with jsfiddle or other ...) please?

**Comment by kazupon** [comment]
Close (in-activity)
