### ISSUE TITLE
Does this work for sites hosted through Github Pages (no backend)?

### ISSUE THREAD

**Issue by flamendless** [kazupon/vue-i18n#1040]

**Comment by exoego** [comment]
> Does this work for sites hosted through Github Pages (no backend)? #1040

Yes, I think `vue-i18n` can work without backend server.
Locale messages must be provided by any of 

- Hard-coded in JS
- Load static file (`.js` or `.json`) hosted on Github pages

**Comment by kazupon** [comment]
As Exoego Mentions.
vue-i18n can work without backend server.
