### ISSUE TITLE
Modifiers applied to linked global messages in components messages

### ISSUE THREAD

**Issue by ydarma** [kazupon/vue-i18n#1041]
Hi,
thank you for your work.

### vue & vue-i18n version
2.6.11, 8.22.1

### Steps to reproduce
First add global messages :
```javascript
const messages = {
  en: {
    global: { world: "World" }
  }
};

const i18n = new VueI18n({
  locale: "en",
  messages: messages
});

//...
```
Then in a component add component messages linked to global message :
```
i18n: {
    messages: {
      en: { greeting: "Hello @.lower:global.world" }
    }
  }
```

### What is Expected?
The `greeting` message should be `Hello world`

### What is actually happening?
console :
```
[Vue warn]: Error in render: "TypeError: str.toLocaleLowerCase is not a function"

found in

---> <PatientList>
       <BaseLayout> at src/layouts/BaseLayout.vue
         <PatientSearch> at src/views/PatientSearch.vue
           <App> at src/App.vue
             <Root>
```

### Workaround
Link to a local message that is itself linked to global message without modifier :
```
i18n: {
    messages: {
      en: { world:"@:global.world", greeting: "Hello @.lower:world" }
    }
  }
```

**Comment by kazupon** [comment]
The locale messages specified for a component will act as the local scope for that component. When you create a `new VueI18n` at the application entry point, the locale message becomes a global scope.

Currently, local scope locale messages handled by the component don't inherit from the global scope and be able to only referenced in the locale component.

**Comment by kazupon** [comment]
So, unfortunately, currently, your workaround is the way around. 😞
