### ISSUE TITLE
[Feature request] Lazy loading of translations from single file components

### ISSUE THREAD

**Issue by fungiboletus** [kazupon/vue-i18n#1043]
Hi,

It would be interesting to support lazy loading of translations from the <i18n> blocks in single file components.

Related: https://stackoverflow.com/questions/53327986/lazy-loading-translation-file-in-i18n-tag

**Comment by kazupon** [comment]
Thank you for your feedback!
For the i18n custom block is the role of a custom loader like vue-i18n-loader.
We already have the same issue in our repo, so we'll close it.
https://github.com/intlify/vue-i18n-loader/issues/59

Thanks
