### ISSUE TITLE
i18n reference to root causes memory leak 

### ISSUE THREAD

**Issue by lzxb** [kazupon/vue-i18n#1044]
### vue & vue-i18n version
ex: 2.6.12, 8.22.1

### Steps to reproduce
![image](https://user-images.githubusercontent.com/8424643/98672579-fa81b780-2390-11eb-9495-379a8b750127.png)

### What is Expected?
i18n.$root in root `beforeDestroy` hook remove it.
![image](https://user-images.githubusercontent.com/8424643/98672808-58160400-2391-11eb-9ba4-a911138e5f58.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/8424643/98672934-898ecf80-2391-11eb-826f-d9eac57a5fa9.png)

When the root instance is destroyed, the i18n object also keeps a reference to the root, which makes it impossible to be recycled by memory

**Comment by lzxb** [comment]
The existing architecture will lead to cross reference when multiple Vue root instances are used

**Comment by kazupon** [comment]
Thank you for your reporting!
good catch!
welcome contribution!

**Comment by kazupon** [comment]
close (release v8.24.2)
https://github.com/kazupon/vue-i18n/releases/tag/v8.24.2
