### ISSUE TITLE
Number format keys missing compared the Intl.Number object

### ISSUE THREAD

**Issue by jevillard** [kazupon/vue-i18n#1047]
### vue & vue-i18n version
ex: 2.6.12, 8.22.1

### Reproduction Link
https://jsfiddle.net/mdzf7npy/

### Steps to reproduce
Use `notation` or `compactDisplay` or `numberingSystem` or `signDisplay` or `unitDisplay` key when formatting a number
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

### What is Expected?
The number to be formatted

### What is actually happening?
The number is not formatted correctly.
The reason is that `notation` or `compactDisplay` or `numberingSystem` or `signDisplay` or `unitDisplay` is not included `numberFormatKeys` and thus the unit option is stripped

**Comment by kazupon** [comment]
close due to merged
