### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by chao921125** [kazupon/vue-i18n#1061]
### vue & vue-i18n version
ex: 3.0.3, 8.22.2

### What is actually happening?

This is my config

import { createApp } from "vue";
import VueI18n from "vue-i18n";
import store from "@/store";

const app = createApp({});

app.use(VueI18n);

const storeI18n = store.getters["i18n"];

function loadLocaleMessages() {
  const locales = require.context("./", true, /[A-Za-z0-9-_,\s]+\.json$/i);
  const messages = {};
  locales.keys().forEach((key) => {
    const matched = key.match(/([A-Za-z0-9-_]+)\./i);
    if (matched && matched.length > 1) {
      const locale = matched[1];
      messages[locale] = locales(key);
    }
  });
  return messages;
}

const i18n = new VueI18n({
  locale: storeI18n || "zh-cn",
  fallbackLocale: storeI18n || "zh-cn",
  messages: loadLocaleMessages(),
  missing: (locale, key, vm) => {
    console.error(locale, key, vm);
  },
});

app.use(i18n);

This is error info
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at extend (vue-i18n.esm.js?a925:221)
    at Function.install (vue-i18n.esm.js?a925:724)
    at Object.use (runtime-core.esm-bundler.js?5c40:2920)
    at eval (index.js?1a52:7)
    at Module../src/plugins/i18n/index.js (app.js:1181)
    at __webpack_require__ (app.js:859)
    at fn (app.js:151)
    at eval (main.js:20)
    at Module../src/main.js (app.js:1124)
    at __webpack_require__ (app.js:859)

**Comment by kazupon** [comment]
You need to use vue-i18n-next.
Please check this repo.
https://github.com/intlify/vue-i18n-next
