### ISSUE TITLE
Support Laravel placeholder

### ISSUE THREAD

**Issue by DasdWaller** [kazupon/vue-i18n#1090]
I share json files (`lang/*.json`) between laravel and vue. My problem is I need to share the same message with same placeholder but the deferent is the format and I don't want to make two different data inside the json file. 

Laravel [doc](https://laravel.com/docs/8.x/localization#replacing-parameters-in-translation-strings)
placeholder: `'welcome' => 'Welcome, :name'`

vue-i18n
placeholder:  `'welcome' => 'Welcome, {name}'`

**Comment by kazupon** [comment]
Unfortunately, vue-i18n's message format can't support all frameworks.
Currently, I am planning to create a framework-agnostic i18n library in the intlify project.

Thanks!
