### ISSUE TITLE
Dynamic generated new Component instance can't find <i18n />

### ISSUE THREAD

**Issue by rockmandash** [kazupon/vue-i18n#1091]
### vue & vue-i18n version
2.6.11, 8.22.2

### Reproduction Link
https://codesandbox.io/s/hopeful-vaughan-9wyn3?file=/src/main.js

### Steps to reproduce

```js
import Vue from "vue";

import VueI18n from "vue-i18n";

Vue.config.productionTip = false;

Vue.use(VueI18n);

const i18n = new VueI18n({
  locale: "en",

  messages: {
    en: {
      message: {
        helloFromParent: "Hello From Parent",
        helloFromChild: "Hello From Child"
      }
    }
  }
});

const Child = Vue.extend({
  render(h) {
    return h("div", null, this.$t("message.helloFromChild"));
  }
});

setTimeout(() => {
  const instance = new Child();
  instance.$mount();
  document.body.appendChild(instance.$el);
}, 3000);

new Vue({
  i18n,
  render(h) {
    return h("div", null, this.$t("message.helloFromParent"));
  }
}).$mount("#app");

```

### What is Expected?

Working normally.

### What is actually happening?

console warns

`[Vue warn]: Error in render: "TypeError: Cannot read property '_t' of undefined"`

`TypeError: Cannot read property '_t' of undefined`

**Comment by kazupon** [comment]
`VueI18n` instance isn't set to `Child`.
you need to set it to `Child`

thanks!
