### ISSUE TITLE
$d does not work in jest tests

### ISSUE THREAD

**Issue by Gwalchmei** [kazupon/vue-i18n#1095]
## Description

This issue may be related to `@testing-library/vue`, `@vue/test-utils` or `jest`.

The translations with `$t` works fine.
The date formatting with `$d` works in the browser.
The date formatting with `$d` does not work in my tests.

### vue & vue-i18n version
vue : 2.6.11
vue-i18n : 8.22.2
@testing-library/vue : 5.61
@vue/test-utils : 1.1.2

### Reproduction Link
https://github.com/Gwalchmei/vue-i18n-jest

### Steps to reproduce
- clone the repo
- install the deps
- `yarn test`

### What is Expected?
`$d(new Date(), 'long', 'fr')` should return a date formatted in french when used with the `fr` locale.

### What is actually happening?
The date is always formatted in english.

**Comment by exoego** [comment]
Which version of node.js was used in test?
I think French locale is not included in older versions of nodes.js.

**Comment by Gwalchmei** [comment]
I executed the tests with node v12.8.3. I executed the test with the docker image `node:latest` and it worked as expected.
