### ISSUE TITLE
Performance of mergeLocaleMessage

### ISSUE THREAD

**Issue by cslee** [kazupon/vue-i18n#1099]
https://github.com/kazupon/vue-i18n/blob/048eac57e9292533057f43bccb7de9648c487c3a/src/index.js#L615

@kazupon Could the line in `mergeLocaleMessage` above be changed to something like this for better performance? I use this method a lot in my components so this is quite important to me. Thank you so much.

```js
    this._vm.$set(this._vm.messages, locale, merge(
      typeof this._vm.messages[locale] !== 'undefined' && Object.keys(this._vm.messages[locale]).length
        ? this._vm.messages[locale]
        : {},
      message
    ))
```

**Comment by kazupon** [comment]
I've just released v8.22.4
You can check it :)
