### ISSUE TITLE
Load messages async

### ISSUE THREAD

**Issue by shahdivyesh** [kazupon/vue-i18n#1103]
I am trying to load messages using the endpoint. To do that I have implemented the following code. Screenshot below.
![image](https://user-images.githubusercontent.com/71421745/104611715-0b79ce00-564b-11eb-805a-45c0815d356f.png)
![image](https://user-images.githubusercontent.com/71421745/104611742-116faf00-564b-11eb-8912-bd0b213b5730.png)
![image](https://user-images.githubusercontent.com/71421745/104611753-15033600-564b-11eb-8b3c-060edd95fbf8.png)

I am getting the following error
![image](https://user-images.githubusercontent.com/71421745/104611770-1a608080-564b-11eb-9473-629da94ce5b7.png)

Any idea what could be causing translation to not loaded in "messages". The endpoint is good. I have validated that and confirmed data are coming back. I believe It's an issue with the promise.

**Comment by exoego** [comment]
This document may help.
It describes asynchronous loading translations.
https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

**Comment by kazupon** [comment]
From the error, it seems that the vue-i18n instance is not configured as a Vue instance and is running. As commented above, the docs may be helpful.

Thanks
