### ISSUE TITLE
Number localization with Custom formatting not working

### ISSUE THREAD

**Issue by sowinski** [kazupon/vue-i18n#1127]
### vue & vue-i18n version
ex: 2.6.12, 8.22.4

I copied this example from the docs and can't compile it. 
MyComponent.vue content:
```
<template>
  <i18n-n :value="100" format="currency">
    <span v-slot:integer="slotProps">{{ slotProps.integer }}</span>
  </i18n-n>
</template>
```
https://kazupon.github.io/vue-i18n/guide/number.html 

Is this a bug or do I miss something?
```
  Errors compiling template:

  v-slot can only be used on components or <template>.

  1  |  
  2  |  <i18n-n :value="100" format="currency">
  3  |    <span v-slot:integer="slotProps">{{ slotProps.integer }}</span>
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  4  |  </i18n-n>
  5  |  
```

**Comment by YosefMets** [comment]
@sowinski I have the same problem. Did you solve it or maybe get the answer?

**Comment by rchl** [comment]
Something like this should be a proper example:

```
<i18n-n :value="100" format="currency">
    <template #integer="slotProps"><span style="font-weight: bold;">{{ slotProps.integer }}</span></template>
</i18n-n>
```

**Comment by YosefMets** [comment]
@rchl thank you, it's smart but now it renders HTML tag only, without any number data
```
<i18n-n :value="100" format="currency" tag="div">
  <template v-slot:integer="slotProps"><span>{{ slotProps.integer }}</span></template>
</i18n-n>
```
renders:
`<div></div>`

Maybe you have any other ideas how to make it work?

**Comment by rchl** [comment]
Did you also correctly set up `numberFormats` as explained in https://kazupon.github.io/vue-i18n/guide/number.html ?

**Comment by YosefMets** [comment]
@rchl I don't know how to do that in Nuxt. I have i18n config file with [Nuxt i18n options](https://i18n.nuxtjs.org/options-reference) . I put `numberFormats` there but it has no effect. Do you know how to do it in Nuxt?

**Comment by rchl** [comment]
You have to put it inside the [vuei18n](https://i18n.nuxtjs.org/options-reference#vuei18n) object within the nuxt-i18n configuration.

**Comment by YosefMets** [comment]
It works, thank you!

**Comment by YosefMets** [comment]
Solved: [https://stackoverflow.com/a/68485249/13712756](https://stackoverflow.com/a/68485249/13712756)

**Comment by kazupon** [comment]
Close!
@rchl 
Thank you for your triage!

**Comment by rchl** [comment]
@kazupon  please fix the example as it's not correct currently. At least in Vue 2.

**Comment by kazupon** [comment]
@rchl 
I'll try to fix the example

**Comment by kazupon** [comment]
I've just updated docs
https://kazupon.github.io/vue-i18n/guide/number.html#custom-formatting
