### ISSUE TITLE
How to use vue-i18n outside of components

### ISSUE THREAD

**Issue by fairking** [kazupon/vue-i18n#1129]
Documentation says nothing. https://kazupon.github.io/vue-i18n/started.html

Please someone explain is there any way to use translations outside of vue components?

**app_menu.ts** (see `My Localized Label`):
```
export const app_menu = new Array<MenuItem>(
    new MenuItem("My Localized Label", icon: "fa fa-podcast" subitems: [ ... ]),
    ...
    ...
);
```
**App.vue**:
```
import { app_menu } from "./app_menu";

export default Vue.extend({
    data() {
        app_menu: app_menu,
    },
});
```

Would be nice to mention it in the documentation.

Thanks.

**Comment by fairking** [comment]
I found a solution.

I was thinking it must be something like this:
```
import Vue from "vue";

console.log(Vue.prototype.$t("My_Resource_Key"));
```

But I was wrong.

Because we have a separate script to load resources and create an instance of i18n:
**i18n.ts**:
```
import Vue from "vue";
import VueI18n, { LocaleMessages } from "vue-i18n";

Vue.use(VueI18n);

const vueI18n = new VueI18n({
	locale: (document ? document["CONFIG_LANG"] : null) || process.env.VUE_APP_I18N_LOCALE || "en",
	fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || "en",
	messages: loadLocaleMessages(), 
});

function loadLocaleMessages(): LocaleMessages {
	// you function to load messages
	return messages;
}

export default vueI18n;
```

We just use that i18n instance instead:
```
import i18n from "@/i18n/i18n";

console.log(i18n.t("My_Resource_Key"));
```

Closing the issue

**Comment by wwwjun** [comment]
> I found a solution.
> 
> I was thinking it must be something like this:
> 
> ```
> import Vue from "vue";
> 
> console.log(Vue.prototype.$t("My_Resource_Key"));
> ```
> 
> But I was wrong.
> 
> Because we have a separate script to load resources and create an instance of i18n: **i18n.ts**:
> 
> ```
> import Vue from "vue";
> import VueI18n, { LocaleMessages } from "vue-i18n";
> 
> Vue.use(VueI18n);
> 
> const vueI18n = new VueI18n({
> 	locale: (document ? document["CONFIG_LANG"] : null) || process.env.VUE_APP_I18N_LOCALE || "en",
> 	fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || "en",
> 	messages: loadLocaleMessages(), 
> });
> 
> function loadLocaleMessages(): LocaleMessages {
> 	// you function to load messages
> 	return messages;
> }
> 
> export default vueI18n;
> ```
> 
> We just use that i18n instance instead:
> 
> ```
> import i18n from "@/i18n/i18n";
> 
> console.log(i18n.t("My_Resource_Key"));
> ```
> 
> Closing the issue

Does not take effect when switching languages

**Comment by fairking** [comment]
> Does not take effect when switching languages

I am refreshing the entire page when user switches language. I cannot see a reason to do that in the existing instance. It makes things more complicated if you want to do that without the refresh.

There are many labels got applied everywhere as string variables, so the best way to update everything is to reload the Vue instance (refresh the page).
