### ISSUE TITLE
latest release?

### ISSUE THREAD

**Issue by steambap** [kazupon/vue-i18n#113]
The latest version (v6.0.0-alpha.2) has some defect with latest vue and probably should not be labeled as latest. Is it a mistake in publish?

**Comment by kazupon** [comment]
No, it is not mistake.
In v6.0.0 later, Use Vue 2.2.
By the time the development of v6 is completed, I think defect with vue latest version is fixed. 😉

**Comment by nikolajlovenhardt** [comment]
I think it was a mistake to label as latest
