### ISSUE TITLE
v9.0.0 running warnings

### ISSUE THREAD

**Issue by Hongbusi** [kazupon/vue-i18n#1130]
![V9 0 0](https://user-images.githubusercontent.com/53554371/109384375-3f713000-7927-11eb-9ed3-366a60f006f9.png)

Switch to previous version normal.

**Comment by eaglemoor** [comment]
https://unpkg.com/vue-i18n@9.0.0/dist/vue-i18n.js die
https://unpkg.com/vue-i18n@9.0.0/dist/vue-i18n.global.js available

nice kill millions site !

**Comment by eaglemoor** [comment]
@kazupon pl, fix this. Error P0

**Comment by eaglemoor** [comment]
@Hongbusi down to available version `v8+`

**Comment by kazupon** [comment]
Thanks feedback.
In about vue-i18n v9 installation,  you can check the [docs](https://vue-i18n.intlify.dev/installation.html)

Thanks!

**Comment by eaglemoor** [comment]
@kazupon before, you has link to https://unpkg.com/vue-i18n@9.0.0/dist/vue-i18n.js in docs. But now, link is die.
All who use this link down. New doc and new link don't resolve this problem.

Please, If u catch this problem in over project, just back link and update doc. Old link need to work. U understand how many people go to download vue-i18n to local path. How many need update in big project to downgrade vue-18n version. 
And how many people say "wow. vue-i18n down, and not up ep, we need find over stable library or copy it in out repo".
