### ISSUE TITLE
insert html span？

### ISSUE THREAD

**Issue by bestkj** [kazupon/vue-i18n#114]
"title": "Receive the value of <span>{money}</span> dollars gift",

{{ $t('title', { money: 750 }) }}

<style>
span { color: blue }
</style>

I want show 'money' color is blue, but above code show <span> text directly.

**Comment by bestkj** [comment]
I use v-html="$t('title', { money: 750 })" ,but style is not shwo

**Comment by kazupon** [comment]
Thank you for your filling.
Can you provide the reproduce minimum codes with Jsfiddle or other please?

**Comment by kazupon** [comment]
Close (inactivity, passed 5 days, and due to be able not to reproduce)

**Comment by SLMNBJ** [comment]
@kazupon I reopen it because I'm facing the same problem.
If styles are scoped, we lost the data-attribute.
https://codesandbox.io/s/8n2ly2k2w8.
