### ISSUE TITLE
Can't escape { } and # in messages

### ISSUE THREAD

**Issue by rytis-simplex** [kazupon/vue-i18n#1149]
Hi,

I can't find a way to escape such characters in translation messages like `{ } #`.

When I use them I get runtime errors telling that message failed to parse.

**Module versions:**
 - `vue`: 3.x
 - `vue-i18n`: 9.0.0

**To Reproduce**
For example such message ```Only Latin characters, numbers and symbols -/+\,.;'[]`=|<>?:"{}~!@#$%^&()_*§±``` gives me errors:

```
Message compilation error: Empty placeholder
1  |  Only Latin characters, numbers and symbols -/+\,.;'[]\`=|<>?:"{}~!@#$%^&()_*§±
   |                                                                 ^ 
Message compilation error: Invalid linked format
1  |  Only Latin characters, numbers and symbols -/+\,.;'[]\`=|<>?:"{}~!@#$%^&()_*§±
   |                                                                     ^
Message compilation error: Unexpected lexical analysis in token: '#$%^&()_*…'
1  |  Only Latin characters, numbers and symbols -/+\,.;'[]\`=|<>?:"{}~!@#$%^&()_*§±
   |                                                                    ^^^^^^^^^^^^ 
Message compilation error: Unexpected empty linked key
1  |  Only Latin characters, numbers and symbols -/+\,.;'[]\`=|<>?:"{}~!@#$%^&()_*§±
   |  
```

**Expected behavior**
Either such characters should be ignored or there would be a way to escape them

**Comment by kazupon** [comment]
This is vue-i18n v9 issue
so, move to target issue.

**Comment by kazupon** [comment]
For the special characters, You can avoid with `literal interpolation`
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

Thanks!

**Comment by SetarehSalehee** [comment]
As @kazupon said literal interpolation is the key so for "@~`!#%$^&*()[]-+={}/|:;“'<,>.?_\", have this in my vue-i18n translation files:
{'@'}{'~'}{'`'}{'!'}{'#'}{'%'}{'$'}{'^'}{'&'}{'*'}{'('}{')'}{'['}{']'}{'-'}{'+'}{'='}{'{'}{'}'}{'/'}{'|'}{':'}{';'}{'“'}{'’'}{'<'}{','}{'>'}{'.'}{'?'}{'_'}{'\\\\'})"
