### ISSUE TITLE
Translation scopes

### ISSUE THREAD

**Issue by r00takaspin** [kazupon/vue-i18n#116]
For example I have such code in my vue templates:
```html
<span  class="text-info float-right mt-1">
   {{ $t('components.documents.passport.autofill.enabled') }}
</span>
```
I would like access to translations by short path:
```
{{ $t('autofill.enabled') }}
```
Is it any scope option in vue-i18n?

**Comment by kazupon** [comment]
Thank you for your question!

In vue-i18n, not support short key path like i18n of Ruby on Rails.
We should use strictly key path.

**Comment by SzNagyMisu** [comment]
I opened #426 on a similar request.
