### ISSUE TITLE
Cannot read property '__disableEmitter' of undefined

### ISSUE THREAD

**Issue by shqyking** [kazupon/vue-i18n#1168]
First of all, I apologize that I cannot provide a reproduction link. I am not able to reproduce the issue without the complex setup of the project that I work on. I will try my best to describe the problem and hope someone can give me some hints or point some direction.

The issue happened when I use [Ant Design Vue Table](https://2x.antdv.com/components/table#API) component with the "slot" functionality. Inside the slot I put a component(let's call it **component A**) to render the content I want. So far so good. Then I click some button to go to a new page. Components of old page start to unmount, and I see the error below

```
Uncaught (in promise) TypeError: Cannot read property '__disableEmitter' of undefined
    at Proxy.beforeUnmount (vue-i18n.esm-bundler.js?47e2:1672)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?5c40:1934)
    at invokeArrayFns (shared.esm-bundler.js?6690:470)
    at unmountComponent (runtime-core.esm-bundler.js?5c40:4769)
    at unmount (runtime-core.esm-bundler.js?5c40:4679)
    at unmountChildren (runtime-core.esm-bundler.js?5c40:4809)
    at unmount (runtime-core.esm-bundler.js?5c40:4700)
    at unmountChildren (runtime-core.esm-bundler.js?5c40:4809)
```

The error stack trace shows it happens to beforeUnmount hook of the **component A** inside the slot. I tried to use different components to make sure it's not the problem of a specific component A. It turns out that no matter what component A is, the error always occurs. In addition, if I use native html element like `<div>` or `<label>`, no error occurs(this makes sense as those elements are not Vue components)

Looked at the complied vue-i18n file, "_vueI18n" is undefined, on line 1672 of screenshot attached. Maybe quick fix is to check "_vueI18n" before access its "__disableEmitter" property?

I suspect the root cause is something that I am even not aware of. At the moment, any help will be helpful. 

Stack trace: 
<img width="1705" alt="Screen Shot 2021-03-30 at 6 06 21 PM" src="https://user-images.githubusercontent.com/5377761/112976318-4d64db80-9187-11eb-8dde-b068e00d0d79.png">

Error position in complied vue-i18n file: 
<img width="1347" alt="Screen Shot 2021-03-30 at 5 53 47 PM" src="https://user-images.githubusercontent.com/5377761/112976427-708f8b00-9187-11eb-82e6-316f573c18af.png">

**Comment by kazupon** [comment]
Thank you for your reporting!
This is vue-i18n v9 issue, and this is the same issue.
https://github.com/intlify/vue-i18n-next/issues/412

Please, check it!
Thanks!

**Comment by gogoinga** [comment]
老哥，知道是什么原因引起了吗
