### ISSUE TITLE
Dependabot mixing this package dependencies with another

### ISSUE THREAD

**Issue by elirehema** [kazupon/vue-i18n#1177]
I have depandabot file in my organization vue [project](https://github.com/ospic/webapp/blob/master/package.json#L37).

In my package.json i have vue-i18n npm dependency which is currently at version 8.24.3 but unexpectedly the dependabot is trying to update this dependency with version of another dependency [vue-i18n-next](https://github.com/intlify/vue-i18n-next) version [ 9.4.1](https://github.com/ospic/webapp/pull/721)

I have also reported this to Github Support team.

**Comment by exoego** [comment]
https://github.com/intlify/vue-i18n-next is a next version (v9) of vue-i18n for Vue 3.
So it seems that dependabot is doing correct.

If you prefer stay in Vue 2 with vue-i18n v8.x, I suggest to configure dependabot so.
