### ISSUE TITLE
Cannot read property 'install' of undefined and warnings in console

### ISSUE THREAD

**Issue by olegatorruzumaki** [kazupon/vue-i18n#1183]
![image](https://user-images.githubusercontent.com/24682361/114892136-506df600-9e2e-11eb-9015-2dcc4f5916ba.png)

![image](https://user-images.githubusercontent.com/24682361/114892164-5663d700-9e2e-11eb-82fe-dc39ffd77d90.png)

hello installed i18n and it's doesn't work, what's going on? 

{
  "name": "identification",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@bachdgvn/vue-otp-input": "^1.0.8",
    "@popperjs/core": "^2.9.1",
    "axios": "^0.21.1",
    "bootstrap": "^5.0.0-beta2",
    "bootstrap-vue": "^2.21.2",
    "core-js": "^3.6.5",
    "graphql": "^15.5.0",
    "vue": "^2.6.12",
    "vue-i18n": "^9.1.5",
    "vue-router": "^3.5.1",
    "vue-the-mask": "^0.11.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-eslint": "^4.5.0",
    "@vue/cli-service": "^4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "sass": "^1.32.8",
    "sass-loader": "^10.1.1",
    "style-loader": "^2.0.0",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^4.46.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by kazupon** [comment]
Thank you for reporting!

Your project environment is Vue 2 base.
vue-i18n v9.x doesn't support Vue 2. that supports Vue 3 only.

You need to use vue-i18n v8.x (v8.x latest version v8.24.3)

Thanks!
