### ISSUE TITLE
Specifing a specific locale in $t

### ISSUE THREAD

**Issue by ibrahimBeladi** [kazupon/vue-i18n#1184]
I would like to ask if there is a way to specify the language used in $t function regardless of the current locale/language.
In other words, I want to show messages in language x without hard-coding the messages.
For example, `$t('some.message', { locale: 'en' })` would result in the English translation regardless of the current locale.

**Comment by kazupon** [comment]
you can use `locale` property of `$i18n`
please check detail docs: 
https://kazupon.github.io/vue-i18n/guide/locale.html

thanks

**Comment by ibrahimBeladi** [comment]
What I am asking is that I have the app with locale = a
I want to show one message with locale: b and another message with locale: c.
So, the messages are shown in locale b and c respectively, while the whole app is displayed as locale = a

**Comment by kazupon** [comment]
This is not the place to ask questions, Here is the bug & issue-reporting place.
You can ask about the question in the [Vue.js Discord](https://vue-land.js.org/).
Please understand.

Thanks

**Comment by codeflorist** [comment]
For anyone else coming accross this question:

Using the old package [kazupon/vue-i18n](https://github.com/kazupon/vue-i18n) the following should be possible:
```
$t(key, locale)
```
----------

When using the successor-package [intlify/vue-i18n-next](https://github.com/intlify/vue-i18n-next) , the answer depends on if you are using Vue I18n's **Legacy API** or the newer **Composition API**:

----------

Using **Legacy API** as described in the normal [setup guide](https://vue-i18n.intlify.dev/guide/) the usages of the `t()` function are stated [here](https://vue-i18n.intlify.dev/api/legacy.html#vuei18ntranslation).

This means you can still use the following call to translate a key to a specific locale (e.g. 'fr'):
```
$t(key, locale)
```
Example:
```
$t('message.key', 'fr')
```
----------

Using the **Composition API** by calling `createI18n()` with the option `legacy: false` (as described [here](https://vue-i18n.intlify.dev/guide/advanced/composition.html)), the usages of the `t()` function are different as stated [here](https://vue-i18n.intlify.dev/api/composition.html#composertranslation). You can no longer pass the locale-string as the second parameter, but the locale can be handed over inside a [`TranslateOptions` object](https://vue-i18n.intlify.dev/api/general.html#translateoptions). Unfortunately, there is no `t(key,TranslateOptions`) variant, but only the following variants:
```
$t(key, plural, TranslateOptions)
$t(key, defaultMsg, TranslateOptions)
$t(key, interpolations, TranslateOptions)
```
So the easiest solution would be e.g.:
```
$t('message.key', 1, { locale: 'fr' })
```
