### ISSUE TITLE
Memory leak caused by component switching

### ISSUE THREAD

**Issue by madguy** [kazupon/vue-i18n#1190]
日本人のプロジェクトを理解しており、英語のライティングがあまり堪能ではないため、伝わりやすいよう日本語で記述させていただきます。ご容赦ください。

**Module versions (please complete the following information):**
 - `vue`: 2.6.12
 - `vue-i18n`: 8.24.2

**Reproduction Link**
状況をわかりやすくするための仮想コードです。
動作しないコードで申し訳ないですが、子コンポーネントを切り替えるようなコードとご理解ください。
https://jsfiddle.net/72dnwcxm/

**To Reproduce**
1. i18nタグを含んだシングルファイルコンポーネントを作成
2. アプリ内でシングルファイルコンポーネントを読み込む
3. v-ifなどで繰り返し読み込むコンポーネントを切り替える

**Expected behavior**
メモリリークが発生する

**Additional context**
https://github.com/kazupon/vue-i18n/commit/ca4e11a9080bdde1b964f8a79c3e977c47782432
このコミットで追加された以下のコードで、子コンポーネントのインスタンス生成時にthis.$rootにイベントを登録するものの、$rootでbeforeDestroyが走らない状況において子コンポーネントの参照が残り続け、読み込んだコンポーネントがガベージコレクションの対象にならない問題が発生しているようです。
```
this.$root.$once('hook:beforeDestroy', () => {
  options.i18n.root = null;
  options.i18n.formatter = null;
  options.i18n.fallbackLocale = null;
  options.i18n.formatFallbackMessages = null;
  options.i18n.silentTranslationWarn = null;
  options.i18n.silentFallbackWarn = null;
  options.i18n.pluralizationRules = null;
  options.i18n.preserveDirectiveContent = null;
});
```

本来であれば修正pull requestを作成すべきだとは思うのですが、vue-i18nの全体像を把握しておらず、検証の時間も取れないためissueのみ作成させていただきます。よろしくお願いします。

**Comment by kazupon** [comment]
分かりやすい issue reporting ありがとうございました。
Thank you for your clear issue reporting.

この https://github.com/kazupon/vue-i18n/commit/ca4e11a9080bdde1b964f8a79c3e977c47782432 による、メモリリークを再現させて確認し、対応したいと思います。

**Comment by kazupon** [comment]
#1192でrevertしたので、closeします。
#1192 revert and close.
