### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by PeterAlfredLee** [kazupon/vue-i18n#1191]
**Module versions (please complete the following information):**
 - `vue`: 2.x
 - `vue-i18n`: 8.24.3

**Reproduction Link**
https://github.com/PeterAlfredLee/vue_i18n_issue

**To Reproduce**
1. Clone the project
2. yarn && yarn serve
3. Click `show` and `destroy` button 
4. Take memory snapshot, you can see there are more than one `VueComponent`

**Expected behavior**
It should be just one `VueComponent`, because other `VueComponent` should be destroyed.

**Additional context**
This issue is relate to #1151. After reverse #1151, everything works fine.
Also, I can't reproduce the leaking that #1044 describe.

**conclusion**
I think we should reverse #1151. WDYT?

**Comment by PeterAlfredLee** [comment]
x-special/nautilus-clipboard
copy
file:///home/csm/Desktop/leak.png

**Comment by PeterAlfredLee** [comment]
![leak](https://user-images.githubusercontent.com/55973914/115812639-434f9900-a424-11eb-9b5c-aecdd2843da8.png)

**Comment by kazupon** [comment]
@PeterAlfredLee 
Thank you for your reporting!
Related issue https://github.com/kazupon/vue-i18n/issues/1190 

We need to work around the memory leak in another way.

**Comment by PeterAlfredLee** [comment]
Hi @kazupon 

I'm not clear why #1151 fix cause the memory leak. I'm willing to push a fix but I don't got any ideas. Do you have any work around solutions?

On the other hand, I can't reproduce the problem in #1044. Could you reproduce that memory leak problem? Maybe we can revert the #1151 to fix this problem. WDYT?

**Comment by kazupon** [comment]
@PeterAlfredLee 
Thanks for your many and usual contributions.  ✨ 

>Do you have any work around solutions?

For the memory leak, unfortunately, I don't have a workaround idea at the moment due to the prototyping of intlify devtools and vue-i18n-next more improvements (e.g. more type safe). 😞 

now, I'm going to revert #1151 to avoid the current memory leaks issue.
