### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by LuckyBlade** [kazupon/vue-i18n#12]
Hello. Please, look at example code:

```
var locale = {
  en1:{
    msg1:"Test1",
    msg2:"Test2"
  },
  en2:{
    msg1:"Test1",
  }
}
```

Now, If I try to use $t('msg1') when lang is set to "en2" I'll see on screen "Test1". But  if I try to use $t('msg2')  I'll see "msg2". How can I set default lang, or what should I do, If I want to return default  lang value, when the value is absent in current lang?

**Comment by guillaumevincent** [comment]
maybe the api could be more friendly like :

    $t('msg2');
    $t('msg2', 'default value');

it's more declarative, can be extracted autocratically, and always display a value, even if an error occurred.

Love the api in the v2 of Intl in FormatJS by yahoo

https://github.com/yahoo/react-intl/issues/162

**Comment by nils-werner** [comment]
Don't other implementations usually work like

    $('This is the original message in the source code')

and translators then define

    var locale = {
      de: {
        "This is the original message in the source code": "Dies ist die Original-Nachricht im Quelltext"
      }
    }

If a translation cannot be found the original message will then be displayed instead.

**Comment by guillaumevincent** [comment]
@nils-werner an id is simpler. because of HTML formatting :

     {{{ $t('<a href="http://example.org/">link</a>') }}}

and because of the structure of the locale file

locale file become big, and I like to regroup translations per component

    $t('component.element');

example

    {{ $t('LoginBar.Sign_up', 'Sign up'); }}

```
var locale = {
  de: {
    LoginBar : {
        Sign_up: 'Anmelden'
    }
  },
  en: {
    LoginBar : {
        Sign_up: 'Sign up'
    }
  }
}
```

**Comment by mmochetti** [comment]
Hi @VegardSkui @guillaumevincent & @LuckyBlade.

I don't know if you already solved this, but there's a fallbackLang property as part of this package that can be set to the Vue.config object to fallback to a specific language.

So whenever bootstrapping your application besides setting the `Vue.config.lang`, also set `Vue.config.fallbackLang`.

e.g.: `Vue.config.fallbackLang = 'en1'`

That would solve your needs.

**Comment by do-web** [comment]
Is this now possible $t('msg2', 'default value'); ?

**Comment by chovy** [comment]
`Vue.config.fallbackLang = 'en'` doesn't seem to do anything. If I switch from en to ru I get the key instead of english.
