### ISSUE TITLE
HTML in params

### ISSUE THREAD

**Issue by alexcroox** [kazupon/vue-i18n#120]
I would like to reduce the amount of html in locale config and remove the maintenance nightmare if I need to modify the markup inside of it, across multiple languages.

Consider the following example:

    This is a test sentence which cannot 
    <a href="https://example.com" class="test-class test-another-class">be split</a> 
    or it will not make sense

The best solution I can come up with is:

    {
        "en": {
            "example": "This is a test sentence which cannot {linkOpen}be split{linkClose} or it will not make sense"
        }
    }

and then in the component template

    <p v-html="$t('example', { 
        'linkOpen': `<a href="https://example/com" class="test-class test-another-class">`,
        'linkClose: '</a>'
        }) 
    "></p>

However this does not work as it seems the $t params do not accept html

**Comment by zeev-kell** [comment]
+1

**Comment by kazupon** [comment]
related #37
I think that this feature can support component interpolation.
