### ISSUE TITLE
What Vue version does this plugin to support?

### ISSUE THREAD

**Issue by R-iskey** [kazupon/vue-i18n#123]
hy?

**Comment by Marsovski** [comment]
Try vue@2.1.10

**Comment by R-iskey** [comment]
@Marsovski Thank for your response, but In website I can't find any example with Webpack.

**Comment by kazupon** [comment]
@R-iskey 
In about it, @Marsovski said
Ref: https://github.com/kazupon/vue-i18n#warning-release-versions

In about webpack, vue-i18n don't depend webpack.
