### ISSUE TITLE
"Hello World" doesn't translate message

### ISSUE THREAD

**Issue by surferjeff** [kazupon/vue-i18n#1233]
I first asked for help in the vuejs forum, but no one replied.
https://forum.vuejs.org/t/trouble-setting-up-i18n/116371

I created a Hello World application:

```
vue create hello-i18n
cd hello-i18n
vue add i18n
```

Then I updated the code to display a translated message, but the message is still not translated.
Full code is here:

https://github.com/surferjeff/surferjeff.github.io/tree/master/hello-i18n

When I visit the app's home page, I expect to see "hello i18n !!",  but instead I see "message."

**Comment by kazupon** [comment]
Thank you for your reporting!

You can avoid it to remove the `default`.

https://github.com/surferjeff/surferjeff.github.io/blob/571d2eb913f5994704f9fb9e0ff77fd615e8aeaf/hello-i18n/src/i18n.ts#L13

```diff
-messages[locale] = locales(key).default
+messages[locale] = locales(key)
```

related issue 
https://github.com/intlify/vue-cli-plugin-i18n/commit/14bad4c2c84c282d36fca9b41db01cef3c94db81

**Comment by kazupon** [comment]
FYI: 
I've just released `vue-cli-plugin-i18n` latest version
https://github.com/intlify/vue-cli-plugin-i18n/releases/tag/v2.1.1

**Comment by surferjeff** [comment]
That fixed it.  Thank you!
