### ISSUE TITLE
`Uncaught (in promise) TypeError: Cannot set property '__VUE_I18N__' of null` on page refresh when using async setup

### ISSUE THREAD

**Issue by webnoob** [kazupon/vue-i18n#1234]
**Module versions (please complete the following information):**
 - `vue`: 3.0.11
 - `vue-i18n`: ^9.0.0-beta.0

**To Reproduce**
When I'm refreshing a page which has an `async setup ()` (composition API) and awaits a method returning a promise, I'm getting the following:

![image](https://user-images.githubusercontent.com/10404747/119242829-227c7f80-bb59-11eb-865a-ed5d7d97f2c4.png)

Pointing to:

```
if (((process.env.NODE_ENV !== 'production') || __VUE_I18N_PROD_DEVTOOLS__) && !false) {
                this.$el.__VUE_I18N__ = this.$i18n.__composer;
                const emitter = (this.__v_emitter = createEmitter());
                const _vueI18n = this.$i18n;
                _vueI18n.__enableEmitter && _vueI18n.__enableEmitter(emitter);
                emitter.on('*', addTimelineEvent);
            }
```
Navigating to the page via vue-router is working. It's only on refresh that I'm getting an error.

My setup:

MyComponent.ts (route: `/select-company`)
```
async setup () {
    const companyMod = companyModule()
    await companyMod.companyService.loadCompaniesForUser()
    return { ...companyMod }
}
```    
`loadCompaniesForUser()` looks like this:
```
async function loadCompaniesForUser () {
    companies.value = []
    setTimeout(() => {
      return Promise.resolve()
    }, 250)
}
```

**Comment by kazupon** [comment]
Thank you for your feedback.
Sorry, late my response.

Your issue is vue-i18n-next.
You can open at it!

Thanks!
