### ISSUE TITLE
Incompatibility with webpack UglifyJsPlugin

### ISSUE THREAD

**Issue by kilobyte2007** [kazupon/vue-i18n#124]
When using the **UglifyJsPlugin** while building for production,  I get the following error wherever I use $t in my .vue files:

`Error: Failed in $t due to not find VueI18n instance.`

It could be that uglifyjs is not compressing the file as it should be. Is there any solution for that, or am I missing something?

(it works perfectly without minification)

**Comment by h-collector** [comment]
It should be the same issue as #118

**Comment by kazupon** [comment]
Close (fixed [v6.0.0-alpha.5](https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0-alpha.5))

**Comment by kilobyte2007** [comment]
Thanks! Works for now!
