### ISSUE TITLE
Option to add data-attribute with message "name"

### ISSUE THREAD

**Issue by ugros** [kazupon/vue-i18n#127]
Hello,

I'm creating an app, that has an API that allows to configure messages. Problem is, that it's hard for the developer to know the "message code", e.g ('delivery_price', that is translated into "Price of delivery", etc.)

Would it be possible to add an option, that adds the data-attribute to every element that uses intl with $t function?

for example:
```
messages: { en: { delivery_price: "Price of delivery" } }
<span>{{ $t('price') }}</span>
```
would result in:

```<span data-language="price">Price of delivery</span>```

(For nested messages, the data attribute would be something like ``` "errors.fetching_error" ```

Thanks!

**Comment by kazupon** [comment]
Thank you for your feedback!

I seem it should be implement userland.
I think that it possible to use the custom directive and `$t` function.
