### ISSUE TITLE
$te() fails on some FF installations

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#129]
In various installations of Firefox, $te() does not work. Always renders false, even if it exists. Does not happen in every FF installation, most are ok. Chrome always ok.
Sadly, have not yet been able to pinpoint the exact issue, as I needed a client to send me screen photo's to eliminate. Client used FF 50.0 but if I install same version, for me it works. I also saw this same problem on a FF mobile installation, but that disappeared with latest upgrade.

So this does never render a list, no matter if `item.list.1` exists or not:

```html
<li v-if="$te('item.list.1')"> hello </li>
```

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you provide the reproduction code with jsfiddle or other please?

**Comment by tvld** [comment]
I only wish I could reproduce :( .... I've had it on two browsers: 1 on my own mobile FireFox but that was lost after i reinstalled. And once on a client's PC in another country at a large company where I don't have access...  Sorry I cant be of better assistance...

**Comment by kazupon** [comment]
Thanks!
okay, close.
Please open a new issue with a reference to this one if you can follow up with more information. 😉
