### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by aom** [kazupon/vue-i18n#130]
I suppose this a feature request just like any other.

Facebook's FlowType is supported using `decls/`. I'd like to see Typescript support. Two ways to accomplish this:

1) Add ie. `types/` folder with *d.ts* files
2) Add types to https://github.com/typings/typings so they can be added as *@types/vue-i18n* 

I'd prefer the first one as it's easier to maintain with other parts of the codebase.

Unfortunately I'm not fluent enough with Typescript yet to help much with contribution. However I got it working for me with this afternoon hack: https://github.com/aom/vue-i18n/tree/typescript-support

**Comment by aom** [comment]
Found one related discussion from StackOverflow which specifically uses this wonderful project as an example: http://stackoverflow.com/questions/42028790/vscode-and-vue-2-plugin-typescript-definitions

**Comment by aicest** [comment]
DefinitelyTyped/types/vue-i18n/index.d.ts
