### ISSUE TITLE
Custom modifiers are broken

### ISSUE THREAD

**Issue by Leemonn** [kazupon/vue-i18n#1308]
**Module versions (please complete the following information):**
 - `vue`: 2.4.2
 - `vue-i18n`: 8.24.5

**Reproduction Link**
https://stackblitz.com/edit/vue-i18n-6abnwm?file=plugins/i18n.js

**To Reproduce**
ex:
1. Use an integrated modifier like upper or capitalize.
2. See that it works
3. Add a custom modifier
4. Use the custom modifier instead of the integrated one.
5. See that the string is not working.

**Expected behavior**
If the custom modifier is declared then it should apply the modifier and it should show the string.

**Comment by Leemonn** [comment]
Bump

**Comment by DZ-study** [comment]
`modifiers: {
    snakeCase: (str) => str.split(' ').join('-')
  },
`
snakeCase转换成snakecase，又可以了。。

**Comment by olenitsj** [comment]
It is still broken, unfortunately.

**Comment by kazupon** [comment]
fixed with #1512
