### ISSUE TITLE
$te returns false if the key contains spaces

### ISSUE THREAD

**Issue by flavio-marchi** [kazupon/vue-i18n#1309]
**Module versions:**
 - `vue`: 2.6.10
 - `vue-i18n`: 7.3.2

**To Reproduce**
1. Have a translation setup (something like this):
`'Test translation': 'Test Übersetzung'`
2. Use `$te('Test translation')` to check for the key
3. It returns false

**Expected behavior**
It should return true, because there is a `'Test translation'` key. This does work like it should when there are no spaces in the key!

**Additional context**
- Everything else is working as intended, only the `$te` method doesn't work
- I don't have an english translation file, the keys I use itself are the english translation, which saves me the english translation, which is why I use spaces in the translation key.
- I would need this to work, because at the moment, when using the english translation, every one of my keys spits out an warning in the console (because there are no english translations) and I could prevent this by doing something like this in a reusable function:
```
const hasKey = this.$te(translationKey);
if (hasKey) {
    return this.$t(translationKey);
}
return translationKey; // english translation case, just use the text, dont even use i18n
```

**Comment by Liwoj** [comment]
btw version 7.3.2 is almost [4 years old](https://github.com/kazupon/vue-i18n/releases/tag/v7.3.2)!

**Comment by flavio-marchi** [comment]
@Liwoj Well its part of the template I'm using. I'll look into updating it.
