### ISSUE TITLE
'mounted' hook sometimes not called with vue-compat 

### ISSUE THREAD

**Issue by team-devops-caldera** [kazupon/vue-i18n#1320]
**Module versions:**
 - `vue`: 3.1.4
 - `@vue/compat`: 3.1.4
 - `vue-i18n`: 8.15.0

**Description**

I'm trying to migrate my Vue 2 app to Vue 3, and I would like to do this progressively using [@vue/compat](https://www.npmjs.com/package/@vue/compat). Here is a simple example app:

```javascript
import Vue, {configureCompat} from "@vue/compat";
import VueI18n from "vue-i18n";

// Enable retro-compatibility with Vue 2.
configureCompat({
	"MODE": 2
});

Vue.use(VueI18n);

Vue.component("Test", {
	"created": () => console.log("created"),
	"mounted": () => console.log("mounted"),
	"template": "<h1>{{ $t('TEST') }}</h1>"
});

new Vue({
	"el": "#app",
	"i18n": new VueI18n({
		"messages": {
			"en": {
				"TEST": "Test"
			}
		},
		"locale": "en"
	}),
	"template": "<test />"
});
```

Everything works as expected so far: the app is showing "Test", and both `created` and `mounted` hooks are called.
Now, if I modify the `Test` component to override some messages in that component:

```javascript
Vue.component("Test", {
	"created": () => console.log("created"),
	"mounted": () => console.log("mounted"),
        "i18n": {
            "messages": {
                "en": {
                    "TEST": "Hello world!"
                }
            }
        },
	"template": "<h1>{{ $t('TEST') }}</h1>"
});
```

Now it correctly shows "Hello world", but for a reason I ignore the `mounted` hook is not called anymore, only `created` is called. You can even try to set `i18n` to an empty object, `mounted` is not called either:

```javascript
Vue.component("Test", {
	"created": () => console.log("created"),
	"mounted": () => console.log("mounted"),
        "i18n": {},
	"template": "<h1>{{ $t('TEST') }}</h1>"
});
```

**Expected behavior**

App should show "Hello world!", and both `created` and `mounted` hooks should be called.

I'm stuck with this for days, any help would greatly be appreciated!

**Comment by kazupon** [comment]
Sorry, late my reply
`@vue/compat` core is Vue 3 base, so you need to use vue-i18n v9 with legacy mode.
vue i18n v9 legacy mode is vue-i18n v8.x compatible
please try to use it

thanks!

**Comment by jonathan-roy** [comment]
Thanks for the answer @kazupon, but actually `@vue/compat` is supposed to run in Vue 2 environment to help migrating to Vue 3 progressively. If we switch to `vue-i18n` v9, we would have the following code:

```javascript
import Vue, {configureCompat} from "@vue/compat";
import {createI18n} from "vue-i18n";

configureCompat({
	"MODE": 2
});

Vue.component("Test", {
	"created": () => console.error("created"),
	"mounted": () => console.error("mounted"),
	"template": "<h1>{{ $t('TEST') }}</h1>", 
	"i18n": {
		"messages": {
			"en": {
				"TEST": "Hello world!"
			}
		}
	}
});

new Vue({
	"el": "#app",
	"i18n": createI18n({
		"messages": {
			"en": {
				"TEST": "Test"
			}
		},
		"locale": "en"
	}),
	"template": "<test />"
});

```

Which gives a `$t is not a function` error since we should call `Vue.use(VueI18n);`, which does not seem to be possible with `vue-i18n` v9 (there is no such `VueI18n` anymore). How are we supposed to handle this?

**Comment by kazupon** [comment]
We are providing `vue-i18n-bridge` for vue 3 migration.
You can use it with vue-i18n v8
please try to use it!
https://vue-i18n.intlify.dev/guide/migration/ways.html

**Comment by jonathan-roy** [comment]
Thanks for your help.

Not sure how `vue-i18n-bridge` can work with `@vue/compat`... From the link you give we should use `@vue/composition-api` but that package is supposed to work with Vue 2, while `@vue/compat` is Vue 3 with Vue 2 "back ports":

> @vue/compat (aka "the migration build") is a build of Vue 3 that provides configurable Vue 2 compatible behavior.

If I try to use it anyway, I have a `[vue-composition-api] only works with Vue 2`. If I remove `@vue/composition-api` then I have a `[vue-composition-api] No vue dependency found` error.

```javascript
import Vue, {configureCompat} from "@vue/compat";
// import VueCompositionAPI from '@vue/composition-api'
import VueI18n from "vue-i18n";
import {createI18n} from "vue-i18n-bridge";

configureCompat({
	"MODE": 2
});

// Vue.use(VueCompositionAPI);
Vue.use(VueI18n, {"bridge": true});

const i18n = createI18n({
	"messages": {
		"en": {
			"TEST": "Test"
		}
	},
	"locale": "en"
}, VueI18n);

Vue.use(i18n);

Vue.component("Test", {
	"created": () => console.error("created"),
	"mounted": () => console.error("mounted"),
	"template": "<h1>{{ $t('TEST') }}</h1>",
});

new Vue({
	"el": "#app",
	"i18n": i18n,
	"template": "<test />"
});
```

**Comment by jonathan-roy** [comment]
The only way I got the `mounted` hook correctly fired is replacing the following:

```javascript
Vue.component("Test", {
	"i18n": {
		"TEST": "Hello world!"
	},
	"created": () => console.error("created"),
	"beforeMount": () => console.error("before mount"),
	"mounted": () => console.error("mounted"),
	"template": "<h1>{{ $t('TEST') }}</h1>",
});
```

by the following: 


```
Vue.component("Test", {
	beforeCreate() {
		this.$i18n.setLocaleMessage("en", {
			"TEST": "Hello world!"
		});
	},
	"created": () => console.error("created"),
	"beforeMount": () => console.error("before mount"),
	"mounted": () => console.error("mounted"),
	"template": "<h1>{{ $t('TEST') }}</h1>",
});
```
