### ISSUE TITLE
Documentation for version 5.x is not properly published

### ISSUE THREAD

**Issue by asmundwego** [kazupon/vue-i18n#133]
### vue-i18n version
v5.x

### Reproduction Link
http://kazupon.github.io/vue-i18n/old/

### Steps to reproduce
Click on a link in the documentation overview page

### What is Expected?
Published documentation should be shown in same window

### What is actually happening?
New window is opened with the documentation source in gitbook instead of published documentation.

### Reclaimer
I know this is not latest version, but it is the latest stable version, so the documentation should be published properly.

**Comment by kazupon** [comment]
Thank you for you filling!

Sorry, late for reply.
Released v6.0.0

AFAIK, Gitbook can not host multi version. 😞 
I'll plan to switch to other from gitbook docs.
