### ISSUE TITLE
[5.0.3] locale message objects don't translate sometimes when property is number

### ISSUE THREAD

**Issue by dapperdanman1400** [kazupon/vue-i18n#134]
In version 5.0.3, when using `Vue.locale` and putting in an object of message strings for the 2nd parameter, if the first level property is a number and there are nested children messages, those messages don't get translated with the `$t` function.
```javascript
// script
var phrases = {
    123: {
    	message: 'This message does not work.'
    }
}
Vue.config.lang = 'en'
Vue.locale('en', phrases)

// html
{{$t('123.message')}}
// 123.message
```

However, properties that are a number but have no child objects (ie: the property is for the terminating message); or properties that contain nested numbers, but the parent property is not a number, do render correctly.
```javascript
// script
var phrases = {
    parent: {
    	123: {
    	    message: 'This message does work.'
       }
    },
    456: 'This also works.'
}
Vue.config.lang = 'en'
Vue.locale('en', phrases)

// html
{{$t('parent.123.message')}}<br />{{$t('456')}}
// This message does work.
// This also works.
```

For details, I set up [this fiddle](http://jsfiddle.net/vjvMp/1373/).

**Comment by kazupon** [comment]
Thank you for your filling!

locale message objects don't support number based property.
Please use the string based property.
