### ISSUE TITLE
When vue3.0 uses vuE-i18n on the server, the Content Security Policy is not met. When we set the Content Security Policy on Nginx, the error is reported and the page cannot be loaded  

### ISSUE THREAD

**Issue by Yaojie1** [kazupon/vue-i18n#1356]
- "vue": "^3.0.5",
 - `vue-i18n`: 9.2.0-beta
 - "typescript": "^4.3.2",
 -"vite": "^2.4.4",
 - "vue-tsc": "^0.2.2"
 - Content-Security-Policy: default-src 'self'; connect-src *; script-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self'; child-src 'self'; object-src 'none'; frame-ancestors 'none'
 -Console error：vendor.6e624922.js:1 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

When vue3.0 uses vuE-i18n on the server, the Content Security Policy is not met. When we set the Content Security Policy on Nginx, the error is reported and the page cannot be loaded  
![Uploading 1627968675.jpg…]()

**Comment by kazupon** [comment]
@Yaojie1 
Sorry for the late reply.

As for the CSP, it is generated to compile the message resources from vue-i18n@v9.x into javascript and then `new Function`.

To workaround this problem, you need to use the bundle tools published by the intlify project for bundlers like vite and webpack.

https://github.com/intlify/bundle-tools

about reason, see here
https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#i18n-resources-pre-compilation

By using bundle tools, the `new Function` is not needed in the inner part, since it will be bundled with the bundler in those tools. Also, the compiler of vue-i18n is not needed when it's distributed, so the code size can be optimized.

about details, see here
https://vue-i18n.intlify.dev/guide/advanced/optimization.html

Thanks!

**Comment by owlyowl** [comment]
Hi @kazupon 
Sorry I'm running into the same issue when trying to compile out in webpack i18n fails CSP because it is generating a new function:

```
__INTLIFY_PROD_DEVTOOLS__&&sm(I,t,O),I}function Pm(e,t,n,r,o){const{missing:s,onWarn:i}=e;if(null!==s){const r=s(e,n,t,o);return Qd(r)?r:t}return t}function Dm(e,t,n){const r=e;r.__localeChainCache=new Map,e.localeFallbacker(e,n,t)}const Mm=e=>e;let Fm=Object.create(null);function jm(e,t={}){{const n=t.onCacheKey||Mm,r=n(e),o=Fm[r];if(o)return o;let s=!1;const i=t.onError||ap;t.onError=e=>{s=!0,i(e)};const{code:a}=Mp(e,t),l=new Function(`return ${a}`)();return s?l:Fm[r]=l}}
```

I couldn't find a version of `@intlify/unplugin-vue-i18n` that works with my `package.json` set. I was wondering if you had any suggestions please?

```
 "dependencies": {
        "core-js": "^3.8.3",
        "raygun4js": "^3.0.1",
        "style-resources-loader": "^1.5.0",
        "uuid": "^9.0.0",
        "vue": "^3.2.13",
        "vue-class-component": "^8.0.0-0",
        "vue-i18n": "^9.2.2",
        "vue-property-decorator": "^10.0.0-rc.3",
        "vuex": "^4.0.0",
        "vuex-module-decorators": "^2.0.0"
    },
    "devDependencies": {
        "@intlify/vue-i18n-loader": "^4.2.0",
        "@types/grecaptcha": "^3.0.7",
        "@types/node": "^18.11.18",
        "@types/raygun4js": "^3.0.0",
        "@types/uuid": "^9.0.0",
        "@typescript-eslint/eslint-plugin": "^5.50.0",
        "@typescript-eslint/parser": "^5.50.0",
        "@vue/cli-plugin-babel": "~5.0.0",
        "@vue/cli-plugin-eslint": "~5.0.8",
        "@vue/cli-plugin-typescript": "~5.0.0",
        "@vue/cli-plugin-vuex": "~5.0.0",
        "@vue/cli-service": "~5.0.0",
        "@vue/eslint-config-standard": "^8.0.1",
        "@vue/eslint-config-typescript": "^11.0.2",
        "aws-sdk": "^2.1308.0",
        "cross-env": "^7.0.3",
        "eslint": "^8.33.0",
        "eslint-config-prettier": "^8.6.0",
        "eslint-plugin-eslint-comments": "^3.2.0",
        "eslint-plugin-import": "^2.27.5",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-promise": "^6.1.1",
        "eslint-plugin-vue": "^9.9.0",
        "pretty-hrtime": "^1.0.3",
        "rimraf": "^4.1.2",
        "sass": "^1.32.7",
        "sass-loader": "^12.0.0",
        "typescript": "~4.5.5",
        "vue-i18n-loader": "^0.1.1"
    }
```
