### ISSUE TITLE
Vue.config error

### ISSUE THREAD

**Issue by Homebrew1** [kazupon/vue-i18n#1357]
**Reporting a bug?**
 vue-i18n.esm.js?a925:1319 Uncaught TypeError: Cannot read property 'config' of undefined
    at VueI18n._initVM (vue-i18n.esm.js?a925:1319)
    at new VueI18n (vue-i18n.esm.js?a925:1258)
    at eval (main.js?56d7:35)
    at Module../src/main.js (app.js:3277)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at Object.1 (app.js:3722)
    at __webpack_require__ (app.js:854)
    at checkDeferredModules (app.js:46)
    at app.js:994
 the specific version you are using.
.github/CONTRIBUTING.md
 - If your issue is resolved but still open, don’t hesitate to close it. In case you found a solution by yourself, it could be helpful to explain how you fixed it.

**Module versions (please complete the following information):**
 - `vue`: 2.6.10
 - `vue-i18n`: 8.25.0

**Reproduction Link**
A minimal JSBin, JSFiddle, Codepen, CodeSandbox, or a GitHub reprository that can reproduce the bug.

You can use reproduction jsfiddle template: https://jsfiddle.net/kazupon/rn724baz/3/

**To Reproduce**
ex:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Homebrew1** [comment]
![image](https://user-images.githubusercontent.com/50045583/128316457-12dee8c2-c582-48ef-b987-d3279067c171.png)

**Comment by Homebrew1** [comment]
![image](https://user-images.githubusercontent.com/50045583/128316937-aeb542af-4c68-420f-ae38-421d14d8a923.png)

**Comment by kazupon** [comment]
Thank you for your reporting!

I seem you don't have vue-i18n installed in your project with `Vue.use`.
Could you check your project about it, please?

**Comment by kazupon** [comment]
Close due to in-activity
If you have still an issue, please you would be possible open as a new issue.

Thanks!
