### ISSUE TITLE
simple email `@` trigger error Invalid linked format 

### ISSUE THREAD

**Issue by nusson** [kazupon/vue-i18n#1358]
**Reporting a bug?**

I believe there is some side effect for the linked message where a simple @ will trigger linked message routine (but should only be within `@:`)

**Module versions (please complete the following information):**
 - `vue`: ^3.0.5
 - `vue-i18n`: ^9.1.7
 - `@kazupon/vue-i18n-loader`: ^0.5.0

**Reproduction Link**

> (do you have a fiddle that works with vue3 and v9 ?)

**To Reproduce**

- add some email within a translation message eg  '{mail_us: `write us: contact@acme.org'}`
- then use this key within vue-i18n `<a :title="$t('mail_us')">some link</a>`

then I got tons of error in console - many occurence of the same error :

```
core-base.esm-bundler.js:700 Message compilation error: Invalid linked format
1  |  write us: contact@acme.org
```

... ultimatly the translation does work ;)

**Expected behavior**

Should not check about linked message and just output translation normaly since it a singe `@` and not `@:`

**Comment by kazupon** [comment]
Thank you for your reporting!
In from vue-i18n@v9.x, `@` is a special character.
You need to use the literal interpolation
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

your case:
```
`contact{'@'}acme.org`
```

Thanks!
