### ISSUE TITLE
Invalid linked format 1

### ISSUE THREAD

**Issue by kyrylo93** [kazupon/vue-i18n#1373]
Hi!

Somehow I got an error, the error only occurred for such string:
`"TITLE": "Manage the {0} in the course. When inviting, use email addresses of your school, such as name@name-school.nl.
",`
<img width="442" alt="Screenshot 2021-08-23 at 11 39 50" src="https://user-images.githubusercontent.com/43705245/130417294-0b7fa722-d62d-41ef-9765-1d35c2816cfd.png">
Currently I use:
"vue-i18n": "^9.2.0-beta.1",
"vue": "^3.1.5",

Again, it's the issue just for this string.
Maybe the lexical analysis reads name@name as a local message modifier, idk.

If pass name@name-school.nl as a prop, no error occurred.

**Comment by kazupon** [comment]
`@` is the special character at vue-i18n@v9.x
You can use the literal characters.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

Thanks!
