### ISSUE TITLE
Feature Request: Fallback Locale as array for cascading fallbacks.

### ISSUE THREAD

**Issue by nchutchind** [kazupon/vue-i18n#138]
It would be nice to be able to specify fallback locale as an array that could cascade when falling back. For example, if someone selects "Canadian French" as their current locale, it would be nice to have a fallback locale of "French" and then an ultimate fallback of "English." This would be helpful for any locale that has sub-locales.

**Comment by martinhbramwell** [comment]
Other i18n packages offer "ultimate" fall backs directly with the text such as : 
```javascript
<span>{{ $t('label.signup', 'Sign Up') }}</span>
```

Does vue-i18n have no such capability?  I don't see how to do it, but I certainly believe it's necessary.

**Comment by nelson6e65** [comment]
@martinhbramwell I sometimes the string as the key, that could be useful for you if you need a "ultimate" fallback:

```vue
<span>{{ $t('Sign Up') }}</span>
```

And then, setup your fallback to (Spanish in this example):

```js
const i18n = new VueI18n({
  locale: 'es-VE',
  fallbackLocale: 'es',
  messages: { }
})
```

But, could be useful if the @nchutchind suggestion is implemented. :100:

**Comment by drorweissweiss** [comment]
This feature seems trivial when handling locale, I guess @kazupon originally intended this project to support only languages.

@nchutchind , did you perhaps manage to solve this yourself somehow?

**Comment by nchutchind** [comment]
@drorweissweiss No, I did not put much more effort into it. I just noticed that it wasn't supported and figured I'd bring it up.

**Comment by martinhbramwell** [comment]
In my opinion, fallbacks are obligatory for any package that wants to use I18N in its name.  I appreciate the point @nelson6e65 makes, but @nchutchind is right in his original request, that easy automatic fall back from dialect, to major language, to English is essential.

**Comment by nelson6e65** [comment]
Yes. I think auto-fallback are necessary, @martinhbramwell. If `locale: 'es_VE'`, it should auto-fallback to `es` and then pass to the `fallbackLocale` in the same way. **And**, as ultimate, to the `en`.

**Comment by alexcarruthers** [comment]
What's the status of this idea? It would be very useful. Especially if we have per-language translation strings and want to add per-locale date formatting.

**Comment by louisameline** [comment]
I also think this feature is a must have. Nobody gave an actual example, so I figure it would be like this:

```
fallbackLocale: {
  'fr-ca': ['fr-fr', 'en-us'],
  'fr-fr': ['en-us'],
  'en-gb': ['en-us']
}
```

As a side note, another solution would be:
- if `en`, `fr` and `fr-ca` messages are provided
- and if `en` is the default fallback
- and if a `fr-ca` key is missing
- then i18n must check `fr` before `en`

But if `fallbackLocale` can be an array it already solves the situation, this second solution is just a nice-to-have. And as it implies that there would be a "default" version of a language and local variations, I'm not sure I like it very much from a cultural point of view :p

This is all described here: https://www.i18next.com/principles/fallback

**Comment by exoego** [comment]
Thanks @louisameline 
1st suggestion in your comment helped me a lot to understand use cases.
It totally make sense to have such feature for languages that have many locales.

It would be happy if `vue-i18n` users understand kazupon, the vue-i18n creator, is currently very busy on productivity toolset around `vue-i18n` and also organizing huge Vue conference in Japan.
I (collaborator) also have very limited time nowadays, but am happy to review and merge if someone opened a pull request 🙏 

I think `vue-i18n` is well architected and have great test suite, so you can smoothly dive into code base and implement feature with confidence (no breaking change), as same as me last year.

**Comment by louisameline** [comment]
@exoego I thought some more about this and amended my previous message with a more definitive wrap-up of the subject. As you'll see, there are actually 3 layers of improvement that don't need to be done at the same time.

It would actually be fun to code, but I don't know when I'll have time for this, so I'm not making any promises. Thank you very much

**Comment by nelson6e65** [comment]
> Spanish-speaking to fall back to `en-gb` before falling back `en` messages.

I think this should be implicit, instead of explicit. I mean... you should only need one fallback.

If you set your locale to `es-ve` and your fallback to `en-gb`, It should be resolved to `es-ve` *locale* and then search in `es` *langguage*. If not available, use your fallback *locale* `en-gb`, that shall reach the `en` *language*.

----
I would like enjoy learning how can I help to this issue, but... I have not time right now. 😭

**Comment by louisameline** [comment]
@nelson6e65 Yes that's what I have in mind too. I reformulated the sentence in case it wasn't clear enough.

**Comment by KBOE2** [comment]
I would really love to see this feature soon.

**Comment by kazupon** [comment]
close, due to release v8.17.0

**Comment by kazupon** [comment]
See the `fallback` section docs:
https://kazupon.github.io/vue-i18n/guide/fallback.html#fallback-localization

**Comment by louisameline** [comment]
Awesome, thank you very much !

**Comment by nelson6e65** [comment]
🎉 Amazing!
