### ISSUE TITLE
can't load messages from json file with property name as "var"

### ISSUE THREAD

**Issue by coader** [kazupon/vue-i18n#1398]
{
"var":123
}

change to var2 is ok

**Comment by kazupon** [comment]
Sorry, my late response.

But, Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin or CodeSandbox containing a set of reproducible steps that can lead to the behavior you described.

Thanks!
