### ISSUE TITLE
Bower vue-i18n^5.0.3 downloads vue-i18n^6.0.0-alpha-1

### ISSUE THREAD

**Issue by gildas** [kazupon/vue-i18n#140]
Since the release of Vue I18n 6.0.0 a few days ago, bower does not seem to be able to get the proper version 5 when requested.

**Comment by gildas** [comment]
And that is because the tag 5.0.3 points to 6.0.0-alpha-1 code:

https://github.com/kazupon/vue-i18n/blob/v5.0.3/dist/vue-i18n.js

**Comment by kazupon** [comment]
sorry, vue-i18n don't support bower.
see the 5.x installation docs:
https://github.com/kazupon/vue-i18n/blob/5.x/gitbook/installation.md
