### ISSUE TITLE
throw an error with Vue.use(VueI18n) Cannot read properties of undefined (reading 'install')

### ISSUE THREAD

**Issue by Benjaminbai** [kazupon/vue-i18n#1401]
1. npm i vue-i18n
2. import VueI18n from 'vue-i18n'
3. Vue.use(VueI18n)

<img width="547" alt="Snipaste_2021-10-08_17-06-06" src="https://user-images.githubusercontent.com/23426556/136530247-c1c16350-cf72-4c24-a88d-b524e2c4eb53.png">
<img width="497" alt="Snipaste_2021-10-08_17-06-51" src="https://user-images.githubusercontent.com/23426556/136530265-94d2464c-a339-4257-a4f0-1dcd0753eebf.png">

**Comment by chocoford** [comment]
+1
same as the question I post in [Stackoverflow](https://stackoverflow.com/questions/69491378/how-to-use-vuei18n-with-typescript-and-vue2-0-new-vuei18n-report-h)

**Comment by Benjaminbai** [comment]
> +1 same as the question I post in [Stackoverflow](https://stackoverflow.com/questions/69491378/how-to-use-vuei18n-with-typescript-and-vue2-0-new-vuei18n-report-h)

I have fixed this issue, the latest vue-i18n version is based on vue3+, if you project built by vue2.0+, pls use lower i18n version,and try it again

**Comment by kazupon** [comment]
Sorry, I made a mistake in typing the tag and set vue-i18n for Vue 3 to latest.
So, you are most likely installing vue-i18n for Vue 3.
I’ve just set `latest` tag vue-i18n for Vue 2.
Please try installing `npm install vue-i18n@latest` again.

**Comment by kazupon** [comment]
Close so in-activity.
if you have an issue, please you would be possible open a new issue.

Thanks!

**Comment by ctq123** [comment]
vue-i18n@9+ will throw this error

**Comment by Enzo-Parodi** [comment]
Same here. vue-i18n@9+ with Vue 3 is undefined.

It only worked onceI imported it like this: `import VueI18n from "vue-i18n/dist/vue-i18n.cjs";`
