### ISSUE TITLE
Casing sensitive path (kebab case)

### ISSUE THREAD

**Issue by Jeromearsene** [kazupon/vue-i18n#1403]
## Module versions
 - `vue`: 2.6.14
 - `vue-i18n`: 8.26.1

## Reproduction Link
Sorry but it is too complicated to replicated folder structure.

## To Reproduce

1. Have a structure like this:
![Capture d’écran 2021-10-14 à 15 15 32](https://user-images.githubusercontent.com/9333686/137324664-ae637e17-4ba4-4b91-910e-20fec99e9fa9.png)

2. In `add-data.json`, have this:
```json
{
  "instructions1": "Glissez-Déposez votre fichier ici",
}
```

3. Try to use translation like this:
```javascript
$t('add-data.instructions1')
```

## Expected behavior
Preserve **kebab-case** and not write in **camelCase** like this:
```javascript
$t('addData.instructions1')
```

It is possible to preserve **kebab-case** style ?

Thanks

**Comment by kazupon** [comment]
Thank you for your reporting!

The file name of the resource for which the locale messages is defined cannot be used as the key.
The key you specify for `$t` is the key defined in the locale messages resource imported with JS `import` syntax (or `require` in commonjs).

Thanks!
