### ISSUE TITLE
$d hours in exceed 23 when hour12: false

### ISSUE THREAD

**Issue by arnovanoordt** [kazupon/vue-i18n#1405]
In 24-hour notation, when using $d with a time between (00:00 and 01:00) the displayed hours exceed 23:
`{{ $d(new Date('2022-09-13T00:52'), 'dateTime') }}` Outputs: "Tue, Sep 13, 2022, 24:52" // wrong, should say `00:52`
`{{ $d(new Date('2022-09-13T01:52'), 'dateTime') }}` Outputs: "Tue, Sep 13, 2022, 01:52" // correct

Using just new Date to string as output seems fine:
`{{ new Date('2022-09-13T00:52') }}` Output: "Tue Sep 13 2022 00:12:00 GMT+0200 (Central European Summer Time)"
 
My dateformat is as follows: 
```
    dateTime: {
         year: 'numeric', month: 'short', day: 'numeric',
         weekday: 'short', hour: 'numeric', minute: 'numeric', hour12: false,
    },
```

Using the 12-hour notation everything works correctly and it says (as it should) `12:##am`, but in the 24-hour notation `24:##` should be written as `00:##`
See also https://en.wikipedia.org/wiki/24-hour_clock at "Times after 24:00"

**Comment by kazupon** [comment]
Thank you for your reporting!

Internally, `$d` uses `Intl.DatetimeFormat`. The options you specify for `dataTime` are the same specification.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

So, `$d` provided by vue-i18n is almost a wrapper.
About it, vue-i18n docs said too.
https://kazupon.github.io/vue-i18n/guide/datetime.html

I believe that this is not a problem with vue-i18n, but with Intl.DatetimeFormat side.
