### ISSUE TITLE
Uncaught TypeError: o is not a function

### ISSUE THREAD

**Issue by asifgulistani** [kazupon/vue-i18n#1406]
I used "vue-i18n": "^9.2.0-beta.12" and "vue": "^3.2.19".

**Comment by kazupon** [comment]
it's duplicate issue.
https://github.com/intlify/vue-i18n-next/issues/747

I've fixed vue-i18n@9.2.0-beta.13
Please try it!

Thanks!

**Comment by lucasfly** [comment]
@kazupon  Hi, I used "vue-i18n": "7.8.1" and "vue": "2.7.3". I also got this error, how can I solve it? Thanks
