### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Broly789** [kazupon/vue-i18n#1413]
![image](https://user-images.githubusercontent.com/16096724/140614591-331485bf-1d65-44c2-9628-7d1457a92290.png)

vue: 3.0.5
vue-i18n: ~9.1.6

Once this error is reported, my entire program will be unresponsive

**Comment by kazupon** [comment]
Thank you for your reporting!
And, I'm sorry late response.

This repo is for vue-i18n v8.x
so, about vue-i18n v9.x and later version,  please you would be able to report the below link:
https://github.com/intlify/vue-i18n-next

Thanks!
