### ISSUE TITLE
File with translations not loading when changing language

### ISSUE THREAD

**Issue by PomPom248** [kazupon/vue-i18n#1417]
**Reporting a bug?**
I'm trying to make a bilingual page, with french and flemish.
I have two yml files for both languages, but when I change languages from the one chosen one as `defaultLocale`, the translations don't load. I don't know what I'm missing as I've copied it as such from the guide. Hope you can help me out!

**Module versions (please complete the following information):**
 - `vue`: 2.6.11
 - `vue-i18n`: 8.18.1

**Screenshots**
Here are screenshots of the code
<img width="1252" alt="Screenshot 2021-11-25 at 12 19 45" src="https://user-images.githubusercontent.com/36451185/143432344-aa1f9faf-d20e-4932-bef0-8c557a27d214.png">
<img width="1252" alt="Screenshot 2021-11-25 at 12 20 01" src="https://user-images.githubusercontent.com/36451185/143432379-703a440c-9fb1-4d9f-99b0-27a41a064219.png">
<img width="1252" alt="Screenshot 2021-11-25 at 12 21 10" src="https://user-images.githubusercontent.com/36451185/143432549-7496795d-f17d-4e1b-9137-4ae923339919.png">
<img width="1252" alt="Screenshot 2021-11-25 at 12 21 45" src="https://user-images.githubusercontent.com/36451185/143432631-d9d8afac-9a10-4ddb-ac0f-bdd7bbc9a021.png">

**Comment by kazupon** [comment]
Thank you for your reporting!

I think nuxt/i18n is used in your application.
First, please make sure that your nuxt/i18n settings are correct.
Then, please isolate the issue as to whether the problem is with nuxt/i18n or vue-i18n.

Thanks!
