### ISSUE TITLE
CamelCase with $tcc 

### ISSUE THREAD

**Issue by danielschmitz** [kazupon/vue-i18n#142]
Please, create a new method $tcc to transalte a text with camel case pattern

Example:

```
{
 product: 'product',
 hello: 'hello world'
}
```
result: 

```
$tcc('product')  ==> Product
$tcc('hello')  ==> Hello World
```

Thanks !!!!

**Comment by kazupon** [comment]
Thank you for your filling.

I think that you can support the caml-case, and it should be user-land.

```js
caml($t('hello'))
```
