### ISSUE TITLE
this.localePath is not a function

### ISSUE THREAD

**Issue by PomPom248** [kazupon/vue-i18n#1423]
**Reporting a bug?**
In my code I'm using this.localePath() for redirection, but when it seems to fail (the error being `this.localePath is not a function`).
I don't understand where the mistake is and how I can fix it, I've been researching it for a few weeks now, but I haven't been able to find an answer. I don't know whether this issue has been brought up in the past, but I hope you can help me fix. 

**Module versions (please complete the following information):**

- `vue`: 2.6.11
- `vue-i18n`: 8.18.1

**Screenshots**
Here are some screenshots of the code (it could be useful)
<img width="881" alt="Screenshot 2021-12-13 at 14 51 37" src="https://user-images.githubusercontent.com/36451185/145824501-fc629d1d-7f43-4f10-9bf2-f7f0faebc861.png">
<img width="881" alt="Screenshot 2021-12-13 at 14 51 55" src="https://user-images.githubusercontent.com/36451185/145824541-bccfd6c8-af65-4dc4-a25f-ed0bf8dc09e9.png">

**Comment by kazupon** [comment]
Thank you for your reporting!

`localePath` function is not defined in vue-i18n.
If you use the `nuxtjs/i18n` in your app, `localePath` function is defined with it.
https://i18n.nuxtjs.org/

The code from which the error stack trace originated might tell us which module is being used or not.

In order for us to work on this issue, we need a minimal amount of reproducible code. Could you give us the reproduction code via github repo, please?
