### ISSUE TITLE
Linked locale messages not wrok

### ISSUE THREAD

**Issue by yangguoquan** [kazupon/vue-i18n#1424]
**Reporting a bug?**
 - Try to search for your issue, it may have already been answered or even fixed in the development branch.
 - Check if the issue is reproducible with the latest version of Vue I18n v8.x. If you are using a pre-release, please indicate the specific version you are using.
 - **If you want to open the issue of Vue I18n v9.x, Please here: https://github.com/intlify/vue-i18n-next/issues
 - For bugs that involves build setups, you can create a reproduction repository with steps in the .github/CONTRIBUTING.md
 - If your issue is resolved but still open, don’t hesitate to close it. In case you found a solution by yourself, it could be helpful to explain how you fixed it.

**Module versions (please complete the following information):**
 - `vue`: 3.2.20
 - `vue-i18n`: 9.1.9

**Reproduction Link**
A minimal JSBin, JSFiddle, Codepen, CodeSandbox, or a GitHub reprository that can reproduce the bug.

You can use reproduction jsfiddle template: https://jsfiddle.net/kazupon/rn724baz/3/

**To Reproduce**
ex:
点击@:(APP)查看信息

now return 点击@:(APP)查看信息

**Expected behavior**
点击我的APP查看信息

**Screenshots**

**Additional context**

**Comment by kazupon** [comment]
Thank you for your reporting!

About paren syntax `(` and `)` in linked message,  it is depricated in vue-i18n v9 or later
See the docs:
https://vue-i18n.intlify.dev/guide/migration/breaking.html#remove-brackets-grouping-for-linked-messages

BTW, Note that this repo is for vue-i18n v8.x. If you would like to report an issue for vue-i18n v9 in the future, please use the following URL vue-i18n-next
https://github.com/intlify/vue-i18n-next

Thanks!
