### ISSUE TITLE
update to v6.1.0 typeError:_vue2.default.locale is not a function

### ISSUE THREAD

**Issue by bestkj** [kazupon/vue-i18n#143]
### vue & vue-i18n version
vue ^2.1.10
vue-i18n ^6.1.0

### Steps to reproduce
update to v6.1.0 later, element-UI show errors, this works fine before update this version.
typeError:_vue2.default.locale is not a function
[vue-i18n] Value of key 'el.select.noData' is not a string!

this code:
<el-select v-model="userForm.industry" :placeholder="$t('usercenter.settings.user-profile.form.company-industry.placeholder')" class="select">
                      <el-option v-for="item in industries" :label="$i18n.locale === 'zh-CN' ? item.labelCn : item.labelEn" :key="item.id" :value="item.id">
                      </el-option>
                    </el-select>
### What is Expected?
fix this bug, thanks

**Comment by kazupon** [comment]
I think that element-ui documentation don't support vue-i18n v6 or later version.
http://element.eleme.io/#/en-US/component/i18n

**Comment by bestkj** [comment]
npm install vue-i18n v6.0.0, above these problem be resolved
