### ISSUE TITLE
CSP issue while we make use of useI18n()

### ISSUE THREAD

**Issue by shaik4949** [kazupon/vue-i18n#1431]
### Reporting a bug?

Below code causes CSP issue:

`mounted() {
    const { t } = useI18n();
    this.loginTitle = t("message.title_login");
}`

CSP error i got is:

`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`

Also above issue happens even for usage of below code within template tag:
`{{ $t("message.title") }}`

I am using below versions:
`"vue": "^3.2.26"`
`"vue-i18n": "^9.1.9"`
`"typescript": "^4.5.4"`

### Expected behavior

Please help me in resolving this issue. I did refer to https://vue-i18n.intlify.dev/ja/guide/advanced/optimization.html#improve-performance-and-reduce-bundle-size-with-runtime-build-only but i didnt get proper details how exactly to use it for my above issue.

### Reproduction

None

### System Info

```shell
`"vue": "^3.2.26"`
`"vue-i18n": "^9.1.9"`
`"typescript": "^4.5.4"`
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

This Github issues on the repo is for **`vue-i18n@v8.x`**
Please open the **GitHub discussions** on the below the link
https://github.com/intlify/vue-i18n-next

As the advice, we will need a reproducing environment to solve your issue.

Thanks!
