### ISSUE TITLE
Question about the copyright listed in assets/README.md

### ISSUE THREAD

**Issue by PeterAlfredLee** [kazupon/vue-i18n#1436]
### Clear and concise description of the problem

Hi @kazupon 
Recently I noticed the assets/README.md contains a `Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License`. I found that the license is prepared for `Vue I18n artworks`.

IMHO this license is decleared for the artworks(including Logo and somethine else), not for the vue-i18n package itself. I think Vue-i18n is still under `MIT License`. Am I right about this?

Thank you for your time.

### Suggested solution

Nope.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
Hi! @PeterAlfredLee 

The vue-i18n packages are `MIT` licensed, but the ones in the asserts directory are `Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License`.

You are right, there is a contradiction.
We should move it to [intlify/arts](https://github.com/intlify/art).

**Comment by PeterAlfredLee** [comment]
Thank you for your reply.
