### ISSUE TITLE
Browser Console Throwing Error Upon Webpack Build

### ISSUE THREAD

**Issue by TheBroox** [kazupon/vue-i18n#146]
I set up my i18n in a separate file and then import than into my app's main.js file. Both files are on display below.

main.js:

    import Vue from 'vue'

    import App from './App'
    import router from './router'
    import store from './store'
    import i18n from './lang'

    import VueResource from 'vue-resource'
    Vue.use(VueResource)
    Vue.http.options.credentials = true
    Vue.http.options.xhr = {withCredentials: true};
    Vue.http.interceptors.push((request, next) => {
        request.credentials = true;
        next();
    });

    import KeenUI from 'keen-ui'
    Vue.use(KeenUI)

    new Vue({
    	el: '#app',
    	router,
    	store,
    	i18n,
    	template: '<App/>',
    	components: { App }
    })

/lang/index.js:

    import Vue from 'vue'
    import VueI18n from 'vue-i18n'

    Vue.use(VueI18n)

    const i18n = new VueI18n({})
    Vue.config.lang = 'en'
    Vue.config.fallbackLang = 'en'

    import english from './english.js'
    import spanish from './spanish.js'
    import french from './french.js'

    var locales = {
    	en : english,
    	sp : spanish,
    	fr : french
    }

    Vue.prototype.$locale = {
    	change (lang) {
    		Vue.config.lang = lang
    	},
    	current () {
    		return Vue.config.lang
    	}
    }

    Object.keys(locales).forEach(function (lang) {
    	Vue.locale(lang, locales[lang])
    })

    export default i18n

Everything works great when I am using the site in dev mode but after I build it and move it to my server I get the following JS console error:

`Uncaught TypeError: Cannot read property 'silent' of undefined`

Tracing the error it seems to stem from the first line of the `setupLanVM()` function when it is called by the `plugin()`.

Any idea what would be changing between dev and build and what changes I could make to fix the issue?

**Comment by kazupon** [comment]
`Vue.config.lang` and `Vue.locale` is deprected in V6 or laster.
Please see the docs:
- migrations
https://kazupon.github.io/vue-i18n/en/migrations.html
- API
https://kazupon.github.io/vue-i18n/en/api.html
