### ISSUE TITLE
Documentation states wrong npm install

### ISSUE THREAD

**Issue by sepkchs** [kazupon/vue-i18n#1464]
### Reporting a bug?

Currently the documentation states that `npm install vue-i18n` is the correct install for 2.x projects.
But the docs state to use the latest, which is for Vue 3.x (vers. 9.1.9) and not the stable tag which has (vers. 8.27.0)

### Expected behavior

Documentation should state the correct npm install for Vue 2.x `npm install vue-i18n@stable`

### Reproduction

Go to https://kazupon.github.io/vue-i18n/installation.html
The NPM section will state the incorrect install.

### System Info

```shell
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/99752431/154113255-1c2b8313-0b3f-4242-9d8e-ccd302f5032b.png)
![image](https://user-images.githubusercontent.com/99752431/154113371-36c6cfbf-bafe-487d-ad31-0ff72ce565f7.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thanks!
I've just tagged v9.1.9 as `stable`
