### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__composer')

### ISSUE THREAD

**Issue by ahmedemarasure** [kazupon/vue-i18n#1489]
### Reporting a bug?

![image](https://user-images.githubusercontent.com/72691078/160468505-03aaff6b-7909-4a0c-84b5-6a867dac4091.png)

### Expected behavior

.

### Reproduction

.

### System Info

```shell
.
```

### Screenshot

![image](https://user-images.githubusercontent.com/72691078/160468505-03aaff6b-7909-4a0c-84b5-6a867dac4091.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thanks for using vue-i18n!

Unfortunately, I could not reproduce this issue 😞 
We need more reproduction information.

And that issue is vue-i18n v9 issue.
You can open the vue-i18n-next repo issue.
https://github.com/intlify/vue-i18n-next

Thanks!

**Comment by ahcl7** [comment]
Version 9.2-beta.30 fixed this issue for me
