### ISSUE TITLE
How to change language at runtime?

### ISSUE THREAD

**Issue by seemsindie** [kazupon/vue-i18n#15]
Hello

As the title says, how i can change the language at runtime?
Using this $t('site.name', getLang()) and implementing getLang() in each component seems dumb.
And chaning Vue.config.lang does nothing.

Is there a way to change it?

Thanks, Ivan.

**Comment by stephanedemotte** [comment]
+1

**Comment by kazupon** [comment]
related #2

**Comment by pierrebonbon** [comment]
+1

**Comment by kazupon** [comment]
close
