### ISSUE TITLE
chang the key "messages" not work?

### ISSUE THREAD

**Issue by luchanan** [kazupon/vue-i18n#150]
### vue & vue-i18n version
ex: 2.x, 6.1.1

### base.js
```javascript
import VueI18n from 'vue-i18n'
Vue.use(VueI18n)
var messages = {
    'en': {
        'global': {
            'logout': 'log out'
        }
    },
    'zh-CN': {
        'global': {
            'logout': '退出登录'
        }
    }
}
const i18n = new VueI18n({
    locale: 'en', // set locale
    messages// set locale messages
})
```
```
<h1 class="flex_item">{{ $t("global.logout") }}</h1>
```
output
```
<h1 class="flex_item">log out</h1>
```
but when i change the key "messages" to other key "tips", it will output html 
```
<h1 class="flex_item">global.logout</h1>
```

**Comment by kazupon** [comment]
Can you provide the minimum reproduction code with jsfiddle or repository please?

**Comment by yunhor** [comment]
I aslo met the same error,only "message" can work.

**Comment by luchanan** [comment]
@kazupon https://jsfiddle.net/ivanlu/jLo6oz5q/

**Comment by yunhor** [comment]
![2017-05-06 01-28-14](https://cloud.githubusercontent.com/assets/1693437/25757009/76444364-31fb-11e7-8103-47611f633d77.png)
![2017-05-06 01-28-36](https://cloud.githubusercontent.com/assets/1693437/25757030/84aed298-31fb-11e7-830f-d3cfbbc539c3.png)
you can see only message work correctly

**Comment by SegersIan** [comment]
That makes sense no?

When you do 
```
const i18n = new VueI18n({
   locale: 'en',
   message
})
```

It is the same as: 
```
const i18n = new VueI18n({
   locale: 'en',
   message : message
})
```

If you want to make your tips work you should do:

```
const tips = {
    'en': {
        'global': {
            'logout': 'log out'
        }
    },
    'zh-CN': {
        'global': {
            'logout': '退出登录'
        }
    }
}
const i18n = new VueI18n({
   locale: 'en',
   message : tips
})
```

This is because the constructor expects an object with property `message` and not with property `tips`. So just make sure that you pass on your translations with the correct parameter name.
As you can see, I updated your [JS Fiddle](https://jsfiddle.net/jLo6oz5q/1/), now it works.

**Comment by luchanan** [comment]
@SegersIan got it， thanks
