### ISSUE TITLE
Pollution of ComponentCustomProperties when not using globalInjection

### ISSUE THREAD

**Issue by Shayan-To** [kazupon/vue-i18n#1509]
### Reporting a bug?

I'm not using `globalInjection`, but the typing for this library is adding some properties to `ComponentCustomProperties`, and this is causing problems for me. I want to inject custom versions of these properties for my project, and this is stopping me from doing so. (I'm currently patching the `vue-i18n` package and removing the typings as a difficult-to-maintain workaround.)

### Expected behavior

These injections should either be opt-in, or there should be a flag to turn them off.

### Reproduction

I don't see how I should do this...

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
    Memory: 2.26 GB / 11.40 GB
    Container: Yes
    Shell: 7.2.4 - /usr/bin/pwsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chromium: 102.0.5005.61
    Firefox: 100.0.2
  npmPackages:
    vue: ^3.2.36 => 3.2.36 
    vue-i18n: patch:vue-i18n@npm:9.1.9#.yarn/patches/vue-i18n-npm-9.1.9-80331a4387 => 9.1.9 
    vue-router: ^4.0.15 => 4.0.15 
    vue-tsc: ^0.36.1 => 0.36.1 
    vuex: ^4.0.2 => 4.0.2 
    vuex-persistedstate: ^4.1.0 => 4.1.0
```

### Additional context

I'd be glad to contribute a PR.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!
This repo is for vue-i18n@v8.x
about vue-i18n@v9.x, please open the [here](https://github.com/intlify/vue-i18n-next)

Thanks!
