### ISSUE TITLE
Error: [vuex] do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by Tusko** [kazupon/vue-i18n#1511]
### Reporting a bug?

`i18n.setLocaleMessage(locale, messages)`

By using this method got errors with Vuex

<img width="1213" alt="CleanShot 2022-06-10 at 10 30 46@2x" src="https://user-images.githubusercontent.com/2039259/173013903-33657e28-0f86-4769-982e-0fc8ab801ef4.png">

### Expected behavior

use `setLocaleMessage` method without errors.

### Reproduction

```
const { default: defaultLocale } = config.locales

const i18n = new VueI18n({
  fallbackLocale: defaultLocale,
  silentTranslationWarn: true,
  silentFallbackWarn: true
})

function setI18nLanguage (locale, messages) {
  if (i18n.locale === locale) return

  i18n.setLocaleMessage(locale, messages) // this line
  i18n.locale = locale

  localStorage.setItem('locale', locale)
  document.querySelector('html').setAttribute('lang', locale)
  store.dispatch('setCurrentLocale', locale)

  import(`dayjs/locale/${locale}.js`).then(() => {
    dayjs.locale(locale)
  })

  return locale
}
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 74.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 97.0.2
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @vue/cli-plugin-babel: ^3.8.0 => 3.12.1
    @vue/cli-plugin-eslint: ^4.4.1 => 4.5.17
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.17
    @vue/cli-service: ^4.5.13 => 4.5.17
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/test-utils: ^1.0.3 => 1.3.0
    vue: ^2.6.11 => 2.6.14
    vue-clickaway: ^2.2.2 => 2.2.2
    vue-clipboard2: ^0.3.1 => 0.3.3
    vue-color: ^2.8.1 => 2.8.1
    vue-echarts: ^5.0.0-beta.0 => 5.0.0-beta.0
    vue-gtm: ^2.3.0 => 2.3.4
    vue-i18n: ^8.27.1 => 8.27.1
    vue-infinite-loading: ^2.4.5 => 2.4.5
    vue-lazyload: ^1.3.3 => 1.3.3
    vue-markdown-loader: ^2.5.0 => 2.5.0
    vue-recaptcha: ^1.3.0 => 1.3.0
    vue-router: ^3.3.2 => 3.5.3
    vue-styleguidist: ^4.44.28 => 4.44.28
    vue-super-eventbus: ^2.4.1 => 2.4.1
    vue-svgicon: ^3.2.6 => 3.2.9
    vue-template-compiler: ^2.6.11 => 2.6.14
    vue2-datepicker: ^3.10.4 => 3.10.4
    vuelidate: ^0.7.5 => 0.7.7
    vuescroll: ^4.14.4 => 4.17.3
    vuex: ^3.4.0 => 3.6.2
    vuex-shared-mutations: ^1.0.2 => 1.0.2
```

### Screenshot

<img width="1213" alt="CleanShot 2022-06-10 at 10 30 46@2x" src="https://user-images.githubusercontent.com/2039259/173013903-33657e28-0f86-4769-982e-0fc8ab801ef4.png">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Tusko** [comment]
any updates?

**Comment by kazupon** [comment]
Thank you for your reporting!

vue-i18n is not implemented with a dependency on vuex.
As far as your error reporting is concerned, that is exactly what the vuex error message is saying about it.

I think you should make sure that your application code is not against the usage of vuex.

**Comment by Tusko** [comment]
I know. And that's strange.
But can you check test.mstrade.org?

**Comment by Eternal-Rise** [comment]
@Tusko , I found our issue. We have a translation in vuex, so when we load the messages this value is updated and causes an error. Need to remove it from vuex.

![image](https://user-images.githubusercontent.com/34982358/177099020-ccad18ad-fb74-478c-be7b-540ff7012778.png)
