### ISSUE TITLE
Browser freezes when use ruby on rails i18n format

### ISSUE THREAD

**Issue by rjurado01** [kazupon/vue-i18n#1514]
### Reporting a bug?

When use [ruby on rails i18n format](https://kazupon.github.io/vue-i18n/guide/formatting.html#support-ruby-on-rails-i18n-format) and you have two variables in a row the browser freezes.

### Expected behavior

It works.

### Reproduction

Use translation with this format:

```
const messages = {
  en: {
    test '%{a} %{b}'
  }
}
```

```html
<p>{{ $t('test', { a: 'aaa', b: 'bbb' }) }}</p>
```

If you add a character between variables `test '%{a}, %{b}'` it works.

### System Info

```shell
System:
    OS: Linux 5.13 KDE neon 5.25
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 7.48 GB / 15.51 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.13.1/.npm/bin/yarn
    npm: 8.1.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
  npmPackages:
    vue: ^3.0 => 3.2.36 
    vue-color: ^2.8.1 => 2.8.1 
    vue-i18n: ^9.1 => 9.1.10 
    vue-router: ^4.0 => 4.0.15 
    vue2-timepicker: ^1.0.1 => 1.1.6 
    vuedraggable: ^2.23.2 => 2.24.3 
    vuejs-dialog: ^1.4.1 => 1.4.2 
    vuex: ^4.0 => 4.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
This issue is vue-i18n v9, and it is fixed by here
https://github.com/intlify/vue-i18n-next/issues/1055

Thanks!
