### ISSUE TITLE
Can we load the language messages asynchronous?

### ISSUE THREAD

**Issue by CommanderXL** [kazupon/vue-i18n#152]
### vue & vue-i18n version

* `vue`: `2.1.8`
* `vue-i18n`: `6.0`

### What is Expected?

Well, sometimes, the language messages is large. So I want to load the language messages asynchronous, and put the language messages to the CDN as a `lang.js` file, and load it through create script tag to the document. But this process is asynchronous and the page is rendered before the language messages loaded. So does it have some other methods to solve this problem?

**Comment by kazupon** [comment]
You can dynamically load locale messages the below URL:
https://kazupon.github.io/vue-i18n/en/migrations.html#dynamic-locale-removed

Vue.js is component oriented framework.
If you can splite the locale messages for each components, I recommended using componend based translation.
https://kazupon.github.io/vue-i18n/en/component.html
