### ISSUE TITLE
Vue.config.silent is undefined when using with Vue 2.7

### ISSUE THREAD

**Issue by WIStudent** [kazupon/vue-i18n#1522]
### Reporting a bug?

I am trying to use vue-i18n with vue 2.7 (and vue-i18n-composable, but I think the issue lies within vue-i18n). When I serve my site with `npm run serve` (using the vue-cli) and try to open it in a browser I get the error that `Vue.config.silent` is undefined.
```
app.js:5181 Uncaught TypeError: Cannot read properties of undefined (reading 'config')
    at VueI18n._initVM (vue-i18n.esm.js?a4e8:1353:1)
    at new VueI18n (vue-i18n.esm.js?a4e8:1292:1)
    at createI18n (index.mjs?0914:6:1)
    at eval (main.ts?5e60:18:1)
    at ./src/main.ts (app.js:2621:1)
    at __webpack_require__ (app.js:5178:33)
    at app.js:6295:109
    at __webpack_require__.O (app.js:5227:23)
    at app.js:6296:53
    at app.js:6298:12
```

I think this is caused by Vue 2.7 not setting window.Vue anymore in ESM builds: https://github.com/vuejs/vue/blob/main/CHANGELOG.md#notes-on-api-exposure

### Expected behavior

Should not throw an error.

### Reproduction

```typescript
import Vue from "vue";
import {createI18n} from "vue-i18n-composable";
import App from "./App.vue";

const i18n = createI18n();

new Vue({
  i18n,
  render: h => h(App),
}).$mount("#app");
```

### System Info

```shell
@intlify/vue-i18n-loader: ^4.0.0 => 4.0.0
    @vue/cli-plugin-eslint: ^5.0.7 => 5.0.7
    @vue/cli-plugin-typescript: ^5.0.6 => 5.0.7
    @vue/cli-plugin-unit-jest: ^5.0.6 => 5.0.7
    @vue/cli-service: ^5.0.7 => 5.0.7
    @vue/composition-api: ^1.6.3 => 1.6.3
    @vue/test-utils: ^1.3.0 => 1.3.0
    @vue/vue2-jest: ^27.0.0 => 27.0.0
    vue: ^2.7.2 => 2.7.2
    vue-cli-plugin-i18n: ^2.3.1 => 2.3.1
    vue-cli-plugin-vuetify: ^2.5.1 => 2.5.1
    vue-i18n: ^8.27.2 => 8.27.2
    vue-i18n-composable: ^2.0.0 => 2.0.0
    vuetify: ^2.6.7 => 2.6.7
    vuetify-loader: ^1.7.3 => 1.7.3
```

### Additional context

Workaround: Add Vue instance to the window object manually:
```typescript
import Vue from "vue";

window.Vue = Vue;
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by skstuder** [comment]
similar issue, following.

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue. 😞 
Could you give us minimum reproduction codes, please? 🙏

**Comment by WIStudent** [comment]
I created a minimal project for reproduction here: https://github.com/WIStudent/vue-i18n-issue-reproduction

**Comment by kazupon** [comment]
Thank you for your repo!

I've just checked your repo!
I noticed that vue-i18n isn't installed by `Vue.use`.

```diff
 import Vue from 'vue'
+import VueI18n from 'vue-i18n'
 import { createI18n } from 'vue-i18n-composable'
 import App from './App.vue'

 Vue.config.productionTip = false

+Vue.use(VueI18n)
 const i18n = createI18n()

 new Vue({
   i18n,
   render: h => h(App),
 }).$mount('#app')
```

**Comment by WIStudent** [comment]
@kazupon I wasn't aware that `Vue.use(VueI18n)` is needed because it isn't included in the [example in the README of vue-i18n-composable.](https://github.com/intlify/vue-i18n-composable#for-vue-27) I just saw that someone else already created a pull request to update these examples: https://github.com/intlify/vue-i18n-composable/pull/19

**Comment by kazupon** [comment]
Sorry, vue-i18n-composable docs is bad...
I've just merged PR!

Thanks!
