### ISSUE TITLE
Missing `availableLocales` type in `I18nOptions` interface

### ISSUE THREAD

**Issue by hamidyfine** [kazupon/vue-i18n#1523]
### Reporting a bug?

When I try to use `availableLocales` in the new instance of the `VueI18n` get the following error:

```
    // Creating new instance
    i18n = new VueI18n({
        locale,
        availableLocales,
        fallbackLocale,
        messages,
        silentTranslationWarn: true,
        ...options
    });
```
*Typescript error*
```
Object literal may only specify known properties, and 'availableLocales' does not exist in type 'I18nOptions'.
```

I investigate the error in this file: `/node_modules/vue-i18n/types/index.d.ts` and find out that the type of `availableLocales` is missing from the `I18nOptions` interface.

### Expected behavior

The `availableLocales` type gets recognized by typescript.

### Reproduction

```javascript
import Vue from 'vue';
import VueI18n from 'vue-i18n';

const i18n = new VueI18n({
    locale,
    availableLocales,
    fallbackLocale,
    messages,
    silentTranslationWarn: true
});
```

### System Info

```shell
System:
    OS: Linux 5.13 Zorin OS 16.1
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 868.75 MB / 11.44 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reproting!

`availableLocales` is read-only property on the VueI18n instance.
So, We couldn't pass the construction options of VueI18n

Type definition code is here:
https://github.com/kazupon/vue-i18n/blob/ac83e9b29755dadfc2369d00c3ca0b0346a2f8fe/types/index.d.ts#L138-L160

However, docs say `availableLocales` can be passed to the constructor option.
That is incorrect documentation
We need to fix it.

Thanks for your feedback!
