### ISSUE TITLE
Fallback language not working in Single File Components

### ISSUE THREAD

**Issue by 2mittens** [kazupon/vue-i18n#153]
### vue & vue-i18n version
Vue 2.2.6
Vue-i18n 6.1.1
vue-i18n-loader 0.1.1

### Reproduction Link
https://github.com/2mittens/vue-i18n-fallback-single-component
vue init webpack + bare setup to reproduce the issue.

### Steps to reproduce
npm install
npm run dev

### What is Expected?
Fallback language should work as expected in [https://kazupon.github.io/vue-i18n/en/fallback.html](https://kazupon.github.io/vue-i18n/en/fallback.html)
Eventually uncommenting `messages` in `/src/main.js` show the expected behavior.

### What is actually happening?
It prints the following output on the console and doesn't work.
```
[Warning] [vue-i18n] Fall back to translate the keypath 'hello' with root locale.
[Warning] [vue-i18n] Cannot translate the value of keypath 'hello'. Use the value of keypath as default.
[Warning] [vue-i18n] Fall back to translate the keypath 'hello' with root locale.
[Warning] [vue-i18n] Cannot translate the value of keypath 'hello'. Use the value of keypath as default.
```

Hope everything is clear, if you have further questions, let me know.
Thank you!

**Comment by kazupon** [comment]
Sorry, my poor docs 🙇 

If you can fallback to locale messages of single file component, you need to configure `i18n` options the below:

```html
<i18n>
{
  "en": {
    "hello": "hello world!"
  }
}
</i18n>

...

<script>
import Hello from './components/Hello'

export default {
  name: 'app',
  i18n: { // fallback to locale messages of single file components
    fallbackLocale: 'en'
  },
  components: {
    Hello
  }
}
</script>
```

**Comment by 2mittens** [comment]
It works, thank you! Perfect! 😁
