### ISSUE TITLE
Static, separated JSON files in production app

### ISSUE THREAD

**Issue by lukaszflorczak** [kazupon/vue-i18n#154]
Hi!

I try to use vue-i18n plugin in my app, but I have a little problem...
I have a lot translations in my app and they are menaged by external system. So I would like to have every translation in a separate file in a production ready app:

```
/i18n/en.json
/i18n/de.json
...
```

JSONs would be generated by external system.

And I would like to load language file dynamically – only required language – for example only en.json. Is it possible?

I use webpack and I tried to use hot reloading example, but then files are added to app.js. I changed my webpack config and now I get `/dist/i18n/` catalog with language json files but they aren't loaded in my app...

**Comment by zezic** [comment]
You can use solution from #95

**Comment by lukaszflorczak** [comment]
Thanks. Finally I used vue-resources to get translation files and Vuex to store them. It works very well.
