### ISSUE TITLE
createCompileError

### ISSUE THREAD

**Issue by xhxhxhxh** [kazupon/vue-i18n#1541]
### Reporting a bug?

`
<span>{{$t(undefined)}}</span>
`
use $t like that, the key is undefined, the component render error, throw createCompileError.

### Expected behavior

I expect the component render success, even the translated result is wrong.

### Reproduction

no link

### System Info

```shell
not need
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

`$t` first argument will be expected **string** key.
So, To occure the error is correct.

sorry, I don't understand the use case why you specify `undefined`.
If you have a usecase, please you would propose it as the issue.

Thanks!

**Comment by xhxhxhxh** [comment]
`
  <span style="width: 95%;">{{ $t(showRelationDirection?.label || '') }}</span>
`
There are hundreds of similar usecase in my project，I can not add `|| ''` everywhere, and it is difficult to ensure the param alaways string. If one place throw err，all template can not render, 
![image](https://user-images.githubusercontent.com/46396186/181405497-cf6e5283-3834-4dec-8f13-65a0a08c7c82.png)
And I can not know which place throw err. Is there any configuration to ignore this error?

**Comment by xhxhxhxh** [comment]
> Thank you for your reporting!
> 
> `$t` first argument will be expected **string** key. So, To occure the error is correct.
> 
> sorry, I don't understand the use case why you specify `undefined`. If you have a usecase, please you would propose it as the issue.
> 
> Thanks!

`
  <span style="width: 95%;">{{ $t(showRelationDirection?.label || '') }}</span>
`
There are hundreds of similar usecase in my project，I can not add `|| ''` everywhere, and it is difficult to ensure the param alaways string. If one place throw err，whole template can not render, 
![image](https://user-images.githubusercontent.com/46396186/181405497-cf6e5283-3834-4dec-8f13-65a0a08c7c82.png)
And I can not know which place throw err. Is there any configuration to ignore this error?
