### ISSUE TITLE
if $t first argument is not string

### ISSUE THREAD

**Issue by xhxhxhxh** [kazupon/vue-i18n#1542]
### Reporting a bug?

`
  <span style="width: 95%;">{{ $t(showRelationDirection?.label || '') }}</span>
`
There are hundreds of similar usecase in my project，I can not add `|| ''` everywhere, and it is difficult to ensure the param alaways string. If one place throw error, whole template can not render, 
![image](https://user-images.githubusercontent.com/46396186/181405497-cf6e5283-3834-4dec-8f13-65a0a08c7c82.png)
And I can not know which place throw error. Is there any configuration to ignore this error?

### Expected behavior

if $t first argument is not string, can return `''` instead of throw error, I expect the template render success.

### Reproduction

no link

### System Info

```shell
...
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
I should you should design the type of `showRelationDirection.label` in your application.
If you would use TypeScript, you can do it with type definition.
The `$t` argument expects exactly what the error message says.

Thanks!
