### ISSUE TITLE
when use "label" as name, it can not be translated

### ISSUE THREAD

**Issue by agoni1212** [kazupon/vue-i18n#1549]
### Reporting a bug?

en-us.json
`"label": {
    "pro_date": "product date"
  },`

used as follows:
`<div>{{ $t('label.pro_date') }}</div>`

### Expected behavior

translate success

### Reproduction

null

### System Info

```shell
vs code
chrome
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue.
Could you give us your minimue reproduction repo please?
