### ISSUE TITLE
Problem in build env when trying to use json in Javascript

### ISSUE THREAD

**Issue by NathanAP** [kazupon/vue-i18n#1551]
### Reporting a bug?

Hi! I'm not sure if this is the right way to talk about my situation. I'm really sorry if it isn't.

I have a file which contains my locale data, one of them contains something like this:

```
{ 
   "translateList": {
      "type": {
         "title": "Tipo",
         "position": 2,
         "attribute": "types"
      }
   }
}
```

I'm trying to use vue-i18n programatically in my app, directly in Javascript. As you can see in the first image, when I run in `dev`, I have that `source` data which contains the key that I need, so if I do `attribute.source`, I get `types`, awesome. 

![Screenshot_2](https://user-images.githubusercontent.com/12821171/191113210-d63f01fe-aa7c-4bfd-9c67-784ec5a7cf48.png)

The problem is that when I use `npm run build`, that attribute changes to the second image and I no longer have the `source`  data, so my `attribute.source` is now `undefined` as you can see in the second image here:

![Screenshot_3](https://user-images.githubusercontent.com/12821171/191113255-4a0c903d-bb89-40f1-9771-fa10beedf57a.png)

How can I get that "types" value that is specified in "attribute" key?

edit: after some testings I noticed that accessing `position` always bring the value `2` correctly its seems that strings has different behavior?

### Expected behavior

I feel that `.source` should keep sending us the same data in `build` and `dev`.

### Reproduction

I have no data ):

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
    Memory: 6.83 GB / 15.92 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^6.0.1 => 6.0.1
    @vitejs/plugin-basic-ssl: ^0.1.2 => 0.1.2
    @vitejs/plugin-vue: ^3.0.3 => 3.0.3
    vite: ^3.0.5 => 3.0.9
    vite-plugin-vuetify: ^1.0.0-alpha.12 => 1.0.0-alpha.14
    vue: ^3.2.37 => 3.2.37
    vue-advanced-cropper: ^2.8.3 => 2.8.3
    vue-axios: ^3.4.1 => 3.4.1
    vue-cli-plugin-vuetify: ~2.5.4 => 2.5.4
    vue-i18n: ^9.2.2 => 9.2.2
    vue-router: ^4.1.4 => 4.1.4
    vuetify: ^3.0.0-beta.0 => 3.0.0-beta.9
    vuetify-loader: ^2.0.0-alpha.0 => 2.0.0-alpha.9
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
duplicated at https://github.com/intlify/vue-i18n-next/issues/1181
