### ISSUE TITLE
Not working with webpack-dev-server

### ISSUE THREAD

**Issue by cpxPratik** [kazupon/vue-i18n#156]
When used with normal webpack command, there is no console errors and works as expected. But when i try to use with `webpack-dev-server` to watch files, it shows multiple `Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.` errors on console and doesn't render template of the vue component.

How to make `vue-i18n` work with dev-server?

**Comment by wannymiarelli** [comment]
same problem here. Just updated the version from 5.x to 6.x and updated all the bootstrap code,  the {{$t()}} is not working.

**Comment by SegersIan** [comment]
Did you guys try the solution from the [docs](http://kazupon.github.io/vue-i18n/en/hot-reload.html) ?

**Comment by cpxPratik** [comment]
That's to watch translation files. I am talking about watching .vue and .js files.

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you provide a minimum reproruduce code with your GitHub repo please?

**Comment by kazupon** [comment]
Close (in-activity)
