### ISSUE TITLE
<Translation /> component wrong types

### ISSUE THREAD

**Issue by szulcus** [kazupon/vue-i18n#1566]
### Reporting a bug?

```
Type '{ class: string; keypath: string; plural: number; tag: string; }' is not assignable to type 'ComponentProps<{ name: string; props: { keypath: { type: StringConstructor; required: boolean; }; plural: { type: (StringConstructor | NumberConstructor)[]; validator: (val: any) => boolean; }; } & { ...; }; setup(props: any, context: any): any; }>'.
  Type '{ class: string; keypath: string; plural: number; tag: string; }' is missing the following properties from type '{ name: string; props: { keypath: { type: StringConstructor; required: boolean; }; plural: { type: (StringConstructor | NumberConstructor)[]; validator: (val: any) => boolean; }; } & { ...; }; setup(props: any, context: any): any; }': name, props, setupts(2322)

```

### Expected behavior

No bug.

### Reproduction

```
<script setup lang="ts">
	import { Translation } from 'vue-i18n';
</script>
<template>
	<Transition :keypath="...">
		...
	</Transition>
</template>
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 4.94 GB / 15.88 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite-plugin-eslint: ^1.8.1 => 1.8.1 
    vite-plugin-stylelint: ^3.0.7 => 3.0.7 
    vite-plugin-svg-icons: ^2.0.1 => 2.0.1 
    vue-advanced-cropper: ^1.11.5 => 1.11.5
```

### Screenshot

![image](https://user-images.githubusercontent.com/48328739/196217753-95b48853-e838-43db-9c9f-5d59e05d38cc.png)

### Additional context

I use Nuxt 3 (`3.0.0-rc.8`) with @nuxtjs/i18n (`^8.0.0-alpha.2`).

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
this is vue-i18n v9
so transfer to repo of package

**Comment by kazupon** [comment]
oh, we could not transfer to intlify/vue-i18n-next ...
so you can open a new issue.
Thanks!
