### ISSUE TITLE
fix(datetime): missing options from $d supports key format object  (#1502) 

### ISSUE THREAD

**Issue by majdkhasib** [kazupon/vue-i18n#1571]
### Reporting a bug?

[This feature](https://github.com/kazupon/vue-i18n/pull/1569) misses some options:
timeZone: 
hour12:
hourCycle: 
formatMatcher: 

### Expected behavior

Adding the args will change the output

### Reproduction

adding the args

### System Info

```shell
Nth
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by majdkhasib** [comment]
@kazupon  
PR is added [here](https://github.com/kazupon/vue-i18n/pull/1572)

**Comment by kazupon** [comment]
I've just released v8.28.1 
Please check it!

**Comment by majdkhasib** [comment]
Thank you!
