### ISSUE TITLE
fix(datetime): fix typo (#1572)

### ISSUE THREAD

**Issue by MKhasib** [kazupon/vue-i18n#1574]
### Reporting a bug?

calender should be calendar in this [config file](https://github.com/kazupon/vue-i18n/pull/1572/files#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R30)

### Expected behavior

Typo calender

### Reproduction

nth

### System Info

```shell
nth
```

### Screenshot

nth

### Additional context

nth

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't [already an issue](https://github.com/kazupon/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/kazupon/vue-i18n/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MKhasib** [comment]
Fixing the type in this [PR](https://github.com/kazupon/vue-i18n/pull/1575)

**Comment by MKhasib** [comment]
@kazupon Please approve this typo fix

**Comment by kazupon** [comment]
I've released 
https://github.com/kazupon/vue-i18n/releases/tag/v8.28.2
so close
Thanks!
