### ISSUE TITLE
Escaping character in Single File Component JSON break the plugin

### ISSUE THREAD

**Issue by 2mittens** [kazupon/vue-i18n#158]
### vue & vue-i18n version
Vue 2.2.6
Vue-i18n 6.1.1
vue-i18n-loader 0.1.1

### Reproduction Link
https://github.com/2mittens/vue-i18n-fallback-single-component
vue init webpack + bare setup to reproduce the issue.
(Reused from last issue, just pull the latest changes)

### Steps to reproduce
npm install
npm run dev

### What is Expected?
Escaped character such as `\n` or `\"` should be ignored and be rendered unescaped.
Eventually uncommenting `messages` in `/src/main.js` shows the expected behavior.

### What is actually happening?
It prints the following output on the console and doesn't work.
```
[Warning] [vue-i18n] Cannot parse locale messages via custom blocks.
[Warning] [vue-i18n] Fall back to translate the keypath 'hello' with root locale.
[Warning] [vue-i18n] Cannot translate the value of keypath 'hello'. Use the value of keypath as default.
[Warning] [vue-i18n] Fall back to translate the keypath 'hello' with root locale.
[Warning] [vue-i18n] Cannot translate the value of keypath 'hello'. Use the value of keypath as default.
```

Hope everything is clear, if you have further questions, let me know.
Thank you!

**Comment by SegersIan** [comment]
In the mean time you can use `html` tags/encoding like this to work around this issue:

Your translation : ` "mykey": "hello <br> world"`
Then in your template : `<p v-html="$t('mykey')"></p>`

**Comment by 2mittens** [comment]
Thank you for the response @SegersIan!

Yes, that's exactly what I'm doing right now for `\n`, not a big deal.
The more tedious problem is with the use of double quotes `"`, I guess I can encode them with `&quot;` and binding with `v-html` as well.

But I noticed that with "inline" messages, escaping is allowed, so something like this inside the component works:
```
i18n: {
  messages: {
    en: {
      hello_world: "\"te\nst\"",
    },
  },
},
```
So maybe it should works like this even in the JSON?

**Comment by kazupon** [comment]
Thank you for your feedback!
This is problem `vue-i18n-loader`.
Please register it to issues of `vue-i18n-loader`.
