### ISSUE TITLE
bug might relate to memory leak issue

### ISSUE THREAD

**Issue by daggerjames** [kazupon/vue-i18n#162]
### vue & vue-i18n version
ex: 2.1.0, 5.0

### Reproduction Link
https://github.com/daggerjames/vue-i18n-bug-report

### Steps to reproduce

see Readme.md in the repository, and I also observe same issue on pre-release of 7.X.X version

**Comment by daggerjames** [comment]
snapshots with vue-i18n
![with vue-i18n](https://github.com/daggerjames/vue-i18n-bug-report/blob/without-i18n/static/profile-with-i18n.jpeg?raw=true)

without:
![without vue-i18n](https://github.com/daggerjames/vue-i18n-bug-report/blob/without-i18n/static/profile-without.png?raw=true)

**Comment by kazupon** [comment]
Thanks for your reporting!

Fixed now at v6.1.3
Please check it!
https://github.com/kazupon/vue-i18n/releases/tag/v6.1.3

**Comment by daggerjames** [comment]
confirmed, thanks!
