### ISSUE TITLE
Is possible to extend vue-i18n to get random translation from array ? 

### ISSUE THREAD

**Issue by plcdnl** [kazupon/vue-i18n#1631]
### Clear and concise description of the problem

I would to know if is possilbe to extend the module like in this case:  https://github.com/i18next/i18next/issues/1070

### Suggested solution

i think that the 18next solution can be useful also for vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/kazupon/vue-i18n/blob/v8.x/CONTRIBUTING.md)
- [X] Read the [Documentation](https://kazupon.github.io/vue-i18n/)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by spengjie** [comment]
Your request is easy to implement by using [Message Function](https://vue-i18n.intlify.dev/guide/advanced/function.html). Please see my sample code below.
```js
messages = {
  random: () => {
    const list = ['Hi', 'Hello'];
     return list[Math.floor(Math.random() * list.length)];
  }
}
```
```html
<span>{{ $t('random') }}</span>
```
