### ISSUE TITLE
Performance issues with big i18n files

### ISSUE THREAD

**Issue by razyon** [kazupon/vue-i18n#165]
Hi,

In my project we have a huge i18n file (~2000 lines) for all the application and we came across big **performance loss** specially on mobile devices and Internet Explorer.

After some profiling of our app with the chome dev tools we found that the most consuming function of all our project is the **looseClone** function in your library.

I think maybe cloning the entire message list every time a translation is done is not the right thing to do as VueJS will refresh the translation every time the scope of the component has changed (If you type into an input, all the translations of the component linked to that input will be re-translated again).

For all I see, this **looseClone** is just a security that ensures that the users of the library will not break it by changing the messages on the fly. Couldn't it be enough to call **looseClone** in the setter of **"prototypeAccessors.locale"** ?

Regards,
David

**Comment by peterchealse** [comment]
"the scope of the component has changed", what does the 'scope' mean, exactly?

**Comment by ahoo** [comment]
this issue still exists?

**Comment by razyon** [comment]
This issue has been solved long time ago.
________________________________
