### ISSUE TITLE
Use $t function outside template

### ISSUE THREAD

**Issue by clementmas** [kazupon/vue-i18n#17]
Hi,

I'm trying to do simple `alert( $t('error') )` in my JavaScript file but $t is undefined.
I've also tried `Vue.$t` but it is also undefined.

Is there any way to use the $t function outside a template ?

Thank you,
clem.

**Comment by manudurgoni** [comment]
It works with `vm.$t`.

**Comment by aaronjpitts** [comment]
How can I use $t outside of a Vue component, for example in a service class which retrieves data from an API and sets strings?

**Comment by jezperp** [comment]
arronjpitts question is still valid, how do i translate text in components? and why is this closed?

**Comment by Alsciende** [comment]
Seconded

**Comment by asvae** [comment]
You can access translator globally like this:

```js
import Vue from 'vue'

Vue.t('your.translation')
```

**Comment by po5i** [comment]
I cannot use the `Vue.t` function on a single file component. The method is undefined.. Is there something more that I have to include at the `<script>` section?

**Comment by po5i** [comment]
I figured it out like [this comment](https://github.com/kazupon/vue-i18n/issues/149#issuecomment-296348086) at issue #149

**Comment by alex-gru** [comment]
This approach works for me like a charm - I use this statement inside a store action:

```
this.app.i18n.t("example.message.key")
```

Source (external): https://forum.vuejs.org/t/how-to-use-t-from-vue-i18n-inside-vuex-action/22146/3
