### ISSUE TITLE
Named formatting fails for fallbackLocale messages

### ISSUE THREAD

**Issue by rodneyrehm** [kazupon/vue-i18n#176]
### vue & vue-i18n version
vue: v2.3.4 (master)
vue-i18n: v7.0.2 (master)

### Reproduction Link
http://jsfiddle.net/1hj1nwu4/4/

### What is actually happening?

[Named formatting](http://kazupon.github.io/vue-i18n/en/formatting.html#named-formatting) and [list formatting](http://kazupon.github.io/vue-i18n/en/formatting.html#list-formatting) works fine if the message is provided through the current locale, but fails where the message is pulled from the fallbackLocale.

**Comment by rodneyrehm** [comment]
thanks!

is it expected for dev to have failing tests? [fresh clone, npm install, npm run test:unit](https://gist.github.com/rodneyrehm/5ceb730affff0c1dbb5a19b8abe6eb99)

**Comment by kazupon** [comment]
oh, unit test codes is bad.
I'll try to improve it later.
