### ISSUE TITLE
Interpolation not working

### ISSUE THREAD

**Issue by oswaldofreitas** [kazupon/vue-i18n#178]
**package.json:**
```
"dependencies": {
    "vue": "^2.3.3",
    "vue-i18n": "git://github.com/kazupon/vue-i18n.git#dev",
```
**messages:**
```
{
  test1: 'test1 {0}',
  test2: 'test2'
}
```
**template:**
```
<template lang='pug'>
  div
    i18n(path='test1')
      | {{$t('test2')}}
</template>
```
**output:**
 #`test1 {0}`

**Comment by kazupon** [comment]
You need to define the locale (e.g. en).
Please see the Locale messages syntax section.
https://kazupon.github.io/vue-i18n/en/messages.html

**Comment by oswaldofreitas** [comment]
sorry, I forgot to mention that messages is a subsection of a locale, it's already inside "en". All my i18n is working, just interpolation not
