### ISSUE TITLE
How to put HTML elements in translations?

### ISSUE THREAD

**Issue by sagaio** [kazupon/vue-i18n#18]
This will print out `<br />` instead of a linebreak:
```
module.exports = {
  en: {
    index: {
       headline: 'Testing html <br /> with i18n'
    }
  }
}

**Comment by mcchin** [comment]
+1

**Comment by aaronjpitts** [comment]
Any update with this? Thanks

**Comment by aaronjpitts** [comment]
If you wrap the translation in 3 brackets like:

    {{ $t("message.hello") }}

 it does actually render the HTML correctly. But is it good practise to do that?

**Comment by edouard-lopez** [comment]
thanks @aaronjpitts.

**Comment by sagaio** [comment]
I think @aaronjpitts solved this. I'm closing this as it's working for me aswell. Thank you!

**Comment by guillaumevincent** [comment]
@sagaio could you re-open the issue ? and consider the issue solved when the documentation has clarified the solution ? I can make a pull request for this one if you want.

**Comment by sagaio** [comment]
Sure. Nice PR!
For the record It's also stated on VueJS offical page: http://vuejs.org/guide/syntax.html#Raw_HTML

**Comment by edouard-lopez** [comment]
@guillaumevincent thanks!
ping @kazupon

**Comment by kazupon** [comment]
@guillaumevincent 
Welcome Pull request :smiley_cat:

**Comment by guillaumevincent** [comment]
@kazupon the PR is already done :

https://github.com/guillaumevincent/vue-i18n/pull/1

**Comment by aaronjpitts** [comment]
What would also be great would be able to render functions like v-link and @click. For example say I have the below json:

	{
		"message": "This is a message <a v-link="{name: 'linkName'}">with a link</a>"
	}

It doesn't render the v-link right now. Is this something you could implement?

As always, thanks

**Comment by guillaumevincent** [comment]
ping @kazupon

**Comment by kazupon** [comment]
@guillaumevincent 
Can you send to kazupon/vue-i18n PR please ?

**Comment by kazupon** [comment]
@aaronjpitts 
Hmm,  :disappointed: 
It cannot render the directive as `v-link`, because it need to compile the directive.

**Comment by guillaumevincent** [comment]
Sorry @kazupon don't understand what I've done :( 
here the good pull request : https://github.com/kazupon/vue-i18n/pull/20

**Comment by deanappen** [comment]
https://vue-i18n.intlify.dev/guide/advanced/component.html
