### ISSUE TITLE
Documentation: Invalid configuration example in DateTime localization

### ISSUE THREAD

**Issue by clement-michelet** [kazupon/vue-i18n#181]
### vue & vue-i18n version
7.0+

### Reproduction Link

http://kazupon.github.io/vue-i18n/en/datetime.html

### Steps to reproduce

Read the documentation

### What is Expected?

The documentation should demonstrate how to configure date time formats using the VueI18n constructor :

> After that like the locale messages, You need to specify the dateTimeFormats option of VueI18n constructor:

```javascript
const i18n = new VueI18n({
  locale: 'fr',
  messages,
  dateTimeFormats,
});
```

### What is actually happening?

The documentation example use the Vue constructor instead of the VueI18n constructor which does nothing.

> After that like the locale messages, You need to specify the dateTimeFormats option of VueI18n constructor:

```javascript
new Vue({
  i18n,
  dateTimeFormats
}).$mount('#app')
```

**Comment by kazupon** [comment]
Thank you for your feedback!
I fixed.
