### ISSUE TITLE
Long i18n resouces with long tree component(element-ui) block the router switch

### ISSUE THREAD

**Issue by xingchch** [kazupon/vue-i18n#187]
Vue-i18n version
 **from 6.1.3 
  6.1.2  have no this issue**

Element UI version

1.3.7

OS/Browsers version

windows /chrome 58

Vue version

2.3.4

Reproduction Link

https://jsfiddle.net/xccxccxcc/ska4oboj/21/

Steps to reproduce

1.click "world", tree shows.

2.click "hello", the switch blocked more then 20s . and then  hello view appear.

What is Expected?

router switch to 'hello' from 'world' should be in time

What is actually happening?

blocked at beforeDestroy more then 20s.

**Comment by xingchch** [comment]
For me this is a serious issue。  If there's anything I can do to help, please let me know. thanks a lot.

**Comment by kazupon** [comment]
Thank for your feedback!
I'm working for solving this issue.
