### ISSUE TITLE
can I use $t() in javascript?

### ISSUE THREAD

**Issue by sergot** [kazupon/vue-i18n#19]
Hey, is there any possibility to use the $t() function inside a javscript file? Like I have a method in my vue script that returns a string and I want it to be internationalized. :)

**Comment by kazupon** [comment]
You can use the `$t` as method of Vue instance.

e.g.
```javascript
new Vue({
  methods: {
    getMessage: function (key) {
      return this.$t(key)
    }
  }
})
```

**Comment by sergot** [comment]
Thanks a lot! :)

**Comment by dionysiosarvanitis** [comment]
Would be nice to see that in README.md

**Comment by donaldinos** [comment]
How can i call this method getMessage from another component, which is in separated .vue file ?

**Comment by rlaace423** [comment]
@donaldinos If you added i18n instance in root vue instance (like Vue.use(i18n)), you can just call this.$t('something') anywhere you want.

**Comment by Inspirateur** [comment]
> You can use the `$t` as method of Vue instance.
> 
> e.g.
> 
> ```js
> new Vue({
>   methods: {
>     getMessage: function (key) {
>       return this.$t(key)
>     }
>   }
> })
> ```

Using Vue 3 and typescript `this.$t` errors with `Object is possibly 'undefined'`  
and `this?.$t` errors with `Property '$t' does not exist on type 'never'`

EDIT: I think in my case the correct solution is
```ts
import { useI18n } from 'vue-i18n';

const { t } = useI18n();
console.log(t(key))```

**Comment by charliech17** [comment]
If you want to use $t in nuxt3 javascript file, try  below code:

`
useNuxtApp().$i18n.t('someWord')
`

I want to note here because i didn't find other information in google.
It took me sometime to figure it out...
