### ISSUE TITLE
Access to VueI18n in window?

### ISSUE THREAD

**Issue by dkpalmer** [kazupon/vue-i18n#190]
_Apologies. I'd ask on the support forums but they appear to be down._

### vue & vue-i18n version
7.0.3

We're in the process of migrating from 5.0.3->7.0.3. One case we've hit a wall with is where we were previously getting VueI18n from window by calling

```
window.Vue.t(message); // works in 5.0.3!
```

Is there a way to do this in 7.0.3?

**Comment by kazupon** [comment]
You can use `VueI18n#t` method.
see detail migration guide:
https://kazupon.github.io/vue-i18n/en/migrations.html#vuet-replaced

**Comment by dkpalmer** [comment]
@kazupon We can't seem to find a reference to the VueI18n instance. It seems to be undefined everywhere. Am I overlooking something obvious?

**Comment by kazupon** [comment]
@dkpalmer 
sorry, my poor explanation 🙇 

`VueI18n` instance can be reference as `$i18n` from Vue instance.
You can use it.

**Comment by joshuajohnson814** [comment]
@kazupon I'm working with @dkpalmer on this. 

We're installing both Vue and VueI18n through a CDN. We're building a component dynamically in javascript through `Vue.extend(require('./MyComponent.vue'));` so previously we had `window.Vue.t(message)` in our code to render the translated message and pass to our dynamic component.

Now `window.Vue.t` and `window.Vue.$i18n` are both undefined. Are we doing something wrong?

**Comment by kazupon** [comment]
@dkpalmer @joshuajohnson814 
In v6 later, There is breaking changes of API.
Would you check the docs?
https://kazupon.github.io/vue-i18n/en/started.html

**Comment by falstack** [comment]
I can't get i18n on window, when i use SSR, how can i do?
