### ISSUE TITLE
List of available languages

### ISSUE THREAD

**Issue by cirience** [kazupon/vue-i18n#193]
I'd like to have an feature which allows me to output all available languages with one method. That would allow to make a list of all available translations.

**Comment by kazupon** [comment]
Thank you for your feedback.

However, I could not understand the reason of your feedback.
Could you talk us more explanation please?

**Comment by thoean** [comment]
I started using https://github.com/bdswiss/country-language, which has methods to retrieve ISO standard names for languages, as well as country specific mapping.

**Comment by SHA-256** [comment]
When I'm adding the 'messages' to your plugin, I'm creating different Objects like en, de, ja. I'd think it would be useful if there is an built-in function to get all 'Objects' which are basically languages-codes in my case.

**Comment by sethmurphy18** [comment]
In the meantime until this comes to fruition, I did find a stop gap:

```js
computed: {
  languages() {
    return Object.keys(this.$i18n.messages);
  }
}
```

**Comment by rimiti** [comment]
@kazupon  It could be nice to provide a **getLocales()** method which returns an array of the available locales: _['en', 'fr', 'pt']_.

PS: With the same result of the @sethmurphy18 snippet.

**Comment by exoego** [comment]
Could someone provide use-case for this feature?

I imagine this may be useful to create language selector UI which shows available languages based on messages objects.
But not sure.

**Comment by exoego** [comment]
@rimiti 
That use-case totally make sense!

**Comment by rimiti** [comment]
It's a good job @exoego, you rock 🚀

**Comment by hacene-ouserir** [comment]
You can do that by "availableLocales" option.
e.g: (i18n.availableLocales), will return an array that has a list of available locales.
