### ISSUE TITLE
Differentiate between regional settings and display language

### ISSUE THREAD

**Issue by thoean** [kazupon/vue-i18n#196]
The configuration object only takes a single `locale` flag. However, display language is something different than the regional settings.

What I believe should be supported independently:
* language -> for the translation, relevant for the `t$(...)` method.
* locale -> for the formatting, relevant for the `n$(...)` and `d$(...)` methods.

In my current use-case, I'm having limited translation for my user interface (German and English), but I have users from various countries, including the UK vs. US which format the day and month in different order. For achieving that, I currently need to inject the desired locale in each date formatting, something like this:

```html
<span>{{ $d(new Date(), 'short', userRegionalSettings()) }}</span>
```

I'd like to replace the necessity to of passing in the locale, but rely on a default.

**Comment by famelartBenoit** [comment]
any news about this one ?

**Comment by mario-d-s** [comment]
IMO this is really important, it's basic functionality for any I18n library... Pleas add priority tag if possible.

**Comment by exoego** [comment]
Could anyone give some examples of  i18n messages JSON that is sutable for the suggested use-case ?
It would help possible contributors to understand user-case and design API changes.

**Comment by BasilaryGroup** [comment]
Another example of important regional differences.

// English Canada
"en-ca": {
  "color": "Colour",
  "money": "no money | loonie | toonie | {count} dollars",
  "z": "Zed"
},
// English United States
"en-us": {
  "color": "Color",
  "money": "no money | {count} dollars",
  "z": "Zee"
}

**Comment by chrisbarton126** [comment]
@kazupon - is there likely to be any traction on this particular item? This would be of great benefit to myself, and obviously others, whereby I need to allow the user to change their display language but keep the relevant locale settings for things like number / date formatting.

**Comment by louisameline** [comment]
Forgive me if I didn't understand the point of this issue, but for me I'm already using vue-i18n like this and it works well I believe:

`app.i18n.locale = 'fr-ca'`
```
app.i18n = new VueI18n({
  dateTimeFormats: {
    'fr-fr': {
      ...
    },
    'fr-ca': {
      ...
    },
   'en-us': {
      ...
    }
}
```
The only thing annoying me is the fallback system which should be improved, as it forces me to redeclare the format even if they are the same in `fr-fr` and `fr-ca`. If a format is not present in `fr-ca`, I wish it used the `fr-fr` format and not directly the default fallback language (`en-us` in my case). This particular issue is discussed in this other issue: https://github.com/kazupon/vue-i18n/issues/138

**Comment by exoego** [comment]
Thank you @louisameline pointed out that 👍 

Yes, it seems that we are already able to differentiate 

* Display language for messages: `$t`, `$tc`
* Regional settings   
    * `$d` for datetime https://kazupon.github.io/vue-i18n/guide/datetime.html
    * `$n` for numer https://kazupon.github.io/vue-i18n/guide/number.html

So I am going to close this issue since it is already supported. 
Feel free to reopen or open a new issue if existing feature does not meet your use case. .

**Comment by sinasita** [comment]
I'm not sure, if I miss something obvious, there are different  handlings of numberFormats and dates, but what if I really need different translations for a country, let's say Switzerland, where I have iso fr-CH, it-CH and de-CH, so I need French, Italian and German. I can add translations for 'ch', but how should that fit for all 3 languages?

**Comment by thoean** [comment]
That was the point of my original ticket:

* The *display language* or *UI language* or whatever you want to name it is one specific setting. Let's say someone sets that to German, then everything should be translated to German. So country `CH` would be translated to `Schweiz`. The code for German is `de` and for a Swiss version of German it's `de-CH`. Many webpages of medium-sized companies can't deal with the complexity of adding another sub-language like `de-CH` but just go with `de` for the translations (and it's close enough for reading purposes to be OK with it).
* The *regional settings* are how to format things. Like, do I want to see `10.40€` or `10,40€` (note the `,` vs. `.`). That's super relevant for readability, especially as we get into date format, like `01/02/2022` vs. `02/01/2022` could mean the same date depending on `en-US` vs. `en-GB`.

So I don't understand your question above, but I hope the additional context helps?

**Comment by NicoHof** [comment]
Hi @thoean i am in the exact same situation. I need to implement a second version of a nuxt page for switzerland. right now its only germany. now i need germany and switzerland. But its not as simple as `de` and `ch` as you said. For switzerland I need translations for ch for german, italian and french.

Can it be a solution to implement four "languages":
- `de-de`
- `ch-de`
- `ch-it`
- `ch-fr`

Or have you found an other or better approach?

**Comment by thoean** [comment]
I didn't invest into this since then, and our apps are on a technology stack. Sorry to not be able to help further.
