### ISSUE TITLE
[FEATURE REQUEST] directive or component instead of instance function

### ISSUE THREAD

**Issue by darkylmnx** [kazupon/vue-i18n#197]
I've been doing asking myself, since `{{ $t('key') }}` is a function, it means on each template update, though the translation hasn't change it will re-execute the func, for apps with many calls to this func (which is the goal of the lib) we'll get pretty lousy perf.

I've been doing things like `<div v-once>{{ $t('key') }}</div>` but it's not ideal, something nice would be a directive like below 
`<div v-trans>key</div>`  or `<div> <trans :params="params">key</trans> </div>` so as to not execute the function if the value has already been evaluated

**Comment by kazupon** [comment]
Released v7.3.0
https://github.com/kazupon/vue-i18n/releases/tag/v7.3.0
