### ISSUE TITLE
Vue.js Avoriaz unit test produces translation warnings when vue-i18n is used

### ISSUE THREAD

**Issue by ndabAP** [kazupon/vue-i18n#198]
### vue & vue-i18n version
vue: 2.2.2
vue-i18n: 7.0.5

### Reproduction Link
https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project/blob/master/frontend/test/unit/specs/Login.spec.js

Question at stackoverflow: https://stackoverflow.com/questions/45184859/vue-js-avoriaz-unit-test-produces-translation-warnings-when-vue-i18n-is-used

### Steps to reproduce
Unit test a working translated Vue.js component with Mocha, PhantomJS and Karma.

### What is Expected?
Don't get any warnings.

### What is actually happening?
Multiple warnings that keys are not translated.

> WARN LOG: '[vue-i18n] Cannot translate the value of keypath 'description.first'. Use the value of keypath as default.'

###

**Comment by kazupon** [comment]
Thank you for your reporting!

I confirmed your reproduction codes.
In avoriaz, I seem that you need to specify `i18n` option to the `options` (second args) of `mount` function with similar uses as store of vuex.
/cc @eddyerburgh

ref:
https://github.com/eddyerburgh/avoriaz/blob/master/docs/guides/using-with-vuex.md

```javascript
const wrapper = mount(Login, { Login.i18n })
```

**Comment by ndabAP** [comment]
Hi, @kazupon and thank you for your answer.

Unfortunately, it doesn't work. 

This modified version also doesn't work:

```
const wrapper = mount(Login, {
  i18n: Login.i18n,
  store
})
```

**Comment by eddyerburgh** [comment]
@ndabAP @kazupon  I'm not sure if this is avoriaz specific or not? 

I got this minimal example passing without warnings:

```js
import Vue from 'vue'
import {
    mount
} from 'avoriaz'
import VueI18n from 'vue-i18n'
import Register from '../src/components/Bar.vue'
import { expect } from 'chai'

Vue.use(VueI18n)

describe('Register', () => {
    it('should accept inputs', () => {
        const messages = {
            en: {
                'description': 'Enter a name',
            },
            de: {
                'description': 'Gebe einen Namen ein',
            }
        }
        const i18n = new VueI18n({
            locale: 'en', // set locale,
            messages
        })
        const wrapper = mount(Register, { i18n })

        expect(wrapper.find('div')[0].text()).to.contain(messages.en.description)
    })
})
```

```js
<template>
	<div>
		{{$t('description')}}
	</div>
</template>

<script>
    export default {
        name: 'bar',
        messages: {
            en: {
                'description': 'Enter a name',
            },
            de: {
                'description': 'Gebe einen Namen ein',
            }
        }
    }
</script>
```

Passes.

**Comment by ndabAP** [comment]
Thank you so much for testing this, @eddyerburgh. I still don't get it to work using vue-18n 7.0.5 and avoriaz 2.5.0. I wonder how you can define messages inside your component without the i18n tag like I did. However, this is my updated (still not working setup):

```javascript
it('should accept inputs', async() => {
    const state = {
      user: {
        name: '',
        password: ''
      }
    }

    const mutations = {
      SET_USER_NAME(state, name) {
        state.user.name = name
      },

      SET_USER_PASSWORD(state, password) {
        state.user.password = password
      }
    }

    const store = new Vuex.Store({
      state,
      mutations
    })

    const messages = {
      en: {
        'description.first': 'Enter a name',
        'label.first': 'Name *',
        'description.second': 'Enter a password',
        'label.second': 'Password *',
        'button.first': 'Create'
      },
      de: {
        'description.first': 'Gebe einen Namen ein',
        'label.first': 'Name *',
        'description.second': 'Gebe ein Passwort ein',
        'label.second': 'Passwort *',
        'figcaption.first': 'Du kannst einen dieser Nutzer wählen, um dich einzuloggen.',
        'button.first': 'Erstellen'
      }
    }

    const i18n = new VueI18n({
      locale: 'en',
      messages
    })

    const wrapper = mount(Register, {
      store,
      i18n
    })

    let name = 'Hans'
    let password = '123'

    let nameInput = wrapper.find('input')[0]
    let passwordInput = wrapper.find('input')[1]

    nameInput.element.value = name
    passwordInput.element.value = password

    nameInput.trigger('input')
    passwordInput.trigger('input')

    expect(wrapper.vm.$store.state.user.name).to.equal(name)
    expect(wrapper.vm.$store.state.user.password).to.equal(password)
  })
```

Any other ideas?

**Comment by ndabAP** [comment]
I made a little progress when I stub the `$t` function like this:

```js
wrapper.vm.$t = sinon.stub()
```

There are still warnings. @kazupon, is it possible to completely disable the translation inside the `VueI18n` instance? I think about something like this:

```js
const i18n = new VueI18n({
  locale: 'en',
  messages
})

i18n.$t = sinon.stub()
```

**Comment by ndabAP** [comment]
## Update
I tried to ignore the warnings inside my `main.js`:

```js
const i18n = new VueI18n({
  locale: 'en',
  silentTranslationWarn: true
})
```

I also tried the "missing" handler. Both didn't work. Only setting the testing enviroment to `production` helped, because of:

https://github.com/kazupon/vue-i18n/blob/dev/src/index.js#L155

This is not a satisfiable solution. I'm still looking for a better one.

**Comment by kazupon** [comment]
You need to setup the locale messages not `'description.first': 'Enter a name'`, but `description: { first: 'Enter a name' }`

**Comment by ndabAP** [comment]
@kazupon, still no success. I changed it in both, the `Register.vue` component and the test file `Register.spec.js`

```
describe('Register', () => {
  it('should accept inputs', async () => {
    const messages = {
      en: {
        'description': {
          'first': 'Enter a name',
          'second': 'Enter a password'
        },
        'label': {
          'first': 'Name *',
          'second': 'Password *'
        },
        'button': {
          'first': 'Create'
        }
      },
      de: {
        'description': {
          'first': 'Enter a name',
          'second': 'Enter a password'
        },
        'label': {
          'first': 'Name *',
          'second': 'Password *'
        },
        'button': {
          'first': 'Create'
        }
      }
    }

    const i18n = new VueI18n({
      locale: 'en',
      messages
    })

    const state = {
      user: {
        name: '',
        password: ''
      }
    }

    const mutations = {
      SET_USER_NAME (state, name) {
        state.user.name = name
      },

      SET_USER_PASSWORD (state, password) {
        state.user.password = password
      }
    }

    const store = new Vuex.Store({
      state,
      mutations
    })

    const wrapper = mount(Register, {
      store,
      i18n
    })

    wrapper.vm.$t = sinon.stub()

    let name = 'Hans'
    let password = '123'

    let nameInput = wrapper.find('input')[0]
    let passwordInput = wrapper.find('input')[1]

    nameInput.element.value = name
    passwordInput.element.value = password

    nameInput.trigger('input')
    passwordInput.trigger('input')

    expect(wrapper.vm.$store.state.user.name).to.equal(name)
    expect(wrapper.vm.$store.state.user.password).to.equal(password)
  })
})
```

**Comment by defel** [comment]
FYI works for me with the example from @eddyerburgh :+1: - seems not be 

@ndabAP can you provide a minimal example, without the  `$t` mock?

**Comment by ndabAP** [comment]
@defel,

Clone [this](https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project) repository and change [this](https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project/blob/master/frontend/build/webpack.test.conf.js#L16) line to: 

```js
'process.env': require('../config/test.env')
```

**Comment by defel** [comment]
@ndabAP sorry, but this is not a minimal example. See the example provided by @eddyerburgh - which works for me. 

The question is, what are you doing different which triggers the error you have? There are too many moving parts at the moment, making it hard to spot what the cause of this problem is.

**Comment by sun-slaven** [comment]
I meet the same issue when running unit test.
**silentTranslationWarn** is not work for test environment?

**Comment by ndabAP** [comment]
@defel it's not a minimal example but an example that demonstrates two things:

**First**: How I consume the translation API is correct, because it works fine out of any test context. If not, I use the API in a way that should be blocked.

**Second**: It doesn't work when running tests while using the same component that does work under a real environment.

I updated vue-i18n to the newest version, switched to vue-test-utils and still got the same issue.

**Comment by josecelano** [comment]
Hi, regarding testing components with translations I think we could make testing easier if the component is wrapped in a HOC which passes only the part of the translations needed by the component as props. That way testing would be very easy as we do not need to mock i18n. The problem is I have only seen that solution for React:

https://www.youtube.com/watch?v=mwYHDXS6uSc

and I do not know how It could be implemented in Vue.

**Comment by voxivoid** [comment]
Hi @ndabAP,
I've managed to fix this problem by setting up the locale on the i18n Login component property and reusing it on the mount instead of creating a new VueI18n instance. The problem was that I already had i18n defined in the Login component options and (I assume) it was creating a conflict between that one and the one that was being set up by the mount function.
``
    Login.i18n.locale = 'en';
    wrapper = mount(Login, {
      i18n: Login.i18n,
      store,
    });
``

**Comment by ndabAP** [comment]
@voxivoid your feedback is great! I already switched to another translation library (which is, unfortunately, far away from this one) but I'll revert some commits to check that out.

**Comment by kazupon** [comment]
@ndabAP 
Could you resolve this issue? 
If so, I hope that close this issue. 🙏

**Comment by ndabAP** [comment]
Sorry for the delay @kazupon 

I will test it!

**Comment by ndabAP** [comment]
Well, maybe I'm doing wrong but I had to do two things to get rid of the warnings:

1. **Disable strict mode because of Babel plugin**
Uncomment in _node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js_ line 166 where it says `inherits: _babelPluginTransformStrictMode2.default`,

2. **Set locale manually**
```
Login.i18n = {locale: 'en'}
// ...
const vm = new Ctor({
  i18n: Login.i18n,
  store
}).$mount()
```

But with this, it works. I close the issue. Thanks for your attention!

**Comment by gkatsanos** [comment]
Too many different version of "a fix". I also have the same issue, I am not sure what the solution is.

**Comment by cristiangiagante** [comment]
I will update the solution from @eddyerburgh to a currently working example:

```js
import { shallowMount, createLocalVue } from '@vue/test-utils'
import VueI18n from 'vue-i18n'
import Register from '../src/components/Bar.vue'

describe('Register', () => {
    it('should accept inputs', () => {
        let localVue = createLocalVue()
        localVue.use(VueI18n)
        const messages = {
            en: {
                description: 'Enter a name',
            },
            es: {
                description: 'Ingresa tu nombre',
            }
        }
        const i18n = new VueI18n({
            locale: 'es', // set locale,
            fallbackLocale: 'es',
            messages
        })
        const wrapper = shallowMount(Register, { i18n, localVue })

        expect(wrapper.find('div')[0].text()).to.contain(messages.en.description)
    })
})
```

Bye!

**Comment by mmelvin0581** [comment]
This isn't working for me. Am I doing something wrong here?

```
import { shallowMount, createLocalVue } from '@vue/test-utils'
import BaseDialog from '@/components/BaseDialog/BaseDialog'
import VueI18n from 'vue-i18n'

describe('BaseDialog', () => {
  it('is called', () => {
    let localVue = createLocalVue()
    localVue.use(VueI18n)
    const messages = {
      gb: {
        'ui.universal.label.ok': 'OK',
        'ui.universal.label.cancel': 'Cancel'
      }
    }

    const i18n = new VueI18n({
      locale: 'gb',
      fallbackLocale: 'gb',
      messages
    })

    const wrapper = shallowMount(BaseDialog, {
      i18n,
      localVue
    })
    expect(wrapper.name()).toBe('BaseDialog')
    expect(wrapper.isVueInstance()).toBeTruthy()
  })
})
```

**Comment by adi3230** [comment]
@mmelvin0581 The code I was working on is similar to yours. In my case the vue i18n was not getting the locale so it was complaining and falling back to default locale. Try to console the current locale and check whether you are getting any locale.. that could probably the reason

**Comment by gmbarroso** [comment]
Hi, I know this is from long time ago, but I want to share my solution. And to explain it better, I want to match the texts inside my component after wrap.

I wasn't able to do this because the translations wasn't comming. This was my html part that I want to test before the solution: `... <span></span> ...` . An empty `span` when my code was waiting for the translation: `<span>{{ $t('menu.title') }}</span>`

My solution:
```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import BootstrapVue from 'bootstrap-vue';

import { shallowMount, createLocalVue } from '@vue/test-utils'
import HeaderComponent from '@/components/HeaderComponent'
import ToggleMenu from '../../src/mixins/ToggleMenu'

import pt from '../../src/i18n/languages/pt-br/pt'

Vue.use(VueI18n)

describe.only('HeaderComponent', () => {
  let wrapper
  const localVue = createLocalVue()

  localVue.use(BootstrapVue, VueI18n)
  localVue.mixin(ToggleMenu)

  beforeEach(() => {
    const messages = {
      pt: pt
    }

    const i18n = new VueI18n({
      locale: 'pt',
      messages
    })

    wrapper = shallowMount(HeaderComponent, {
      localVue,
      i18n,
      stubs: ['router-link'],
      mixins: [ToggleMenu],
    })
  })
    
  it('ensure that HeaderComponent is a Vue instance', () => {
    expect(wrapper.isVueInstance()).toBeTruthy()
  })
  
  it('render the important elements', () => {
    expect(wrapper.contains('.menu-bar')).toBe(true)
    expect(wrapper.contains('#open_menu')).toBe(true)
    expect(wrapper.text()).toMatch('Menu');
    expect(wrapper.text()).toMatch('Sair');
  })
})
```

Now I have a fullfilled span: `<span>Menu</span>` and I am able to match all my text elements.
