### ISSUE TITLE
Translations Missing

### ISSUE THREAD

**Issue by markomiljkovic** [kazupon/vue-i18n#199]
I have a small question, I have used i18n and it is great but is there a way to see missing translations before starting the app and walking trough components
http://jsfiddle.net/qegsr2pn/2/

Here it is ok , but can I see all missing translation without having to traverse the app manually.
I mean when I just start app I want to see all missing translation not only when I run specific component.

Thanx in advance

**Comment by markomiljkovic** [comment]
Somebody???

**Comment by kazupon** [comment]
soory, i'm busy with wok too. :bow:
in next week, i'll check about this issue.
please wating.

**Comment by markomiljkovic** [comment]
Ok sorry for bothering you :)
Ill wait, thanx in advance

**Comment by kazupon** [comment]
Hmm, 🤔 
`vue-i18n` don't support pre(static) translation due to dynamically translation.
In part of the use case like #197 or need to performance , pre translation is desirable.

in the future, I'm thinking of supporting it.

**Comment by kazupon** [comment]
Released v7.3.0
https://github.com/kazupon/vue-i18n/releases/tag/v7.3.0
