### ISSUE TITLE
Strange warning messages 'Value of key '<<message>>' is not a string!'

### ISSUE THREAD

**Issue by mcongy** [kazupon/vue-i18n#201]
Vue version: 2.4.2
vue-i18n version: 7.0.5

Hello,

I'm using both global messages
`const i18n = new VueI18n({ locale: getCurrentUserLanguage(), messages });`
and local, component based messages:
```
i18n: {
    messages: {
      en: { msg: 'msg' },
      sk: { msg: 'msg' }
    }
  }
```

Everything works as expected. 
But when I access global messages in the component that does have local, component-based messages, I get following warning:
![image](https://user-images.githubusercontent.com/20205489/28752607-01ab90ae-7524-11e7-8c35-47b869218e55.png)

I really don't like having bloated console, just to inform me about using fallback to global-translation.
And the warning message is kind of misleading.

Am I doing something wrong? If not, please consider removing this warning message for this particular use-case.

Thanks!

**Comment by kazupon** [comment]
You can avoid with `silentTranslationWarn`.
https://kazupon.github.io/vue-i18n/en/api.html#vuei18n-class#silenttranslationwarn

**Comment by roelvan** [comment]
Yep I added this:
```
export default new VueI18n({
  locale: 'en',
  silentTranslationWarn: process.env.NODE_ENV !== 'production'
})
```

**Comment by romain-web** [comment]
Maybe it's a good point to add this use case in the documentation for [Component based localization](http://kazupon.github.io/vue-i18n/en/component.html)

**Comment by Fusseldieb** [comment]
That seems to work, but it's a workaround, because it also silences real errros, I believe.

Is it **_wrong_** to access global translation on a Component based approach? If so, why?

**Comment by kevinmarrec** [comment]
Since 8.8 there is a [`silentFallbackWarn`](https://kazupon.github.io/vue-i18n/api/#silentfallbackwarn) option that should better fit for people using [Component based localization](http://kazupon.github.io/vue-i18n/guide/component.html).

**Comment by mateuszrusiecki** [comment]
So the solution to this issue is to silence it? seriously? xD
