### ISSUE TITLE
Can't change locale/language realtime

### ISSUE THREAD

**Issue by martijnhiemstra** [kazupon/vue-i18n#202]
I am using VueJS and Vue i18n.

Part of my packages.json
    
    "vue": "^2.3.4",
    "vue-i18n": "^7.1.0",

I can use language labels like this:

`    {{ $t('logout') }}`

so everything works fine however when a user logins in I set 
    Vue.config.lang = user.language
the locale doesn't change. Somehow Vue i18n isn't changing the language when I set the Vue config  language.

**Comment by kazupon** [comment]
> Vue.config.lang = user.language

`Vue.config.lang` cannot use from v6.x later.
You need to migration to `VueI18n` class

See:
https://kazupon.github.io/vue-i18n/en/migrations.html

**Comment by martijnhiemstra** [comment]
It is unclear in the given url how you can change the locale from lets say the router.  I have tried

    VueI18n.locale = user.locale 

but that gives an undefined error. How can I change the locale where I don't have access to the VueI18n or the app object?
