### ISSUE TITLE
Сustom block i18n doesn't work

### ISSUE THREAD

**Issue by Ihor-Shevtsov** [kazupon/vue-i18n#205]
Hello
I have a problem with custom block i18n. At first I thought that the problem was local, but then I ran a demo of this feature. -> https://github.com/kazupon/vue-i18n/tree/dev/examples/sfc.
I have such warning:
[vue-i18n] Cannot parse locale messages via custom blocks.
TypeError: options.__i18n.forEach is not a function
[vue-i18n] Fall back to translate the keypath 'hello' with root locale
[vue-i18n] Value of key 'hello' is not a string!
[vue-i18n] Cannot translate the value of keypath 'hello'. Use the value of keypath as default.

### vue & vue-i18n version
vue: 2.4.2
vue-i18n version: 7.1.1
webpack: 3.4.1

### Reproduction Link
https://github.com/kazupon/vue-i18n/tree/dev/examples/sfc

### Steps to reproduce
Just run the described steps in the link above

### What is Expected?
All text will be taken from the block i18n.

### What is actually happening?
Text is not taken from the block i18n. It's just parse key to string and put it in tag.

**Comment by MishaMykhalyuk** [comment]
+1

**Comment by Ann-Dederkal** [comment]
+1

**Comment by gefangshuai** [comment]
+1

**Comment by eminos** [comment]
+1
