### ISSUE TITLE
I can't figure out how to get vue-i18n work with v-if

### ISSUE THREAD

**Issue by cassandradanger** [kazupon/vue-i18n#207]
I have a JSON file with translations, but I can't seem to loop through the data with the v-if statement. Any thoughts?

JSON data
```
{
	"global": {
		"good": "Good",
		"morning": "morning",
		"afternoon": "afternoon",
		"evening": "evening",
		"friendlyMsg": "This is a message from your friendly staff at"
	},
}

```
vue component
```
            <div v-for="template in $t('message.global')">
                    <li>{{template}}</li>
            </div>

```

I've tried accessing $t('message.global') to loop through in several different ways - passing it in as a prop, but it doesn't get assigned correctly in the App.js file. I know the connection works, because if I list 
`<h2>{{ $t("message.global.good") }}</h2>`
that will appear as expected.

UPDATE: Looks like if I target a key directly like 
`            <div v-for="template in $t('message.global.friendlyMsg')">`
It will list out each character in that string
- T
- h
- i
- s
- 
- i
- s
- 
etc

Just having trouble figuring out how to loop through.
Thanks in advance!

**Comment by VADS** [comment]
Did you find a solution for this?
