### ISSUE TITLE
Uncaught ReferenceError: settings is not defined

### ISSUE THREAD

**Issue by yurimindfreak** [kazupon/vue-i18n#209]
Hi!

I put my language properties file under resources/bundle/Messages_**.properties

I imported the plugin:

`
        <script src="resources/js/jquery.i18n.properties.min.js" type="text/javascript"></script>`

and loaded in my .js file:

`$(document).ready(function () {
    jQuery.i18n.properties({
        name: 'Messages',
        path: 'resources/bundle/',
        mode: 'both',
        language: 'en',
        async: true,
        callback: function () {
            console.info('Iniciando internacionalização');
            $('[data-i18n]').each(function (e) {
                var tagName = $(this).get(0).tagName;
                switch (tagName) {
                    case "A":
                        $(this).html(jQuery.i18n.prop($(this).attr("data-i18n")));
                        break;
                }
            });
        }
    });
});`

but I`m getting the following error:

> jquery.i18n.properties.min.js:9 Uncaught ReferenceError: settings is not defined
    at Object.h.i18n.prop (jquery.i18n.properties.min.js:9)
    at HTMLAnchorElement.<anonymous> (default.js:35)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at Object.callback (default.js:31)
    at v (jquery.i18n.properties.min.js:1)
    at n (jquery.i18n.properties.min.js:1)
    at jquery.i18n.properties.min.js:1
    at Object.success (jquery.i18n.properties.min.js:2)
    at i (jquery.min.js:2)

what am I doing wrong?

**Comment by kazupon** [comment]
Thank you for your reporting!
However, Vue-i18n is not **jQuery plugin**.
it looks like a jquery plugin problem.

**Comment by yurimindfreak** [comment]
I'm sorry! I posted in the wrong project!
