### ISSUE TITLE
Can i18n be done in the compile stage

### ISSUE THREAD

**Issue by Kingwl** [kazupon/vue-i18n#212]
### vue & vue-i18n version
vue: all
vue-i18n: all

### Reproduction Link

\-
### Steps to reproduce
\-
### What is Expected?

I have to do i18n at runtime and need to replace all the text
so can we insert a hook into compiler to use it translate the text?

### What is actually happening?

We do not need to manually replace all the text

**Comment by kazupon** [comment]
related #197 

I'll sometime soon plan to support pre-translte optimaization with vue compiler hooks (`translateNode`,`genCode`, etc ...). 😉

**Comment by kazupon** [comment]
Released v7.3.0
https://github.com/kazupon/vue-i18n/releases/tag/v7.3.0
