### ISSUE TITLE
Error using the $d formatting date in ios 9.0.2

### ISSUE THREAD

**Issue by chenyanfa729** [kazupon/vue-i18n#215]
### vue & vue-i18n version
v2.4.0 , v7.1.1

### Reproduction Link
[https://jsfiddle.net/yanfaChen/bjfgo9L2/26/](https://jsfiddle.net/yanfaChen/bjfgo9L2/26/)

### Steps to reproduce
The above demo was opened in the **ios 9.0.2**,  **safari**, and the page was not rendered properly.

### What is Expected?
Pages can render normally

### What is actually happening?
Use the $d formatting date, The page does not render anything, and the viewing console finds the error: `Can't find variable: Intl`

**Comment by rodneyrehm** [comment]
While Intl support is [pretty good](http://caniuse.com/#feat=internationalization) you'll need to load the [polyfill](https://www.npmjs.com/package/intl) for iOS 9, IE10, Android 4.3. Unfortunately that's only hinted at in the [docs](https://kazupon.github.io/vue-i18n/en/api.html#availabilities)

**Comment by kazupon** [comment]
As @rodneyrehm mentioned, you need to load the polyfill.
You can check with using `VueI18n.availabilities` API.
(Sorry, my poor docs :bow:)
