### ISSUE TITLE
Path won't change from EN to FR

### ISSUE THREAD

**Issue by jaubut** [kazupon/vue-i18n#217]
Hi, I've tried to implement vue-i18n to my nuxtjs project with this [tuto](https://nuxtjs.org/examples/i18n/) and it load correctly, it does add the routes but it seems like it cant go get the correct json file and it doesnt update from fr to en when I switch from en to fr.. it will go /fr/ and when I click again /fr/fr/fr/fr/fr on and on.. Any tips ? 

And here is the [branch](https://github.com/jaubut/jechanvre_web/tree/international)

I use the last 7.1.2 version.

Thanks..

**Comment by kazupon** [comment]
sorry, late for reply 🙇 

I tried to check your reproduction repo, Unfortunately I could not reproduce it.
As long as I confirm your reporting content, I seem it's a problem with nuxt.js, not vue-i18n.

You can ask nuxt.js for help at [issues](https://github.com/nuxt/nuxtjs.org/issues). :)
