### ISSUE TITLE
Dynamic localizations from server

### ISSUE THREAD

**Issue by godzsa** [kazupon/vue-i18n#219]
It would be nice to have the option to dynamically update the locale with data from the server.

For example if you have a webshop with multiple languages, and the admin can upload products with names, descriptions in all of the supported languages. You only want to download the translations for the products being displayed.

e.g.

```html
<template>
     <div v-for="product in products">
         <img :src="product.img">
         <h3 class="title">{{ $t( product.id + '_title' ) }}</h3>
         <p class="description"> {{ $t(product.id + '_description') }} </p>
     </div>
</template>

<script>
  import axios from 'axios'
  
  function transform(serverData){...} // returns {en: {...}, de: {...}, fr: {...}}
  
  export default {
    beforeCreate: function() {
      axios.get(...)
      .then(res => this.$i18n.mergeTranslations(transform(res.data)))
      .catch(e => ... )
    }
  }
</script>
```

**Comment by arjanski** [comment]
I am also very interested in this feature! Or is there a workaround somebody knows of?

**Comment by godzsa** [comment]
I wrote a small mixin for using it with dynamic text: 

```
export default {
  methods: {
    $t: function (translate) {
      if (typeof translate === 'string') {
        return this.$i18n.t(translate)
      } else if (translate === void 0) {
        return this.$i18n.t('loading')
      }
      return translate[this.$i18n.locale]
    }
  }
}
```

And I use it this way:
`<p>{{ $t(hello) }}</p>` where hello is in the `data` field:

```
data(){
   return { hello: null }
}
```

And I init in in the beforeMount:

```
beforeMount(){
   axios.get(...).then(data=>this.hello = data.hello)  // data.hello looks something like this { 'en': 'Hello', 'de': 'Halo' } 
}
```

**Comment by arjanski** [comment]
This also seems to be one solution for the problem if I'm not mistaken:

http://digital-cult.com/vue-i18n-async-loading-languages/

**Comment by kazupon** [comment]
close, due to exists workaround the below:
https://kazupon.github.io/vue-i18n/en/lazy-loading.html
