### ISSUE TITLE
Bind translations in v-for loops: does not work?

### ISSUE THREAD

**Issue by Qathom** [kazupon/vue-i18n#22]
Hello,

First of all, thank you for sharing this wonderful plugin! :)
I am facing a problem with loops.
In fact, the plugin returns the default value in loops.

**Example:**
```javascript
<ul class="list-files">
	<li v-for="file in files">
		<ul class="file-actions">
			<li><a href="#" @click="insertFile">{{ $t('insert') }}</a></li>
			<li><a href="#" @click="deleteFile">{{ $t('delete') }}</a></li>
		</ul>
		<div class="file-name">
			<a href="{{ file.url }}" title="{{ file.name }}">{{ file.name }}</a>
		</div>
	</li>
</ul>
```

Am I doing something wrong?
Thanks in advance.

**Comment by kazupon** [comment]
Thank you for your reporting !!
Can you provide the reproduction code with jsfiddle or other please ?

**Comment by Qathom** [comment]
Oups.
I ran several tests and I've realized that I forgot to update my translated locales, so the default value is shown. But I have now a suggestion about this: what do you think if it possible to set a default value or if the plugin returns a simple warning if the keypath is not present?

**Comment by kazupon** [comment]
I'll plan to consider simple warn outputting to console.

**Comment by Qathom** [comment]
Great! Thanks @kazupon :)
