### ISSUE TITLE
Default locale based on browser settings?

### ISSUE THREAD

**Issue by miloandco** [kazupon/vue-i18n#220]
As title says, I can't see anything regarding this in the docs. Am I missing something?

**Comment by oboshto** [comment]
```
const i18n = new VueI18n({
  locale: navigator.language,
  messages: {
    // your messages
  }
});
```

**Comment by kazupon** [comment]
In about it, @oboshto  mentioned .
You can resolve it. 😉

**Comment by fungiboletus** [comment]
Shouldn't it be the default ?

**Comment by praetp** [comment]
@fungiboletus I would assume so...

**Comment by justice47** [comment]
For those who use 2-chars code of the language in i18n ('en', 'ru', etc.) you can easily translate `navigator.language` to that format via:
`locale: navigator.language.split('-')[0]`

**Comment by zolomatok** [comment]
The answer to [this](https://stackoverflow.com/questions/8199760/how-to-get-the-browser-language-using-javascript) question is saying `locale: navigator.language || navigator.userLanguage`

Plus, it might be a good idea to clip the second half of the locale string as per justice47's comment.

**Comment by fjeddy** [comment]
@zolomatok Why would that be a good idea? Unless you used two characters from the get-go and destroyed the ability to actually support all languages and just support one single language per country.

**Comment by zolomatok** [comment]
@fjeddy Hmm, yeah fair point.
TBH I was just thinging of en-US and en-GB, since not many sites bother with that distinction, but you’re right, there are countries where the distinction matters.

**Comment by zolomatok** [comment]
@fjeddy Although this is about dialects of the same language, not multiple languages in the same country. That’s still supported this way, since it’s the language tag you keep, not the dialect part.

**Comment by fjeddy** [comment]
@zolomatok You couldn't be more wrong, there are multiple countries, including my own, that has and use multiple completely different languages that have nothing to do with one another (As in, not dialects).

nb_NO
nn_NO
se_NO

In this case, `nb` and `no` are interchangeable, it's just the typing that's different (A dialect), but absolutely no one that speaks `nb` or `nn` will understand a word of what `se` is saying. As it is a completely different language within the same country. Norway isn't alone here, there are plenty of countries that has multiple, independent languages, France for one.

**Comment by zolomatok** [comment]
@fjeddy 

Yupp, I know that, but the thing I wrote about stripping the second half of the string (“_NO”) doesn’t create a problem in this regard.

You are left with `nb`, `nn` or `se` and if your site supports that, you can switch to that language for the user. It doesn’t matter in this case, that the user’s country itself is Norway, what matters is the actual language.

**Comment by fjeddy** [comment]
Yes, you're right, there is still, just no need to do it this way tho.

**Comment by zolomatok** [comment]
@fjeddy 

If you want to _store_ the locale, than sure, I agree, store the whole thing for sure.

But my impression was this is just a frontend question and the OP just want to check and set the language locally, without storing the value.

**Comment by fjeddy** [comment]
@zolomatok Not what I mean.

He is obviously storing and keep his own translations and language files as `en` and `nb`. Otherwise, it wouldn't be necessary to split it when defining the locale. If he made the language as `en-US` it wouldn't be a problem.

You create the languages with the full ISO code and write code to check if you have the exact language the user wants, then you check if you have the language code he wants, and if both of them fail, you fall back to default.

**Comment by saltcute** [comment]
In an ideal situation one should never use only the two letter code for a language. A perfect example is `zh-CN`, `zh-TW` and `zh-HK`. They all have largely different writing system and vocabulary, while still being the same `zh` Mandarin Chinese.

**Comment by fjeddy** [comment]
> In an ideal situation one should never use only the two letter code for a language. A perfect example is `zh-CN`, `zh-TW` and `zh-HK`. They all have largely different writing system and vocabulary, while still being the same `zh` Mandarin Chinese.

The language code in this situation is `TW` `HK` and `CN`. Not `zh`

**Comment by saltcute** [comment]
> The language code in this situation is `TW` `HK` and `CN`. Not `zh`

The language of Mandarin Chinese is represented as `zh` in ISO-639-1, and it makes sense if you know the kinda complicated geopolitics and history of the region. 

Also those are not languages, but country/region names. I wouldn't think it to be a good idea to name them like that. I mean, no one speaks American or Brazilian.
