### ISSUE TITLE
Prototype based i18n custom block

### ISSUE THREAD

**Issue by itveev** [kazupon/vue-i18n#224]
Hello, my suggestion is the following.
Now in section "component based localization" says that "if the component doesn't have the locale message, it fallbacks and localizes global locale message". It would be great to add prototype based localization - if the Child component doesn't have the locale message, it fallbacks and localizes Parent locale message. This feature should support i18n custom block.

list.vue:
```
<template lang="pug">
div
  h5(v-text="$t('title')")
    ul
      li(v-for="item in args.items")
</template>
<script lang="babel" type="text/babel">
  export default {
    props:['args'],
    data() {
      return {}
    }
  }
</script>
```
parent1.vue:
```
<i18n>
  {
    "en": {
      "title" : "Title 1"
    }
  }
</i18n>
<template lang="pug">
  list-vue( v-bind:args="listArgs" )
</template>
<script lang="babel" type="text/babel">
  export default {
    data() {
      return {
        listArgs:{
          items:[{ },{  }]
        }
      }
    },
    components:{
      listVue
    }
  }
</script>
```
parent2.vue:
```
<i18n>
  {
    "en": {
      "title" : "Title 2"
    }
  }
</i18n>
<template lang="pug">
  list-vue( v-bind:args="listArgs" )
</template>
<script lang="babel" type="text/babel">
  export default {
    data() {
      return {
        listArgs:{
          items:[{ },{ }]
        }
      }
    },
    components:{
      listVue
    }
  }
</script>
```
sidebar.vue
```
<template lang="pug">
div
  parent1-vue
  parent2-vue
</template>
<script lang="babel" type="text/babel">
  export default {
    data() {
      return { }
      }
    },
    components:{
      parent1Vue,
      parent2Vue
    }
  }
</script>
```
If there is a way to do it now, please, correct me.

**Comment by jansim** [comment]
Stumbled upon this as well. I was able to circumvent the problem by inheriting the parent locale messages on created:
```
created () {
  const parentI18n = this.$parent.$i18n
  if (!parentI18n) { return }

  // Inherit parent locale messages
  const messages = parentI18n.messages
  Object.keys(messages).forEach((locale) => {
    this.$i18n.mergeLocaleMessage(locale, messages[locale])
  })
}
```

**Comment by kazupon** [comment]
in about i18n custom block based on property, In i18n, I don't plan to extend it in the future due to the complexity of managing component messages resources and the difficulty of understanding the context of localize.

In vue-i18n, local scope and global scope messages resources are the best practice.

thanks your suggestions!
