### ISSUE TITLE
V-IF with CLASS weird V-T directive behaviour

### ISSUE THREAD

**Issue by karol-f** [kazupon/vue-i18n#226]
### vue & vue-i18n version
vue@2.4.4, vue-i18n@7.3.0

### Reproduction Link
https://www.webpackbin.com/bins/-Kv7F4nCE6JXglvqh0WZ

### Steps to reproduce
- V-IF with any class attribute added, V-T directive appended inside
- V-ELSE with V-T directive on it

### What is Expected?

Toggling translation would work.

### What is actually happening?
Toggling V-IF creates V-ELSE translation inside it on top of correct translation

**Comment by kazupon** [comment]
Thank you for your reporting!

I seem that this behavior is bug of vue when used custom directive together with v-else(v-if).
see the small repro link
https://jsfiddle.net/fjfnxq2r/2/

**Comment by mstefaniak** [comment]
It looks the same. Did you pass it by to Vue developers? Is there a bug reported? Could you link it?

**Comment by kazupon** [comment]
This behavior is spec of Vue.
As the workaround, You can use `key` special attribute.
See the [docs](https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key)
