### ISSUE TITLE
Please add option to configure interpolation rules

### ISSUE THREAD

**Issue by alfeg** [kazupon/vue-i18n#229]
Please add ability to configure way interpolation works, so it be possible to use double curly `{{ }}` for params, like it done in i18next lib.

We have sevreal apps using same localization files. Historically double curly used everywhere. 

### vue & vue-i18n version
2.4.4 & 7.3.1

**Comment by alfeg** [comment]
Nevermind. Just used custom formatter.
```js
const RE_TOKEN_NAMED_VALUE = /^(\w)+/
const RE_TOKEN_OPEN = "{{"
const RE_TOKEN_CLOSE = "}}"

export function parse(format) {
    const tokens = []
    let start = 0, end = 0;

    while (end != -1 && start != -1) {
        start = format.indexOf(RE_TOKEN_OPEN, end);

        if (start == -1) break;

        if (start - end > 0) {
            tokens.push({ type: 'text', value: format.substring(end, start) });
        }

        end = format.indexOf(RE_TOKEN_CLOSE, start);

        if (end != -1) {
            const text = format.substring(start + RE_TOKEN_OPEN.length, end);

            const type = RE_TOKEN_NAMED_VALUE.test(text)
                ? 'named'
                : 'unknown'

            tokens.push({ value: text, type })

            end += RE_TOKEN_CLOSE.length; // advancing end pointer at the end of closing braces
        }
    }

    // append last part of text
    if (end != -1) {
        const text = format.substring(end);
        if(text.length > 0)
            tokens.push({ type: 'text', value: text });
    }

    return tokens
}
```

**Comment by purell** [comment]
+1

I will be more happy with `{{` than `{`. First for escaping. This should not be a big work to expose interpolation rules ?

On server side I'm using **i18next** package directly and by default the suffix/prefix is `{{`.

**Comment by julian91** [comment]
hey dude, thanks heaps for making that effort, but I'm sort of confused how to use this custom formatter! any chance you could let me know?

**Comment by nevenduranec** [comment]
@alfeg where should this code example of yours go inside the project? I tried using it in https://kazupon.github.io/vue-i18n/guide/formatting.html#custom-formatting but it didn't work.

**Comment by kevrousso** [comment]
Interested as well!
How would an approach like this be done with "Hello :attr" using the custom formatter for example?

**Comment by changavila** [comment]
@kevrousso, i dont think you can. There's no easy way but to Create your own formatter for it. For me, i used the existing BaseFormatter and changed how its checks for the tokens. As an example, https://github.com/kazupon/vue-i18n/issues/229#issuecomment-335433635
This is what i changed for the parser for it to handle `{{ }}`
