### ISSUE TITLE
Need little help with interpolation

### ISSUE THREAD

**Issue by XakepSDK** [kazupon/vue-i18n#234]
Hi guys! I have this:
```html
<i18n path="forums.description" tag="p">
    <a place="link" href="https://example.com/" v-t="'forums.link'"></a>
</i18n>
```
My translation contains this:
```
"description":"Some text here\n{link}.\nOther text here.",
"link":"Forums"
```
Description draws, but {link} dissapears.
I tried `$t` notation, but this doesn't help.

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry for my late reply. 🙇 
Could you provide the minimum repo code via GitHub repo or [codesandbox.io](http://codesandbox.io) please? 🙏

**Comment by kazupon** [comment]
close due to in-activity
