### ISSUE TITLE
Avoid using reserved keywords in expression "continue" in a t function

### ISSUE THREAD

**Issue by barnabas-szekeres** [kazupon/vue-i18n#24]
When i want to write t function in a template i get this warning. It caused by the "continue" word in a string. Is it normal? :)

**Example:**
In the template file: {{ $t('continue-with-new-account') }}

Then the console says:
[Vue warn]: Avoid using reserved keywords in expression: 'continue-with-new-account'

**Comment by sagaio** [comment]
Try  `_` instead of `-`. Think javascript interprets it as a subtraction, but I'm not sure.

**Comment by kazupon** [comment]
This issue is occuring to use the parser of Vue.
In future, I'll consider to improve. 😺 

If you want to avoid the this issue,  Try `_` instead of `-`
