### ISSUE TITLE
Single file component and using Vue.component() + component tag

### ISSUE THREAD

**Issue by o2genum** [kazupon/vue-i18n#241]
I have a constraint set by a library that I have to use `Vue.component('app', App)` in `entry.js` and `<App></App>` in `index.html`. I asked the [question on SO](https://stackoverflow.com/questions/46869516/vue-i18n-single-file-component-initialization-with-neutronium-library). Can't seem to understand if it's possible to do this.

**Comment by kazupon** [comment]
Close (due to page not found)
