### ISSUE TITLE
Nuxt module or plugin?

### ISSUE THREAD

**Issue by lucpotage** [kazupon/vue-i18n#245]
Thank you for providing a Vue i18n module for Nuxt.
After digging into the module example and reading the official Nuxt docs, it seems the approach is totally different. One is a module integration, the other, a plugin integration.

- https://github.com/kazupon/vue-i18n/tree/dev/examples/module/nuxt
- https://nuxtjs.org/examples/i18n/

Could you explain the pros and cons of using one solution over another?

I also didn't find a way to use the `$t()` function into the template script to change the head title for instance. Any idea on how to achieve this?

Thank you.

**Comment by sudhir600** [comment]
did you found any solution for how to change data inside `<head>`.
i am using this - 
```
fetch ({ store, params }) {
        var metaDetails = {
            pageTitle: 'Welcome! this is test title',
            keyword: 'this is test meta keyword',
            description: 'this is sample description from home page'
        }
        store.commit('setMetaData', metaDetails)
    }
```

but i have issue with locale. how to call `$t()` here?

**Comment by kazupon** [comment]
`examples/module/nuxt` is advanced example that high performance localization with using Vue compiler and `v-t` for nuxt.js
I recommend that read the below my blog:
https://medium.com/@kazu_pon/performance-optimization-of-vue-i18n-83099eb45c2d

if you want to use `$t` at Nuxt.js, you should use You should follow the Nuxt example.
