### ISSUE TITLE
allow default imports from modules

### ISSUE THREAD

**Issue by khanharis87** [kazupon/vue-i18n#250]
### Reproduction Steps?
- Upgrade to vue.js 2.5
- remove “allowSyntheticDefaultImports”: true from tsconfig.json (as users are required to use ES-style imports in all cases.)

### What is Expected?
```
import VueI18n from 'vue-i18n'
```
to work. 

### What is actually happening?

Typescript error TS1192 : Module '"project/node-modules/vue-i18n/types/index"' has no default export

**Comment by khanharis87** [comment]
```export default VueI18n;```
than
```export = VueI18n; ```
inside _types/index.d.ts_ fileworks for me, but I am unable to pass all the test

**Comment by ryall** [comment]
Why was this closed? The issue is still present from what I can see.

**Comment by gouflv** [comment]
Same problem in current version

**Comment by gouflv** [comment]
Same problem in current version

**Comment by kazupon** [comment]
sorry :bow:
released v7.3.3
please check it!
https://github.com/kazupon/vue-i18n
