### ISSUE TITLE
Set locale dynamically at runtime

### ISSUE THREAD

**Issue by Francisc** [kazupon/vue-i18n#253]
Hello,

It unclear to me from the docs if using `setLocaleMessage()` is how you get dynamic locales at runtime to work. There are many articles about how to do that at build time, but none that I could see about runtime changes.

To give an example, here is what I mean in the form of a timeline:
1. App loads, reads locale requirement.
2. Makes AJAX call to fetch the appropriate JSON file (e.g. en.json).
3. Calls `setLocaleMessage()` as shown below:
```
const i18n = new VueI18n({...});
...
i18n.setLocaleMessage('en', {...pathsHere});
...
//Later on:
//After another AJAX call to fetch fr.json:
i18n.setLocaleMessage('fr', {...pathsHere});
```

**Comment by tvld** [comment]
This works for me ``locale_switcher.vue``:
```js
<template>
  <div class="locale-switcher">
    <!-- {{ initLocale() }} -->
    <b-nav-item-dropdown :dropup="dropup" :text="dropdownLbl" right>
      <b-dropdown-item
        class="locale-link"
        v-for="locale in locales"
        :key="locale.id"
        @click="setLocale(locale)"
        :class="{ 'is-current': locale === activeLocale }"
        href="#">
        {{ getLanguageString(locale) }}
      </b-dropdown-item>
    </b-nav-item-dropdown>
  </div>
</template>

<script>

  import Vue from 'vue'
  // Restore locale from cookie, if it was set
  import VueCookie from 'vue-cookie'
  Vue.use(VueCookie)

  const localeStrings = {
    en: "English",
    nl: "Nederlands",
    ru: "Russian",
    ua: "Ukrainian",
    fr: "Français",
    de: "Deutsch"
  }

  Vue.config.lang = VueCookie.get('locale') || 'en'
  console.log("Locale from cookie = " + Vue.config.lang + ": language = " + localeStrings[Vue.config.lang])

  export default {
    props: {
      locales: {
        type: Array,
        default: ['en']
      },
      showFull: Boolean,
      dropup: Boolean,
      locLabel: {
        type: String,
        default: ''
      }
    },
    data: function () {
      return {
        activeLocale: Vue.config.lang
      }
    },
    computed: {
      dropdownLbl: function () {
        return this.locLabel ? this.locLabel : this.activeLocale
      }
    },
    methods: {
      setLocale: function (locale) {
        Vue.config.lang = locale
        this.activeLocale = locale
        this.$cookie.set('locale', locale)
        this.$i18n.locale = Vue.config.lang
        console.log("New locale = " + Vue.config.lang + ": language = " + localeStrings[Vue.config.lang])
      },
      getLanguageString: function (locale) {
        return this.showFull ? localeStrings[locale] : locale
      }
    }
  }
</script>
```
And as component:
```html
  <locale-switcher :locales="['en', 'nl']" :show-full="true" ></locale-switcher>
````

**Comment by ABleas** [comment]
@BenoitRanque that solution is very nice, thanks!

**Comment by marouim** [comment]
@BenoitRanque So easy compared to other solutions I've seen ! Thanks a lot.
just a quick one.. this.$root.i18n.locale didn't work...  this works  this.$locale.

**Comment by mekeor** [comment]
@kazupon Why do you think this issue is solved?

Personally, I could work this issue around like this:
```js
// change global locale like this in any component:
this.$root.$i18n.locale = 'newLocale';
```
```js
// then, use the global locale like this in any (other or the same) component:
this.$t('path', this.$root.$i18n.locale, someParameter, anotherParameter);
```

IMHO you can find the best (but still bad) documentation regarding this here: https://kazupon.github.io/vue-i18n/en/migrations.html#instance-properties @kazupon Do I see correctly that `$i18n` isn't documented anywhere else than there?

**Comment by mekeor** [comment]
There should be some easy way to change the global language/locale at run-time / dynamically and it should be documented very well and at a central point because this IMHO is an essential feature of this type of library.

**Comment by outime** [comment]
Any update about this? I'm a bit surprised that it got closed by @kazupon since I would also say it's a missing core feature.

**Comment by Gecko222** [comment]
+1

**Comment by pggalaviz** [comment]
+1

**Comment by Jserrano12** [comment]
+1

**Comment by olvenmage** [comment]
Place it in a store?

**Comment by DMouroutis** [comment]
I don't like to use this.$root in general so my solution since I'm using vuex was this:

On **i18n.js** I use a dynamic locale value from a state getter with a fallback as well.

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import store from '@/store.js'

Vue.use(VueI18n)

export default new VueI18n({
  locale: store.getters.getLangKey || 'en',
  messages: loadLocaleMessages()
})
```

**Comment by gdebn** [comment]
This works perfectly for me. You just have to access to the i18n object directly and change its params there.

`this.$root._i18n._vm.locale`

**Comment by Ahmed7fathi** [comment]
> I don't like to use this.$root in general so my solution since I'm using vuex was this:
> 
> On **i18n.js** I use a dynamic locale value from a state getter with a fallback as well.
> 
> ```
> import Vue from 'vue'
> import VueI18n from 'vue-i18n'
> import store from '@/store.js'
> 
> Vue.use(VueI18n)
> 
> export default new VueI18n({
>   locale: store.getters.getLangKey || 'en',
>   messages: loadLocaleMessages()
> })
> ```

this require refreshing the page any other good one ?
