### ISSUE TITLE
cant resolve correct if use CustomFormatter

### ISSUE THREAD

**Issue by aKaigege** [kazupon/vue-i18n#254]
if you use this ,cant resolve correct。
```
  messages: {
    'en-US': {
     exp : 'this xxx {0}'
     exp1 : 'test'
    },
```
```
<i18n>
<a></a>
</i18n> 
```

html:
**this xxx [objectobejct]**

`export default class CustomFormatter {
  constructor (options = {}) {
    this._locale = options.locale || 'en-US'
    this._formatter = new MessageFormat(this._locale)
    this._formatter.setIntlSupport(true)
    this._caches = Object.create(null)
  }

  interpolate (message, values) {
    let fn = this._caches[message]
    if (!fn) {
      fn = this._formatter.compile(message, this._locale)
      this._caches[message] = fn
    }
    return [fn(values)]
  }
}`

**Comment by kazupon** [comment]
Thank you for your reporting!
Sorry for my late reply. 🙇 
Could you provide the minimum repo code via GitHub repo or [codesandbox.io](http://codesandbox.io) please? 🙏

**Comment by kazupon** [comment]
close (due to in-activity)

**Comment by Tcheikovski** [comment]
Hello and thank you for your work!
I'm having the same issue here, When using i18n components with "messageformat" custom formatter, the nested values are displayed like "[object Object]".

I'm using the same code as you custom formatting example [here](https://github.com/kazupon/vue-i18n/tree/dev/examples/formatting/custom).

Here's my code:
```
// pages/Home.vue
<i18n v-if="!verified" path="sentence.sendVerification">
    <a href="#" place="link">{{ $t('word.here') }}</a>
</i18n>
```

The language file looks like:
```
// lang/fr.json
{
    ...
    "sentence": {
        ...
        "sendVerification": "Cliquez {link} pour envoyer le mail de confirmation."
        ...
    },
    "word": {
        ...
        "here": "ici"
        ...
    }
    ...
}
```

And the output is:
> Cliquez [object Object] pour envoyer le mail de confirmation.

I also tried without the "place" prop and the numeric placeholder, but the result is the same.

Do you know how to fix this? Is there something I did wrong or forgot ?
Thank you ! 😃

**Comment by antoineguillaume** [comment]
Hi,

I have exactly the same issue as @Tcheikovski and the problem occurs only when I'm using i18n functional component. Did someone find a solution ?

Thanks for any help !
