### ISSUE TITLE
automatic rerender of translated data properties

### ISSUE THREAD

**Issue by measwel** [kazupon/vue-i18n#258]
When I set a translation like this:
`v-bind:label="$t('message.website')"`
Then the view is updated at once when I change the locale.

However, if I set a translation for a data item like this:
`label: this.$t('message.labelimage')`
Then the view is not updated when changing the locale. 

I have to reload the page to see the translation. Is there a way to have the view rerended automatically with new translations for data items too?

**Comment by kazupon** [comment]
close (fixed at #260)

**Comment by mertindervish** [comment]
I'm facing the same issue in v7.3.3. After changing locale the translations used in data() are not updated. Reproduction link: https://codepen.io/mertindervish/pen/jYmgya

**Comment by sunshuaisky** [comment]
@mertindervish  You should use v-t.  link:https://codepen.io/anon/pen/mpwqoN

**Comment by mertindervish** [comment]
My use case requires the translation to be accessible by the component in created(). I solved the problem using computed properties insted of data().
