### ISSUE TITLE
7.3.3 throws error while using $t with function.apply

### ISSUE THREAD

**Issue by wxsms** [kazupon/vue-i18n#264]
### vue & vue-i18n version
2.5.11, 7.3.3

### Steps to reproduce

```javascript
let i18nHandler = function () {
  // `this` is the Vue component instance, which has vue-i18n installed
  const vuei18n = Object.getPrototypeOf(this).$t
  return vuei18n.apply(this, arguments)
}
```

throws an error:

```
Error in render: "TypeError: Cannot read property '_t' of undefined"
```

### What is Expected?

No error (as in 7.3.2)

### What is actually happening?

Error in 7.3.3

**Comment by wxsms** [comment]
I have make a workaround temporary:

```javascript
try {
  return vuei18n.apply(this, arguments)
} catch (err) {
  return this.$t(...arguments)
}
```

**Comment by gefangshuai** [comment]
i also have the problem!!!
![image](https://user-images.githubusercontent.com/3143306/34381880-54004532-eb46-11e7-90b5-331034cc18cd.png)

**Comment by gefangshuai** [comment]
![image](https://user-images.githubusercontent.com/3143306/34382007-1944d920-eb47-11e7-943c-32c2d946fa77.png)
the first can pass，but the second report the error！！

**Comment by PierreRambaud** [comment]
Sam problem here!

**Comment by kazupon** [comment]
Thank you for your feedback.
Sorry for my late reply. 🙇 

You need to use `$t` in `Vue` prototype context.
