### ISSUE TITLE
why change this.$i18n.locale can auto change value that use $t

### ISSUE THREAD

**Issue by sunchenguang** [kazupon/vue-i18n#267]
### vue & vue-i18n version
ex: 2.5.10, 7.3.2

### Steps to reproduce
click a button, then change web app's i18n, 
```
this.$i18n.locale = lang
```

### What is Expected?
work as expected

### What is actually happening?
i want to know why change VueI18n instance's locale property, then all place that use `$t('i18nView.success')` can auto change theris value to corresponding i18n。

i search in source code, but i don't find it's reason.

**Comment by kazupon** [comment]
Thank you for your reporting!
Could you provide the minimum repo code via GitHub repo or [codesandbox.io](http://codesandbox.io) please?

**Comment by kazupon** [comment]
close (due to in-activity)
