### ISSUE TITLE
Why the way of 'this.$t() used in data ' binding can't  auto change when click the switch btn

### ISSUE THREAD

**Issue by lilywang711** [kazupon/vue-i18n#271]
### vue & vue-i18n version
ex: ^2.5.2, ^7.3.4

### Reproduction Link
问题描述: 在data中通过this.$t()绑定的方式，切换语言时不会主动变化
在data中绑定vue-i18n的值
![image](https://user-images.githubusercontent.com/17040010/34716961-6ddd3f7a-f56c-11e7-944d-197b7b86a1ed.png)
中英文的key
![image](https://user-images.githubusercontent.com/17040010/34717009-90eb377e-f56c-11e7-9504-ec6b442f1b47.png)

### What is Expected?
期待的是，切换英文时，下面表格的表头会切换成英文
![image](https://user-images.githubusercontent.com/17040010/34717101-d8734848-f56c-11e7-9ea6-07cbefcb6483.png)
### What is actually happening?
实际上，通过这种方式绑定的，切换时，不会实时更新成英文，必须得刷新页面才可以
  请问，有什么办法可以让这种方式也可以 自实时更新吗

**Comment by kazupon** [comment]
Thank you for your feedback.
Sorry, i cannot speak chinese.
I hope you'll speak in english. 🙏

**Comment by GreedyPirate** [comment]
I hava the same problem, too, when I define a variable in Vue data funciton like this
`data() {
        return {
          text: this.$t('lang.name')
        }
}`
then I change the locale by a button click event
`this.$i18n.locale = 'zh'`
however the 'text' did not change it's value

**Comment by ding-js** [comment]
same problem.
this.$t in data not work when changed this.$i18n.locale
Here is [probelem demo](https://codepen.io/dingjs/pen/paymJY)

**Comment by WillieYang** [comment]
I do have same problem too, if I use this.$("data") in data property and then assign it to a value which would be used in the corresponding template, it would not be changed automatically when I click the swithch locale button (this button is used to change the value of locale by this.$i18n.locale), and the most weird part is that, when I change the value of locale manually, the data on the webpage would be changed automatically, such weird...

**Comment by GreedyPirate** [comment]
@kazupon need your help

**Comment by kazupon** [comment]
sorry,  my job work is very busy. 🙇
Please wait 🙏

**Comment by vBandiTv** [comment]
Here is an example of the problem:
https://codesandbox.io/s/z2nwwnw9px

**Comment by kazupon** [comment]
this is not problem of vue-i18n.
see the https://github.com/kazupon/vue-i18n/commit/d007ac8e91261dda63eb9ce95cf2b7bb73bf7968

**Comment by LeonWuV** [comment]
I have same problem too， and  i solved it with this way.
####  wrong way：
![1545126803 1](https://user-images.githubusercontent.com/21948236/50146256-4f743a80-02ee-11e9-949d-f501f2564a87.jpg)
![1545126878 1](https://user-images.githubusercontent.com/21948236/50146261-51d69480-02ee-11e9-95c9-2adcc41b8e1f.jpg)
####  right way:
![1545126929 1](https://user-images.githubusercontent.com/21948236/50146290-66b32800-02ee-11e9-87d7-9df4398377cc.jpg)
![1545126846 1](https://user-images.githubusercontent.com/21948236/50146291-687ceb80-02ee-11e9-8510-5e65751032cf.jpg)

Hope I can help you!

**Comment by curryhh** [comment]
你好怎么解决的？

**Comment by GreedyPirate** [comment]
> 你好怎么解决的？

Chinese too， so here is a solution：use computed instead of data function， like below code
![image](https://user-images.githubusercontent.com/14834990/63430157-7c18bd00-c44e-11e9-93af-a1d8a322ca80.png)
![image](https://user-images.githubusercontent.com/14834990/63430203-9f436c80-c44e-11e9-8815-6a1d5eb48cd2.png)
I'm gonna unsubscribe this issue now, good luck

**Comment by curryhh** [comment]
> > 你好怎么解决的？
> 
> Chinese too， so here is a solution：use computed instead of data function， like below code
> ![image](https://user-images.githubusercontent.com/14834990/63430157-7c18bd00-c44e-11e9-93af-a1d8a322ca80.png)
> ![image](https://user-images.githubusercontent.com/14834990/63430203-9f436c80-c44e-11e9-8815-6a1d5eb48cd2.png)
> I'm gonna unsubscribe this issue now, good luck

Thank you for your answer

**Comment by codelhf** [comment]
```
methods: {
   itemRules() {
      return {
        username: [{ required: true, message: this.$t('users.itemRules.username'), trigger: 'blur' }],
        description: [{ required: true, message: this.$t('users.itemRules.description'), trigger: 'blur' }]
      }
    }
}
```
I used this way, because computed aways undefined
