### ISSUE TITLE
Force UTF-8 Encoding Route-Name (After Reloading The Path)

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [kazupon/vue-i18n#274]
### vue & vue-i18n version
ex: 2.1.0, 5.0
nuxt: 1.0.0-rc11
vue-i18n: ^7.4.0

### Reproduction Link

1. use any repo that uses `vue-i18n` and `nuxtJS`
like this: https://github.com/paulgv/nuxt-i18n-routing
```
a. clone repo
b. yarn
c. change any route-name to another language different from Latin.
d. go to page of the route-name, it should work fine.
e. try to refresh you will get an error!!!!
```
### Steps to reproduce

2. try to translate any `route-name` to another language like `Arabic` or `Chinese`.
```
const ROUTES_ALIASES = {
  about: {
    fr: '/周有七天',
    en: '/about-us'
  },
  category: {
    fr: '/categorie'
  },
  'category-slug': {
    fr: '/categorie/:slug'
  }
}
```

3. after click to button that direct to the path `Works Fine!`, but after refresh the page i get `The Error`!!
`layouts/default.vue`
```
<nuxt-link :to="getLocalizedRoute({ name: 'about' })" class="button--green">
        {{ $t('labels.about') }}
</nuxt-link>
```
the link direct to `about` page and the URL: `http://localhost:3000/fr/周有七天`
everything fine! Until refresh the current page, then i get an error.

4. i have tried another `Characters` different from `Latin` the same error.
```
const ROUTES_ALIASES = {
  about: {
    fr: '/من-نحن؟',
    en: '/about-us'
  },
  category: {
    fr: '/categorie'
  },
  'category-slug': {
    fr: '/categorie/:slug'
  }
}
```
5. any text writed in `Latin Characters` works fine. 

### What is Expected?
after refresh the page that have the `translated route-name`:
`http://localhost:3000/fr/周有七天`
i get error.

### What is actually happening?
navigation between `links` is fine, but after refreshing the page transfer to error!!!

**Comment by kazupon** [comment]
Thank you for your feedback!
However, vue-i18 is not expected this usage.  
I hope you can other workaround. 🙏

**Comment by Chrisimir** [comment]
I am experiencing the same issue as @NadhirBoukhenifra but with russian. The nuxt-link works fine, but when I reload, it can't find the route.
The translated routes are informed like this:
`nuxtI18n: {
    paths: {
      en: "/for-sale/",
      es: "/en-venta/",
      ru: "/для-продажи/",
    }
  }`

I have observed that if I go directly to the encoded path, it will work, but if I use the russian characters it won't.
So I imagine that for you, going to http://localhost:3000/fr/周有七天 won't work, but going to http://localhost:3000/fr/%E5%91%A8%E6%9C%89%E4%B8%83%E5%A4%A9 probably will.
Have you found any workaround or solution?

**Comment by julienmalard** [comment]
Hello,

A bit late, but a workable workaround is to use `encodeURI` on the paths in both the router and where they are called.

In router:
```
{
    path: encodeURI("/समुदाय"),
    name: "समुदाय",
    component: () => import("../views/समुदाय.vue"),
},
```

To use:
```
<v-list-item link @click="$router.push({ path: encodeURI('/समुदाय') })">
  <v-list-item-icon>
      <v-icon>mdi-share-variant</v-icon>
  </v-list-item-icon>
  <v-list-item-title>समुदाय डाताहरु</v-list-item-title>
</v-list-item>
```

This then works through both programmatically through the router, as well as directly by typing a url into the url bar of the navigator.
