### ISSUE TITLE
Pluralism for other languages

### ISSUE THREAD

**Issue by pmatisko** [kazupon/vue-i18n#284]
Hello,
would it be possible to add pluralism for languages that use more complex plural forms? window.locale should be replace by actual vue component setting. this is just my quick hack. I included an example for languages sk/cz.  The option for "zero" is not needed in this case.

Some languages have 3 or 4 different form based on the number of the items. E.g. in CZ, the word cat:

1 kočka, 2-4 kočky, 0 or 5+ koček
one, few, many

`function getChoiceIndex (choice, choicesLength) {
  choice = Math.abs(choice);

  if (choicesLength === 2) { return getOldChoiceIndexFixed(choice) }

   var index = 0;
    switch (window.locale) {
        case 'cs' :
        case 'sk' :
            index = (choice === 1) ? 0 : (choice >= 2 && choice <= 4) ? 1 : 2
            break;
        default :
           index = (choice === 1) ? 0 : 1;
    }

  return index;
}`

**Comment by shrpne** [comment]
duplicate of #78

**Comment by kazupon** [comment]
close (due to duplicate at #78)
