### ISSUE TITLE
How can I add $t inside the js-code

### ISSUE THREAD

**Issue by voroncv** [kazupon/vue-i18n#287]
I try to do it like this.$t('pages.datetime.today'), but it turns into a string and in the warning console Value of key 'pages.datetime.today' is not a string!

**Comment by lmiller1990** [comment]
What is the type of `today`? a `Date`? You will probably need to make it into a string first, by using `toISOString`, etc.

Can you post the code?

**Comment by voroncv** [comment]
Today is a simple line. Can you send an example of JavaScript code, how do I write this correctly?

**Comment by kazupon** [comment]
You can import VueI18n instance.

e.g. app generated with vue-cli:

`src/i18n.js`:
```js
import VueI18n from 'vue-i18n'
import Vue from 'vue'

Vue.use(VueI18n)

export default new VueI18n({
  // ...
})
```

`src/foo.js`:
```js
import i18n from './i18n'

console.log(i18n.t('foo.bar')
```

**Comment by shailee-m** [comment]
How to pluralize here?
