### ISSUE TITLE
Are component based locales supported?

### ISSUE THREAD

**Issue by TheDutchCoder** [kazupon/vue-i18n#29]
Does this plugin allow you to define a locale on a per component basis, or does it only work with one big global locale definition?

I ask because there's an alternative plugin that does support this, but it lacks in some other areas.

**Comment by kazupon** [comment]
Thank you for your feedback!
Currently, This plugin cannot define a locale on a per component basis.

When I developed v3.0, I didn't understand really whether this feature need.
If there is a demand, I would like to develop this feature.
