### ISSUE TITLE
`v-t` directive doesn't work with SSR, only $t('') works.

### ISSUE THREAD

**Issue by DaxChen** [kazupon/vue-i18n#293]
### vue & vue-i18n version
vue@2.5.13 (with nuxt@1.3.0)
vue-i18n@7.4.2

### Reproduction Link
[Online Demo](https://daxchen.github.io/vue-i18n-ssr-directive-bug/)
[Github Repo](https://github.com/DaxChen/vue-i18n-ssr-directive-bug)

### Steps to reproduce
Open the online demo link:
1. refresh and see that `{{ $t('xxx') }}` shows immediately (SSR) but `v-t="'xxx'"` shows a bit later (no SSR)
2. Right-click and "View page source", and you can see this:

```html
<h1 class="curly_bracket">Using {{ }}, shows in SSR!</h1>
<h1 class="directive"></h1>
```

Only `{{ $t() }}` is server side rendered, `v-t="'xxx"` isn't.

### What is Expected?

`v-t` directive to work nicely with SSR

### What is actually happening?

contents using `v-t` don't show in SSR result, which makes:
1. Not good for SEO.
2. First page load experience is not good, need to wait for js to render in client side.
3. Content will not show if javascript is disabled.

**Comment by DaxChen** [comment]
Hi, @kazupon.
Can you estimate if this will be fixed in soon?
Not to push or anything, just that if this will take relatively long to fix, I need to temporarily change all `v-t` to `$t()` throughout SEO important parts.

**Comment by darkylmnx** [comment]
according to the docs : 

> Also, when you use server-side rendering, you need to set the custom directive to directives option of the createRenderer function.

https://kazupon.github.io/vue-i18n/en/directive.html#t-vs-v-t

**Comment by DaxChen** [comment]
Whoa!!!! How did I missed that?!! I've read that page like 20 times before...orz
Thank you so much @darkylmnx! Sorry for the interruption.

**Comment by DaxChen** [comment]
example usage with nuxt, see: https://github.com/nuxt/nuxt.js/issues/1826#issuecomment-336103348

**Comment by DaxChen** [comment]
Found that the SSR custom directive only works with primitive html tags, but not with vue components such as `<router-link>`.
Opened issue: https://github.com/kazupon/vue-i18n-extensions/issues/1
