### ISSUE TITLE
Component interpolation fallback fails

### ISSUE THREAD

**Issue by AlexandreBonaventure** [kazupon/vue-i18n#296]
vue@2.5.13 & vue-i18n@7.4.2

### Reproduction Link
[http://jsfiddle.net/qegsr2pn/10/](http://jsfiddle.net/qegsr2pn/10/)

### Steps to reproduce
Interpolate with i18n component without providing message

### What is Expected?
That interpolation falls back to default path

### What is actually happening?
Interpolation is prevented. That can lead to unexpected behaviours in applications where there is a progressive adoption of translations.
Moreover, interpolation is often used for displaying links like 'Terms of services', in case translation does not exists the link will just disappear ...... :(

**Comment by kazupon** [comment]
I think this behavior is expected.
When localized failed, vue-i18n is warnning in console log.
in production env, vue-i18n warn should be resolved in develoment env.

**Comment by AlexandreBonaventure** [comment]
Up! 
With the newest vue-i18n@8.14, this could be worth revisiting since #637 
Updated fiddle http://jsfiddle.net/cs5x7oyp/
