### ISSUE TITLE
MissingHandler

### ISSUE THREAD

**Issue by koslo** [kazupon/vue-i18n#297]
Hi,
is there a suitable reason why the returning value of MissingHandler is ignored in the `_warnDefault`-function and not returned?

For example we have a array with system data merged with user data. The system data is defined in the code/DB and the user data were created by the user. The translation of the system data is stored in a subarray of all translations. So we have to use a key path to translate the messages. e.q.:
```
types = [system messages + user messages]
for type in types
   <p>$t('event.types.' + type)</p>
```
The translation of the user data (no translations available) are causing the expected warning and the translator is printing the key path like `event.types.testType` out. Now it were be nice to transform the key or do other cool stuff... which can handle the MissingHandler.

**Comment by fracz** [comment]
+1 

IMO, the `MissingHandler` should be able to return the value that should be used as a translation. Currently the `missing` config option cannot be used to solve the situation when the translation is missing for whatever reason.

**Comment by patriciussanctus** [comment]
+1
i need in ```default``` fixed key in object

**Comment by H3xx3n** [comment]
I too want that MissingHandler can be used to return the missing translation.

**Comment by kazupon** [comment]
implemented with https://github.com/kazupon/vue-i18n/pull/256
please wait next version releasing.

**Comment by koslo** [comment]
thx
