### ISSUE TITLE
Unable to use Vue.prototype.$t() inside a global mixin

### ISSUE THREAD

**Issue by sergiocastrovale** [kazupon/vue-i18n#298]
Hi guys, thanks a lot for this package.

I'm trying to bundle i18n inside a global mixin but I'm not being able to use $t() inside it. Here is my code:

global mixin:

```
import Vue from 'vue'

export default {
  data: () => ({
    loading: true,
  }),
  methods: {
    errorAPI: (error, module) => {
      const keys = Object.keys(error.errors)
      this.error = Vue.prototype.$t(`${module}.${keys[0]}`) // Cannot read property '_t' of undefined
    }
  }
}
```

main.js call:
```
...
import globalMixin from './mixins/global'

import VueI18n from 'vue-i18n'

Vue.mixin(globalMixin)
```

Shouldn't this work? How can I access $t() from within the global Vue instance?

**Comment by kazupon** [comment]
In `$t` method, It's inside using with VueI18n instance.
In this case, It seem that is not initialized wth component options.

You need to not use `Vue.prototype.$t`, but use `this.$t`

And also, before `Vue.mixin`, You need to install vue-i18n plugin with `Vue.use`.
