### ISSUE TITLE
Need Breadcrumb to be translated

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [kazupon/vue-i18n#299]
Hi @kazupon, Thank you amazing plugin. I need some way to translate my breadcrumb which is the part of vue-router, let me show you in following code:

### vue & vue-i18n version
2.5.0, 6.0

### Steps to reproduce
The Vue-Router code is as follow:
```
{
      path: '/',
      beforeEnter: auth,
      redirect: '/dashboard',
      component: Dashboard,
      name: 'Dashboard',
      meta: { title: 'Dashboard', description: 'OEM Dashboard' }
    },
```
So here I am taking the name and meta i.e. title and description as my breadcrumb in master template given below:
```
<div>
<section class="content-header">
        <h1>
          {{ $route.name }}
          <small>{{ $route.meta.description }}</small>
        </h1>
	      <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	        <li class="active">{{ $route.name }}</li>
	      </ol>
	    </section>

    	<!-- Main content -->
    	<section class="content">
    	  <router-view></router-view>
    	</section>
</div>
```
My problem is that I am unable to translate **Title** and **Description** in vue-Router, could you please some sample code?

**Comment by kazupon** [comment]
I thint that you can be realized with navigation guard.
ref: https://github.com/vuejs/vue-router/issues/914

```js
import i18n from './i18n' // import VueI18n instance

router.beforeEach((to, from, next) => {
  document.title = i18n.t(to.meta.title) // meta.title is keypath of locale messages
  next()
})
```

**Comment by hmaesta** [comment]
The above suggestion should work today?

I am using `documentTitle` to declare page title in every .vue file.
It works with normal text, but not with i18n .

```js
  import i18n from 'vue-i18n';

  export default {
    documentTitle: i18n.t(to.Auth.Sign_up),

(...)
```

I tried several ways and no one seems to work.

```js
documentTitle: i18n.t(to.Auth.Sign_up) // to is not defined
documentTitle: i18n.t(Auth.Sign_up)    // Auth is not defined
documentTitle: $t('Auth.Sign_up')      // $t is not defined
documentTitle: i18n.$t('Auth.Sign_up') // vue_i18n__WEBPACK_IMPORTED_MODULE_11__.default.$t is not a function
documentTitle: this.$t('Auth.Sign_up') // Cannot read property '$t' of undefined
```

**Comment by laonier** [comment]
import VueI18n instance not module

**Comment by inane** [comment]
> I thint that you can be realized with navigation guard.
> ref: [vuejs/vue-router#914](https://github.com/vuejs/vue-router/issues/914)
> 
> ```js
> import i18n from './i18n' // import VueI18n instance
> 
> router.beforeEach((to, from, next) => {
>   document.title = i18n.t(to.meta.title) // meta.title is keypath of locale messages
>   next()
> })
> ```

In my case, with your fix is appearing these warning messages in the console:

vue-i18n] Value of key 'Profile' is not a string or function !
vue-i18n.esm.js?a925:38 [vue-i18n] Cannot translate the value of keypath 'Profile'. Use the value of keypath as default.
