### ISSUE TITLE
Data interpolation within locale strings

### ISSUE THREAD

**Issue by dwightjack** [kazupon/vue-i18n#3]
Hi,

Does this plugin support dynamic data interpolation for locales as in projects such as [Polyglot](https://airbnb.github.io/polyglot.js/)?

Something like:

Locale object:
```js
var locales = {
  en: {
    message: {
      hello: 'total products %{num}'
    }
  }
};
```

Template:

```
<div id="message">
{{$t('message.hello', 10)}}
</div>
```

Rendered HTML:

```
<div id="message">
total products 10
</div>
```

Thanks in advance!

**Comment by kazupon** [comment]
There are two ways.

### named formatting

locale:
```js
var locales = {
  en: {
    message: {
      hello: 'total products {num}'
    }
  }
}
```

tempale:
```html
<div id="message">
{{$t('message.hello', { num: 10 })}}
</div>
```


### list formatting

locale:
```js
var locales = {
  en: {
    message: {
      hello: 'total products {0}'
    }
  }
}
```

tempale:
```html
<div id="message">
{{$t('message.hello', [10])}}
</div>
```


Sorry, poor document ;)

**Comment by dwightjack** [comment]
No problem. Sounds great!

Thank you very much!
