### ISSUE TITLE
 7.4.2 Cannot read property '_t' of undefined

### ISSUE THREAD

**Issue by qiaochangwei** [kazupon/vue-i18n#306]
```
[Vue warn]: Error in render: "TypeError: Cannot read property '_t' of undefined"

found in

---> <ISelect>
       <Test> at resources/assets/js/views/test.vue
         <Root>
TypeError: Cannot read property '_t' of undefined
    at VueComponent.<anonymous> (app.js:83551)
    at VueComponent.i18nHandler (app.js:53665)
    at VueComponent.t (app.js:53670)
    at VueComponent.t (app.js:49081)
    at VueComponent.boundFn [as t] (app.js:654)
    at VueComponent.localePlaceholder (app.js:51461)
    at Watcher.get (app.js:3577)
    at Watcher.evaluate (app.js:3684)
    at Proxy.computedGetter (app.js:3936)
    at Proxy.render (app.js:71068)
```

I've had the same problem. I have not used the '_t' property .I found that someone also met the same problem.
Here are some of my configurations
**main.js**
```
import iView from 'iview'
import VueI18n from 'vue-i18n';
Vue.use(VueI18n);
Vue.locale = () => {};
const messages = {
    zh: Object.assign(require('./lang/zh-cn'), zh),
    en: Object.assign(require('./lang/en-us'), en),
};

const i18n = new VueI18n({
    locale: 'zh', // set locale
    messages // set locale messages
});

const app = new Vue(Vue.util.extend({ router, store, i18n }, App)).$mount('#app');
```
**test.vue**
```
<template>
    <div>
        <Select v-model="global">
            <Option :value="item.id" :key="item.id" v-for="item in country">{{ item.name }}</Option>
        </Select>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                global:'',
                country:this.$t('country'), 
            }
        },
        methods: {
        },
        mounted() {
        },
    }
</script>

```

When I use iView's DatePicker and Select  tags, it will happen

**Comment by jankulma** [comment]
I have the same problem. 

`
import VueI18n from 'vue-i18n';
import Locales from './../../assets/js/vue-i18n-locales.generated.js';

Vue.use(VueI18n, {
    lang: 'en',
    Locales
});
`

**Comment by qiaochangwei** [comment]
The document has been omitted. 
```
iview.i18n((key, value) => i18n.t(key, value))
```
add this code ,it will be ok

The complete example should be:
```
Vue.locale = () => {};
    const messages = {
        en: Object.assign({ message: 'hello' }, iview.langs['en-US']),
        zh: Object.assign({ message: '你好' }, iview.langs['zh-CN'])
    };

    const i18n = new VueI18n({
      locale: 'en', // set locale
      messages, // set locale messages
    })

    iview.i18n((key, value) => i18n.t(key, value))

    new Vue({
        el: '#app',
        i18n: i18n,
        data: {
            visible: false,
            date: ''
        },
        methods: {
            show: function () {
                this.visible = true;
            }
        }
    })
```

**Comment by H3xx3n** [comment]
I also had this problem. I found that if you pass the i18n configuration in an extend it won't work.
If you pass it in a new Vue(... it will work

**Comment by PierreRambaud** [comment]
Sam problem here, using NuxtJs as framework. Can reproduce by updating https://github.com/DBAdventure/web package.json to >7.3.2

**Comment by lakb248** [comment]
I think this problem is caused by this merge: https://github.com/kazupon/vue-i18n/pull/260

**Comment by Jarzka** [comment]
This is still happening with unit testing. Any help with that?

**Comment by jimenaleom** [comment]
I have the same problem, someone could solve this

**Comment by GuilhermeAB** [comment]
I have the same problem:
`Error in render: "TypeError: Cannot read property 't' of undefined"`

```
vue.runtime.esm.js?1d62:1832 TypeError: Cannot read property 't' of undefined
    at VueComponent.listData (VSelect.js?8dc3:159)
    at VueComponent.listData (VAutocomplete.js?8ce8:143)
    at Watcher.get (vue.runtime.esm.js?1d62:3269)
    at Watcher.evaluate (vue.runtime.esm.js?1d62:3374)
    at VueComponent.computedGetter [as listData] (vue.runtime.esm.js?1d62:3626)
    at VueComponent.staticList (VSelect.js?8dc3:178)
    at Watcher.get (vue.runtime.esm.js?1d62:3269)
    at Watcher.evaluate (vue.runtime.esm.js?1d62:3374)
    at VueComponent.computedGetter [as staticList] (vue.runtime.esm.js?1d62:3626)
    at VueComponent.genList (VSelect.js?8dc3:358)
```

at VueComponent.listData (VSelect.js?8dc3:159) = noDataText: this.$vuetify.t(this.noDataText),
```
listData: function listData() {
            var scopeId = this.$vnode && this.$vnode.context.$options._scopeId;
            return {
                attrs: scopeId ? _defineProperty({}, scopeId, true) : null,
                props: {
                    action: this.multiple && !this.isHidingSelected,
                    color: this.color,
                    dense: this.dense,
                    hideSelected: this.hideSelected,
                    items: this.virtualizedItems,
                    noDataText: this.$vuetify.t(this.noDataText),
                    selectedItems: this.selectedItems,
                    itemAvatar: this.itemAvatar,
                    itemDisabled: this.itemDisabled,
                    itemValue: this.itemValue,
                    itemText: this.itemText
                },
                on: {
                    select: this.selectItem
                },
                scopedSlots: {
                    item: this.$scopedSlots.item
                }
            };
        },
```

**Comment by valentinoPereira** [comment]
> The document has been omitted.
> 
> ```
> iview.i18n((key, value) => i18n.t(key, value))
> ```
> 
> add this code ,it will be ok
> 
> The complete example should be:
> 
> ```
> Vue.locale = () => {};
>     const messages = {
>         en: Object.assign({ message: 'hello' }, iview.langs['en-US']),
>         zh: Object.assign({ message: '你好' }, iview.langs['zh-CN'])
>     };
> 
>     const i18n = new VueI18n({
>       locale: 'en', // set locale
>       messages, // set locale messages
>     })
> 
>     iview.i18n((key, value) => i18n.t(key, value))
> 
>     new Vue({
>         el: '#app',
>         i18n: i18n,
>         data: {
>             visible: false,
>             date: ''
>         },
>         methods: {
>             show: function () {
>                 this.visible = true;
>             }
>         }
>     })
> ```

I'm getting error
Uncaught ReferenceError: iview is not defined

**Comment by Knivstakocken** [comment]
Have the same problem with vue-i18n version 8.13. Did copy the example code for Lazy loading from the page.

**Comment by vedmant** [comment]
The same here, this package documentation is terrible, examples just don't work.

**Comment by QuestofIranon** [comment]
For anyone finding this issue in the future from a search, this page shows the proper solution:

https://lmiller1990.github.io/vue-testing-handbook/mocking-global-objects.html#example-with-vue-i18n

**Comment by almas** [comment]
My problem was I passed $t to $bvModal option.

`this.$bvModal.msgBoxOk(
          messageTxt,
          {
            title: this.$t("messageTitle"),
            centered: true
          }
        );`
fix:

`
let messageTitle = this.$t("messageTitle");
this.$bvModal.msgBoxOk(
          messageTxt,
          {
            title: messageTitle,
            centered: true
          }
        );`

**Comment by OzanKurt** [comment]
Still the same error since years...

**Comment by simon-moulin** [comment]
Me too, did you fix it ?

**Comment by hawking-feng** [comment]
after delete this line : Vue.locale = () => {}; it works fine for me
