### ISSUE TITLE
Feature request: Get "child translations" from key

### ISSUE THREAD

**Issue by manniL** [kazupon/vue-i18n#309]
## Setup

Let's assume having the following language setup:

```
en: {
    about: {
       title: 'About us',
       description: 'Some info about us',
    }
  },
de: {
    about: {
       title: 'Über uns',
       description: 'Informationen über uns',
    }
 }
```

## Problem

If I want to access the translations of `about.title` and `about.description` now, I'd need to explicitly ask for it, e.g. with `$t('about.title')`.

## Solution

So why not return an object with "child translations" of a key. When using $t('about'), you could receive something like:
```
{
 title: 'About us',
 description: 'Some info about us'
}
```

## Use case
When using `vue-i18n in combination` with `vue-meta`, you could create translated meta-data (which are SEO-relevant) easily.

Unfortunately, not every page has each attribute set, so a general method wouldn't be possible without much boilerplate code.

## Related
https://github.com/kazupon/vue-i18n/pull/262

**Comment by kazupon** [comment]
close (due to release: https://github.com/kazupon/vue-i18n/releases/tag/v7.5.0)
