### ISSUE TITLE
Error in render: "RangeError: Invalid language tag: fr_FR"

### ISSUE THREAD

**Issue by ligne13** [kazupon/vue-i18n#312]
### vue & vue-i18n version
Vue 2.5.7
Vue-i18n 7.3.3

### Steps to reproduce
```
const messages = {
    'en_US': require("json-loader!yaml-loader!./lang/en_US.yml"),
    'fr_FR': require("json-loader!yaml-loader!./lang/fr_FR.yml")
};

const dateTimeFormats = {
    'en_US': {
        short: {
            year: 'numeric', month: 'short', day: 'numeric'
        },
        long: {
            year: 'numeric', month: 'short', day: 'numeric',
            weekday: 'short', hour: 'numeric', minute: 'numeric'
        }
    },
    'fr_FR': {
        short: {
            year: 'numeric', month: 'short', day: 'numeric'
        },
        long: {
            year: 'numeric', month: 'short', day: 'numeric',
            weekday: 'short', hour: 'numeric', minute: 'numeric', hour12: true
        }
    }
};

const i18n = new VueI18n({
    messages,
    dateTimeFormats,
    locale: "en_US",
    fallbackLocale: "en_US",
});

const app = new Vue({
    i18n,
}).$mount("#app");
```
then, trying to display a formatted date :
```
$d(new Date(), 'short', 'fr_FR');
```
I get the following errors in the console :
![image](https://user-images.githubusercontent.com/81624/37409342-6b46adbe-279e-11e8-8abb-ccb18d8e1246.png)

### What is Expected?
The date should be displayed with the fr_FR localization.

### What is actually happening?
Errors in the console saying the tag fr_FR is invalid.

**Comment by kazupon** [comment]
Thank you for your reporting!

From the error of your reporting,  This issue is not vue-i18n.
I seem it's issue of `Intl.DateTimeFormat`.
You can check `dateTimeFormats` options at [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
