### ISSUE TITLE
Lazy loading for modules

### ISSUE THREAD

**Issue by Shyam-Chen** [kazupon/vue-i18n#317]
### vue & vue-i18n version

2.5.16, 7.6.0

### Reproduction Link

❌

### Steps to reproduce

❌

### What is Expected?

Similar to Vuex Modules. Is there any way like [Vuex's Dynamic Module Registration](https://vuex.vuejs.org/guide/modules.html#dynamic-module-registration)?

```yml
# en is default

# home page
.
├── en  // load
├── ja  // lazy
├── zh  // lazy
└── foo  // feature module
    ├── en  // lazy
    ├── ja  // lazy
    └── zh  // lazy

# go to foo
.
├── en  // load
├── ja  // lazy
├── zh  // lazy
└── foo  // feature module
    ├── en  // load
    ├── ja  // lazy
    └── zh  // lazy

# switch to ja (current page is foo)
.
├── en  // load
├── ja  // lazy
├── zh  // lazy
└── foo  // module
    ├── en  // load
    ├── ja  // load
    └── zh  // lazy
```

### What is actually happening?

[This guide](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html) can only split the language system and cannot split the feature module of the current language system.

https://github.com/kazupon/vue-i18n/issues/677

**Comment by Shyam-Chen** [comment]
```js
<i18n src="./languages/en.yml"></i18n>
<i18n src="./languages/zh.yml" lazy></i18n>  <!-- lazy loading? -->

<template>
  <v-layout column>
    <v-layout row>
      <p class="pa-3">{{ $t('hello') }}</p>
    </v-layout>
  </v-layout>
</template>

<script>
export default {};
</script>
```

**Comment by kazupon** [comment]
close due to being able to replaced by the following ways
- TC32 dynamic `import` statement: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
- dynamic import with webpack or other bundler
