### ISSUE TITLE
[Bug] Pluralization with html formating

### ISSUE THREAD

**Issue by renanbronchart** [kazupon/vue-i18n#319]
Pluralization doesn't work with html formating.
It works but I see the flag, who is not interpreted.

{{ $tc('hero.days_html', 3, { count: 3 }) }}
days_html: '{count} day<br />left ! | {count} day<br />left ! | {count} days<br />left !'

**Comment by MasterKale** [comment]
HTML within translation strings will only be rendered if you perform the translation in VueJS's `v-html` directive.

For example, assuming the following translation string:
```js
days_html: 'today\'s the<br>day ! | 1 day<br>left ! | {count} days<br>left !'
```

And the following HTML:
```html
<h2>HTML in pluralization</h2>
<p v-html="$tc('days_html', 0)"></p>
<p v-html="$tc('days_html', 1)"></p>
<p v-html="$tc('days_html', 2, { count: 3 })"></p>
```

You'll get back your translations with line breaks intact:

<img width="252" alt="screen shot 2018-05-16 at 6 29 24 pm" src="https://user-images.githubusercontent.com/5166470/40151857-184d9184-5937-11e8-918b-eabdefdb9de1.png">

**Comment by kazupon** [comment]
close due to answer with @MasterKale
