### ISSUE TITLE
Using $http request instead of fetch?

### ISSUE THREAD

**Issue by websanova** [kazupon/vue-i18n#32]
In the example docs, it uses `fetch`, but I guess since most apps will use the `vue-resource` package they can just use `$http`. The `fetch` call seems to add an additional 8Kb (minified) to my app file (I guess for polyfill's).

```
this.$http.get('/i18n/en-US.json', function (json) {
    Vue.locale('en-US', json);
    Vue.config.lang = 'en-US';
});
```

Might be useful to update the docs if there is no particular reason for using `fetch`.

Great little plugin btw :-)

**Comment by danpantry** [comment]
having a dependency on `vue-resource` would probably be heavier than the polyfills for the `fetch` polyfills, especially as many new browsers support `fetch`... just my 2c

**Comment by kazupon** [comment]
Close (vue-ressource retire from vuejs organisation)
