### ISSUE TITLE
Usage with weblate

### ISSUE THREAD

**Issue by nothingismagick** [kazupon/vue-i18n#325]
I would like to use [weblate](https://docs.weblate.org/en/latest/) to translate our interface and some short content. It would be excellent to have some documentation about how to do this - or a quick tip would also be great...

**Comment by avenla-mvirkkunen** [comment]
You could put all your translations into JSON files which [that tool seems to support](https://docs.weblate.org/en/latest/formats.html#json-files). Then you just load the JSON files into vue-i18n's messages property. If you're using webpack for instance, you can just `import` a .json file into a variable.

**Comment by kazupon** [comment]
close due to be not a issue ...
