### ISSUE TITLE
SSR: Ability to update the locale dynamically

### ISSUE THREAD

**Issue by abhipanda** [kazupon/vue-i18n#326]
Hi,

I wanted to check if there was an example for HN2 SSR with dynamic locale change.

Thanks,
Abhi

**Comment by Shyam-Chen** [comment]
```js
const val = 'zh';

this.$i18n.locale = val;
document.documentElement.lang = val;
localStorage.setItem('lang', val);
```

**Comment by kazupon** [comment]
You can check the [example](https://github.com/kazupon/vue-i18n/tree/dev/examples/ssr/hn2)
