### ISSUE TITLE
[Feature Request] Basic Markdown Support for i18n text

### ISSUE THREAD

**Issue by cuddlecake** [kazupon/vue-i18n#330]
Hello guys,

it would be nice if I could do some basic formatting within my i18n messages (such as italic, bold, lists), which would probably be most easily achieved using (optional) basic markdown support.

This way I could avoid coupling between the text I prepare and the way it has to be inserted in HTML, as I would not have to use interpolation for basic formatting anymore.

Example for how it has to be done currently:
```html
<div id="app">
  <!-- ... -->
  <i18n path="text" tag="p">
    <strong place="boldText">{{ $t('bold') }}</strong>
  </i18n>
  <!-- ... -->
</div>
```
```js
const messages = {
  en: {
    text: 'This is {boldText}.'
    boldText: 'bold text'
  }
}
```

Example for how I would like to do it:
```html
<div id="app">
  <i18n path="text" tag="p"/>
</div>
```

```js
const messages = {
  en: {
    text: 'This is __bold text__.'
  }
}
```

As a result, other people working on my project can add formatted text without concerning themselves how the HTML markup should look. Additionally, this way I can iterate over messages arrays and still have formatted text.

**Comment by sem4phor** [comment]
You can just use the translation in a v-html tag and add html style formazting like <br> <strong> and so on. Styling text isn't really a task for a translation plugin IMO :D

**Comment by cuddlecake** [comment]
@sem4phor You're right. I realized that nothing stops me from wrapping the `<i18n>` tags in a markdown renderer, if I require that.

Thanks for the hint.

**Comment by luckylooke** [comment]
Using `v-html` has its security and styling issues:

> Security Note
> Dynamically rendering arbitrary HTML on your website can be very dangerous because it can easily lead to [XSS attacks](https://en.wikipedia.org/wiki/Cross-site_scripting). Only use v-html on trusted content and never on user-provided content.
> 
> In [Single-File Components](https://vuejs.org/guide/scaling-up/sfc.html), scoped styles will not apply to content inside v-html, because that HTML is not processed by Vue's template compiler. If you want to target v-html content with scoped CSS, you can instead use [CSS modules](https://vuejs.org/api/sfc-css-features.html#css-modules) or an additional, global <style> element with a manual scoping strategy such as BEM.


reference: https://vuejs.org/api/built-in-directives.html#v-html

**Comment by rlemaigre** [comment]
> You can just use the translation in a v-html tag and add html style formazting like `<br> \<strong\>` and so on. Styling text isn't really a task for a translation plugin IMO :D

If you go that way, substituting placeholders with values isn't, either. Vue-i18n could just tell users to do that job themselves in post-processing, with whatever templating engine they like. But Vue-i18n supports a basic templating engine because it is so convenient and generally useful. So why not support a basic formatting engine too, at least as an add-on, an option or something ? Basic support for bold, underlined and italic text would be useful already.

**Comment by frederikheld** [comment]
Did anything towards markdown support or any other way of formatting messages? I would really appreciate this feature as well.
