### ISSUE TITLE
$t and SFC locales not working in functional components

### ISSUE THREAD

**Issue by darkylmnx** [kazupon/vue-i18n#334]
### vue & vue-i18n version
Vue: 2.5.13
Vue-i18n : 7.4.2

### Steps to reproduce
- Create a project with Vue and Vue-i18n
- Add a locale and some messages
```html
// for example
<i18n>
{
  "fr": {
      "my_message": "Bonjour"
  }
}
``` 
- Create a **functional** component and user **$t** function or **v-t** directive
```html
<template functional>
  <p>{{ $t('my_message') }} <span v-t="'my_message'"></span></p>
</template>
```

### What is Expected?
I'm excpecting to see "Bonjour Bonjour" in a **p** and a **span** tag 

### What is actually happening?
warnings / errors / only keys are rendered

---
![image](https://user-images.githubusercontent.com/1426357/39010540-3c8a0a2e-440f-11e8-9e41-3ef6a3748a7c.png)

**Comment by poldixd** [comment]
Same here with YAML Syntax

- @kazupon/vue-i18n-loader@0.3.0
- webpack@4.10.2
- vue-loader@15.2.4
- yaml-loader@0.5.0
- vue-i18n@7.8.0

**Comment by kimuraz** [comment]
@poldixd did you try this: https://github.com/vuejs/vue/issues/8074 ?
Basically you should use `parent.$t`, I believe it's because of:
```
In cases like this, we can mark components as functional, which means that they’re stateless (no reactive data) and instanceless (no this context). 
``` 
[VueJS Docs](https://vuejs.org/v2/guide/render-function.html#Functional-Components)

**Comment by darkylmnx** [comment]
@kimuraz as I said it's not working for $t and SFC, what you said works for "$t" yes but SFC i18n tag still doesn't work from what I saw

**Comment by kazupon** [comment]
https://github.com/kazupon/vue-i18n/pull/370

**Comment by gwyohm** [comment]
Is it OK to do like this?

**in /src/i18n.js**
```javascript
import VueI18n from 'vue-i18n';
import Vue from 'vue';

Vue.use(VueI18n);
export const i18n = new VueI18n({
  locale: '',
  fallbackLocale: 'en',
  messages: {},
});
/// ...
```

**in /src/functional-component.js**
```javascript
import { i18n } from './i18n.js;

const t = i18n.t.bind(i18n);

export default {
  name: 'FunctionalComponent',
  functional: true,
  props: {
    someKey: { type: String, default: 'hello' },
  },
  render(h, context) {
    return h('span', {}, [t(context.props.someKey)]
  }
} 
```
