### ISSUE TITLE
SFC with global i18n results in warnings + unexpected output

### ISSUE THREAD

**Issue by renzo-s** [kazupon/vue-i18n#335]
When using the SFC's and the translations stored in a `<i18n>` block globally set translations are overridden (using all YAML btw).

Case:
- Attach the plugin to Vue in `main.js`(without any translations present)
- Have `utils/toasts` use `mergeLocaleMessage()` to include it's own translations
- The sfc (say todo.vue) which uses toasts includes it's own `<i18n>` block

Result in context of `todo.vue`:
- `this.$i18n.getLocaleMessage('en-US')` results only in the translations of that component
- `this.$t('toasts.changes_saved')` results in three warnings:
  1. 2x Value of key 'toasts.changes_saved' is not a string!
  2. Fall back to translate the keypath 'toasts.changes_saved' with root locale.
- Correct translation is returned 🤷‍♂️

Having to do this for every global message type is a bit annoying but not a big deal:

```
for (let l in trans) {
  i.mergeLocaleMessage(l, trans[l])
}
```

Alt case:
- Attach the plugin to Vue in `main.js` with all the global messages already defined

Result is the same as above.

It feels like an bug, or am I approaching this wrong?

**Comment by kazupon** [comment]
Thank you for your reporting!
However, I could not understand your issue.
Could you provide minimum repo repo please?

**Comment by kazupon** [comment]
close due to in-activity
