### ISSUE TITLE
why i18n load default locale 1st then requested locale in nuxt?

### ISSUE THREAD

**Issue by sudhir600** [kazupon/vue-i18n#336]
I am using i18n plugin in nuxt app. everything is working fine but i notice an issue that, when i change any route, My page 1st loaded in English (which is default locale) and after a less than second, its load in another locale which was set previously.  

I have not configured this into middleware, just added in the plugin and wrote this before switching the locale.

```
var requestedLocale = ''
  if(process.browser) {
  	requestedLocale = localStorage.getItem('locale')
  }
app.i18n = new VueI18n({
....
locale: requestedLocale,
fallbackLocale: 'en',
...
```
and my output is like this

![i18n issue](https://user-images.githubusercontent.com/4952560/39049618-dad49b26-44bf-11e8-8b6b-26b47b6bbae9.gif)

Please suggest the appropriate way so text can load at first attempt only.

**Comment by sudhir600** [comment]
@dts  I changes locale with cookies and its working fine but by doing this i am getting nuxt error in console. Because of this error, my axios is also not working.  

![image](https://user-images.githubusercontent.com/4952560/39359127-549a34fe-4a36-11e8-9621-ce7aab828f7d.png)


I tried putting try..catch, process.server but no one worked.

**Comment by dts** [comment]
Looks like you're running server-side code in your client to me.

**Comment by kazupon** [comment]
I seem that not a problem of vue-i18n
close due to no acltivty.
