### ISSUE TITLE
Underscore in named formatting does not work as expected

### ISSUE THREAD

**Issue by chaoszcat** [kazupon/vue-i18n#35]
In the named formatting, if I include an underscore in the named variable, the replacement failed. Is this an expected behavior?

(vue-i18n, v4.0.0)

For example:

```
var locales = {
  en: {
    message: {
      hello: '{test_msg} world'
    }
  }
}
```
Template the following:
```
<p>{{ $t('message.hello', { test_msg: "hello" }) }}</p>
```

Output:
```
<p>{test_msg} world</p>
```

Expecting:
```
<p>hello world</p>
```

**Comment by kazupon** [comment]
Fixed.
https://github.com/kazupon/vue-i18n/releases
