### ISSUE TITLE
feature suggestion + code: auto load language files in directory

### ISSUE THREAD

**Issue by SilBoydens** [kazupon/vue-i18n#350]
I made a script that automatically imports all files in a directory (requires webpack) and make the messages json from them.
This way you can have separate files for each language and you don't need to include them yourself in anymore. I wanted to share this with the community, does not need to be implemented but could be usefull for others.

This way i just make a file for each language and put them all in the i18n folder.

To add a new language i can just add a file for that language, no need to import it anywhere else.
Usefull for crowdin projects where a lot of people help with the translations

my setup:
```
src/
|- main.js
\- i18n/
   |- index.js
   |- en.json
   |- other language.json
```
```js
// i18n/index.js
const files = require.context(
  '.', // current directory
  true, // subdirectories
  /.+\.json$/ // only .json
)
var messages = {}
files.keys().forEach(fileName => {
  messages[fileName.replace('.json', '').replace('./', '')] = files(fileName)
})
export default messages
``` 
```js
// main.js
import VueI18n from 'vue-i18n'
import messages from './i18n'
Vue.use(VueI18n)
const i18n = new VueI18n({
  locale: 'en', // set locale, can get changed somewhere else
  fallbackLocale: 'en',
  messages
})
new Vue({ i18n })
```

**Comment by kazupon** [comment]
Maybe, I'll plan to support as addon of Vue CLI UI.

**Comment by kazupon** [comment]
Released out in vue-cli-plugin-i18n
https://github.com/kazupon/vue-cli-plugin-i18n/compare/v0.2.0...v0.3.0
