### ISSUE TITLE
Fallback language

### ISSUE THREAD

**Issue by melloc01** [kazupon/vue-i18n#36]
Hello,
is there a way to set a fallback language?
for example: 

*en.json*
```json
{
  "message": {
    "hello": "Hi"
  } 
}
````

*spanish.json*
```json
{
  "message": { 
  } 
}
````
````javascript
Vue.config.lang = 'spanish'
Vue.config.fallbackLang = 'en'

$t('message.hello')
// would return `Hi` 

````

Is there a way to do this ?

**Comment by rssfrncs** [comment]
This would be so useful please!

**Comment by hiwye** [comment]
@kazupon Is this going to be implemented?

**Comment by melloc01** [comment]
Guys, I created a solution on my own app and it was very helpful = ]

1. Create a `mixin` that creates a `translate` method.
2. Make it global.

mixins/translate.js
````javascript
...
    let fallbackLang = config.fallbackLang; 
    return $t(key) || $(key, fallbackLang);
...
````

use it:

inside a component:
````javascript
    this.translate(key);
````

on a template:
````html
    <div> translate(key) </div>
````

@kazupon @hiwye @rssfrncs

**Comment by hiwye** [comment]
That looks awesome, trying it out right now. Good job 👍

**Comment by kazupon** [comment]
released v4.2.0

**Comment by dansullivan86** [comment]
@kazupon this looks really good, but any chance it could still throw a warning in development?

**Comment by melloc01** [comment]
really cool @kazupon, also it'd be cool to have warnings as @dansullivan86 pointed

**Comment by kazupon** [comment]
released v.4.2.1
I supported fallback translation warning.
https://github.com/kazupon/vue-i18n/releases/tag/v4.2.1
