### ISSUE TITLE
Scoped styles not applied to HTML message

### ISSUE THREAD

**Issue by SLMNBJ** [kazupon/vue-i18n#362]
Scoped styles are not applied to HTML message. Vue-i18n doesn't preserve the data-v attribute needed to apply the style.

https://codesandbox.io/s/8n2ly2k2w8

**Comment by Jcdroid** [comment]
+1

**Comment by kimuraz** [comment]
@kazupon how can this issue be closed? Does it need a `note` in the documentation or something like that?

**Comment by kazupon** [comment]
@SLMNBJ 

In about this case,  it's the specification of scoped css.
see the [vue-loader docs](https://vue-loader.vuejs.org/guide/scoped-css.html#dynamically-generated-content)

@kimuraz 
Thank you for always your support!
It's a good idea to include it in the document as `note`.

You can send the Pull request. :)
