### ISSUE TITLE
Add precision prefix on currency format

### ISSUE THREAD

**Issue by Lacroute** [kazupon/vue-i18n#369]
I think it could be nice to have the possibility to specify a precision prefix for the number display following the [SI standards](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes) prefixes.

It allows you to resolve this situation:
I have to display 116 millions dollars. For now, it shows `$116,000,000` but it would be more readable if it shows `$116M`.

I propose to add an extra entry in number's format like this:

```
'en': {
    currency: {
      style: 'currency',
      currency: 'USD',
      precisionPrefix: 'M' // will display $116M
    }
  },
  'fr': {
    currency: {
      style: 'currency',
      currency: 'USD',
      precisionPrefix: 'M' // will display 116 M$
    }
  }
```
What do you think?

**Comment by kazupon** [comment]
Hmm, 
Unfortunately, it can not be used in Intl.NumberFormat. 😞 In the future, Intl.NumberFormat may be supported or may be supported in the future i18n planned.

**Comment by Lacroute** [comment]
Meantime, a workaround is to reimplement the `n` function with a custom boolean and the help of [d3-format](https://github.com/d3/d3-format). Like discussed [here](https://stackoverflow.com/questions/50795507/vue-i18n-how-to-abbreviate-currency-display/50883079?noredirect=1#comment88826602_50883079). Can't wait for this support!

**Comment by kazupon** [comment]
You can realize with i18n-n functional component.
See this PR: https://github.com/kazupon/vue-i18n/pull/541
