### ISSUE TITLE
Allow components interpolation

### ISSUE THREAD

**Issue by alanwillms** [kazupon/vue-i18n#37]
It would be helpful if we could use components as named arguments.

Suppose I have this message source:

``` js
{post: {posted_by: 'Posted by {author}'}}
```

And I want to display a tag with bindings or any kind of component in the place of `{author}`:

``` html
Posted by <a class="foo" v-link="{name: 'author', params: {id: post.author.id}}">Foo</a>
```

Currently, there is no way to do something like this:

``` html
{{{ $t('post.posted_by', {author: myComponent}) }}}
```

**Comment by alanwillms** [comment]
While this does not exist, do you suggest any alternative @kazupon ?

**Comment by kingcarter** [comment]
+1 
I also hava the demand.
It would be helpful if vue-i18n support the grammar.

**Comment by kazupon** [comment]
v7.0.0-beta.1 release out!
please check it! :)
https://github.com/kazupon/vue-i18n/releases/tag/v7.0.0-beta.1
