### ISSUE TITLE
Error addin  vue-i18n in laravel 5.6 project

### ISSUE THREAD

**Issue by sergeynilov** [kazupon/vue-i18n#373]
Hello!
I try to run vue-i18n in my laravel/vuejs app:

And after package installed in resources/assets/js/app.js I wrote :

```
import Vue from 'vue';
...
import VueI18n from 'vue-i18n'
Vue.use(VueI18n)
```

I use it in resources/assets/js/components/document_categories/DocumentCategoryEdit.vue:

```
<template>

	<section class="card col-sm-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2">

		<p>{{ $t("message.hello") }}</p>

   </section>  <!-- class="card" -->

</template>


<script>
    import {bus} from '../../app';
    import appMixin from '../../appMixin';
//    import VueI18n from 'vue-i18n'  

    Vue.component('markdown-editor', require('../../components/lib/MarkdownEditor.vue'));
    Vue.component('editor-header', require('../../components/lib/EditorHeader.vue'));
    Vue.component('editor-buttons', require('../../components/lib/EditorButtons.vue'));
//    Vue.use(VueI18n)

    const messages = {
        en: {
            message: {
                hello: 'hello world'
            }
        },
        fr: {
            message: {
                hello: 'bonjour'
            }
        }
    }

    // Create VueI18n instance with options
    const i18n = new VueI18n({
        locale: 'fr', // set locale
        messages, // set locale messages
    })

    export default {
        created() {
        ...
```

and I have an error in console:
app.js:152341 Uncaught ReferenceError: VueI18n is not defined
    at Object.render (app.js:152341)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:152192)
    at __webpack_require__ (app.js:20)
    at Object._typeof (app.js:4735)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:80447)
    at __webpack_require__ (app.js:20)
    at app.js:63
    at app.js:66
```


If uncomment 2 rows with attaching and using of VueI18n I got error :

```
app.js:6917 [Vue warn]: Error in render: "TypeError: Cannot read property '_t' of undefined"
```

Looks VueI18n is not attached, but I supposed I have no to import it in my vue file...

Which is the right way?


```
        Laravel Framework : 5.6.24
        "vue": "^2.5.7"
        "vue-i18n": "^7.8.0",
```

Thanks!

**Comment by kazupon** [comment]
Thank yo for your reporting!
Can you provide minium repo codes please?

**Comment by kazupon** [comment]
fixed in https://github.com/kazupon/vue-i18n/commit/aa0e831e89c713bb430d24f45eb2d561cf50c961 commit
