### ISSUE TITLE
global translations not reactive when component translations present

### ISSUE THREAD

**Issue by MathieuDerelle** [kazupon/vue-i18n#375]
### vue & vue-i18n version
ex: 2.5.16, master

### Reproduction Link
http://jsfiddle.net/qegsr2pn/40/
just switch between the two languages

### Steps to reproduce
- add some global translations and some translations in a component
- change $i18n.locale on the fly

### What is Expected?
global translations should be reactive

### What is actually happening?
global translations are not reactive (the translation is correctly done on "boot")

(btw the link for vuejs in the jsfiddle is broken ; the jsfiddle described in a new issue comment)

**Comment by kazupon** [comment]
This is specification of component based localization.
See the [docs](https://kazupon.github.io/vue-i18n/guide/component.html#translation-in-functional-component)

>As in the example above, if the component doesn't have the locale message, it falls back to globally defined localization info. The component uses the language set in the root instance (in the above example: `locale: 'ja'`).
If you hope localize in the component locale, you can realize with `sync: false` and locale in `i18n` option.

**Comment by MathieuDerelle** [comment]
If it is an expected behavior, then please give us a way to get reactive global translations 

Ex : a new method like `$tg('global.message')`

**Comment by kazupon** [comment]
You can change root locale the below:

`<select v-model="$root.$i18n.locale">`

**Comment by goldengecko** [comment]
Suggest adding this to the docs.
