### ISSUE TITLE
v-t is breaking parent v-if in various situations

### ISSUE THREAD

**Issue by TimotheeJeannin** [kazupon/vue-i18n#377]
Hi, 

When using `vue-i18n`, in a specific scenario, some text is displayed when it shouldn't be. 

### Reproduction Link
https://jsfiddle.net/7s5brn12/

### Notes
In the JSFiddle above, if i stop using `v-t`, everything works fine. But as soon as I want to translate the string `SHOULD_NOT_DISPLAY_WHEN_TIMEOUT_EQUAL_TRUE`, then the text is ignoring the `v-if` directive.

### Steps to reproduce
Click on the `click me to start timeout` button.
### What is Expected?
`SHOULD_NOT_DISPLAY_WHEN_TIMEOUT_EQUAL_TRUE` should be hidden during the duration of the timeout.
### What is actually happening?
`SHOULD_NOT_DISPLAY_WHEN_TIMEOUT_EQUAL_TRUE` is displayed during the duration of the timeout.

Let me know if you need more explanation/details.

Tim

**Comment by kazupon** [comment]
Thanks for your reporting.
I just have fixed now.
