### ISSUE TITLE
Does vue-i18n support ssr?

### ISSUE THREAD

**Issue by boyWangaC** [kazupon/vue-i18n#378]
Hello, does the support for vue-i18n work normally in nuxt.js?

module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'my-nuxt',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  plugins: [
    { src: '~/plugins/nuxt-swiper-plugin.js', ssr: false },
    { src: '~/plugins/vue-i18n.js', ssr: false }
  ],
  css: [
    'swiper/dist/css/swiper.css'
  ],
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLint on save
    */
    // extend (config, { isDev, isClient }) {
    //   if (isDev && isClient) {
    //     config.module.rules.push({
    //       enforce: 'pre',
    //       test: /\.(js|vue)$/,
    //       loader: 'eslint-loader',
    //       exclude: /(node_modules)/
    //     })
    //   }
    // },
    // vendor: ['~/plugins/vue-awesome-swiper']   
  }
}

**Comment by kazupon** [comment]
Thank yo for your reporting!
Can you provide minium repo codes please?

**Comment by kazupon** [comment]
close due to in-activity
