### ISSUE TITLE
Text not translated in invisible areas

### ISSUE THREAD

**Issue by adi-zz** [kazupon/vue-i18n#381]
### vue & vue-i18n version
2.5.16 & 8.0.0
(also nuxt 1.4.1, nuxt-i18n 4.0.1, vuetify 1.0.19 - but I don't think it's relevant)

### Reproduction Link
https://github.com/adi-zz/nuxt-vuetify-i18n/tree/vue-i18n_issue_381

### Steps to reproduce
- open `http://localhost:3000/`; note the 2 buttons ('spanish' and 'go to /inspire') are in english
- click the menu/hamburger icon on the right top corner, an english message ('global hello message') appears
- click outside the popup in order to close it and now click the button 'spanish' (to switch to spanish translations)

### What is Expected?
- the 2 buttons should be translated to spanish
- when you would click the menu/hamburger icon, the spanish translation should appear

### What is actually happening?
- the buttons are translated - OK
- the english translation appears in the menu/hamburger icon triggered popup - NOK

**Comment by kazupon** [comment]
Thank you for your reporting!
I checked your Repo. 👀 

Demo app are changing `Demo` component locale.
You need to change the locale of global level (e.g `$root.$i18n.locale = 'es').
