### ISSUE TITLE
Replace $t by v-t in case of nested content

### ISSUE THREAD

**Issue by kissu** [kazupon/vue-i18n#384]
Hi ! ✋ 
I've read that [part](https://kazupon.github.io/vue-i18n/guide/directive.html#t-vs-v-t) of the doc.
It is recommended to use `v-t` instead of `$t` performance wise.

The issue is that I do have that kind of code

```vue
<a class="nav-link">
  <i class="fa fa-fw fa-sign-out-alt"></i>{{ $t('topbar.logout') }}
</a>
```
and if I write

```vue
<a class="nav-link" v-t="'topbar.logout'">
  <i class="fa fa-fw fa-sign-out-alt"></i>
</a>
```
the translation will be properly displayed but the nested content (the icon) will be overwritten. I was wondering how to preserve it without using some ugly hacky stuff. 😅

NB: I'm posting it here since I didn't get any answer from the [forum](https://forum.vuejs.org/t/i18n-v-t-nested-fontawesome-icon/37354) and that I could PR that part to the documentation later on.

**Comment by aivarsliepa** [comment]
Hi!

This should work.

```html
<a class="nav-link">
  <i class="fa fa-fw fa-sign-out-alt"></i>
  <span v-t="'topbar.logout'"></span>
</a>
```

**Comment by kissu** [comment]
Yep, was totally that. Kinda stupid too, surprised didn't thought about it. Thanks ! :muscle:

**Comment by kissu** [comment]
Yep, was totally that. Kinda stupid too, surprised didn't thought about it. Thanks ! :muscle:
