### ISSUE TITLE
Vue-i18n image from json file doesn't show in Vuetify carousel ( through v-for and :src of the translation )

### ISSUE THREAD

**Issue by alexgil1994** [kazupon/vue-i18n#387]
### nuxt & vue & vue-i18n & Vuetify version
ex: 1.0.0 ,  2.5.16,  8.0.0, 0.17.3

### Reproduction Link
https://github.com/alexgil1994/logistics-gls

### Steps to reproduce
```
npm install
```
```
npm run dev
```
### What is Expected?
In the index.vue page the Vuetify carousel uses a v-for connected with an array from the vue-i18n en-US.json file (in "lang" folder) . This specific (for this index.vue page) array "items" has "src" , "title", "text" and "to" objects. The "src" has the name of the (already imported in the script of the index.vue page) images to load, the rest are used for different v-card on each image. 
<br>Expected the images to load as did before using vue-i18n when the "items" array was in the index.vue data.

### What is actually happening?
Images do not show, the rest do show. No error is being displayed in the console.

**Comment by alexgil1994** [comment]
Found a solution to the problem!
<br>Nuxt generates automatically a path for the images which has an extra id, like : /_nuxt/img/img5.b6c3c18.jpg instead of /_nuxt/img/img5.jpg . So one way to solve this, is by inputting to the .json files for the translations the generated path instead of just "img1" which will only return this way this name with no connection to the path and neither the theoritical path (wont work) but the one nuxt generated.

**Comment by kazupon** [comment]
good for you! 😉 
enjoy i18n 🌐
