### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by rssfrncs** [kazupon/vue-i18n#39]
Attempting to run the project locally. When i run npm install i get the following error.

![error](https://i.gyazo.com/75b4dd88c4a1ec3535a6cf8ed966c507.png)

**Comment by kazupon** [comment]
I tried to install vue-i18n at `node@5.11.0` and `npm@3.10..5`.
However, i could not reproduce this issue.

I seems to be not issue of vue-i18n.
