### ISSUE TITLE
Dynamic source file for custom block

### ISSUE THREAD

**Issue by NaoSup** [kazupon/vue-i18n#391]
I was wondering if there is a way to dynamically change the source file of `<i18n>` to match the locale language.

For each vue component I have a folder with my different translations :

```
├── myComponent
|   └── lang
|       ├── en.json
|       ├── fr.json
|   └── index.vue
```

In my `index.vue` I'd like to do something like :

`<i18n src='./lang/' + $i18n.locale + '.json'></i18n>`

which doesn't work for me..
Is it possible ?

**Comment by kazupon** [comment]
Sorry late for my response. 🙇 

Unfortunately, vue-i18n-loader cannot use Vue's reactive at webpack custom loader. because that is browser env but node.js env. 

In the future, I'll plan to suppor multiple importing with `src` attr.
https://github.com/kazupon/vue-i18n-loader/issues/10

**Comment by NaoSup** [comment]
thanks for the answer !
