### ISSUE TITLE
Pluralization: Numeral format makes the number equal to zero

### ISSUE THREAD

**Issue by Lyncis** [kazupon/vue-i18n#404]
I am using the following template for pluralization:
```
<div>
        {{ $tc('points', totalPoints, { count: totalPoints }) }}
</div>
```
Locale messages:
```
en: {
        points: "0 points | 1 point | {count} points"
}
```
totalPoints calculation:
```
totalPoints = overallPoints;
```

When I just use the totalPoints without formatting it displays the correct result:
![image](https://user-images.githubusercontent.com/8875863/43406401-212d524c-93ea-11e8-9ad7-b9f01fefa575.png)

When I try to use the following code, it always displays result as 0:
```
totalPoints = numeral (overallPoints).format();
```
Result:
![image](https://user-images.githubusercontent.com/8875863/43406310-f0918022-93e9-11e8-859f-a6d54e906276.png)

I would appreciate any help with resolving this problem. For now I don't see why it is not working.

**Comment by exoego** [comment]
@Lyncis 
I suppose you passed the formatted string (maybe "1,429") to `$tc`.
`$tc` expects a number passed,  since `$tc` choose message from `0 | 1 | many` by the number. 

You may get the expected result with the below:

```js
formattedTotalPoints = numeral(overallPoints).format();
```
```html
<div>
{{ $tc('points', overallPoints, { count: formattedTotalPoints }) }}
</div>
```
http://jsfiddle.net/8zjqtLv1/2/

**Comment by Lyncis** [comment]
@exoego Thanks! I'll check it out :)

**Comment by kazupon** [comment]
close due to there is a workaround
