### ISSUE TITLE
[Feature Request] Support named formatting in the key: "{count} 人关注": "{count} followers"

### ISSUE THREAD

**Issue by imageslr** [kazupon/vue-i18n#407]
Hello, thanks for your great work!

## Background
I am now using vue-i18n by the format of 

```JSON
{
  "en": {
      "CHINESE": "ENGLISH_TRANSLATION"
  }
}
```
instead of

```JSON
{
  "zh": {
      "key": "CHINESE"
  },
  "en": {
      "key": "ENGLISH_TRANSLATION"
  }
}
```

For example: 

```JSON
{
  "en": {
    "该项目已被甲方取消": "The project has been canceled",
    "收藏": "Favorite",
    "取消收藏": "Unfavorite",
    "我要报名": "Apply",
    "报名项目": "Apply the project",
    "报名成功": "Successfully apply"
  }
}
```

```vue
<p v-t="'该项目已被甲方取消'" />
<p v-t="'报名成功'" />
```

## Reason
This is very convenient. **I don't have to find a key for every string**(You know, naming things are always troublesome), and I don't have to write a single string in two places with different language. 

I can just write my original language in html and if there were no translated language, by default, it will simply show the original language.

Combining with `v-t`, **the code becomes more readable for me (a Chinese developer).**

## What is Expected?(This is not a bug report!!!)
When I pass a string with named formatting, if there were no matched translated language, It will not process the mustache within it and just return the string. I hope vue-i18n can **process named format in unmatched key string**.

For example:

```JSON
{
  "en": {
    "{count} 人关注": "{count} followers"
  }
}
```

```vue
<p>{{ $t('{count} 人关注', { count: 2 }) }}</p> 
```

#### Expected:
Output: `2 人关注` 
#### Actually happened 
Output: `{count} 人关注`

#### Now I'm actually doing this like

```JSON
{
  "zh": {
    "followerCount": "{count} 人关注"
  },
  "en": {
    "followerCount": "{count} followers"
  }
}
```

```vue
<p>{{ $t('followerCount', { count: 2 }) }}</p>
```

Thank you!

**Comment by Dunwolf** [comment]
I experienced the same difficulties.
It turned out, the reason in the mustache: check that it was exactly the symbol that the library processes. Perhaps, **in fact you are using a different char**!
I hope this helps you.

**Comment by imageslr** [comment]
@Dunwolf  Would you mind paste your code here? The `i18n` definition and its usage in html. Thank you!

**Comment by Dunwolf** [comment]
Initialization according to the tutorial: http://kazupon.github.io/vue-i18n/guide/started.html

I use [webpack template](https://vuejs-templates.github.io/webpack/).
I'll insert my simplified code just in case:
```
import Vue from 'vue'
import App from './App'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

const messages = {
  'en': require('./lang/en.json'),
  'ru': require('./lang/ru.json'),
  'cn': require('./lang/cn.json'),
  'jp': require('./lang/jp.json'),
  'kr': require('./lang/kr.json')
}

const i18n = new VueI18n({
  locale: 'en',
  messages
})

new Vue({
  i18n,
  el: '#app',
  components: { App },
  template: '<App/>'
})
```
My language file looks like (en.json):
```
{
  "language": "English",
  "messages": {
    "example": "Example {var} phrase",
  }
}
```

**Comment by imageslr** [comment]
I have known how to use mustache and I'm now using `vue-i18n` almost as same as your way. And this issue is for a tiny request which is no big deal even not implement. 

Thank you for your kind response!

**Comment by Dunwolf** [comment]
@imageslr I'm not sure I understood you correctly.
But your sections "Expeсted" and "Actually happened" led me to the idea that the matter is in a specific mustache symbol.
Since the library processes only the mustache of the unicode table. The rest she perceives simply as text.
I hope that I helped :) Goodluck!

**Comment by imageslr** [comment]
It does look like a bug report, my fault😂. And this seems like a unnecessary requirement. 
Still greatly thanks for your time and attention! Have a nice day :)
