### ISSUE TITLE
[vue-i18n] Cannot translate the value of keypath...

### ISSUE THREAD

**Issue by CinKon** [kazupon/vue-i18n#41]
### vue & vue-i18n version
ex: 2.0.0-beta.3, 4.1.0

### Steps to reproduce
```javascript
// main.js

import Vue          from 'vue'
import VueResource  from 'vue-resource'
import VueI18n      from 'vue-i18n'
import router       from './router/routes.js'
import App          from './App'

// =======================
// Store
// =======================
Vue.use(VueResource)

// =======================
// Localization
// =======================
Vue.use(VueI18n)

// let self = this
const lang = 'de'

Vue.locale(lang, function () {
  // self.loading = true
  return fetch('../static/lang_' + lang + '.json', {
    method: 'get',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    }
  }).then(function (res) {
    return res.json()
  }).then(function (json) {
    // self.loading = false
    if (Object.keys(json).length === 0) {
      return Promise.reject(new Error('locale empty !!'))
    } else {
      return Promise.resolve(json)
    }
  }).catch(function (error) {
    // self.error = error.message
    console.error(error.message)
    return Promise.reject()
  })
}, function () {
  Vue.config.lang = lang
})

/* eslint-disable no-new */
new Vue({
  router,
  render: h => h(App),
  http: {
    root: '/root',
    headers: {
      Authorization: 'Basic YXBpOnBhc3N3b3Jk'
    }
  }
}).$mount('app')
```

```json
//lang_de.json

{
  "apptitle": "App erstellen",
  "headnav": {
    "help": "Hilfe / FAQ",
    "register": "Registrieren",
    "login": "Anmelden"
  }
}
```

```jade
// Template
<template lang="pug">
  header.brandbar
      h1.brand__title {{ $t("apptitle") }}
</template>
```
### What is Expected?
No warnings :)

### What is actually happening?
I try to use your plugin with webpack and vue, and it does what it says - `apptitle` is rendered as `App erstellen`, but i get annoying console-warnings:

`[vue-i18n] Cannot translate the value of keypath "apptitle". Use the value of keypath as default`

**Comment by michielkempen** [comment]
Got the same problem. Any thoughts?

**Comment by kazupon** [comment]
Sorry for my late reply.

I seems that vue rendering is working earlier than locale loading.
Can you try the below code please?

```js
Vue.locale(lang, function () {
  ...
}, function () {
  Vue.config.lang = lang
  new Vue({
    ...
  }).$mount('#app')
})
```

**Comment by CinKon** [comment]
No Change

**Comment by Frozire** [comment]
Getting the exact same issue in the version for Vue v1 - I can't seem to find a way to turn simply turn off the notifications?

**Comment by CinKon** [comment]
I think the problem really is, that the Vue-Instance is created BEFORE the data from the json is loaded.
I tried to create a Fiddle with my code, but used a static variable just like in the examples, and the problem was solved.
@kazupon 's suggestion is probably the correct way to solve this.

**Comment by Frozire** [comment]
Yeah - just a bit problematic when you have a lot of other dependencies that further delays when you can instantiate vue app instance.

I would much prefer if we could set a variable like "hasLoadedTranslations" on the instance and only then will translations be set.

**Comment by kazupon** [comment]
Hmm.
I think that we can resolve with using callback of `Vue.locale` and `v-cloak`.
e.g.
http://jsfiddle.net/kazupon/Lh980stL/8/

**Comment by mygaochunming** [comment]
@kazupon i can't open http://jsfiddle.net/kazupon/Lh980stL/8/ please give me the new url

thank you!

**Comment by Jordy-A** [comment]
I'm having the same issue. Solution worked for me, but it would be better if the locales are loaded before the Vue instance starts.

**Comment by mygaochunming** [comment]
i known the real url is https://jsfiddle.net/kazupon/Lh980stL/8/

**Comment by Francisc** [comment]
Old thread, but where is `Vue.locale` method documented, please?
Or was it removed and no longer present in the current version of vue-i18n.
