### ISSUE TITLE
how to use in vuex?

### ISSUE THREAD

**Issue by smileshirley6699** [kazupon/vue-i18n#415]
### vue & vue-i18n version
ex: 2.1.0, 5.0

**Comment by smileshirley6699** [comment]
how to use in vuex ?

**Comment by MaximVanhove** [comment]
Create a file where you initialise i18n

`i18n.js`

```
import Vue from 'vue';
import VueI18n from 'vue-i18n';

Vue.use(VueI18n);

const messages = {
    en: {
        message: {
            hello: 'hello world',
        },
    },
};

const i18n = new VueI18n({
    locale: 'en',
    messages,
});

export default i18n;
```

Import i18n in your store, then you can use the .t() function to translate or any other.

`store.js`

```
import i18n from 'path/to/i18n';

const state = {
    title: i18n.t('title'),
};
```

These functions are available: http://kazupon.github.io/vue-i18n/api/#methods

**Comment by smileshirley6699** [comment]
Thanks! Same as I thought. But i find a problem,  when i change the language as "this.$i18n.locale = xxx;"
in the vue components, the data of vuex can not update.

**Comment by MaximVanhove** [comment]
I would go for an action to switch language

`this.$store.dispatch('locale', 'en');`

And then reassign the messages. Can you share a piece of your code why you need this in vuex? There might be better solutions.

**Comment by smileshirley6699** [comment]
i18n.js=============
import VueI18n from "vue-i18n";
let language = "en_US";
const i18n = new VueI18n({
    // 语言标识
    locale: language,
    messages: {
        "in_ID": require("./in_ID"),
        "en_US": require("./en_US")
    }
});
export default i18n;
state.js=============
import i18n from "../../../i18n/i18n";
export default {
    MD_TREE: {
        COMMON_STATUS: [
            {value: 1, name: i18n.t("common.status.enable")},
            {value: 2, name: i18n.t("common.status.disabled")}
        ]
    }
};
when language change========
 self.$i18n.locale = "in_ID";

Like this, I want to save some common data in the vuex's state.js.
But, the status data still english.
If i add the code "this.$store.dispatch('locale', 'in_ID');"
error : unknown action type: locale

**Comment by smileshirley6699** [comment]
- `mounted () {
        this.initStoreData();
    },
    computed : {
        ...mapGetters({
            language : types.GET_LANG
        })
    },
    methods: {
        ...mapActions({
            setCommonStatus : types.MD_TREE.SET_COMMON_STATUS
        }),
        initStoreData () {
            this.initCommonStatusData();
        },
        // 初始化级别数据到vuex
        initCommonStatusData () {
            this.setCommonStatus([
                {value: 1, name: this.$t("common.status.enable")},
                {value: 2, name: this.$t("common.status.disabled")}
            ]);
        }
    },
    watch: {
        language () {
            this.initStoreData();
        }
    }```
And now i manual refresh it like this.

**Comment by smileshirley6699** [comment]
In a common vue components, I think it will better to refresh as this.$store.dispatch('locale', 'in_ID');

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Vue Land](https://vue-land.js.org/),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by MichaelFBA** [comment]
If your using vue SSR you can also add $t to your store like so.
`store.$t = app.$i18n.t;`

then it will be available in your store like `this.$t('key')`

**Comment by smileshirley6699** [comment]
OK！thanks！




------------------ 原始邮件 ------------------
发件人: "Michael Bell"<notifications@github.com>; 
发送时间: 2019年8月26日(星期一) 下午5:30
收件人: "kazupon/vue-i18n"<vue-i18n@noreply.github.com>; 
抄送: "249998027"<249998027@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kazupon/vue-i18n] how to use in vuex? (#415)




If your using vue SSR you can also add $t to your store like so.
 store.$t = app.$i18n.t;
 
then it will be available in your store like this.$t('key')

**Comment by MichaelFBA** [comment]
Just had a look at this. I had to use the tc function for some reason
`store = app.$i18n`
Then `this.$t.tc('key')`

**Comment by BarnabasSzabolcs** [comment]
> import i18n from

Path is typically 
`import i18n from 'src/boot/i18n'`

**Comment by eserdinyo** [comment]
Hi there. Somehow If you are using this with NUXT I found a solution like this.

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'

import en from '~/lang/en'

Vue.use(VueI18n)

const i18n = new VueI18n({
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en
  },
})

export default ({ app, store, route }, inject) => {
  inject('i18n', i18n)
  app.i18n = i18n
}
```

And now you can use it in your store like this.
`this.app.$i18n.t('CART.MIN_PRICE')`

**Comment by SciManJD** [comment]
This doesn't work. I export i18n, that is in my main.js. Then I import in in one of my stores. When I call it like this:

i18n.t('welcome')

I get error:

TypeError: i.default.t is not a function

What I'm doing wrong?

**Comment by MaximVanhove** [comment]
@SciManJD are you on Vue 2 or Vue 3?

**Comment by SciManJD** [comment]
I use Vue 3.

**Comment by SciManJD** [comment]
Please, help me! I really blocked on this...

**Comment by MaximVanhove** [comment]
The example above is for Vue 2. Here is an example for Vue 3:

```js
// i18n.js
import { createI18n } from 'vue-i18n';

const locale = 'en';

const messages = {
    en: {...},
};

export const i18n = createI18n({
    locale,
    messages,
});
```


```js
// In vuex or your component

import { i18n } from '@/app/i18n.js';

i18n.global.t('My message');
```

**Comment by magistr4815** [comment]
> Я думаю, что будет лучше обновить, как `this.$store.dispatch('locale', 'in_ID'); ` вы сказали.

Hi, I still don't understand how you made it work. Can you show the complete files of your application?
How to force static translations to be updated in state.js?
