### ISSUE TITLE
SSR mismatch

### ISSUE THREAD

**Issue by tillkruss** [kazupon/vue-i18n#419]
I'm using Vue 2.5.17,  Vue-i18n 8.0.0 and Nuxt 1.4.2.

I'm seeing a mismatch error when using Nuxt's SSR. Is that expected, or can it be fixed?

### Steps to reproduce

```js
<template>

    <footer>
        <div class="container mt-5">

            <p v-if="! $isCustomDomain()" class="text-center text-muted" v-text="$t('copyright')" />

            <i18n v-else path="madewith" tag="p" class="text-center text-muted">
                <a place="name" href="https://example.com" class="text-muted" target="_blank" rel="noopener">
                    <u>{{ $t('name') }}</u>
                </a>
            </i18n>

        </div>
    </footer>

</template>

<i18n>
{
    "en": {
        "copyright": "Copyright © 2018 Foobar. All rights reserved.",
        "madewith": "Made with ♥ at {name}.",
        "name": "Foobar"
    }
}
</i18n>
```

### What is Expected?

No mismatch error.

### What is actually happening?

<img width="1245" alt="screen shot 2018-08-30 at 3 15 32 pm" src="https://user-images.githubusercontent.com/665029/44882303-9bc83b80-ac67-11e8-9ea6-fc0bef81503c.png">

**Comment by 0pt1m1z3r** [comment]
Same problem with 8.1.0
@kazupon ping

**Comment by 0pt1m1z3r** [comment]
The problem was in my code.
I put out `new VueI18n()` of the exported default function in `plugins`.
@tillkruss show how you apply the plugin, maybe I'll tell you what's wrong

**Comment by tillkruss** [comment]
@0pt1m1z3r: I use a Nuxt plugin for it:

```js
import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

export default ({ app }) => {
    app.i18n = new VueI18n({
        locale: process.env.locale,
        fallbackLocale: 'en',
        silentTranslationWarn: true,
        messages: {
            'en': require('~/locales/en.json'),
        }
    })
}
```

**Comment by 0pt1m1z3r** [comment]
@tillkruss try to replace `require`, use es6 `import`

**Comment by HadiChen** [comment]
I feel this is not a vue-i18n problem, you can try to use `v-show`, or in `mounted` you change the value of `$isCustomDomain()` @tillkruss

**Comment by kazupon** [comment]
Could you provide the minimum repro repo please?

**Comment by tillkruss** [comment]
I solved it with wrapping the element in a parent. If it comes up again, I'll reopen the issue.
