### ISSUE TITLE
Error when evaluating expression

### ISSUE THREAD

**Issue by francoisromain** [kazupon/vue-i18n#42]
### vue & vue-i18n version
ex: 1.0.26, 4.1

### What is actually happening?
vue-i18n is working great in a project. 
When I npm install my project on another computer however, it is making an error in the console and the translations don't display. 

the error: 

    Error when evaluating expression "$t("my-expression": TypeError: Cannot read property 'util' of undefined

I don't see any diference in the 2 computers configuration. What can I do to solve this? 

Thank you

**Comment by francoisromain** [comment]
this is a bug from version 4.2.1 which can not evaluate the content of an array. 
I rolled back to 4.1 which works fine for now…

**Comment by kazupon** [comment]
Thank you for your reporting!!
Can you provide the reproduction code with jsfiddle or other please?

**Comment by kazupon** [comment]
related?
https://github.com/kazupon/vue-i18n/issues/43

**Comment by francoisromain** [comment]
@kazupon yes it look lie the same thing.

**Comment by kazupon** [comment]
oh my god ...
sorry, I'll try to fix.
