### ISSUE TITLE
Date conversion error

### ISSUE THREAD

**Issue by bayern12** [kazupon/vue-i18n#424]
I'm seeing a error when using **WeChat miniprogram web-view**. Can it be fixed?

### vue & vue-i18n version
Vue 2.5.17
Vue-i18n 8.1.0

### Steps to reproduce

dateTimeFormats
```
  "numericDate": {
    "month": "short",
    "day": "numeric",
    "year": "numeric"
  }
```
new Date()
![image](https://user-images.githubusercontent.com/7699536/45739502-c3d30b00-bc25-11e8-889c-5edd208a9a75.png)
```
  this.$d( newDate, 'numericDate' )
```

### What is Expected?
Aug 31, 1987.

### What is actually happening?
<img width="276" alt="wx20180919-161044 2x" src="https://user-images.githubusercontent.com/7699536/45739885-976bbe80-bc26-11e8-95ec-dd519efc7f01.png">

**Comment by kazupon** [comment]
Thank you for your PR!
However, I could not repro the this issue ...
close.

**Comment by bayern12** [comment]
> Thank you for your PR!
> However, I could not repro the this issue ...
> close.

Please see this
https://developers.weixin.qq.com/miniprogram/en/dev/component/web-view.html
I found problems with this web-view component...

**Comment by bayern12** [comment]
> Thank you for your PR!
> However, I could not repro the this issue ...
> close.

@kazupon Please see this
https://developers.weixin.qq.com/miniprogram/en/dev/component/web-view.html
I found problems with this web-view component...

**Comment by kazupon** [comment]
I don't understand how to reproduction with using `web-view`. 😢 
Could you provide the repository of  minimum reproduction please? 🙏

**Comment by bayern12** [comment]
@kazupon Hi, you can download a developer tool [here](https://developers.weixin.qq.com/miniprogram/en/dev/devtools/download.html).
Open [this page](https://developers.weixin.qq.com/miniprogram/en/dev/component/web-view.html) to find sample code.

![image](https://user-images.githubusercontent.com/7699536/46196453-b3afdf80-c339-11e8-9eba-178c400bf25b.png)

Click the green button to import

![image](https://user-images.githubusercontent.com/7699536/46196532-f40f5d80-c339-11e8-8605-6fbe4619c392.png)

Open the editor, find the **index.wxml**, modify it here

![image](https://user-images.githubusercontent.com/7699536/46196804-96c7dc00-c33a-11e8-9d7f-3655d3cba774.png)

**If you can't access it, just check this one.**

![image](https://user-images.githubusercontent.com/7699536/46197240-ca573600-c33b-11e8-8b51-bd7e4c86d900.png)

**Comment by kazupon** [comment]
I cannot access the QR code URL ...
![image](https://user-images.githubusercontent.com/72989/46206277-6db94280-c35e-11e8-99ab-de3aa7dcbf15.png)

**Comment by bayern12** [comment]
> I cannot access the QR code URL ...
> ![image](https://user-images.githubusercontent.com/72989/46206277-6db94280-c35e-11e8-99ab-de3aa7dcbf15.pn

> I cannot access the QR code URL ...
> ![image](https://user-images.githubusercontent.com/72989/46206277-6db94280-c35e-11e8-99ab-de3aa7dcbf15.png)

Do you have a WeChat account? You need to sign in with WeChat.
