### ISSUE TITLE
Add a filter directive or mention it in the documentation

### ISSUE THREAD

**Issue by Fohlen** [kazupon/vue-i18n#425]
Hey there!
I think this is an amazing project, especially the `vue-cli-plugin` is *super useful*.
I noticed that you have a very similar syntax to `panter/vue-i18next`, and there I suggested the following filter directive to be added:

```
Vue.filter("t", value => {
  if (!value) return "";
  return i18n.t(value);
});
```

This allows for using the shortcut in your templates,
instead of `$t('translate')` you can use `'translate' | t` which is simply much more read- and maintainable.  As @panter pointed out this might be _"going away further from the i18n specification"_, which you may or may not agree with. So my feature request here is: either add this as a built in directive or mention it in the docs. It will surely save a lot of people a lot of time!

If you would like to add this as a directive I could also provide a pull request.

**Comment by kazupon** [comment]
Thank you for your suggestion!

it posting as a tips in the document certainly is friendly, however, for the purpose of Vue 3.0,  I'll plan to major upgrade vue-i18n in the future.
Sorry, I'll be not add it to the docs.
