### ISSUE TITLE
Uncaught Error: Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.25.0"

### ISSUE THREAD

**Issue by maxttor** [kazupon/vue-i18n#427]
### vue & vue-i18n version
2.4.2

### Reproduction Link
https://github.com/kazupon/vue-i18n/tree/dev/examples/sfc

### Steps to reproduce
npm install
npm run dev

### What is Expected?
Run example

### What is actually happening?
Uncaught Error: Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.25.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

**Comment by samuelterra22** [comment]
@maxttor you need add **@babel/core**, **babel-core** and **vue-i18n** in package.json

Just run:
``
$ npm i @babel/core babel-core vue-i18n*
``

I had a similar bug that [I saw how to fix it here](https://github.com/facebook/jest/issues/6913#issuecomment-423684647) and by now you just need to add the two packages in your project. It may be a bug that they will correct.
