### ISSUE TITLE
[feature-request] add yaml file type, folders and splitting

### ISSUE THREAD

**Issue by gabrielmustiere** [kazupon/vue-i18n#428]
The JSON syntax is good, but it is verbose, especially for long translation files, the YAML syntax is much lighter.  Wouldn't it be interesting to propose the YAML format to describe translations.

An interesting features would be to propose a folder per language rather than a single file, and to allow the separation of our translation files into as many desirable files, with the name of the files as the first level key of the translation object.

Br.

**Comment by jovanmaric** [comment]
You can change to YAML with http://kazupon.github.io/vue-i18n/guide/sfc.html#yaml-loading.

I'm not a big fan of large translations files myself as they are missing context, and make it harder to translate. But shouldn't it be possible to roll your own implementation considering that global translations are available when setting it up like this:

```
// http://kazupon.github.io/vue-i18n/guide/started.html#html

const messages = {
  en: {
    message: {
      hello: 'hello world'
    }
  },
  ja: {
    message: {
      hello: 'こんにちは、世界'
    }
  }
}

// Create VueI18n instance with options
const i18n = new VueI18n({
  locale: 'ja', // set locale
  messages, // set locale messages
})
```
Just merge all your files into a global object and add it to VueI18n, in the same way as messages above. Keep in mind that this will result in always loading all locales and i'm not sure what impact this has on SSR.

**Comment by gabrielmustiere** [comment]
Thank you for the answer, I clearly haven't read enough the documentation.

Concerning the tips for merging different files that would represent different contexts for my translations, when I posted this message, I was on a vue-cli project and I had added vue-i18n via vue-cli, the method of loading locales was managed via webpack and require.context().

```
//generated with vue-cli

import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

function loadLocaleMessages() {
  const locales = require.context('./locales', true, /[A-Za-z0-9-_,\s]+\.json$/i)
  const messages = {}
  locales.keys().forEach(key => {
    const matched = key.match(/([a-z0-9]+)\./i)
    if (matched && matched.length > 1) {
      const locale = matched[1]
      messages[locale] = locales(key)
    }
  })
  return messages
}

export default new VueI18n({
  locale: process.env.VUE_APP_I18N_LOCALE || 'en',
  fallbackLocale: process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en',
  messages: loadLocaleMessages()
})
```
I couldn't get by, but yes, for me the strategy is pretty clear, it's more about implementation that I block (I'm new to JS).

Thank you very much for the feedback

**Comment by centerorbit** [comment]
I too was using @gabrielmustiere method via Vue CLI. I found a nice way to get everything working with YAML files.

First, you need the loaders:
```
npm install --save yaml-loader json-loader
```

Next, configure `vue.config.js`. Add this into the module.exports object, like so:
```
module.exports = {
...
chainWebpack: config => {
    config.module
      .rule('i18n-loader')
      .test(/.\.yaml$/)
      .use('json')
        .loader('json-loader')
      .end()
      .use('yaml')
        .loader('yaml-loader')
      .end();
  },
...
}
```
Finally, update this line in your `i18n.js` file to be for yaml instead of json:
```
  const locales = require.context('@/locales', true, /[A-Za-z0-9-_,\s]+\.yaml$/i);
```

Restart your webpack build. It should now use the YAML files instead of JSON!

One thing to note, is that this seems to be incompatible with the `i18n:report` script. Even if you update it (in your package.json) file to be:
```
    "i18n:report": "vue-cli-service i18n:report --src \"./src/**/*.?(js|vue)\" --locales \"./src/locales/**/*.yaml\"",

**Comment by Libidine** [comment]
> I too was using @gabrielmustiere method via Vue CLI. I found a nice way to get everything working with YAML files.
> 
> First, you need the loaders:
> 
> ```
> npm install --save yaml-loader json-loader
> ```
> 
> Next, configure `vue.config.js`. Add this into the module.exports object, like so:
> 
> ```
> module.exports = {
> ...
> chainWebpack: config => {
>     config.module
>       .rule('i18n-loader')
>       .test(/.\.yaml$/)
>       .use('json')
>         .loader('json-loader')
>       .end()
>       .use('yaml')
>         .loader('yaml-loader')
>       .end();
>   },
> ...
> }
> ```
> 
> Finally, update this line in your `i18n.js` file to be for yaml instead of json:
> 
> ```
>   const locales = require.context('@/locales', true, /[A-Za-z0-9-_,\s]+\.yaml$/i);
> ```
> 
> Restart your webpack build. It should now use the YAML files instead of JSON!
> 
> One thing to note, is that this seems to be incompatible with the `i18n:report` script. Even if you update it (in your package.json) file to be yaml instead of json, like so:
> 
> ```
>     "i18n:report": "vue-cli-service i18n:report --src \"./src/**/*.?(js|vue)\" --locales \"./src/locales/**/*.yaml\"",
> ```
> 
> It doesn't seem to be compatible with yaml out of the box.

Hi, can you give me more details? I tried your configuration and it doesn't work.

I opened a new issued here: https://github.com/kazupon/vue-i18n/issues/873
