### ISSUE TITLE
Cannot create property 'isRootInsert' on string '...'

### ISSUE THREAD

**Issue by zateynik** [kazupon/vue-i18n#429]
Main code:
```
<template>
	<div class="reg__msg-wrapper">
		<div class="reg__msg" v-if="showMessage">
			<i18n :path="message" tag="span">
				<span place="TEMPLATE">
					123
				</span>
			</i18n>
		</div>
	</div>
</template>
```
Localization message: 'Sign in to send a message to {TEMPLATE} or invite them to your project'

In browser console:
```
[Vue warn]: Error in nextTick: "TypeError: Cannot create property 'isRootInsert' on string 'Sign in to send a message to '"
TypeError: Cannot create property 'isRootInsert' on string 'Sign in to send a message to '
```

I created a copy of i18n component with functional: false and my example works without errors.
You can fix it i18n component?

**Comment by kazupon** [comment]
Thanks for filing the issue! 
Please follow the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin or CodeSandbox containing a set of reproducible steps that can lead to the behavior you described.

**Comment by glaures** [comment]
I am having the same issue. Any updates?

**Comment by AshokkumarMuthukrishnan** [comment]
I'm also having the same issue. Does anyone know how to fix this issue?
