### ISSUE TITLE
Using $t method in plugin

### ISSUE THREAD

**Issue by victor192** [kazupon/vue-i18n#439]
I want to use access to `$t` method in separate JS plugin (not in component, not in store). For example, implement a function that will return a message depending on a function parameter. How to access $ t in a plugin so that reactivity is preserved (to change the message when changing the language)?

**Comment by kazupon** [comment]
You can access `$t` via Vue instance.
See the API docs: https://kazupon.github.io/vue-i18n/api/#vue-injected-methods
