### ISSUE TITLE
#Pluralization  output error

### ISSUE THREAD

**Issue by babysbreath1994** [kazupon/vue-i18n#443]
js:
const messages = {
  en: {
    apple: 'no apples | one apple | {count} apples',
    banana: 'no bananas | {n} banana | {n} bananas'
  }
}

html:
```html 
<p>{{ $tc('banana', 1) }}</p>
```

output:
{n} banana

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. 
The issue list only accepts bug reports and feature requests. 
Questions should be posted to the [Discord for Vue Community](https://vue-land.js.org/),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue-i18n).

Thanks.
