### ISSUE TITLE
Default datetime formats

### ISSUE THREAD

**Issue by garniersam** [kazupon/vue-i18n#445]
When you have the same datetime formats for each locale, you have to duplicate the formats : 

`const dateTimeFormats = {
  'en': {
    short: {
      year: 'numeric', month: 'short', day: 'numeric'
    },
    long: {
      year: 'numeric', month: 'short', day: 'numeric',
      weekday: 'short', hour: 'numeric', minute: 'numeric'
    }
  },
  'fr': {
    short: {
      year: 'numeric', month: 'short', day: 'numeric'
    },
    long: {
          year: 'numeric', month: 'short', day: 'numeric',
          weekday: 'short', hour: 'numeric', minute: 'numeric'
    }
  }
}
`

It could be good to have a set of default formats that could be overriden by locale : 
`const dateTimeFormats = {
  'default': {
    short: {
      year: 'numeric', month: 'short', day: 'numeric'
    },
    long: {
      year: 'numeric', month: 'short', day: 'numeric',
      weekday: 'short', hour: 'numeric', minute: 'numeric'
    }
  },
  'fr': {
    short: {
      month: 'short', day: 'numeric'
    }
  }
}
`

What do you think of that ?

**Comment by kazupon** [comment]
I think that it should be dealed with user.
vue-i18n should not be supported.
