### ISSUE TITLE
Updating the html tags lang attribute automatically

### ISSUE THREAD

**Issue by jarikmarwede** [kazupon/vue-i18n#447]
I think it would be a good idea to automatically update the lang attribute of the HTML tag when the `i18n.locale` variable is changed.
It isn't hard to implement it yourself but I think a lot of people forget it or don't even know about it so changing it automatically by default would be helpful.
It's as simple as `document.getElementsByTagName("html")[0].lang = newLanguage;`.
Is there a reason this shouldn't be implemented?

More information on w3.org:
[Why use the language attribute](https://www.w3.org/International/questions/qa-lang-why.en)

**Comment by chiaweilee** [comment]
I believe it's easy to update lang attribute with a watcher.
I did it with different ways, e.g `html-webpack-plugin`, `vuex store watch`...
And also I have a repo of a docs-site, which support different languages in docs only, but my site is in English.

Sooo, I don't think it's a good idea for `vue-i18n` itself.

**Comment by jarikmarwede** [comment]
I agree that it is pretty easy to change it yourself.
I just meant that people often probably don't even think about it.
But `i18n.locale` not having the same standard as `html lang` is definitely a problem.

**Comment by kazupon** [comment]
`html lang` should be changed with userland.

**Comment by gilles-crealp** [comment]
> `html lang` should be changed with userland.

@kazupon Can you be a bit more specific on how to achieve that?
