### ISSUE TITLE
Hello, I use V-for, i18 can not switch language, can not switch.

### ISSUE THREAD

**Issue by duuliy** [kazupon/vue-i18n#448]
Hello, I use V-for, i18 can not switch language, can not switch.

eg:
 infolist:[
        {
          'tit':this.$t('m.Whicdocumentfo'),
          'answer':this.$t('m.WhicdocumentfAnswer')
        },
        {
          'tit':this.$t('m.Listoflanguages'),
          'answer':this.$t('m.ListoflanguagesAnswer')
        },

or:

this.buttons=[this.$t('m.Operatingvideo'), this.$t('m.Operationguide'), this.$t('m.Commonproblem')];

thanks

**Comment by kazupon** [comment]
Thanks for filing the issue!
Please follow the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin or CodeSandbox containing a set of reproducible steps that can lead to the behavior you described.
