### ISSUE TITLE
i18n tag in single file component prevents $i18n.locale change to propagate to other components

### ISSUE THREAD

**Issue by frederikbeaudry** [kazupon/vue-i18n#454]
I have a single file component to switch locale between French and English

![image](https://user-images.githubusercontent.com/2176548/47853102-0efb4480-ddb4-11e8-8529-91a3f99bea45.png)

When the "change" method is called, $i18n.locale is modified for this component only instead of being changed globally for my app. After fiddling around, I realized that if I remove the i18n tag from my LocaleSwitcher component, everything works as expected.

To be sure this wasn't the desired behavior, I added the messages in my vuei18n configuration and everything works as expected.

![image](https://user-images.githubusercontent.com/2176548/47853126-23d7d800-ddb4-11e8-8c2b-1d0d6b1385df.png)

Edit : Sorry for images, couldn't get the code for single file components to render properly

**Comment by chiaweilee** [comment]
Did you used `vue-i18n-loader`?

**Comment by frederikbeaudry** [comment]
> Did you used `vue-i18n-loader`?

Yes I did.

`module.exports = {
    outputDir: path.resolve(__dirname, "../wwwroot"),
    chainWebpack: config => {
        config.module
          .rule("i18n")
          .resourceQuery(/blockType=i18n/)
          .use("i18n")
            .loader("@kazupon/vue-i18n-loader")
            .end();
      }
}`

**Comment by frederikbeaudry** [comment]
As mentionned in my initial post, if the component used to switch languages does not contain a i18n tag, everything works fine.

**Comment by Finley-Zhang** [comment]
I met the same problem? vm.$i18n no longer points to the global i18n when ＜i18n＞ tag used

**Comment by kazupon** [comment]
same issue #216 

This is expected behavior in vue-i18n.

When we used custom blocks in the component, Each components is isolated localization.
However, It is possible change the locale from root.
If you want to change the other components locale from target component, you need to use the global state management (e.g Vuex).
