### ISSUE TITLE
[Question/Feature Request] About translations of css

### ISSUE THREAD

**Issue by ColinTree** [kazupon/vue-i18n#457]
Background: https://github.com/bootstrap-vue/bootstrap-vue/issues/2143
I want to use `vue-ci18n` to translate my work, but got stuck by bootstrap custom file input - which use 
```
.custom-file-label::after {
  content: "Browse"
}
```
to define the view:
![image](https://user-images.githubusercontent.com/22613139/48001980-28e6af80-e145-11e8-9879-c8a46de304cf.png)
![image](https://user-images.githubusercontent.com/22613139/48003292-06ef2c00-e149-11e8-9e93-8f101a736083.png)
![image](https://user-images.githubusercontent.com/22613139/48003273-f6d74c80-e148-11e8-9564-f1b580aaed3a.png)

Please give some advice to this case & try making style sheet internationalizing available
Thanks in advance

**Comment by exoego** [comment]
You may 

* Use [`attr()` CSS function](https://developer.mozilla.org/en-US/docs/Web/CSS/attr) to extract [custom data attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) for translation (something like `data-after` attribute).
* Use vue-i18n method inside the data attribute to put the translation text .

Demo:
http://jsfiddle.net/q7yf48ms/

**Comment by ColinTree** [comment]
Thanks, this may be able to solve.
