### ISSUE TITLE
npm ERR! Failed at the vue-i18n@4.3.0 postinstall script 'gitbook install ./gitbook'.

### ISSUE THREAD

**Issue by francoisromain** [kazupon/vue-i18n#46]
with version 4.3, there is a problem when doing npm install vue-i18n: 

    npm ERR! vue-i18n@4.3.0 postinstall: `gitbook install ./gitbook`
    npm ERR! spawn ENOENT
    npm ERR!
    npm ERR! Failed at the vue-i18n@4.3.0 postinstall script 'gitbook install ./gitbook'.

and then it's not installed in node_modules

**Comment by barnabas-szekeres** [comment]
Same issue here!

**Comment by mdreizin** [comment]
@kazupon could you please fix it? https://travis-ci.org/kazupon/vue-i18n/builds/155265914

**Comment by kazupon** [comment]
sorry, I fixed quickly this issues.

**Comment by kazupon** [comment]
@mdreizin 
I registered this issue.
https://github.com/kazupon/vue-i18n/issues/48

**Comment by mdreizin** [comment]
@kazupon Thanks a lot ;)

**Comment by francoisromain** [comment]
@kazupon thank you
