### ISSUE TITLE
Special Characters in CLI3 do not display

### ISSUE THREAD

**Issue by jappyjan** [kazupon/vue-i18n#461]
### vue & vue-i18n version
2.5.17, 8.0.0

### Steps to reproduce
Generate a Vue-Cli 3 Project
Add the i18n Plugin
Create a locale JSON file which contains a Value using a special Char (tested with 'Ö','Ä','Ü')

### What is Expected?
The special Char should display on the page.

### What is actually happening?
Instead there is a questionmark Symbol.
Not only on the page, but even in the JS Code. Propably WebPack is making some weird things with encoding(?!)

**Comment by kazupon** [comment]
I think it has some cause in your editor enviroment.

**Comment by kevinbourassahoule** [comment]
For anyone encountering this issue with the � character, changing the encoding of the files containing my translations to UTF-8 fixed it for me.
