### ISSUE TITLE
[test] Deprecated assert.equal should be replaced with assert.strictEqual

### ISSUE THREAD

**Issue by exoego** [kazupon/vue-i18n#466]
In test codes, `assert` module's `assert.equal` are heavily used.

It is legacy API and deprecated since Node.js v9.9.0.
https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message

It is recommended to replace `assert.equal` with `assert.strictEqual`, so that test codes can run on future version of Node.js.

# What is a problem?

It emits warning and backward compatibility is **not guaranteed**.

For example, tons of the warnings are shown in test codes in IDE like WebStorm and Intellij IDEA.
![image](https://user-images.githubusercontent.com/127635/48653202-e8d9d380-ea46-11e8-9062-92ff08840f5c.png)

Such warnings may prevent contributors from finding important warnings.

# Note
I think this is `good first issue` for new contributors.

**Comment by kazupon** [comment]
@kimuraz 
sure! 😃
