### ISSUE TITLE
Add support for pluralization locales in component interpolation

### ISSUE THREAD

**Issue by sebermann** [kazupon/vue-i18n#471]
In order to avoid having to add markup to translations it would be helpful if component interpolation would also work for pluralization locales.

```js
const messages = {
  en: {
    comments: 'No comments | {n} comment | {n} comments'
  }
}
```

```html
<i18n path="comments" tag="p">
  <b place="n">{{ comments.length }}</b>
</i18n>
```

**Comment by WilliamDASILVA** [comment]
Hello,
It may be out of context but I was wondering how people handled pluralization with the component interpolation until now?

**Comment by ymhr** [comment]
What about an alternative implementation like:
```vue
<i18n path="some.path" :plural="3" />
```
It feels weird that there's some significant functionality in this library that you can't use if you're using the `<i18n />` tag.

**Comment by WilliamDASILVA** [comment]
I don't mind making the PR for this, but if we could agree on the specs of this?
I like @ymhr proposal to add the plural count in props.

@kazupon Any opinions on that?

**Comment by arantes555** [comment]
IMHO, it would be better to have another component name, like `$tc` is different from `$t`. I wouldn't really mind if it were the same component though, the feature would still be nice to have 😄

**Comment by sense-it-gmbh** [comment]
Are there any updates on this? Im running into this problem quite often.

I really like the proposal of @arantes555

**Comment by ewohlken2** [comment]
As a workaround I'm currently handling interpolation + pluralization like this:

```javascript
const messages = {
  en: {
    'comments': '{n} {comments-text}',
    'comments-plural': 'No comments | comment | comments',
  }
}
```

```html
<i18n path="comments" tag="h1">
    <b v-if="comments.length !== 0" slot="n">{{ comments.length }}</b>
    <span slot="comments-text">{{$tc('comments-plural', comments.length)}}</span>
</i18n>
```

It's not ideal, if anyone has better solution please let me know

**Comment by mariomka** [comment]
Something new? It will be so useful.

**Comment by KonradDeskiewicz** [comment]
@kazupon What do you mean by status: "Ready"? Is there a way to use pluralization in component interpolation?

**Comment by Magenta94** [comment]
Are you planning to release it soon? It's a useful feature

**Comment by dmitry** [comment]
I've made a bit simplier, rails way pluralization:

```javascript
  // https://github.com/eemeli/make-plural/blob/master/packages/plurals/plurals.js
  const pluralizationRules = {
    en: function (n) {
      const s = String(n).split('.')
      const v0 = !s[1]
      return (n === 1 && v0 ? 'one' : 'other')
    },
    de: function (n) {
      const s = String(n).split('.')
      const v0 = !s[1]
      return (n === 1 && v0 ? 'one' : 'other')
    }
  }

  Vue.prototype.$t = function (key, ...values) {
    const i18n = this.$i18n

    const options = values[0] || {}

    if (Object.keys(options).includes('count')) {
      key = `${key}.${pluralizationRules[i18n.locale](options.count)}`
    }

    return i18n._t(key, i18n.locale, i18n._getMessages(), this, ...values)
  }
```

**Comment by BlakeB415** [comment]
This is a very useful feature. Any ETA?

**Comment by dmitry** [comment]
@BlakeB415 https://github.com/intlify/vue-i18n-next

**Comment by nicooprat** [comment]
~~Docs: https://vue-i18n-next.intlify.dev/guide/advanced/component.html#pluralization-usage~~

Edit: https://vue-i18n.intlify.dev/guide/advanced/component.html#pluralization-usage

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
please try it!

**Comment by roelvanhintum** [comment]
Late to the party, but nuxt i18n is still on v8 so here's another workaround:

```vue
<i18n :path="`some.key.${Math.min(2, count)}`">
  <template #count>
    <strong>{{ count }}</strong>
  </template>
</i18n>
```

```js
module.exports = {
  some: {
    key: {
      0: '{count} equals none',
      1: '{count} equals one',
      2: '{count} equals more than one',
    },
  },
};
```
