### ISSUE TITLE
vue-i18n-extensions module with nuxt2 fail

### ISSUE THREAD

**Issue by ac88** [kazupon/vue-i18n#486]
### nuxt & vue-i18n version
ex: 2.3.1, 8.5.0

### Reproduction Link

vue-i18n-extensions-module-using-example-for-nuxt2

[![Edit vue-i18n-extensions-module-using-example-for-nuxt2](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nwnxp205kl)

use nuxt2 browser console display

```
[Vue warn]: Failed to resolve directive: t

(found in <Pages/index.vue> at pages/index.vue)
```

vue-i18n-extensions-module-using-example-for-nuxt1

[![Edit vue-i18n-extensions-module-using-example-for-nuxt1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n4jy4326w0)

nuxt1 version success,but nuxt 2 fail!

**Comment by kazupon** [comment]
Thank you for your reproting!

I seem `vue-i18n-extensions` isn't correctly installed in `nuxt.config.js`

please. you should check nuxt.js configuration, webpack 4 configration and vue-loader.
https://nuxtjs.org/faq/extend-webpack#how-to-extend-webpack-config-

**Comment by ac88** [comment]
@kazupon  https://codesandbox.io/s/n4jy4326w0 is success
can you update https://github.com/kazupon/vue-i18n/tree/dev/examples/module/nuxt  dependencies & use nuxt 2?
