### ISSUE TITLE
Release zips appear to have old versions of files

### ISSUE THREAD

**Issue by psiinon** [kazupon/vue-i18n#488]
### vue-i18n version
ex: 8.5.0 and earlier

### Reproduction Link
https://github.com/kazupon/vue-i18n/archive/v8.5.0.zip

### Steps to reproduce
Open the above archive and extract dist/vue-i18n.js

### What is Expected?
vue-i18n.js should be version 8.5.0

### What is actually happening?
vue-i18n.js is version 8.4.0

It looks like you are tagging too early? https://github.com/kazupon/vue-i18n/commits/dev

**Comment by kazupon** [comment]
Oh, Indeed. 😹 
That's tagged with `conventional-github-releaser`.
Maybe, That have a bug ...

**Comment by psiinon** [comment]
This is still happening - the vue-i18n library in v8.7.0 still says v8.6.0
