### ISSUE TITLE
Translate a key in a different language than the global locale

### ISSUE THREAD

**Issue by lucpotage** [kazupon/vue-i18n#491]
Hi, I'm using Nuxt.js with the nuxt-i18n module and I try to translate a specific key in a language that is different from the global locale `$i18n.locale`.

I tried to write something like `{{ $t('example', 'fr') }}` but by string is never translated in French. Do you have an idea whether this is a bug with the module or a feature that is not supported in vue-i18n?

The use case is the following: a user arrives on a page that is in English but the browser language is French. I want to invite the user to read the page in French and want to display the invitation in French whereas the rest of the page is in English.

Thanks in advance for your help.

**Comment by lucpotage** [comment]
Adding @manniL for reference.

**Comment by dobromir-hristov** [comment]
That works actually. I am using that feature, exactly as you have shown, second param is the desired language. I have not tested the nuxt module though.

**Comment by lucpotage** [comment]
OK. I'll close this issue since it's not directly related to the plugin. Thanks.

**Comment by codeflorist** [comment]
For anyone else coming accross this question:

Using the old package [kazupon/vue-i18n](https://github.com/kazupon/vue-i18n) the following should be possible:
```
$t(key, locale)
```
----------

When using the successor-package [intlify/vue-i18n-next](https://github.com/intlify/vue-i18n-next) , the answer depends on if you are using Vue I18n's **Legacy API** or the newer **Composition API**:

----------

Using **Legacy API** as described in the normal [setup guide](https://vue-i18n.intlify.dev/guide/) the usages of the `t()` function are stated [here](https://vue-i18n.intlify.dev/api/legacy.html#vuei18ntranslation).

This means you can still use the following call to translate a key to a specific locale (e.g. 'fr'):
```
$t(key, locale)
```
Example:
```
$t('message.key', 'fr')
```
----------

Using the **Composition API** by calling `createI18n()` with the option `legacy: false` (as described [here](https://vue-i18n.intlify.dev/guide/advanced/composition.html)), the usages of the `t()` function are different as stated [here](https://vue-i18n.intlify.dev/api/composition.html#composertranslation). You can no longer pass the locale-string as the second parameter, but the locale can be handed over inside a [`TranslateOptions` object](https://vue-i18n.intlify.dev/api/general.html#translateoptions). Unfortunately, there is no `t(key,TranslateOptions`) variant, but only the following variants:
```
$t(key, plural, TranslateOptions)
$t(key, defaultMsg, TranslateOptions)
$t(key, interpolations, TranslateOptions)
```
So the easiest solution would be e.g.:
```
$t('message.key', 1, { locale: 'fr' })
```
