### ISSUE TITLE
Documentation website seems not updating

### ISSUE THREAD

**Issue by bponomarenko** [kazupon/vue-i18n#494]
It seems like documentation website is not updated due to presence of two conflicting docs folders:
* [gitbook](https://github.com/kazupon/vue-i18n/tree/dev/gitbook)
* [vuepress](https://github.com/kazupon/vue-i18n/tree/dev/vuepress)

Looks like the actual documentation is located in `vuepress` folder, however multiple recent commits are updating docs in `gitbook` folder only.

Presence of two documentation folders are misleading and have to be fixed either by removing one of them, or updating Contribution Guideline with a clear information where to update docs.

### Steps to reproduce
1. Open one of the recent PRs with documentation update – for example [PR with new `pluralizationRules` constructor option](https://github.com/kazupon/vue-i18n/commit/ef4b1a6f50c120032f258f86b8a5f99df2ef1e0e).
1. Go to [corresponding section](https://kazupon.github.io/vue-i18n/api/#constructor-options) on documentation website and check the presence of new option.

### What is Expected?
Documentation website is updated.

### What is actually happening?
Documentation website is not updated.

**Comment by kazupon** [comment]
sorry, maybe, it's my mistake.
currently, website have updated.

**Comment by Loskir** [comment]
As I can see, there is still no mention of `pluralizationRules` on this page
https://kazupon.github.io/vue-i18n/guide/pluralization.html
