### ISSUE TITLE
[Bug Report] beforeDestroy can not find this.$t

### ISSUE THREAD

**Issue by masongzhi** [kazupon/vue-i18n#499]
### vue & vue-i18n version
ex: 2.5.21, 8.7.0

### Reproduction Link

https://jsfiddle.net/masongzhi/tpy4kv1e/8/
### Steps to reproduce
click the `destory vm` button, it will cause destroy the vm
### What is Expected?
should alert `こんにちは、世界`
### What is actually happening?
TypeError: Cannot read property '_t' of null

**Comment by masongzhi** [comment]
I make a PR to fix it
https://github.com/kazupon/vue-i18n/pull/500

**Comment by kazupon** [comment]
close due to merge!
