### ISSUE TITLE
What about directive?

### ISSUE THREAD

**Issue by Disorrder** [kazupon/vue-i18n#5]
Please, make it useful like angular-translate. I mean, it's really good to use it by directive and filter

For example,
```html
<span v-translate="error.{{authError}}"></span>
```
Renders into
```html
<span>Unexpected username!</span>
```

**Comment by kazupon** [comment]
Hi @Disorrder !!
Thank you for your comment.

The `vue-i18n` is inspired by Rails Internationalization API.
http://guides.rubyonrails.org/i18n.html

I think that current translation style is simple than better angular translate style.

Also, it's flexible as in the following code (e.g. inline, computed property and method).
https://jsfiddle.net/kazupon/0wmy4va2/3/

I don't plan to add feature in future.

**Comment by Disorrder** [comment]
easy, aniki :D Special for you! (es6 & jade syntax)
````es6
Vue.directive('translate', {
    isLiteral: true,
    update(val) {
        this.el.innerHTML = this.vm.$t(val);
    }
})
````
````jade
span(v-if="error", v-translate="error.{{error}}")
````

**Comment by kazupon** [comment]
Yes !
You can extend with custome directive. :)

**Comment by airtonix** [comment]
@Disorrder this would have also worked: 

```html
<a :v-text="$t('error.' + error)"></a>
```
