### ISSUE TITLE
can't parse key contain space in sub path correctly

### ISSUE THREAD

**Issue by gaodeng** [kazupon/vue-i18n#502]
### vue & vue-i18n version
2.5.16, 8.7.0

### Reproduction Link
http://jsfiddle.net/vshjg5bq/

### Steps to reproduce
```jsx
<div>{{ $t('PopupMenu.Play Now') }}</div>
<div>{{ $t('Hello World') }}</div>
```
```js
new VueI18n({
  locale: 'en',
  messages: {
    en: {
      'PopupMenu': {
        'Play Now': 'Play Now'
      },
      'Hello World':'Hello World'
    }
  }
})
```
### What is Expected?
Play Now
Hello World
### What is actually happening?
PopupMenu.Play Now
Hello World
```js
Cannot translate the value of keypath 'PopupMenu.Play Now'. Use the value of keypath as default.
```

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, keypath with hierarchical structure does not support space. 😞 
In the next major version, we plan to improve. 

However, you can avoid it with `_`. :)

**Comment by BobNobrain** [comment]
Maybe this should be noted in documentation? I didn't see this feature there

**Comment by exoego** [comment]
Opened a PR #533 to address this in `v8.x` before next major version.
