### ISSUE TITLE
Inline router links

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#507]
I often have translation such as:
```js
en: {
    message: {
      contact: 'Please <a href="/#contact">contact</a> us.'
    }
  },
```
But Vue does not see 'href' as a ``<router-link>``, so it refreshes the complete page. It would be great if we could use this to use the router as it should:
```js
en: {
    message: {
      contact: 'Please <a to="/#contact">contact</a> us.'
    }
  },
```

**Comment by onexdata** [comment]
You can use interpolation to do this very easily with <router-link> or any other component/mix/use-case you can think of.

https://kazupon.github.io/vue-i18n/guide/interpolation.html#advanced-usage

**Comment by tvld** [comment]
Excellent, use of ``<i18n place="contact">..</i18n>`` is even more elegant... thank you very much.
