### ISSUE TITLE
Dash "-" in key

### ISSUE THREAD

**Issue by vellotis** [kazupon/vue-i18n#51]
Hi

I have a question or a feature request. Why isn't  a dash (`-`) a [part of "indent"](https://github.com/kazupon/vue-i18n/blob/dev/src/path.js#L127-L129) instead of "else" in path parsing?

Example:
```js
{
  a: {
    b: 1,
    "b-c": 2 // <--
  }
}
```
I am migrating a SPA app to Vue and there internationalization keys use dashes.

I could make a PR for that if there is no reason why dash wouldn't be a part of a key name.

**Comment by mmochetti** [comment]
same as #24

**Comment by vellotis** [comment]
@kazupon ping?

**Comment by kazupon** [comment]
sorry, I'm busy too...
Please wait.

**Comment by tariq86** [comment]
I ran into the same issue while working on a project; PR submitted with solution suggested by @vellotis

**Comment by kazupon** [comment]
released v4.4.1
https://github.com/kazupon/vue-i18n/releases/tag/v4.4.1
