### ISSUE TITLE
$te will return false for empty strings

### ISSUE THREAD

**Issue by MrWook** [kazupon/vue-i18n#515]
With the newest version (probably with this commit https://github.com/kazupon/vue-i18n/commit/bed9c39) `$te` will return `false` for empty Strings.
Before the update it returned `true` for empty Strings.

### vue & vue-i18n version
ex: 2.5.2, 8.8.8

### Reproduction Link
 https://codesandbox.io/s/l4mlj428jl

Here is the same repo with the previous version:
https://codesandbox.io/s/ox9vj9x0l9

### Steps to reproduce
- click on the reproduction link
- look on the example application

### What is Expected?
- it should print `hi hello world! true

### What is actually happening?
- it print `hi hello world! false`

**Comment by kimuraz** [comment]
Hi @kazupon, can i get this one? :grimacing:

**Comment by kazupon** [comment]
@kimuraz 
Sure! :)
