### ISSUE TITLE
Ability to initialize plugin with empty messages object

### ISSUE THREAD

**Issue by lamka02sk** [kazupon/vue-i18n#516]
Currently when you initialize i18n with empty messages object, it gives warnings:
```
[vue-i18n] Value of key 'abcd' is not a string! vue-i18n.esm.js:14
[vue-i18n] Cannot translate the value of keypath 'abcd'. Use the value of keypath as default.
```
I think this would be super useful when you don't want to bundle default language into your project, because you don't actually know which one it will be. When importing default language in suck situation, you are just wasting users bandwidth. So in result, creating an instance would look like this:
```javascript
new VueI18n({
    locale: null
    messages: {}
});
```

**Comment by kazupon** [comment]
In general, when we implement the application, we bundle and release the default language. I have never encountered cases that generally do not bundle the default language. Also, even if there is, it is an edge case.
