### ISSUE TITLE
How to translate dynamic html

### ISSUE THREAD

**Issue by cwang18** [kazupon/vue-i18n#517]
Hello,

I'm trying to translate messages which contains Vue binding but couldn't make it work. For example:

html:

<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-i18n/dist/vue-i18n"></script>
<div id="app">
  <p v-html="$t('tonextpage')"></p>
</div>

JS:

Vue.use(VueI18n);

const messages = {
	en: {
  		tonextpage: "Go to <a :href='toNextPage'>next</a> page"
	  }
 };

window.i18n = new VueI18n({
  locale: 'en', // set locale
  fallbackLocale: 'en',
	messages, // set locale messages
  });

new Vue({
  el: '#app',
  i18n,
  methods: {
     toNextPage() { alert("YAY!"); }
  }
})

There are ways to make it work if only for this one message "tonextpage". But the value of "tonextpage" may change, and there could be more messages containing other Vue directives.

Any general solutions to translate a message with Vue directives?

Many thanks in advance!

**Comment by kazupon** [comment]
Could you provide more context, please?

**Comment by cwang18** [comment]
Sorry looks like I pasted wrong code. Corrected here:

HTML:

<script src="https://unpkg.com/vue"></script> <script src="https://unpkg.com/vue-i18n/dist/vue-i18n"></script> 

<div id="app">
  <p v-html="$t('tonextpage')"></p>
  <p> <a href="#" @click='toNextPage()'>Go to next page</a></p>
</div>


JS:

Vue.use(VueI18n);
const messages = {
en: {
tonextpage: "<a href='#' @click='toNextPage'>Go to next page</a>"
}
};
window.i18n = new VueI18n({
locale: 'en', // set locale
fallbackLocale: 'en',
messages, // set locale messages
});
new Vue({
el: '#app',
i18n,
methods: {
toNextPage() { alert("YAY!"); }
}
})

My Question is, how to make the @click work in translation.

Many thanks!

**Comment by kazupon** [comment]
You can use the component interpolation.
See the docs:
https://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage

**Comment by cwang18** [comment]
Thanks!
