### ISSUE TITLE
Question: Translate strings in alert

### ISSUE THREAD

**Issue by hajkli** [kazupon/vue-i18n#523]
Hello

Could I ask you, if there is some way to translate strings in alert. 

Example:
After click on buttom I got alert() whit some string. Can I get this string dynamicali from i18n based on current locale?

Edit: my alert function is not part of vue.js, I have to pass trasnlated data to another library to execute some staff like special alert.

Thank you very much.

Edit 2 : Solved:  alert(i18n.t("message.hello")) is my answer.

**Comment by kazupon** [comment]
closing due to self-resolved
