### ISSUE TITLE
Lack of documentation?

### ISSUE THREAD

**Issue by karimcambridge** [kazupon/vue-i18n#527]
I don't understand...

I have this, based on documentation

```// Ready translated locale messages
const messages = {
	en: {
		release_notes: 'Release Notes'
	},
	fi: {
		release_notes: 'Julkaisutiedot'
	}
};

// Create VueI18n instance with options
const i18n = new VueI18n({
	locale: 'en',
	fallbackLocale: 'en',
	messages
});

const component1 = {
  template: `<div class="changelog-heading" id="changelog-heading">
						{{ $t("release_notes") }}
					</div>`,
  i18n: { // `i18n` option, setup locale info for component
    messages: {
      en: { release_notes: 'Release Notes' },
      fi: { release_notes: 'Julkaisutiedot' }
    }
  }
};

new Vue({
  i18n,
  components: {
    component1
  }
}).$mount('#app');
```

So then I do this `i18n.locale = currentLanguageCode;` later on in my code for when a user changes their language.. but nothing updates.

I googled it and it says something about using `computed` or `data` properties... BUT

there is NO documentation for this stuff? http://kazupon.github.io/vue-i18n/introduction.html

**Comment by kimuraz** [comment]
Hi @karimcambridge did you see [this](https://kazupon.github.io/vue-i18n/guide/locale.html#locale-changing) part of the docs?

**Comment by karimcambridge** [comment]
Yes?

My code is already changing the locale (I've debugged and testing it)

but it says nothing about the text/data automatically switching to the new locale or whats not. It's a bit vague.

Also no where still explains what `data` or `computed` does exactly.

**Comment by kazupon** [comment]
close (in-activity)
