### ISSUE TITLE
IE11 + template literals in translations

### ISSUE THREAD

**Issue by devboxr** [kazupon/vue-i18n#53]
Hi there,

I have a JSON such as:

```
{
  "statuses": {
    "good: "Good",
    "bad: "Bad",
  }
}
```

In my `.vue` files I'm using, for example:

```html
<p>
  {{ $t(`statuses.${status}`) }}
</p>
```

This works fine in all browsers except IE.

It works however if I change it to the classic style:

```html
<p>
  {{ $t('statuses.' + status') }}
</p>
```

**Note:** Remove use of template literals and concat string instead. Unfortunately this is then breaking the airbnb/javascript guidelines, so this is not an option for me.

Is this known? Any way around this?

I am using the webpack vue-cli template.

Thanks

**Comment by kazupon** [comment]
You can avoid with using transpiler like `babel` or `bible`.
