### ISSUE TITLE
[Feature Request] i18n filter

### ISSUE THREAD

**Issue by chiaweilee** [kazupon/vue-i18n#534]
### Feature

filter support

#### Declarative

```javascript
// {{ $t('hello') }}
{{ 'hello' | t }}
```

#### Functional Programming

```javascript
// {{ capitalize($t('hello')) }}
// {{ $t('hello') | capitalize }}
{{ 'hello' | t | capitalize }}
```

**Comment by exoego** [comment]
@chiaweilee 
Could you add more detail to issue?
Do you want to introduce new feature (Vue filter `t` as different form of `$t`) to `vue-i18n`?

If so, you should [create a Pull Request](https://help.github.com/en/articles/creating-a-pull-request)

**Comment by chiaweilee** [comment]
> @chiaweilee
> Could you add more detail to issue?
> Do you want to introduce new feature (Vue filter `t` as different form of `$t`) to `vue-i18n`?
> 
> If so, you should [create a Pull Request](https://help.github.com/en/articles/creating-a-pull-request)

🚥processing...

**Comment by bponomarenko** [comment]
@chiaweilee I'm wondering is `$t` as a filter name would be more consistent than just `t`? What if `t` were already defined in some existing projects as a filter – will that create a conflict on update to a newer `vue-i18n` pacakge version?

**Comment by chiaweilee** [comment]
> @chiaweilee I'm wondering is `$t` as a filter name would be more consistent than just `t`? What if `t` were already defined in some existing projects as a filter – will that create a conflict on update to a newer `vue-i18n` pacakge version?

It is, however, `t` is more declarative and elegant.
A warning of conflict could be helpful.

**Comment by exoego** [comment]
Closing due to https://github.com/kazupon/vue-i18n/pull/555#issuecomment-517828465
Thanks for opening this feature request.
