### ISSUE TITLE
What's format of `en.js` or `ja.js` in lazy load

### ISSUE THREAD

**Issue by essivision** [kazupon/vue-i18n#537]
Got a question?
===============
What's format of `en.js` or `ja.js` in lazy load? below code doesn't work: 
```
// en.js
export default
    {
        title: 'Title',
        greeting: 'How are you'
    };
```
and 
```
import Vue from 'vue';
import InventoryList from "./components/InventoryList";
import VueI18n from 'vue-i18n';
import messages from 'lang/fa';

Vue.use(VueI18n);

const i18n = new VueI18n({
    locale: 'en',
    fallbackLocale: 'en',
    messages
});

Vue.component('inventory-list', InventoryList);

const app = new Vue({
    i18n,
    el: '#app',
});
```
What should I do?

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. 
The issue list only accepts bug reports and feature requests. 
Questions should be posted to the [Discord for Vue Community](https://vue-land.js.org/),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue-i18n).

Thanks.

**Comment by kazupon** [comment]
> import messages from 'lang/fa';

Is it correct locale messages structure?
