### ISSUE TITLE
[Feature request] Formatting for localized numbers

### ISSUE THREAD

**Issue by bponomarenko** [kazupon/vue-i18n#539]
### Use case

On a project I'm working on there is requirement to have customized formatting of the localized numbers. For example, it should be possible to render fraction part of the number with superscript styles:

```html
$3.500,<span style="vertical-align: super">00</span>
```

In my experience, this is common use case, so possibility to have such formatting will be beneficial not only to my project.

### Feature request

This custom formatting can be easily achieved by utilising [`Intl.Numberformat.prototype.formatToParts()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts) method.

In terms of `vue-i18n` implementation, this would require to introduce few new APIs:

1. New private `_ntp` method (aka _numberToParts).
Implementation wise it will be exact copy of the existing `_n` method with the only difference in the formatting function and returned output. `_ntp` with use `formatToParts` and will output array of objects containing the formatted number in parts.

1. New functional component `<i18n-n>`.
This component will utilise `_ntp` method to format number, and will allow to specify named slots to apply custom formatting. Slot names will be the same as [type attribute of the objects from `_ntp` returned Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts#Description).

   Component props:

   - `value {number}`: required
   - `key {Path | object}`: optional
   - `locale {Locale}`: optional, locale
   - `tag {string}`: optional, default `span`

#### Usage examples

Number formats:
```js
const numberFormats = {
  'en-US': {
    currency: {
      style: 'currency', currency: 'USD'
    }
  },
  'ja-JP': {
    currency: {
      style: 'currency', currency: 'JPY', currencyDisplay: 'symbol'
    }
  }
}
```

Template:
```html
<i18n-n :value="3500" key="currency"></i18n-n>

<i18n-n :value="100" key="currency" locale="ja-JP"></i18n-n>

<i18n-n :value="1234" :key="{ style: 'currency', currency: 'EUR', currencyDisplay: 'code' }" tag="p">
  <span v-slot:currency="({ currency })" style="font-weight: bold">{{ currency }}</span>
  <span v-slot:fraction="({ fraction })" style="vertical-align: super">{{ fraction }}</span>
</i18n-n>
```

Expected result:
```html
<span>$3,500.00</span>

<span>￥100</span>

<p><span style="font-weight: bold">EUR</span> 1,234.<span style="vertical-align: super">00</span></p>
```

Each slot will have the following properties:
- `[type]` – property with actual value, which will have the same name as slot's type.
- `index` – indicates index of the of the specific part in the parts array. Can be useful when formatting part that appears multiple times (i.e. "integer").
- `parts` – raw parts array as returned from the `_ntp` function. Can be useful for conditional part formatting based on the presence of specific parts in the resulting array.

### Other potential usage

Can be utilised to workaround #369 by adding number abbreviation after fraction part:

```html
<template>
  <i18n-n :value="formatValue">
    <template v-slot:fraction="({ fraction })">
      {{`${fraction}${abbreviation}` }}
    </template>
  </i18n-n>
</template>

<script>
export default {
  data: () => ({ value: 1200000 }), // 1,2M
  computed: {
    formatValue() {
        return this.value / Math.pow(10, d3.precisionPrefix(1, this.value));
    },
    abbreviation() {
        return d3.formatPrefix('.0s', this.value)(this.value).replace(/\d/, '');
    },
  },
};
</script>
```

For sure, this implementation have to be improved to handle situation when formatted number has no fraction part, but that's a good start. This can even be turned into separate component (inside actual project), so no hacky overrides of the `vue-i18n` functionality.

What do you think @kazupon ? I can create PR if API is ok with you.

**Comment by kazupon** [comment]
@bponomarenko 
Thank you for your proposal!
I think it's awesome!
I'll be waiting for your PR.

**Comment by bponomarenko** [comment]
@kazupon Great!

I have a follow up question then. There is `src/component.js` for existing `<i18n>` component, so I wonder where I have to put code for `<i18n-n>` component, because `src/component-n.js` does not sound as a great idea?

Should I rename `src/component.js` to `src/components/i18n.js` and have `src/components/i18n-n.js` next to it? Would it be a breaking change?
Or maybe you have a better suggestion?

**Comment by kazupon** [comment]
>Should I rename src/component.js to src/components/i18n.js and have src/components/i18n-n.js next to it?

I hope it!
I don't think it's breaking change, because feature request is backward compatible.
Also, Basically, this feature request is extend of the feature.

**Comment by bponomarenko** [comment]
Hmm, ok.
I hope nobody is dependant on the internal files structure. After all, it is not "public API".
