### ISSUE TITLE
Usage inside .text("")

### ISSUE THREAD

**Issue by PetraBencek** [kazupon/vue-i18n#542]
Hello!

Can you please suggest me how can I include my: `{{ $t("message.page_title") }}` inside: 

`$('#pageTitle').text("Reservation")`

 instead of word `Reservation`? Thank you!

**Comment by bponomarenko** [comment]
I guess, the easiest option would be to manually create VueI18n instance and use `t` function on it:

```js
var i18n = new VueI18n({ ... });

$('#pageTitle').text(i18n.t('message.page_title'));
```

**Comment by kazupon** [comment]
You can be solved with the way @bponomarenko mentioned.
