### ISSUE TITLE
(PART 2): [vuex] Do not mutate vuex store state outside mutation handlers - how to dynamically change locale w/o state being affected?

### ISSUE THREAD

**Issue by skalfyfan** [kazupon/vue-i18n#55]
Hi! 

I'd like to re-visit the following issue that was reported earlier: https://github.com/kazupon/vue-i18n/issues/38

First off, we love the plugin and it appears to be the perfect solution for our multilingual app, but we're into a similar issue as linked above. The above issue was closed simply by the reporter changing their Vuex module setting of:

`strict: true` to `strict: false`

To me this is not a "_solution_", but rather a kind of hack-fix. Would like to get to the bottom of the issue? While `strict: true` should not be configured for production, we do use this mode in dev to ensure we're building correctly and if we're receiving the above error message there is an underlying issue. 

Is there a simple way to dynamically change the locale without setting it affecting the state? Can you change the locale at the router and/or component level at all ? Is there some kind of deep watchers conflict between vue-i18n and vuex which is causing this? all kinds of questions :)

We are running into the same issue above, but are changing the language dynamically using `vue-router` like so:

```
router.beforeEach((transition) => {
    // determine language
    // hyHeader.lang configured property defining what language to use
    let hyHeader = document.querySelector('hy-header')
    if (hyHeader !== null) {
      Vue.config.lang = hyHeader.lang
    }

    console.log(`Language: ${Vue.config.lang}`)

    window.scrollTo(0, 0)
    transition.next()
})
```

Everything works fine in English locale (default), but as soon as we switch to French (fr) and after a transition the console errors state (Chrome):

```
vue.common.js?e881:3337 Uncaught Error: [vuex] Do not mutate vuex store state outside mutation handlers.Watcher.deep @ vuex.js?90cb:624Watcher.run @ vue.common.js?e881:3340Watcher.update @ vue.common.js?e881:3292update @ vue-i18n.common.js?2c49:134(anonymous function) @ vue-i18n.common.js?2c49:150Watcher.run @ vue.common.js?e881:3332runBatcherQueue @ vue.common.js?e881:3071flushBatcherQueue @ vue.common.js?e881:3042nextTickHandler @ vue.common.js?e881:445
vue.common.js?e881:3301 Uncaught Error: [vue] async stack trace
```

It doesn't really make sense to me because we are not using anything at all related to Vuex or state to configure our language? 

**Using:**
_VueJS_ 1.0.26
_Vuex_ 1.0.0 RC2
_Vue-Router_ 0.7.11
_Vue-i18n_ 4.4.1

**Comment by kazupon** [comment]
I tried to reproduce this issue.
https://jsfiddle.net/kazupon/y1qtk2tq/16/

I'll try to improve this issue.

**Comment by skalfyfan** [comment]
Nice example! It is basically demonstrating what we are seeing as well, and when this error occurs it kills all Vue reactivity (in your example, if you try and switch back to 'en' from 'ja' the content does not update locale change.

I find it very odd though. Where in your example are you mutating state outside of the mutation handler? Does mutating state in the _plugin_ count as mutating state outside mutation handlers? 

In our example we are *NOT* using `Vuex` to change language at all. As you'll see in my original post above we are changing language in the `router` using the `beforeEach` hook.

We are very confused why this error only appears in `strict: true` mode and when we switch to french, and go to the next route. Any ideas?

Thanks for trying to reproduce!

**Comment by kazupon** [comment]
>I find it very odd though. Where in your example are you mutating state outside of the mutation handler? Does mutating state in the plugin count as mutating state outside mutation handlers?

The cause of vuex mutation error is bacause force updating with `watcher.update` in Vue instance.
This error occur in vue 1.0.x.
See the below implementation code:
https://github.com/kazupon/vue-i18n/blob/dev/src/override.js#L6-L8

by the way, In Vue 2.0, it does not occur.
http://jsfiddle.net/kazupon/k2z77mv7/7/

>We are very confused why this error only appears in strict: true mode and when we switch to french, and go to the next route. Any ideas?

I think the you can avoid with using `$store.state` 
see the jsfiddle example:
http://jsfiddle.net/kazupon/gva8x8ct/2/

**Comment by kazupon** [comment]
release v6.0.0
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0
