### ISSUE TITLE
A slot with an I18N functional component does not render the contents of the slot. Why?

### ISSUE THREAD

**Issue by qiqingfu** [kazupon/vue-i18n#556]
This is my code. 

```javascript
   export default {
	crumbs: {
		tos: 'Term of Service',
		term: 'I have read the terms of service.'
	}
}
```

Using I18N functional components
```javascript
<i18n
      path="crumbs.term"
      tag="p"
    >
      <a href="#">$t('crumbs.tos')</a>
    </i18n>
```

But the rendering is like this
```html
<p>I have read the terms of service.</p>
``` 
I don't know why the tag a used has not been rendered, I'm following the official example. Is there anything wrong with my use?

**Comment by bponomarenko** [comment]
@qiqingfu Indeed your setup is not entirely correct – `crumbs.term` is missing formatting parameter. It should be like this:

```js
crumbs: {
  tos: 'Term of Service',
  term: 'I have read the {0}.'
}
```

**Comment by qiqingfu** [comment]
@bponomarenko thank
