### ISSUE TITLE
Pluralization : block at 3 variables

### ISSUE THREAD

**Issue by sdeceuninck** [kazupon/vue-i18n#562]
VERSION
vue : latest version based on CDN (fiddle)
vue-i18n : lastest version based on CDN (fiddle)

### Reproduction Link
https://jsfiddle.net/SylvainD/xkoev5m9/3/

### Steps to reproduce
Create a pluralization with 5 elements
Try to show this 5 elements using $tc

### What is Expected?
The result should be an page with the 5 numbers.

### What is actually happening?
The first 3 first number are OK but the 2 lastest are not, it seems that the index of $tc does'nt work after the third element is the list.

**Comment by everhardt** [comment]
Documentation is not to clear about it, but I gather:
- if you specify 2 elements, the first will be used for n=1, the second for all other n
- if you specify 3 or more elements, the first will be used for 0, the second for 1 and the third for 2 or more. All elements after that are ignored. 

To try it out, see https://jsfiddle.net/3myo1qnd/2/ and https://jsfiddle.net/3myo1qnd/1/

**Comment by sdeceuninck** [comment]
Ah ok !!!! It's for me a really strange behaviour ...
I didn't get it at all.

Thanks for your answer.

**Comment by chenweihuan** [comment]
Who can tell me why? This is strange.
