### ISSUE TITLE
translation doesn't work if used within data()

### ISSUE THREAD

**Issue by saitam1** [kazupon/vue-i18n#569]
### vue & vue-i18n version
3.5.1 & 8.10.0

### Reproduction Link
https://codepen.io/saitam1/pen/rbzGPY
_check the navigation drawer_

### Steps to reproduce
Use `$t()` within `data`

### What is Expected?
Translation as in all other situations

### What is actually happening?
Doesn't translate

**Comment by kazupon** [comment]
Thank you for your reporting!

You can avoid with `this.$t.bind(this)`.
See the docs:
https://kazupon.github.io/vue-i18n/api/#vue-injected-methods
