### ISSUE TITLE
Using vue-i18n with Node without Vue?

### ISSUE THREAD

**Issue by nicooprat** [kazupon/vue-i18n#570]
Hi there,

I'm trying to use vue-i18n server-side to translate some email templates with a process as close as possible of what we're doing client-side.

I got it working like this: https://runkit.com/nicooprat/vue-i18n-node. It could be fine this way but it's sad to import Vue only to init vue-i18n...

Would it be possible to get it working without Vue and `Vue.use()`?

Thanks!

**Comment by kazupon** [comment]
Unfortunatly, vue-i18n need to require vue.

In the future, I extract i18n common features and I have plan to provide that as the library/framework.

**Comment by nicooprat** [comment]
Glad to hear! For what's it's worth, it's possible to use it with Vue server-side as is. If needed to render some components, just use `vue-server-renderer`: https://ssr.vuejs.org/guide/#rendering-a-vue-instance

**Comment by mhf-ir** [comment]
Is there any method to use locales file without VueJS
* Centralize i18n messages For back ends and front ends :tokyo_tower: 
* Front with vue :globe_with_meridians: 
* Backedn with nodejs for example sending email or Generate PDF or etc ... :email:

**Comment by nicooprat** [comment]
As long as the i18n library you use in your backend can understand the format of the translation files, there's no problem at all I guess!

**Comment by mhf-ir** [comment]
I think this must be part of documentation, using plurals, formatter or etc just using this package and messages.

**Comment by exoego** [comment]
Contribution welcome.
