### ISSUE TITLE
o.formatToParts is not a function

### ISSUE THREAD

**Issue by jkvora** [kazupon/vue-i18n#571]
I am using vue-i18n for displaying currency in different locale.But in safari browser 
**formatToParts** is not supported.
Here is the compatibility browser matrix: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts

**Comment by kazupon** [comment]
You can avoid that issue with polyfill
e.g. Intl.js: https://github.com/andyearnshaw/Intl.js
