### ISSUE TITLE
How to solve language invariant in js file

### ISSUE THREAD

**Issue by mrTwelve12** [kazupon/vue-i18n#578]
### vue & vue-i18n version
ex: 2.1.0, 5.0

**Comment by mrTwelve12** [comment]
like this 
`var orderType = [
  { title: i18n.t('global.directMail'), value: 1 }
]`

**Comment by kazupon** [comment]
Thanks for filing the issue!
Please follow the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin or CodeSandbox containing a set of reproducible steps that can lead to the behavior you described.
