### ISSUE TITLE
Translation strings not passed through vue parser

### ISSUE THREAD

**Issue by callumacrae** [kazupon/vue-i18n#58]
I'm using vue-router, so when I want to make a link, I use v-link. Unfortunately, that means it's impossible for me to make a link in a translation, because the text isn't being passed through the parser.

en-GB.js:

``` js
export default {
     link: '<p>Click this <a v-link="{ path: \'/some-page\' }">link</a></p>',
};
```

`Page.vue`:

``` html
<template>
  <div>{{{ $t('link') }}}</div>
</template>
```

Expected output:

``` html
<p>Click this <a href="#!/some-page">link</a></p>
```

Actual output:

``` html
<p>Click this <a v-link="{ path: \'/some-page\' }">link</a></p>
```

**Comment by Pawlox** [comment]
Any workaround for that? :/

**Comment by kazupon** [comment]
related #37
I think that this feature can support component interpolation.
