### ISSUE TITLE
Translation should not return an object

### ISSUE THREAD

**Issue by victor71** [kazupon/vue-i18n#583]
Locale messages like this:
`
en : {
    tips: {
                 select: "Please select an record!"  
            }
}
`
this.$t("tips") will return a plain object, but I just want it return 'tips'.

**Comment by mathieumagalhaes** [comment]
I do like the fact that it return an object as it works with arrays as well.
It should be nice if this changes, to make it configurable and optional

**Comment by victor71** [comment]
@mathieumagalhaes Yes, configurable would be very nice.

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
In v9, you need to use `tm` or `$tm`.
please try it!
