### ISSUE TITLE
Wild idea?  Full text search?

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#586]
i18n is our main text driver and a great tool. Breaking our heads over how to implement a good, multi-language site search, it occurred to us that i18n already holds all our text and so in theory, this could work:
```js
let searchFor = 'red wine'
let resultArray = this.$tf(searchFor) // finds array of objects with at least the found text and $route
```
Of course the issue is to get all the $routes for each call of $t() ...But I don't have good answer. Rendering all pages in background on first search would not work for very large sites...

**Comment by kazupon** [comment]
Full-text search is not a feature of VueI18n and should be implemented in userland.
