### ISSUE TITLE
Array is not supported.

### ISSUE THREAD

**Issue by Wanderxx** [kazupon/vue-i18n#59]
When I work on a `select` component I want to $t return different array depends on the lang I set.
Like,

```
locales : {
  zh : {
    userTypes : ['普通用户', '管理员', '访客']
  },
  en : {
    userTypes : ['user', 'admin', 'visitor']
  }
}
```

Right now, it only returns `string`.

My work around is directly return the `val` when args is `[]`
In `translate function()`,

```
return ( args && args != 0 )? format(val, args) : val
```

**Comment by callumacrae** [comment]
Please make sure that when this is implemented, you don't break `new String('My string')`: Check `Array.isArray()`, not `typeof` :)
