### ISSUE TITLE
Can I add dynamic locales?

### ISSUE THREAD

**Issue by Disorrder** [kazupon/vue-i18n#6]
Hello.
I have several big files with locales. What is the best way to include them to i18n?
I see only one solution now, add all locales anywhere in global scope (f.e. `window`) and then init 
````javascript
Vue.use(window['vue-i18n'], {
    lang: 'en', // here I want to set 1st language I defined
    locales: window.locales
})
````
But uncomfortable, because I must define all locales before `Vue.use()`.

**Comment by kazupon** [comment]
Hi

One Solution, You can include  locales which was bundled with browserify or webpack, and then you can use `require` function (CommonJS style).

brwserify
http://browserify.org

webpack
http://webpack.github.io

**Comment by SeoFood** [comment]
Im also interested in loading the translations dynamic. Because you dont need all languages compiled into js. You can load them via json etc.

**Comment by meganabigaildavidson** [comment]
:+1: for being able to load individual locales from json, this would help cut down on having to include every single locale file, especially if you support many languages and the files are large. I know with i18next-client you can point it towards a directory and it will call the relevant son file depending upon the language.

**Comment by aaronjpitts** [comment]
Any update on support for this? It is a must to be able to load languages on demand and not all at once. Thanks again

**Comment by kazupon** [comment]
sorry, I'm hard work ...  :bow:
