### ISSUE TITLE
Example of i18n custom formatter?

### ISSUE THREAD

**Issue by skalfyfan** [kazupon/vue-i18n#61]
Would it be possible to get an example (in the example folder source) for creating a custom i18n formatter as described at the bottom of the documentation on this page:

https://kazupon.github.io/vue-i18n/formatting.html

We'd like to create a custom _currency_ formatter which will render currency depending on active language.

For example we'd like to have a locale setup like:

```
{
  "en": {
    "charged": "${dollars} will be charged to your credit card"
  },
  "fr": {
    "charged": "Un montant de ${dollars} sera porté à votre carte de crédit"
  }
}
```

and then be able to call via:

```
$t('charged', { dollars: 10.00 })
```

This would render: 
EN:
_$10.00 will be charged to your credit card_
FR:
_Un montant de 10,00 $ sera porté à votre carte de crédit_

Is this possible at all currently? It seems like this would be a perfect example for a custom i18n formatter :) The formatter can then determine the language and render the currency correctly whether it be  dollars, yen, pounds etc.

**Comment by kazupon** [comment]
release v6.0.0
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0
