### ISSUE TITLE
Cannot read property '_t' of null

### ISSUE THREAD

**Issue by zeloat** [kazupon/vue-i18n#618]
### vue & vue-i18n version
ex: 2.6.10, 8.10.0

### Reproduction Link

`mounted () {
    setTimout(() => {
        this.$t('test');
    }, 2000);
}`

### Steps to reproduce

After entering the page, jump out in 2 seconds. The console will report an error

### What is Expected?

The console display nothing

### What is actually happening?

Console Error: Cannot read property '_t' of null

This actually happens in some asynchronous requests.

**Comment by kazupon** [comment]
Thanks for filing the issue!
Please follow the [Issue Reporting Guidelines](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin or CodeSandbox containing a set of reproducible steps that can lead to the behavior you described.
