### ISSUE TITLE
Unexpected space

### ISSUE THREAD

**Issue by MNemoto15** [kazupon/vue-i18n#623]
### vue & vue-i18n version

vue: 2.6.10
vue-i18n: 8.11.2

### Reproduction Link

https://jsfiddle.net/MNemoto15/20o9m4vq/4/

### Steps to reproduce

* message

```js
const i18n = new VueI18n({
  locale: 'en',
  messages: {
    en: {
      info: 'You can {action}, until 15 minutes from departure.',
      change: 'change your flight',
    }
  }
});
```

* add line breaks before closing tab

```vue
<i18n path="info" tag="p">
  <a place="action" :href="changeUrl">
    {{ $t('change') }}
  </a>
</i18n>
```
* appear a space in front of comma

```
You can change your flight , until 15 minutes from departure.
```

### What is Expected?

No space in front of comma

**Comment by thedamon** [comment]
I wouldn't say this is entirely unexpected. A linebreak in html counts as a space so this is being interpreted in a way that is logical and correct even though it is not particularly intuitive. 

As you show in the jsfiddle, you can work around it by not including the linebreak before the closing `</a>` tag. With the linebreak there, a space is being added. This is a 'feature' of HTML, and happens in Vue.js components in general. 

The main issue is inline elements being formatted as block elements for readability when HTML is not a syntax that concerns itself with readability.

**Comment by MNemoto15** [comment]
Thank you for your kind instruction.
I understand this is not library problem.
