### ISSUE TITLE
Root fallback uses fallback locale even though current locale is available

### ISSUE THREAD

**Issue by graup** [kazupon/vue-i18n#624]
### vue & vue-i18n version
vue@2.6.10, vue-i18n@8.11.2

### Reproduction Link
https://github.com/graup/vue-i18n-issue

### Steps to reproduce
1. Add messages to root and component
2. Use key missing in component but available in root

### What is Expected?
It uses the root fallback in the current language.

### What is actually happening?
It uses the root fallback in the fallback language.

**Comment by graup** [comment]
Oh, I just found the solution here: https://github.com/kazupon/vue-i18n/issues/216#issuecomment-449799739

Maybe we could add a note to the docs ([here](https://kazupon.github.io/vue-i18n/guide/locale.html#locale-changing)) that using `$i18n.locale` does not update the root locale.

**Comment by kazupon** [comment]
@graup 
You can send PR! :)
