### ISSUE TITLE
Dot notation as key is not supported / not working

### ISSUE THREAD

**Issue by darkylmnx** [kazupon/vue-i18n#63]
### vue & vue-i18n version
4.6

with the bellow json code as translation

```
{
  "CATEGORIES": {

    "HOME": "Maison",

    "HOME.KITCHEN_USTENSIL": "Ustensiles de cuisine (batteur, plat...)",

    "HOME.KITCHEN_APPLIANCE": "Matériel de cuisine (appareil à crêpes, raclette...)",

    "HOME.DECORATION": "Décoration et art de la table (nappe, tenture...)",

    "HOME.MAINTENANCE": "Matériel d'entretien / nettoyage",

    "HOME.FURNITURE": "Mobilier intérieur/extérieur",

    "HOME.OFFICE_EQUIPMENT": "Matériel de bureau",

    "HOME.DOMESTIC_ELECTRICAL": "Electroménager",

    "HOME.PET_SHOP": "Animalerie",

    "DIY_AND_GARDEN": "Bricolage & jardinage",

    "DIY_AND_GARDEN.DIY": "Matériel et outils de bricolage / réparation",

    "DIY_AND_GARDEN.GARDENING": "Matériel et outils de jardinage",

    "DIY_AND_GARDEN.BUILDING_MATERIAL": "Matériel de construction"
  }
}
```

### What is Expected?

as in angular-translate, i was excpecting `CATEGORIES.HOME.KITCHEN_USTENSIL` to compile to it's content in the json

### What is actually happening?
warn : Cannot translate the value of keypath "CATEGORIES.HOME.KITCHEN_USTENSIL"

I understand why it does that, it's because you interpolate and never check if there's a key having the dot notation pattern, any fix soon ?

**Comment by kazupon** [comment]
sorry, for the late response.

in currently version, this is the specification that dot notation pattern of keypath cannot compile to content in the json.

I will not plan to support it, because keypath translating became complexity If dot notation pattern of keypath should resolve.

**Comment by darkylmnx** [comment]
@kazupon yes, i guess it brings complexity, well any alternatives ? because currently, it's the rest API who is sending me bundle keys and i'm not the one dealing with it, it's an enterprise, API :

```
{
  "CATEGORIES": {
    "HOME": "Maison",
    "HOME.KITCHEN_USTENSIL": "Ustensiles de cuisine (batteur, plat...)"
   }
}
```
How can i get the following to work ? : 
`{{ $t('HOME') }} and {{ $t('HOME.KITCHEN_USTENSIL') }}`

arigatou gozaimasu.
