### ISSUE TITLE
Are locale json files global?

### ISSUE THREAD

**Issue by GELight** [kazupon/vue-i18n#630]
Hi,

I hope it is ok for you when I post my forum post from the vue forum.
https://forum.vuejs.org/t/is-the-import-from-global/67367

It looks that our app related localization files in the locales folder ( z.B. de.json ) are  global for all i18n plugins defined...!?!?

Is this correct or is there a problem how a I use your vue plugin?

Best regards,
Mario

**Comment by kazupon** [comment]
Basically, the localization information set in the VueI18n instance is global.
