### ISSUE TITLE
How to keep language after refresh?

### ISSUE THREAD

**Issue by mawieutc** [kazupon/vue-i18n#633]
Hi,
I don't know how to access $i18n.locale in runtime. Therefore I don't know how to keep it in my session.

```
<select class="dropdown-menu-lang " aria-labelledby="dropdown07" v-model="$i18n.locale" @change="langChanged($i18n.locale)" >
                            <option class="dropdown-item-lang" v-for="(lang, i) in langs" :key="`Lang${i}`" :value="lang">{{ lang }}</option>
                        </select>

langs: ['fr', 'en'],
```

Here is what I tried
```
 mounted(){
     if(localStorage.Lang!=null) $i18n.locale=localStorage.Lang; //how to access $i18n.locale ??
 },
```

```
langChanged(lang){
      localStorage.Lang=lang; //this is OK
},
```

Thank you very much

**Comment by pribadi1st** [comment]
my suggestion you can save it in vuex store

**Comment by mathieumagalhaes** [comment]
I check in vue-router beforeEach() lifecycle if the route is prefixed with /en /nl or /fr and adjust the language accordingly if needed. This also works with SSR

**Comment by kazupon** [comment]
This is not a problem of vue-i18n. If you want to keep locale across concepts, you need to use a store such as vuex.
