### ISSUE TITLE
Mixin erases i18n block in SFC

### ISSUE THREAD

**Issue by thedamon** [kazupon/vue-i18n#634]
I am setting translations within i18n blocks with the vue-i18n-loader inside my single file components. it was working perfectly until I added an i18n block inside a mixin that the component is using. 

The mixin i18n block seems to replace the component's i18n block ( `Cannot translate the value of keypath...` ). It will happen even if the i18n block in the mixin is empty. And if I log `this.$i18n.messages` in a mounted hook, it *does* contain the messages from the i18n block, but not the ones from the mixin...

I'm not totally sire this is a bug -- it's possible that it was never intended for this to work, but there should be some way for a mixin to provide some translations to components that are using the i18n block.

Component.vue
```
<template>
{{ $t('foo') }} <!-- works without mixin, fails with mixin -->
</template>
<script>
export default {
  mixins: {mixin}
}
</script>
<i18n>
en: {foo: 'hello'}
</i18n>
```

mixin.js
```
i18n: {}
```

**Comment by kazupon** [comment]
Unfortunately, due to mixin limitations, namespace collisions are inevitable. You need to use the i18n option with the script component, not the mixin.
