### ISSUE TITLE
Feature request: allow for typescript enum

### ISSUE THREAD

**Issue by RobbinBaauw** [kazupon/vue-i18n#635]
Hi, it would be amazing if you would be able to do the following:
- Define your strings to be translated in an enum
- Force all languages to translate all messages
- Use the enum instead of strings (so you can never have the problem of a non-existent string).

I tried this, and it seems to work up to one point: if you use the enum to call the `$t` method, it passes a number. If you do that, it won't do anything (it doesn't log an error/warning to console either). If you pass "0" instead of 0, it will work.

Is it possible to add support for enums (and thus actual numbers) as keys for to be translated messages? Here's an example of how it'd work:

```typescript
import Vue from 'vue';
import VueI18n from 'vue-i18n';

export enum Messages {
    TEST,
    TEST2,
}

type MessagesList = {
    [x in Messages]: string;
};

const messages: {
    en: MessagesList,
} = {
    en: {
        [Messages.TEST]: 'test',
        [Messages.TEST2]: 'test2',
    },
};

Vue.use(VueI18n);

const i18n = new VueI18n({
    locale: 'en',
    messages,
});

export default i18n;
```

And then using it a component template (i18n is a reference to the `Messages` enum): 
```html
<template>
    <div id="app">
        <p>{{$t(i18n.TEST)}}</p>
    </div>
</template>
```

It seems that being able to pass a `0` instead of `"0"` should be enough, as passing a "0" manually and changing nothing else works while passing a 0 manually doesn't. I hope this is easily possible to include.

**Comment by bruddah** [comment]
A temp workaround till feature gets implemented:

```
export enum Messages {
    TEST = 'TEST',
    TEST2 = 'TEST2',
}

```

**Comment by Shinigami92** [comment]
> A temp workaround till feature gets implemented:
> 
> ```
> export enum Messages {
>     TEST = 'TEST',
>     TEST2 = 'TEST2',
> }
> ```

You should use `const enum`!

Try it: (remove and add `const` to the enum)
https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBAYwgOwM72MgrgWzgWWFVQEMBzIuAbwCg564AVAUQGVG4BeOAchfZ4AaOg36MATF15jxQmgF8aNJGngwi8boWLkiAOjE0gA

**Comment by kazupon** [comment]
There are no plans to support it at this time.
I have commented here for more information.
https://github.com/intlify/vite-plugin-vue-i18n/issues/67#issuecomment-783499153

thanks

**Comment by art1373** [comment]
```
export namespace Module{
          export const Strings = {
          key: i18n.t("translation.key")
          }
 }
 ```
 this was my work around where I had enum instead of obj.
