### ISSUE TITLE
Is it possible to set language in individual component

### ISSUE THREAD

**Issue by leo108** [kazupon/vue-i18n#64]
Says that I have introduced two third-party vue components into my project, and both of components use vue-i18n, component A has locales `en-US`/`zh-CN` and component B has locales `en`/`cn`, in this case I can not set a proper value for `Vue.config.lang` and `Vue.config. fallbackLang`

**Comment by kazupon** [comment]
sorry, for the late response.

you can set language in individual component.
see the example:
http://jsfiddle.net/kazupon/vy1derLL/4/

**Comment by leo108** [comment]
Thanks
