### ISSUE TITLE
Custom lang setter

### ISSUE THREAD

**Issue by rayfranco** [kazupon/vue-i18n#65]
Having a custom setter could allow us to dynamically load the locales on demand. Here is an example of how we could achieve this:

``` javascript
Vue.locale(function (lang) {
  return fetch(`/locale/${lang}`,{
    method: 'get',
    // ...
  }).then(function (json) {
    return Promise.resolve(json)
  }).catch(function (error) {
    return Promise.reject()
  })
})
```

If the first argument of `Vue.locale` is omitted and a function is passed instead, it is considered as a setter and will go trough it every time we set `Vue.config.lang` that is not registered yet (or it could be called every time but we need a way to test if the locale is already registered which is not a possibility in the current API).

Open for discussion.

**Comment by kazupon** [comment]
close due to being able to replaced by the following ways
- TC32 dynamic `import` statement: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
- dynamic import with webpack or other bundler
