### ISSUE TITLE
Automate merging PRs for dependencies

### ISSUE THREAD

**Issue by exoego** [kazupon/vue-i18n#661]
There are lots of automatic PRs for dependency updates.
I suggest https://mergify.io/ or similar to automate merging such PRs so that you are not bothered by bots.
You can see [an example of automatic merging PRs made by dependabot](https://medium.com/mergify/merging-bots-pull-requests-automatically-548ed0b4a424)

**Comment by kazupon** [comment]
Thanks!

**Comment by kazupon** [comment]
done
https://github.com/kazupon/vue-i18n/blob/dev/.mergify.yml
