### ISSUE TITLE
Cannot render text to input placeholder?

### ISSUE THREAD

**Issue by forddyce** [kazupon/vue-i18n#68]
`<input type="text" name="name" class="form-control" required="" placeholder="{{ $t("expense.formNamePlaceholder") }}">`

becomes:

> ") }}">

**Comment by kazupon** [comment]
Sorry, for the late response. :bow:

Can you provide the minimum reproduction code with jsfiddle (or other), and environments (vue version, etc) please?

**Comment by zeusLeeJh** [comment]
@kazupon  I also have this question in my project. I am using vue2.0 and here is my code.
## HTML
`<input type="text" placeholder="{{ $t("hello") }}">`

## Json
` hello: 'hello world'`

and then it doesn't work just perform like this

![place](https://cloud.githubusercontent.com/assets/15540537/19846277/cc43a298-9f78-11e6-87e6-67fb7bf63b49.png)

and i also try  like this (delete the double quotes after `placeholder=` )
`<input type="text" placeholder={{ $t("hello") }}>`

and it will perform like this

![default](https://cloud.githubusercontent.com/assets/15540537/19846347/65f4c9e4-9f79-11e6-8873-e4aa40924bfd.png)

I think it must to be a bug for vue-i18n. the vue-i18n can't work with the style attribute.

**Comment by forddyce** [comment]
[SOLVED] 
@kazupon @zeusLeeJh by Vue JS 2 you should do this: https://jsfiddle.net/2av8r31w/3/
I think this (`v-bind`) needs to be in Vue I18n documentation though.

**Comment by zeusLeeJh** [comment]
@forddyce Thanks a lot, it works. I think it may be a bug about `{{ }}`.

**Comment by zeusLeeJh** [comment]
@forddyce Thanks a lot, it works. I think it may be a bug about `{{ }}`.

**Comment by spwinner2017** [comment]
@forddyce worked for me

**Comment by ikreb7** [comment]
Could you please add this to the documentation or fix this bug?

**Comment by pdfco1999** [comment]
Just use` :placeholder="$t('expense.formNamePlaceholder')"`.
Hope to work.
