### ISSUE TITLE
Extending the feature for Fallback Localization

### ISSUE THREAD

**Issue by manojchowdary27** [kazupon/vue-i18n#687]
Hello,

I have gone through the documentation and found "**fallbackLocale**" property which will be used if the key doesn't exist in desired locale during trnsalation. But It would be awesome when there is fallback for the **fallbackLocale**.

Example:

const i18n = new VueI18n({
  locale: 'ja',
  fallbackLocale: 'en',
  messages
})

In the above configuration if the key doesn't exist in **ja**, It will check for **en**
What if the doesn't exist in **en** also? It will print the path of the property which looks ugly to the end user. So I think we  need something similar to the following
**$t("property.nestedProperty.hello", { fallbackMessage: 'A clear fallback message' })**
 
 

### vue & vue-i18n version
ex: 2.1.0, 5.0

**Comment by kazupon** [comment]
close (similar issue #138 )
