### ISSUE TITLE
Numbers in locale object

### ISSUE THREAD

**Issue by Disorrder** [kazupon/vue-i18n#7]
My localization code consist of items like this
````js
error: {
    5: 'Invalid username or password'
}
````
`$t('error.5')` returns `error.5` string.

Where `5` is number of ESS code from server.

Works only with
````js
'error.5': 'Invalid username or password'
````
But this style available only for root-placed keys. Look:
````js
 'ich.ni': {
    'san': '3' // returns 'ich.ni.san' instead of '3'
}
````

**Comment by kazupon** [comment]
related #24

**Comment by kazupon** [comment]
See the detail:
https://kazupon.github.io/vue-i18n/syntax.html
