### ISSUE TITLE
SFC not testable with jest

### ISSUE THREAD

**Issue by alexanderVu** [kazupon/vue-i18n#706]
### vue & vue-i18n version
ex: 2.6.10, 8.14.0

### Reproduction Link
To reproduce use this [repo](https://github.com/alexanderVu/i18nSFC) https://github.com/alexanderVu/i18nSFC
This is a new Project created with Vue-CLI, added I18n plugin via vue ui.

### Steps to reproduce
Just run `npm i` to install and then `npm run test:unit`. 
### What is Expected?
Translated text in component when testing.
### What is actually happening?
Tests produce 3 warnings like `[vue-i18n] Value of key 'hello' is not a string!`
The test fail and show that the string is not translated. When running the app with `npm run serve` the component it directly visible and work fine. The text is translated.

When using translations files in locales folder, the tests work like expected.

**Comment by deifyed** [comment]
Also having this issue. Any workarounds available?

**Comment by alexanderVu** [comment]
Unfortunately, I have not found a workaround.

**Comment by MathiasCiarlo** [comment]
This affects us too. Hope someone finds a workaround or this gets fixed soon!

**Comment by kazupon** [comment]
You can use `mocks` or `stubs` of `@vue/test-utils`.
See the comment:
https://github.com/kazupon/vue-i18n/issues/323#issuecomment-383770042

I believe that maybe it will help you.
