### ISSUE TITLE
{{ $t('key') }} dies

### ISSUE THREAD

**Issue by BananaAcid** [kazupon/vue-i18n#708]
I am not able to use $t in any view. Looks like a Bug.

```
TypeError: Cannot read property '_t' of undefined
    at Proxy.Vue.$t (vue-i18n.esm.js:178)
    at Proxy.render (app.vue?./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options:24)
    at VueComponent.Vue._render (vue.esm.js:3545)
    at VueComponent.updateComponent (vue.esm.js:4063)
    at Watcher.get (vue.esm.js:4476)
    at new Watcher (vue.esm.js:4465)
    at mountComponent (vue.esm.js:4070)
    at VueComponent.Vue.$mount (vue.esm.js:9047)
    at VueComponent.Vue.$mount (vue.esm.js:11941)
    at init (vue.esm.js:3124)
```

```
// app.js

import Vue from 'vue';

// use
import VueI18n from './vue-config-i18n.js';
Vue.use(VueI18n);
...

new Vue({
	el: '#app',
	template: '<app/>',

	// Register App Component
	components: {
		app: App
	}
});
````

```
// vue-config-i18n.js
import VueI18n from 'vue-i18n';

import lang_de from '@/lang/de.json'; // gets imported.

export default {
	install (Vue, options) {

		Vue.use(VueI18n);

		let i18n = new VueI18n({
			locale: 'de',
			fallbackLocale: 'de',
		});

		(async ()=>{
			let lang = 'de';
			
			//let msgs = await import('@/lang/'+lang+'.json');
			let msgs = lang_de;

			if (msgs) {
				i18n.setLocaleMessage(lang, msgs.default || msgs);
				i18n.lang = lang;

				console.log('i18n loaded lang', lang);
			}
			else {
				console.warn('i18n did not load lang', lang);
			}
		})();
	}
}
```

```
// app.vue
<template>
  <div>
    {{ $t('hello') }}
  </div>
</template>
```

```
// ./lang/de.json
{
	"hello": "Hallo Welt"
}
```

**Comment by exoego** [comment]
Could you refer [Issue Reporting Guideline](https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and describe how to reproduce?
I think that `vue-config-i18n.js` is not enough to reproduce.

**Comment by BananaAcid** [comment]
I added all related code - no specials used / required. The important part is the `vue-config-i18n.js`

**Comment by CrixuAMG** [comment]
Experiencing the same problem. Console logging `this` in `vue-i18n-esm.js` (line 176) reveals a vue component, filled with the data as expected, with `$i18n` being `null`.

**Comment by exoego** [comment]
Did your codes work fine in older versions of vue-i18n/vue.js ?
If so, could you tell us what was the latest versions of vue-i18n/vue.js that run your code fine

**Comment by CrixuAMG** [comment]
This is my package.json:
```
{
  "name": "aurora",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "compile": "npm run build && npx cap sync",
    "compile:ios": "npm run compile && npx cap open ios",
    "compile:android": "npm run compile && npx cap open android"
  },
  "dependencies": {
    "@bugsnag/js": "^6.4.0",
    "@bugsnag/plugin-vue": "^6.4.0",
    "@capacitor/android": "^1.2.0",
    "@capacitor/cli": "^1.2.0",
    "@capacitor/core": "^1.2.0",
    "@capacitor/ios": "^1.2.0",
    "axios": "^0.18.1",
    "fastclick": "^1.0.6",
    "moment": "^2.24.0",
    "suncalc": "^1.8.0",
    "vue": "^2.6.10",
    "vue-click-outside": "^1.0.7",
    "vue-i18n": "^8.14.1",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@vue/cli-service": "^3.11.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.3.1",
    "vue-template-compiler": "^2.6.10"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

In my Vue config I am only using the sourcemap option for stylesheets, other than this I am not running any custom polyfills or plugins.

**Comment by BananaAcid** [comment]
... same for me

**Comment by BananaAcid** [comment]
@CrixuAMG what route did you go to get translation working / alternative?

**Comment by CrixuAMG** [comment]
@BananaAcid  what I've done for now is check if the i18n key is null and use a normal string to prevent errors.
Not recommended, only using it since the app I'm developing is not ready for the stores yet 🙃

**Comment by kazupon** [comment]
You need to install VueI18n instance to root Vue instance.
Please see the docs:
https://kazupon.github.io/vue-i18n/started.html#javascript

**Comment by BananaAcid** [comment]
@kazupon so you say, the module is *not compatible* to the Vue's default method of `Vue.use(..plugin..)` ? As I did show above (app.js) what I tried. What ever `$mount` is for, is does not match the [vue guide](https://vuejs.org/v2/guide/#Declarative-Rendering). I would not have asked, and would not be the only one having trouble, if the [vue-i18n docs](https://kazupon.github.io/vue-i18n/started.html#javascript) would be crystal clear on this.

**Comment by beau-gosse** [comment]
FWIW the module approach doesn't seem to work. The setup that worked for me (with Vue CLI) is instantiating `VueI18n` inside `main.js`. 

```javascript
// main.js
import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)
const messages = {
  en: {
    message: {
      hello: 'hello world'
    }
  }
}

const i18n = new VueI18n({
  locale: 'en', // set locale  
  messages
})

new Vue({
  i18n,
  render: h => h(App)
}).$mount('#app')
```
