### ISSUE TITLE
Wrong behaviour of custom formatting

### ISSUE THREAD

**Issue by davidoff0895** [kazupon/vue-i18n#711]
Hi. I have a problem with custom formatting (tag <i18n/>). Formatting has wrong behaviour In case if i write a second element into <i18n/>. Problem reproduce in 8.14.0 version. In 8.12.0 - all is stable.
### vue & vue-i18n version
ex: 2.6.10, 8.14.0

### Reproduction Link
https://codepen.io/davidoff0895/pen/NWKXMqE

### What is Expected?
'hello my dear friend'

### What is actually happening?
'hello my'

**Comment by Demivan** [comment]
I'm having the same issue. Created pull request with fix: #712

**Comment by exoego** [comment]
Regression in v8.14.0 due to #685

**Comment by exoego** [comment]
Fixed in https://github.com/kazupon/vue-i18n/pull/712#merged-event
