### ISSUE TITLE
vue2.0 got function Vue.t undefined.

### ISSUE THREAD

**Issue by codeskyblue** [kazupon/vue-i18n#72]
Here is my code

```js
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import App from './App.vue'

Vue.use(VueI18n)

console.log(Vue.t)

Vue.filter('translate', function(value) {
  return Vue.t(value);
  // return value;
})
```

But the console.log shows Vue.t is undefined.

* vue-i18n 4.6.0
* vue 2.0.3

**Comment by codeskyblue** [comment]
my fault, import twice.

**Comment by eric-burel** [comment]
Hi @codeskyblue , what do you mean import twice ? How did you solve this ?

**Comment by Adizbek** [comment]
For who are looking for solution:

You can use VueI18n.t('key')
