### ISSUE TITLE
Filter cannot be used here

### ISSUE THREAD

**Issue by zihao-AL** [kazupon/vue-i18n#720]
<span>
  {{ $t('carInfo.sumInsured', { len: 100 | filterMoney } ) }}
</span>

<span>
  {{ $t('carInfo.sumInsured', [ 100 | filterMoney  ] ) }}
</span>

**Comment by BananaAcid** [comment]
Vue-Filters do not work in Javascript expressions - or Objects, you need to do them outside, as specified in the Vue documentation. See [docs](https://vuejs.org/v2/guide/filters.html)

**Comment by kazupon** [comment]
Vue.js 2.x cannot suport `this` ...
https://github.com/vuejs/vue/issues/5998
