### ISSUE TITLE
Raw HTML - invalid expression for {{{ }}} in Vue 2.0

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#73]
As per the documentation and #18, I tried:
```js
message: {
      hello: 'hello <br> world'
    }
```
```html
<p>{{{ $t('message.hello') }}}</p>
```
But this gives me : ``template syntax error - invalid expression: {{{ $t('message.hello') }}}``
Vue 2.0 is more picky on what is between the '{{{...}}}' then 1.0... or am I overlooking something ? Would `` v-html="rawHtml"`` help?
What is the alternative?

**Comment by tvld** [comment]
Ok.. .got it ... this works : 
```html
<div v-html="$t('home.header.title')"></div>
```

**Comment by myst729** [comment]
http://vuejs.org/guide/migration.html#HTML-Interpolation-deprecated
