### ISSUE TITLE
Combination of parameters and linked messages

### ISSUE THREAD

**Issue by GabrielMancik** [kazupon/vue-i18n#733]
I want to have message which i can parametrize with another linked message. Something like:
```
{
   message "@:entityTypes.{entityType} is not valid"
   entityTypes: {
      A: "entity a in this language"
      B: "entity b in this language"
   }
}
```

I know that I can achieve this by duplicating message for each entityType. But can I somehow achieve this without duplication? If it cant be done we can consider this as feature request.

**Comment by kazupon** [comment]
Sorry 😞, I  could not understand your feature request.
Could you tell us more explanation, please?

**Comment by GabrielMancik** [comment]
I have three types of entities in system. EntityA, EntityB a EntityC. Each has its own translation key:
```
"entities":
{
    "entityA": "Entity of type A",
    "entityB": "Entity of type B",
    "entityC": "Entity of type C"
}
```
For each entity type I want to be able to display message saying that it is not valid. I can do something like this:

```
"entities":
{
    "entityA": "Entity of type A",
    "entityB": "Entity of type B",
    "entityC": "Entity of type C"
},
"validationMessages":
{
    "entityANotValid": "@:entities.entityA is not valid",
    "entityBNotValid": "@:entities.entityB is not valid",
    "entityCNotValid": "@:entities.entityC is not valid"
}
```
Can I do this without having three entityXNotValid validation messages? They all differ only in one part. I have tried to supply this part by parametrization (not sure if official term. I mean passing parameter by context):

```
"entities":
{
    "entityA": "Entity of type A",
    "entityB": "Entity of type B",
    "entityC": "Entity of type C"
},
"validationMessages":
{
    "entityNotValid": "@:entities.{alwaysDifferentEntity} is not valid"
}
```

But this does not work.

**Comment by epaezrubio** [comment]
Is there currently a workaround for this?

**Comment by Tcheikovski** [comment]
I really need a workaround for this too, someone has any idea?

**Comment by GabrielMancik** [comment]
I have ended up duplicating each validation message. After some thoughts I have decided composition is not the way to go. Different languages could have totaly different sentence compositions. In some subject may naturally appear in start of the sentence while in others elsewhere. This would force me to formulate sentences (in other languages) in unnatural way just to satisfy formula. Other problem is conjugations and declensions (thanks vocabulary). While in english one form (or two taking plural in mind) of the word could be enough in other languages I may need multiple forms. 
In the end I think its better to duplicate and have absolute freedom with sentences and phrases.

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
please try it!

**Comment by v1r0x** [comment]
Hey there,

I know this is an old issue and it is already closed and fixed. But I couldn't figure out how to reference/link to another message using a variable.

**Comment by danielwillms** [comment]
I also just stumbled upon this, @v1r0x !

following example setup:

```javascript
const messages = {
  "Login": {
    "error": "Failed to login! (@:Error.{err})",
    "errorGrouping": "Failed to login! (@:(Error.{err}))"
  },
  "Error": {
    "wrong_password": "Wrong user or password!"
  }
}
```

now I tried it like this : 
```$t("Login.error", {err: "wrong_password"})``` 
which results in => ```Failed to login! (wrong_password)```
And also tried the grouping way: 
```$t("Login.errorGrouping", {err: "wrong_password"})``` 
which results in => ```Failed to login! (@:(Error.{err}))```

So what is the appropriate way to access linked messages via params, @kazupon  ?
