### ISSUE TITLE
v8.10.0 with Breaking changes

### ISSUE THREAD

**Issue by Roriz** [kazupon/vue-i18n#736]
### vue-i18n version
v8.10.0

### Description
On version v8.10.0 we merge the PR: https://github.com/kazupon/vue-i18n/pull/533, with this new feature, a project with an old version can be broke without warning or error. In my opinion, this feature is very useful but is a breaking change.
I work on a project with very large keys, when these keys surpass 80 characters we using a string template and brake line to fit on linter rule.

### Reproduction Link
https://jsfiddle.net/e4ms1gy7/

### Expected Link
https://jsfiddle.net/e4ms1gy7/1/

### Steps to reproduce
Use a break line or space between keys

### What is Expected?
Normally translate

### What is actually happening?
Translate is missing

### Sugestion
We can change the release message to:
```
:star: New Features
number: i18n-n functional component (#541) by @bponomarenko (b33579d), closes #541

:boom: Breaking changes
path: Keypath should parse if sub path contains spaces. (#533) by @exoego (640daaf), closes #533

:zap: Improvements
number: support data fall through in i18n-n (#545) (71cadbf), closes #545
memo docs
vuepress: translate documents for chinese (#536) by @xuhongbo (ccf29f8), closes #536 #531 #1 #533 #540 #541 #1 #2
```

Or we can rollback this feature and merge again on next major version

**Comment by lucassonsinlima** [comment]
Any updates for this? I'm facing the same issue as @Roriz

**Comment by exoego** [comment]
Sorry about the accidental breaking change.
It is unexpected for me that someone is using string template to avoid linter error.

How about migrating your code using concatenation instead, something like

```vue
{{ $t("very."
    + "long.key") }}
```
