### ISSUE TITLE
Multiple fallback locales 

### ISSUE THREAD

**Issue by sergeystoma** [kazupon/vue-i18n#738]
Is it possible to configure multiple fallback locales? For example, a use case - French Canadian localization, which could be covered by:

1) en locale 
2) generic fr locale
3) and specific fr-CA locale with only some overrides

So ideally it would be nice if there was a way to configure a chain of fallbacks: fr-CA -> fr -> en

**Comment by KBOE2** [comment]
This is already requested in #138  :)

**Comment by sergeystoma** [comment]
Oh duh. Didn't find it at first, but then it is 2AM...
