### ISSUE TITLE
Config parameter for default html

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#74]
As per issue #73 

Actually, now I think of it.... ALL our translations are html. Would it be possible to have like a config parameter, so that vue-18n forces Vue 2.0  that it should treat all strings as ``v-html``, even if passed normally, so between `` {{...}}`` ?

**Comment by kazupon** [comment]
I think that  our translations are not html. That design is bad.
You should be not design that locales used as html translation.

**Comment by tvld** [comment]
Thinking  about it... agree... Sorry to bother you...)

**Comment by kazupon** [comment]
No worries :)
