### ISSUE TITLE
Weird behavior in messages discovery

### ISSUE THREAD

**Issue by romulof** [kazupon/vue-i18n#740]
### vue & vue-i18n version
`vue` 2.6.10
`vue-i18n` 8.15.0

### Reproduction Link
https://codesandbox.io/s/vue-18n-weird-s0s06

### Steps to reproduce
- Don't have messages (`i18n` key in component definition) in `App` component (root component)
- Set up messages in `AppContainer`
- Use translation message in `AppContent` (leaf component)

### What is Expected?
Leaf component to use translation message from the closes parent who has it defined

### What is actually happening?
I know docs are correct, but `vue-i18n` implements instance discovery in a weird way, checking first for component's own definition of `i18n`, then checks the root element and only afterwards it checks the parent.

Here's the commit where it was introduced: https://github.com/kazupon/vue-i18n/commit/13585a4e29eda6be956796f55a6a6af3345c0a30

**Comment by kazupon** [comment]
Thank you for your feedback!

That behavior is correct.
Vue I18n will be discovered to bubble up to parents.

**Comment by romulof** [comment]
That's the point: It's not bubbling.

| Attempt |         Bubbling         |          Current implementation          |
|--------:|:------------------------:|:-------------------------:|
|       1 |     current component    |     current component     |
|       2 |          parent          |            root           |
|       3 |      parent > parent     |           parent          |
|       4 | parent > parent > parent |      parent > parent      |
|     ... |            ...           |            ...            |
|    last |           root           | root's child |
