### ISSUE TITLE
Vuex v3.1.2 warns when informing an existing module

### ISSUE THREAD

**Issue by davidpelayo** [kazupon/vue-i18n#742]
Due to [this](https://github.com/vuejs/vuex/pull/1554) at [Vuex v3.1.2](https://github.com/vuejs/vuex/releases/tag/v3.1.2), we now get a warning when initialising the usage of the `vuex-i18n` plugin informing a third parameter, _config_, containing a specific _moduleName_.

Within my SPA bootstrapping process, I'm declaring a module named _I18nModule_ with my own state keys and everything, which I then later reuse to inject the managed-by-vue-i18n-translations, to avoid having two different modules for the same purpose.

I'm wondering why instead of reusing the existing one a new one is being created here, leading to the warning.

Any idea on this regard? Help is appreciated. Thanks.

**Comment by kazupon** [comment]
Thank fou you for the feedback!

vue-i18n does not have a module and namespace.
about vuex-i18n, you can access the here.
https://github.com/dkfbasel/vuex-i18n
