### ISSUE TITLE
silentTranslationWarn for specific calls only

### ISSUE THREAD

**Issue by unpollito** [kazupon/vue-i18n#743]
Hello,

I've come across a situation where I'd need to translate strings coming from a server, but I don't know which ones can be translated and which ones are unique. For instance, in an application for a house alarm system, there may be some common names that can be translated (e.g., "Kitchen"), but also some which are specific to a certain house ("David's room") and thus not translated.

Right now I'm getting console warnings when I try to translate these. I am aware that I can turn this off by setting `silentTranslationWarn` to `true` when initializing VueI18N. However, this would just turn off warnings for the entire application, which would be undesirable as they're a good sign that something may not be working as expected.

Ideally I should be able to disable warnings only for specific calls, e.g.:

`this.$t(someString, {}, { silentTranslationWarn: false })`

Is there a way in which I can achieve this behavior? :)

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
You can specify to `TranslationOptions`.
https://vue-i18n.intlify.dev/api/composition.html#t-key-plural-options
please try it!
