### ISSUE TITLE
Issue with array and objects in version 8.15.3

### ISSUE THREAD

**Issue by lk77** [kazupon/vue-i18n#759]
### vue & vue-i18n version
2.6.11 & 8.15.2

### Reproduction Link

Hello

i've tried to reproduce it, but in jsfiddle it's still working

https://jsfiddle.net/lk77/ph85ms2e/

i will try again to reproduce it.

i've added `<8.15.1` to the version constraint of vue-i18n and it resolved my issue.

### Steps to reproduce

pass an array in messages :
![Screenshot from 2019-12-31 09-27-59](https://user-images.githubusercontent.com/9606882/71616867-b6425a00-2bb8-11ea-82c2-77d4d7c9e09b.png)

you can see that the array has become an object

### What is Expected?

if we pass an array to vue-i18n, it's stays an array and don't become an object

### What is actually happening?

the array is becoming an object :
```
['test']
```
becomes :
```
{
    '0': 'test'
}
```

thanks.

**Comment by kazupon** [comment]
Thank you for your feedback!

Unfortunately, I could not reproduce the issue... 😞 
Could you provide the minimum reproduction codes, please?

**Comment by lk77** [comment]
Hello,

i will try to find a way to reproduce it/
the issue has been introduced in 8.5.2 it seems?

**Comment by KBOE2** [comment]
I do have the same issue in Version `8.17.0`!
The error occurs for me whenever I use `mergeLocaleMessage`.
For example: I got a file `./i18n/de_DE.json`. It is loaded in the beginning of the file via
```js
$i18n.mergeLocaleMessage('de_DE', {
    modules: {
        buildingHover: require('./i18n/de_DE'),
    },
});
```
it works as it should except that it turns any array into objects.
In this case, I got an array in my `./i18n/de_DE.json`:
```json
"schoolBuildings": [1, 3, 8, 10]
```
However, when inspecting the translation messages in the Browser, I can see that the former array is now an Object:
```json
{
  "0": 1,
  "1": 3,
  "2": 8,
  "3": 10
}
```

I hope, that helps you reproducing the issue and fixing the bug :)

Greetings
Jan

**Comment by KBOE2** [comment]
Workaround:
Instead of using the translation object directly, use `Object.values(translation)` for Arrays.
Example:
```js
// translations.de_DE.json
"schoolBuildings": [1, 3, 8, 10]
```
Usage:
```js
// fails because this.$t('schoolBuildings') becomes an Object instead of Array:
this.$t('schoolBuildings').forEach(/*…*/);

// works as if this.$t('schoolBuildings') would return an Array:
Object.values(this.$t('schoolBuildings')).forEach(/*…*/); // Will also work when the Bug is fixed, and this.$t('schoolBuildings') returns the correct Array!
```

**Comment by sgurin** [comment]
Hi, Is any news about the issue. Still relevant in [v8.28.2]

**Comment by lk77** [comment]
This issue was closed a long time ago, i suggest you to make a new one

**Comment by sgurin** [comment]
Sorry, some not clear behavior. If helps, you have to use mergeLocale when you have key in initial object. Otherwise object would be in the results

![image](https://user-images.githubusercontent.com/25930200/224737076-4570e858-f70a-44ff-abc8-77c8c62e5864.png)
![image](https://user-images.githubusercontent.com/25930200/224737221-6fff5159-6f48-4d48-be6c-886f4b3ec4a9.png)
