### ISSUE TITLE
Exclude the last dot in the link key instead of escaping the key

### ISSUE THREAD

**Issue by FramaJosephK** [kazupon/vue-i18n#761]
I know [we can escape the key of the link in this way `@:(foo.bar).`](http://kazupon.github.io/vue-i18n/guide/messages.html#grouping-by-brackets), but why didn't you exclude the dot as the last character since this is the main issue?

Maybe with this regex for example (to replace [this line](https://github.com/kazupon/vue-i18n/blob/dev/src/index.js#L22)) 
``` javascript
const linkKeyMatcher = /(?:@(?:\.[a-z]+)?:(?:([\w\-_|.]+[\w\-_|]+)))/g
```

I think this would be a better approach because if translators have to translate a sentence where the link has to be placed at the end of the sentence (and if this is not the case in the original language), they cannot guess that the key has to be escaped in this way. 

This would avoid the need for re-readings and explanations on this point of vigilance.

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
please try it!
