### ISSUE TITLE
Regarding use non-english for message key and linked locale messages.

### ISSUE THREAD

**Issue by flyskyne** [kazupon/vue-i18n#762]
I want to use non-english for message key.
For example:

```json
{
  "학생": "학생"
}
```

If developer speaks non-english and use english for message key, he waste time to making english key name.
Because of this, I like use my mother language for message key.

Vue-i18n is works well for this example.

```javascript
this.$t('학생') // returns "학생"
```

But "linked locale messages" is not works.
For example:
(We generally use mother language for glossary)

```json
{
  "glossary": {
    "학생": "학생",
  },
  "manageStudent": {
    "confirmDeleteStudent": "@:(glossary.학생)을 삭제하시겠습니까?"
  }

}
```

```javascript
this.$t('manageStudent.confirmDeleteStudent') // returns "@:(glossary.학생)을 삭제하시겠습니까?", expected is "학생을 삭제하시겠습니까?"
```

If I give up use mother language for message key, there is another problem.
For example:

```json
{
  "glossary": {
    "student": "학생",
  },
  "manageStudent": {
    "confirmDeleteStudent": "@:(glossary.student)을 삭제하시겠습니까?"
  }
  
}
```

Translator should follow message key and find its origin word.
If message key same as source language(`@:(glossary.학생)을 삭제하시겠습니까?`), translator can work easily.

`linkKeymatcher` suppose that message key is alphanumeric, - and _.

```javascript
var linkKeyMatcher = /(?:@(?:\.[a-z]+)?:(?:[\w\-_|.]+|\([\w\-_|.]+\)))/g;
```

How about change this?

**Comment by exoego** [comment]
I think this proposal is worth to be implemented 👍 
Using mother language in message key is very likely !!

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
please try it!
