### ISSUE TITLE
Docs - Wrong npm command to install vue-i18n

### ISSUE THREAD

**Issue by Mikilll94** [kazupon/vue-i18n#773]
https://kazupon.github.io/vue-i18n/installation.html#direct-download-cdn

![image](https://user-images.githubusercontent.com/17653648/73309773-3e049e00-4223-11ea-9a9f-97f823657305.png)

Instead it should be:
```npm install vue-i18n --save```

**Comment by exoego** [comment]
Thanks of reporting.
I wonder why you think --save is needed, do you see some error?
What version of npm are you using?

IIUC, the flag became no longer required somewhere around npm 5.0, and dropped from document in https://docs.npmjs.com/cli/install

**Comment by Mikilll94** [comment]
@exoego 
Thanks. I didn't know that --save is optional from npm 5.0.0

This issue can be closed.

**Comment by exoego** [comment]
OK!
Closing as resolved.
