### ISSUE TITLE
Modifiers are applied at wrong stage

### ISSUE THREAD

**Issue by lllopo** [kazupon/vue-i18n#778]
I think the modifiers are applied at a wrong stage of processing. 
I have a custom modifier, performing capitalization of the first letter of the string. Now, this works fine with regular strings, but does not work with pluralized strings. This is because the modifier is applied before the pluralization processing. So, in my case :

```
"Appointment": {
	"appointment": "no appointments | appointment | appointments",
	"Appointment": "@.ucfirst:Appointment.appointment"
}
```

Calling **$tc('Appointment.Appointment', 1)** results "**appointment**" while **$tc('Appointment.Appointment', 0)** results "**No appointments**", since the capitalization is performed on the whole "no appointments | appointment | appointments" instead of the pluralized/parsed "appointment".

In my opinion, the modifiers should be applied at the end of the processing queue not at the start of it … or there should be start and end result modifiers separately available.

**Comment by kazupon** [comment]
we supported in Vue I18n v9.
please try it!
