### ISSUE TITLE
Scoped style with deep selector not working for scss

### ISSUE THREAD

**Issue by fractalf** [kazupon/vue-i18n#780]
Ref https://github.com/kazupon/vue-i18n/issues/492 and https://github.com/kazupon/vue-i18n/issues/362  

[sandbox](https://codesandbox.io/s/0mwy22968v):
```vue
<template>
  <div class="scoped">
    <h2>Scoped styles:</h2>
    <p v-html="$t('message.hello')"></p>
  </div>
</template>
<script>
export default {
  name: "ScopedStyles"
};
</script>
<style scoped>
.scoped >>> span {
  color: green;
}
</style>
```

This **does not work** if you use scss (`lang="scss"` in the style tag)

**UPDATE**

Further research led me to this https://stackoverflow.com/a/55368933 answer which basically states that `>>>` doesn't work with scss. User `::v-deep` or `/deep/` instead.

Please update the docs with this info? :)

https://kazupon.github.io/vue-i18n/guide/sfc.html#scoped-style

**Comment by kazupon** [comment]
This is not an issue of vue-i18n.
This is limitation of vue.js
