### ISSUE TITLE
path string is not formatted

### ISSUE THREAD

**Issue by ztj1993** [kazupon/vue-i18n#784]
I use the original language as the path, and the default is the original language, so that my page can use the default language even if there is no language pack.

Now, I find that formatting has not been processed. How can I do it?

Example: [https://jsfiddle.net/8xrzpje4/](https://jsfiddle.net/8xrzpje4/)

I hope that div.item3 can be formatted and displayed as div.item2.

**Comment by kleinfreund** [comment]
Have you tried setting `formatFallbackMessages: true` as documented on https://kazupon.github.io/vue-i18n/guide/fallback.html#fallback-interpolation?

This solves your problem.

**Comment by ztj1993** [comment]
@kleinfreund thanks! This is exactly what I want. You have found that the Chinese version of the document is missing.

------

The above content comes from software translation.

**Comment by exoego** [comment]
Contribution to Chinise version document is highly appreciated 🙏

**Comment by kazupon** [comment]
Thanks!

**Comment by kazupon** [comment]
I already lived in real world :)
