### ISSUE TITLE
'setLocaleMessage' / 'mergeLocaleMessage' doesn't work if 'warnHtmlInMessage' is set to 'error'

### ISSUE THREAD

**Issue by vovkss** [kazupon/vue-i18n#789]
### vue & vue-i18n version
vue version: 2.6.11
vue-i18n version: 8.15.4

### Reproduction Link

https://jsfiddle.net/vovkss/4p5y86rn/

### Steps to reproduce

Set `warnHtmlInMessage: true`. 

Call `setLocaleMessage` or `mergeLocaleMessage` to change messages for any locale. 
It doesn't matter whether messages were already set for the locale or not. 

The new messages must NOT contain HTML. 

### What is Expected?

Messages are changed for the target locale. 

### What is actually happening?

`setLocaleMessage` or `mergeLocaleMessage` have no effect.

**Comment by vovkss** [comment]
The reason is the following line of code for `setLocaleMessage`: 

https://github.com/kazupon/vue-i18n/blob/v8.x/src/index.js#L606

and the following line for `mergeLocaleMessage`: 

https://github.com/kazupon/vue-i18n/blob/v8.x/src/index.js#L614

**Comment by aym3nb** [comment]
Hey @vovkss  
Can I grab this?
Also, since we expect the messages to be changed anyway, what's the point of having an `error` flag for `warnHtmlInMessage`?

**Comment by vovkss** [comment]
> 
> 
> Hey @vovkss
> Can I grab this?
> Also, since we expect the messages to be changed anyway, what's the point of having an `error` flag for `warnHtmlInMessage`?

Sure, I guess you can :) 

According to the [docs](https://kazupon.github.io/vue-i18n/api/#methods), 'warnHtmlInMessage' applies to dynamically loaded messages: 

> setLocaleMessage( locale, message )
> ...
> If you set warn or error in the `warnHtmlInMessage` property, when this method is executed, it will check if HTML formatting is used for locale message.
