### ISSUE TITLE
vue-i18n _render always tries to 'join' when interpolateMode is 'string'

### ISSUE THREAD

**Issue by sihyeonn** [kazupon/vue-i18n#793]
https://github.com/kazupon/vue-i18n/blob/7e015c4215889a521e565dc8add3acb23528fb0a/dist/vue-i18n.esm.js#L1425

I agree the reason to join the result to make 'string'. But `ret` could be already string because of customized interpolation. I think it should be changed with considering the case when `ret` is already string. I'd like to work on this.

**Comment by exoego** [comment]
Thanks for suggestion.
It sounds reasonable to be implemented.
`ret.join('')` will fail if `ret` is a `String` in case of customized interpolation, since `String` do not have `join` method.

**Comment by kazupon** [comment]
close due to merged
