### ISSUE TITLE
[Question] Is it possible to temporarily show the keys instead of the translations?

### ISSUE THREAD

**Issue by ThaDaVos** [kazupon/vue-i18n#796]
No bug, just a question/feature request.

Is it possible to show the translation keys instead of the translations itself? Even if a translation exists?
This would be great for when you need to find where a translation is coming from if you're not a programmer or if you aren't well known with the code base and have to translate a specific string.

**Comment by Excalibaard** [comment]
Not really an answer to your question, but if you use VSCode, you could take a look at [I18n-Ally](https://github.com/antfu/i18n-ally). That should have everything you need without having to disable/override the actual translation of the keys in the codebase.

**Comment by exoego** [comment]
> Is it possible to show the translation keys instead of the translations itself? Even if a translation exists?

Short answer is NO. it is not possible OOTB.

I think it is required to modify temporarliy the code to instantiate `VueI18n`, like below:

```javascript
// suppose you have `en` locale
const i18n = new VueI18n({
    locale: 'no-such-locale',
    fallbackLocale: 'no-such-locale'
})
```

`VueI18n` in this settings will try to use `no-such-locale` locale, but it will fail (since not exist), then use show message key as fallbck.

**Comment by ThaDaVos** [comment]
> 
> 
> Not really an answer to your question, but if you use VSCode, you could take a look at [I18n-Ally](https://github.com/antfu/i18n-ally). That should have everything you need for managing translations without having to disable/override the actual translation of the keys in the codebase.

I'm already using i18n-Ally - love it this far - but what I'm talking about is in the browser



> 
> 
> > Is it possible to show the translation keys instead of the translations itself? Even if a translation exists?
> 
> Short answer is NO. it is not possible OOTB.
> 
> I think it is required to modify the code to instantiate `VueI18n` temporarliy, like below:
> 
> ```js
> const i18n = new VueI18n({
>     locale: 'no-such-locale',
>     fallbackLocale: 'no-such-locale'
> })
> ```
> 
> `VueI18n` in this settings will try to use `no-such-locale` locale, but it will fail (since not exist), then show message key as fallbck.

Thanks for the heads up -> could the locale and fallbackLocale be changed after instatiation or only during?

**Comment by exoego** [comment]
> could the locale and fallbackLocale be changed after instatiation or only during?

Good question !
I think it can be changed, as long as `i18n` is exposed.

**Comment by exoego** [comment]
@ThaDaVos 

It seems that my answers helps you to temporarily show the keys.
So let me close the issue as answered.
Feel free to reopen if you need more help, or you think this feature should be added to vue-i18n.
