### ISSUE TITLE
Cannot assign type 'translateresult' to type 'string'

### ISSUE THREAD

**Issue by eliot-ye** [kazupon/vue-i18n#810]
### vue & vue-i18n version
"vue": "^2.6.10",
"vue-i18n": "^8.15.3",

### What is Expected?

i18n.t() can return string type

### What is actually happening?

When I enable TS checking, there are often "Cannot assign type 'translateresult' to type 'string' errors"

**Comment by kleinfreund** [comment]
Please use the search before opening new issues: https://github.com/kazupon/vue-i18n/issues?q=is%3Aissue+is%3Aopen+string+typescript

This is a duplicate of https://github.com/kazupon/vue-i18n/issues/410.

**Comment by exoego** [comment]
Closing as duplicate of #410 
PRs are welcome.
