### ISSUE TITLE
Why is vue-i18n in a single label element can not be used normally?

### ISSUE THREAD

**Issue by linfulongnet** [kazupon/vue-i18n#83]
Why is vue-i18n in a single label element can not be used normally?
This is a small example of the web site：
https://jsfiddle.net/linfulong/4k7aLb3p/

**Comment by drozdzynski** [comment]
You must bind value of element
I change `<input type="button" value="{{ $t('message.hello') }}" >` to `<input type="button" :value="$t('message.hello')" >`

example:
https://jsfiddle.net/no0n7s3u/1/

**Comment by kazupon** [comment]
As say @drozdzynski , You can use the `v-bind` about it.
