### ISSUE TITLE
Getting locale of message inside custom formatter

### ISSUE THREAD

**Issue by sgtfrankieboy** [kazupon/vue-i18n#835]
I've been looking but can't find a proper answer. Certain libraries like `intl-messageformatter` and `messageformatter` require you to pass a locale in their message build/constructor.

In the example provided this is passed in the constructor but from what I can tell that won't work if the message comes from the fallbackLocale or if the locale changes at runtime.

So my question is, is there a way to get the locale of the `message` in the interpolate method?
```ts
interface Formatter {
  interpolate(message: string, values: Values | undefined, path: string, locale: string): (any[] | null);
}
```

**Comment by exoego** [comment]
> won't work if the message comes from the fallbackLocale or if the locale changes at runtime.

Are you sure that fallback locale have translations for the message key ?
Could you create a repro ?

**Comment by sgtfrankieboy** [comment]
I've written the following Custom Message Formatter:
```
import IntlMessageFormat from 'intl-messageformat';

export default class IntlMessageFormatter {

  constructor(options = {}) {
    this._i18n = options.i18n
  }

  interpolate (message, values) {
    const msg = new IntlMessageFormat(message, this._i18n.locale)
    return msg.format(values)
  }
}
```

Which I then assign like this:
```
const i18n = new VueI18n({
  locale: locale,
  fallbackLocale: 'en',
  silentTranslationWarn: false,
  messages: {
    // The `en` import is a requirement.
    en: await import(/* webpackChunkName: "locale-[request]" */ `@/i18n/en.json`)
  }
})
i18n.formatter = new IntlMessageFormatter({ i18n })
```

When I wrote my Issue I had mostly copied [this example](https://github.com/kazupon/vue-i18n/tree/dev/examples/formatting/custom/src) but have since changed it to pass the i18n instance so I can get the current locale if it changes on runtime.

However an issue is that if the `locale` is `nl-NL` and its missing a key it will fallback to `en`. But when that string is passed through interpolate, the `i18n.locale` is set to Dutch but the locale of the message is English, causing possible translation issues in IntlMessageFormat.

**Comment by exoego** [comment]
```ts
interpolate(message: string, values: Values | undefined, path: string, locale: string): (any[] | null);
```

Ah, I think I understood your question.
You want know what locale should be used in interpolate method in custom formatter ?
You expect `locale` is `nl-NL` if translation exist, but `en` if no translation ?

**Comment by exoego** [comment]
I think invoking `this._i18n.$te(key)` tells the translation exists for the key and the current locale.

https://kazupon.github.io/vue-i18n/api/#te

**Comment by sgtfrankieboy** [comment]
Yes that's correct. Thanks for the method, I think it will suit my needs.
