### ISSUE TITLE
Possible to update json files after app is built?

### ISSUE THREAD

**Issue by Lehren** [kazupon/vue-i18n#838]
Is it possible to update some json localization files and have the website automatically update itself on a refresh? As in, the website is built and deployed on a server and I purely change some keys or upload a whole new lang.json file and on a refresh the changes are processed? 
Or would I need to run a new build?
The hot reload feature only works when webpack is running I suppose, which is not really what I'm looking for.

**Comment by KBOE2** [comment]
Maybe, you can use the [lazy loading translations](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html) in combination with an ajax call. Each time the user then loads the page, it gets the latest translations.

Have a look at the last part in function `loadLanguageAsync` in the example on the link above:
```js
// If the language hasn't been loaded yet
return import(/* webpackChunkName: "lang-[request]" */ `@/i18n/messages/${lang}.js`).then(
    messages => {
        i18n.setLocaleMessage(lang, messages.default)
        loadedLanguages.push(lang)
        return setI18nLanguage(lang)
    }
)
```
I'm pretty sure, you can replace the import part with an Ajax call, for example with axios.

**Comment by Lehren** [comment]
What if the translation files are not coming from an ajax call, but from local files? I see webpack builds those files into the bundle, is it still possible to replace those?

**Comment by KBOE2** [comment]
Is the translations file somewhere on the server?
If yes, you can be able to create a call to get the file.

As Webpack writes the content of the json file statically in the build, you have to either rebuild or dynamically import the translations.

**Comment by exoego** [comment]
You may find it usefule the document regarding lazy loading translation files with webpack.
https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

**Comment by exoego** [comment]
As @KBOE2 suggested, I also think rebuild is required if the translation files are bundled with webpack or similar build tools.
Closinng since it seems answered and a bit off-topic.
But feel free to reopen if you think there is a room for improvement in vue-i18n.
