### ISSUE TITLE
Latest release breaks my app on Internet Explorer because of use of endsWidth()

### ISSUE THREAD

**Issue by mihaicosma** [kazupon/vue-i18n#839]
Version vue-i18n 

My vue app only shows a grey screen on Internet Explorer with console output of the following message: {description: "Object does...", message: "Object does...", name: "TypeError", number: -2146827850, stack: "TypeError: ...", Symbol()_b.g97vvmj5gf9: undefined, Symbol(Lang fallback)_e.g97vvmj5gf9: undefined}

description"Object doesn't support property or method 'endsWith'"

I tracked down the difference to using vue-i18n v8.17.0  instead of the previously using v8.15.3.

Please consider defining String.endswith() locally as it is not implemented on Internet Explorer. Polyfill works for my code, but not for modules.

**Comment by linlinyang** [comment]
update and then throw 'endsWith' not babel translate
