### ISSUE TITLE
[Vue warn]: Error in render: "ReferenceError: “Map”未定义"

### ISSUE THREAD

**Issue by linlinyang** [kazupon/vue-i18n#842]
"vue-i18n": "^8.17.1"

In IE ,project run then throw :
[Vue warn]: Error in render: "ReferenceError: “Map”未定义"
just use {{ $t('title') }}

delete and run well.

old version(8.15.3) run well

**Comment by exoego** [comment]
Please follow the issue reporting guidlines and provide how to reproduce the issue.
https://github.com/kazupon/vue-i18n/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

**Comment by kazupon** [comment]
We must replace to `Object.create(null)`.
https://github.com/kazupon/vue-i18n/blob/528d1ad839fe1874f350d6fd2b512a5c721b4002/src/index.js#L240

**Comment by exoego** [comment]
I am working on it

**Comment by exoego** [comment]
Hmm, this is weird 🤔 
IE11 support `Map` and our code base uses only `map.get` and `map.set` which is usable in IE11.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility

@linlinyang Could you tell us what exact IE version are you using when seeing this error ?

**Comment by exoego** [comment]
@kazupon Is it OK to suppor only IE11 ? (No support IE10/9/8...)

**Comment by kazupon** [comment]
@exoego 
Vue 2 is supported on IE10/9.
We need to support these versions.
