### ISSUE TITLE
Dynamic locale and vue-resource combo doesn't update translations after loading

### ISSUE THREAD

**Issue by Lacroute** [kazupon/vue-i18n#85]
### vue & vue-i18n version
```
"vue": "^2.0.1",
"vue-i18n": "^4.7.1",
"vue-resource": "^1.0.3"
```
### Reproduction Link
http://jsfiddle.net/t4kdoqj7/3/

### Steps to reproduce
Try to comment line 19 and 20

### What is Expected?
I want my translation updated when the vue-resource request is resolved.

### What is actually happening?
I got an error message `Cannot translate the value of keypath "foo". Use the value of keypath as default` because there is no translation and when the file is ready, nothing happen.

Should I load the translations files separatly ?
Is there a step in the asynchronous locale setting that am I missing ?

**Comment by Lacroute** [comment]
I found a dumb solution : just set `Vue.config.lang = ''` before loading anything. It forces the locale update.
Update (line 9) > http://jsfiddle.net/t4kdoqj7/4/

**Comment by ScreamZ** [comment]
Just happened to me, very strange, sometimes it works sometime not. The hack did the work

**Comment by kazupon** [comment]
Close (inactivity)
