### ISSUE TITLE
Outdated dist files

### ISSUE THREAD

**Issue by rchl** [kazupon/vue-i18n#850]
The dist files are not up to date with the source. For example this line is different:
https://github.com/kazupon/vue-i18n/blob/ecb78660035e5ac43f1f74c951648ca42589a7c8/dist/vue-i18n.common.js#L1109

I suppose this is not really a problem since on releasing those are built fresh anyway but then I'm not sure if there is a point in committing dist files. Maybe those should be gitignored?

**Comment by kazupon** [comment]
Hmm, It's strang ... 🤔
