### ISSUE TITLE
Edit vue-i18n-locales.generated.js : versionning or reload

### ISSUE THREAD

**Issue by mawieutc** [kazupon/vue-i18n#856]
Hello,

I would am using vue-i18n: 
I edit the file vue-i18n-locales.generated.js itself with all translations, and I would like to version it so that it could be edited in an admin panel.
In vue-i18n-generator, I can see these two line:
    'jsFile' => '/resources/assets/js/vue-i18n-locales.generated.js',

So I am wondering if it would be possible to version this file, so that each change would create a new version and we could get the last version of the file.

If any other suggestion so that I don't need to run npm run prod each time, let me know :)
Thank you

**Comment by exoego** [comment]
How do you generate `vue-i18n-locales.generated.js` ?

**Comment by kazupon** [comment]
close due to in-activity
