### ISSUE TITLE
Hello, I am setting up i18n in same way but getting warnings for the same, but its translating all the words though. Can anyone help me with this.

### ISSUE THREAD

**Issue by richirich999** [kazupon/vue-i18n#862]
Hello, I am setting up i18n in same way but getting warnings for the same, but its translating all the words though. Can anyone help me with this.

**Warnings:** "Value of key 'No list available' is not a string!
Cannot translate the value of keypath 'No list available'. Use the value of keypath as default."

**Comment by GoatFreezy** [comment]
Same here, but not on everypage tho

**Comment by exoego** [comment]
Could you provide minimum repron on JSFiddle/JSBin/Codepen or any tool ?
You could start with [this JSFiddle template](https://jsfiddle.net/kazupon/rn724baz/3/) that already includes the latest version of Vue & Vue-i18n.

**Comment by kazupon** [comment]
close due to in-activity
