### ISSUE TITLE
Tip to include externals...

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#87]
If you would like to include a long external html file in vue.js, instead of providing a string, you could put your regular html file in a file ``mylongtext.en.html``  and for example  ``mylongtext.nl.html``.

And then include the files like this:
```html
  <div v-html="require('./mylongtext' + lang + '.html')"></div>
```
The ``lang`` variabele I set like so:
```js
export default {
  data: function () {
    return {
      lang: Vue.config.lang
    }
  }
}
```

I am starting to like this plugin more and more. Excellent for short text fields, versatile enough for the long stuff !

**Comment by kazupon** [comment]
You can set the long external html with `require` in the following:

```js
const en = {
  foo: require('mylongtext.en.html') // you need to bundler (webpack or browserify)
}
```

**Comment by tvld** [comment]
@kazupon Might be an idea to accommodate in the api?  So that for example we can insert a complete html file like so:
```html
<div v-html="$t({ html_file: './lang/mylongtext' })"></div>
```
This would automatically include ``./lang/mylongtext.en.html`` or ``./lang/mylongtext.nl.txt``  .. nice ;-)
