### ISSUE TITLE
New tool for 3rd party tooling in documentation

### ISSUE THREAD

**Issue by danigayosog** [kazupon/vue-i18n#874]
I've found a plugin https://github.com/nyavro/i18nPlugin compatible with vue-i18n for Intellij that it's not listed in the documentation (in section https://kazupon.github.io/vue-i18n/guide/tooling.html#_3rd-party-tooling). This plugin it's a great help for improve productivity.
Could you add a link to this tool in the documentation?

P.S. I’m not the owner of the plugin, only a user

**Comment by exoego** [comment]
Pull request is welcome !!
