### ISSUE TITLE
Does not work inside vuex state.js

### ISSUE THREAD

**Issue by ssuess** [kazupon/vue-i18n#885]
I have a menu that I would like to store in vuex (rather than in the top level component). This menu has titles that are translated using vue-i18n. Inside the component, everything works great, but when I move my menu to my vuex store (inside state.js), my app refuses to load and I get errors that are all similar to:

`state.js?6b3c:16 Uncaught TypeError: src_boot_i18n__WEBPACK_IMPORTED_MODULE_0__.default.t is not a function`

my state.js file looks like this (and variations of it):

```
// state.js
import i18n from 'src/boot/i18n'
export default {
  storeVersion: '1',
  version: {
    version: 0,
    date: 0,
    PWA: 0
  },
  menu: [
    {
      active: 'dashboard',
      main: [
        {
          id: 'dashboard',
          parent: null,
          title: this.$i18n.t('dashboard'),
          subtitle: this.$i18n.t('dashboardSub'),
          url: '/dashboard'
        }, // etc, etc
```
I have tried replacing translatable strings like `this.$i18n.t('dashboard')` with:

`i18n.t('dashboard')`
`$i18n.t('dashboard')`
`app.i18n.t('dashboard')`
`i18n.$t('dashboard')`
`$i18n.$t('dashboard')`
`app.i18n.$t('dashboard')`
`i18n.tc('dashboard')`
`$i18n.tc('dashboard')`
`app.i18n.tc('dashboard')`

and so on, but I keep getting variations on the error above telling me that t (or tc, or whatever) is not a function. Any idea if this is even possible to do? vue-i18n is installed and working flawlessly in all of my components, I just wanted to move this one global menu item to the store, but it seems I am missing something fundamental. Any advice appreciated. Thanks!

in case you are wondering, my boot file looks like this:

```
import VueI18n from 'vue-i18n'
import messages from 'src/i18n'

let i18n

export default ({ app, Vue }) => {
  Vue.use(VueI18n)

  // Set i18n instance on app
  app.i18n = new VueI18n({
    locale: 'en-gb',
    fallbackLocale: 'en-gb',
    silentFallbackWarn: true,
    silentTranslationWarn: true,
    // enableInSFC: true,
    messages
  })
  i18n = app.i18n
}

export { i18n }
```

**Comment by ssuess** [comment]
Interestingly, (and although it does not throw an error) when I `console.log(i18n)` I get `undefined`

**Comment by ssuess** [comment]
If i18n is not yet initialized and that is why I get undefined, does this imply that translation commands can't be stored in vuex? Is no one doing this?

**Comment by ssuess** [comment]
Anybody home?

**Comment by exoego** [comment]
I am not using vue-i18n insite vuex, so I am not sure, but this blog may help.
https://www.guipss.com/posts/vuex_and_vue_i18n/

**Comment by ssuess** [comment]
Thanks, but I have seen that link, and it only deals with writing information into vuex that is already translated. What I am trying to do is store translation functions themselves inside vuex so that they will be automatically translated. See my example above for what I am trying to store in my `state.js` file, it is all there.

**Comment by kazupon** [comment]
This.$i18n in state.js will not work.
Because the properties and methods injected by Vue I18n prefixed with $ are for components.
vuex can also work outside the context of a component in some cases. Therefore, it may not work.
