### ISSUE TITLE
Can't use in jsfiddle.net

### ISSUE THREAD

**Issue by glittle** [kazupon/vue-i18n#886]
### vue & vue-i18n version
Vue: 2.6.11
Vue-i18n: 8.17.7

### Reproduction Link
https://jsfiddle.net/glittle/tys17Lvu/1/

### Steps to reproduce
1) Go to jsfiddle.net and start with a Vue boilerplate.
2) Add a resource pointing to https://unpkg.com/vue-i18n/dist/vue-i18n.js
3) Add   {{ $t('test') }}   in the HTML panel.
4) Run the fiddle.

### What is Expected?
The word "test" should appear in the output.

### What is actually happening?
The Console shows these errors:
Property or method "$t" is not defined on the instance but referenced during render. 
Error in render: "TypeError: $t is not a function"

**Comment by kazupon** [comment]
Thank you for your feedback!

In about `Vue boilerplate` of jsfiddle, Unfortunatly I don't know how to load Vue.js resource. 😞 
vue-i18n it works with together loading Vue.js resource.
here the example:
https://jsfiddle.net/kazupon/rn724baz/3/

**Comment by glittle** [comment]
Thank you. I was missing the step of manually creating an instance of VueI18n.
Sorry for taking your time.
