### ISSUE TITLE
Allow extending vue-i18n instance created when handling custom blocks

### ISSUE THREAD

**Issue by rchl** [kazupon/vue-i18n#887]
### vue & vue-i18n version
8.17.3

For `nuxt-i18n`, I'm extending `i18n` object with a couple of properties (one of them being `locales`). This breaks when there is a custom `i18n` block in the vue file due to the code that creates a new instance of `vue-i18n` and copies the known properties to it [1]. That obviously doesn't include my custom properties so things break.

To fix that, I propose the following:
 - allow user (in this case `nuxt-i18n`) to add a hook/listener for when a new instance is created and being extended
 - from the linked code, call that listener with both original and the newly created instance so that user code can extend it further.

### Related links:
[1] https://github.com/kazupon/vue-i18n/blob/f42e81f65a88eeeccc311b970d2d4fd4181712ed/src/mixin.js#L33-L42
nuxt-i18n issue: https://github.com/nuxt-community/nuxt-i18n/issues/557

**Comment by kazupon** [comment]
Thank you for your feedback!

> from the linked code, call that listener with both original and the newly created instance so that user code can extend it further.

if you have the your proposal example, Could you provide it to us please ? 🙏

**Comment by rchl** [comment]
Did you mean the actual code with the proposed implementation or a more formal text proposal?
I can work on the code for this. It should be really simple.

**Comment by kazupon** [comment]
> Did you mean the actual code with the proposed implementation or a more formal text proposal?

I mean that is actual code.
