### ISSUE TITLE
Vue-cli-plugin-i18n/index.js throws undefined error

### ISSUE THREAD

**Issue by LarsF1** [kazupon/vue-i18n#889]
Okay so I had an existing Vue-Application because we've got a school project to work on. I then implemented Multilingualism to my Application with Vue-i18n and the following guide: (Just the 
i18n part, with installing, editing the router etc.) 
https://webdeasy.de/vue-i18n-app/

It worked all fine until I tried to start my application on the next day. I'm suddenly getting the following error:

```
TypeError: Cannot read property 'i18n' of undefined
    at module.exports (..\node_modules\vue-cli-plugin-i18n\index.js:4:49)
    at ..\node_modules\@vue\cli-service\lib\Service.js:93:7
    at Array.forEach (<anonymous>)
    at Service.init (..\node_modules\@vue\cli-service\lib\Service.js:91:18)
    at Service.run (..\node_modules\@vue\cli-service\lib\Service.js:230:10)
    at Object.<anonymous> (..\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
```

It appears, that the error is in the index.js (vue-cli-plugin-i18n) that looks like this:
```
const debug = require('debug')('vue-cli-plugin-i18n:service')

module.exports = (api, options) => {
  const { enableInSFC } = options.pluginOptions.i18n
  debug('options', options)

  api.chainWebpack(webpackConfig => {
    debug('chainWebpack called')

    if (enableInSFC) {
      webpackConfig.module
        .rule('i18n')
          .resourceQuery(/blockType=i18n/)
          .type('javascript/auto')
          .use('i18n')
            .loader('@intlify/vue-i18n-loader')
            .end()
          .end()
    }
  })

  const report = require('./report')
  api.registerCommand('i18n:report', report.options, args => report.service(args, api))
}
```

if I comment out some code, so the file looks like this:

```
const debug = require('debug')('vue-cli-plugin-i18n:service')

module.exports = (api, options) => {
  // const { enableInSFC } = options.pluginOptions.i18n
  debug('options', options)

  api.chainWebpack(webpackConfig => {
    debug('chainWebpack called')

    // if (enableInSFC) {
    //   webpackConfig.module
    //     .rule('i18n')
    //       .resourceQuery(/blockType=i18n/)
    //       .type('javascript/auto')
    //       .use('i18n')
    //         .loader('@intlify/vue-i18n-loader')
    //         .end()
    //       .end()
    // }
  })

  const report = require('./report')
  api.registerCommand('i18n:report', report.options, args => report.service(args, api))
}
```

it works all fine, even the translations are still working, I can translate my whole application. Since the code, that I commented out above "resets" itself everytime I Uûse either
`npm install` or `npm install vue-i18n` my solution isn't really good.. 

Did I do something wrong? Do you need any more information or did anyone else have this problem?

If you need more code, please let me know!

**Comment by LarsF1** [comment]
okay, so after I uninstalled i18n and commented out the usages in my files (for example I created an instance in the main.js and commented that out etc.) and added with
`vue add i18n`
it seems to work.. I'm sorry for the trouble. I guess this can be closed? It works for me now.

**Comment by exoego** [comment]
I am sorry, but the issue and how to reproduce is unclear for me.
Closing as resolved.
Feel free to reopen if you still have same error and a minimum repro.
