### ISSUE TITLE
How to change the language of text in data

### ISSUE THREAD

**Issue by nincorada** [kazupon/vue-i18n#891]
I have a custom dropdown that i pass array to with objects inside.
The needed are aSortOptions and oSelectedSortOtpions
![image](https://user-images.githubusercontent.com/47456728/82890890-7b81f980-9f7f-11ea-9584-d2cf10b97531.png)

The problem is when i change the locale, the selected sort option does not change the text to the respective language

![thisisaproblem](https://user-images.githubusercontent.com/47456728/82891127-d1ef3800-9f7f-11ea-8e6a-eb982f03e0b5.gif)

**Comment by exoego** [comment]
Could you respect the issue template ?
Otherwise maintainers and contributors can not reproduce issue and investigate .

**Comment by kazupon** [comment]
close due to in-acitivty
