### ISSUE TITLE
integrate vue-i18n in vue-beautiful-chat

### ISSUE THREAD

**Issue by arabakevin** [kazupon/vue-i18n#912]
Hi,
I try to integrate (vue-i18n) at this library (https://github.com/mattmezza/vue-beautiful-chat) in src folder but I have some integration problems so, in this file ./i18n/translations.js => we have the translations in src/index.js
so,
in this file ./i18n/translations.js => we have the translations
in src/index.js
```
import Launcher from './Launcher.vue'
import VTooltip from 'v-tooltip'
import VueI18n from 'vue-i18n'
import messages from './i18n/translations.js'

const defaultComponentName = 'beautiful-chat'

const Plugin = {
  install (Vue, options = {}) {
    /**
     * Makes sure that plugin can be installed only once
     */
    if (this.installed) {
      return
    }

    Vue.use(VueI18n)
    const locale = navigator.language
    const i18n = new VueI18n({
      fallbackLocale: 'fr',
      locale: locale,
      messages
    })

    this.installed = true
    this.event = new Vue({i18n})
    this.dynamicContainer = null
    this.componentName = options.componentName || defaultComponentName
    /**
     * Plugin API
     */
    Vue.prototype.$chat = {
      _setDynamicContainer (dynamicContainer) {
        Plugin.dynamicContainer = dynamicContainer
      }
    }
    /**
     * Sets custom component name (if provided)
     */
    Vue.component(this.componentName, Launcher)
    Vue.use(VTooltip)
    Vue.use(VueI18n)
  }
}
export default Plugin
```
And i start to change in the file "src/Launcher.vue" "you" in the header of the chat
```
  computed: {
    chatWindowTitle() {
      if (this.title !== '') {
        return this.title
      }
      if (this.participants.length === 0) {
        return $t('participant.you_only')
      } else if (this.participants.length > 1) {
        return $t('participant.you_and_participants', { participant: 'this.participants[0].name' })
      } else {
        return 'You & ' + this.participants[0].name
      }
    }
  },
```
but i receive this error

![Capture d’écran 2020-06-02 à 21 46 25](https://user-images.githubusercontent.com/16837548/83562844-85c16c00-a51a-11ea-8088-36fa318e8609.png)

i have try few others methods as `this.$i18n` and others.
Can you help me please ?
Thanks a lot.

**Comment by kazupon** [comment]
In this case, I have a VueI18n instance set up in the Vue instance set to `this.event`, 
but I seem that Vue instance used in an application like `Launcher.vue` has the VueI18n instance does not set.

**Comment by arabakevin** [comment]
thanks for your answer but can you give me more details or example ?

**Comment by kazupon** [comment]
close due to in-activity
