### ISSUE TITLE
Complete API reference

### ISSUE THREAD

**Issue by FrankyBoy** [kazupon/vue-i18n#915]
Hi!

It seems that right now there only are "guides" on how to do various things. However I think it would be hugely helpful if there was some actual API reference that contains all the methods/properties/etc that vue-i18n offers (i.e. all the things that $t, $tc, $i18n, ... offer). 

Thanks :)

**Comment by AleksandrSl** [comment]
Hi, have you seen this?
https://kazupon.github.io/vue-i18n/api/

**Comment by exoego** [comment]
As @AleksandrSl pointed out, docs site have API reference.

Maybe the navigation to API reference is hard to find ???
![image](https://user-images.githubusercontent.com/127635/84035607-f5ca6900-a9d6-11ea-8589-679d1c31893d.png)

**Comment by FrankyBoy** [comment]
That ... is very well hidden. Thanks for pointing that out. 

Could this be made more visible somehow in the guide, as all links point to that? Ideally in the sidebar, same like you got the "Legacy" section.

**Comment by AleksandrSl** [comment]
On the one hand it's reaaly not so easy to find, from the other hand it repeats the same behaviour as [Vue](https://vuejs.org) docs
![image](https://user-images.githubusercontent.com/15820496/84058074-5e0e5000-a9c1-11ea-9a13-5b0f20a34a28.png)

**Comment by rchl** [comment]
But `Vue` has a lot more items that they have to fit somewhere.
For `nuxt-i18n` I've exposed those in the root: https://nuxt-community.github.io/nuxt-i18n/

**Comment by AleksandrSl** [comment]
@rchl looks perfect to me, and [vuex](https://vuex.vuejs.org) has the same solution

**Comment by exoego** [comment]
PR to improve navigation is welcome 🙏

**Comment by AleksandrSl** [comment]
I will try to do it, if nobody minds

**Comment by AleksandrSl** [comment]
Can be closed I think

**Comment by exoego** [comment]
Thanks !!
Closing as resolved in #920 and the changes were deployed.
