### ISSUE TITLE
custom  default language load fail messages

### ISSUE THREAD

**Issue by mygaochunming** [kazupon/vue-i18n#92]
hi , thanks for the great plugin and i love it very much.

when i use the plugin ,sometimes it use the default keypath when the keypath does not exist or some other reason. it is clear for the developers but not friendly enough for the user i think.

may be there is a way for me to give a default fail message like 'language loaded failed' instead of 'XXX.XXXX.XXX.XXX'

and thank you again.

**Comment by kazupon** [comment]
thank you for your feedback.
I'll try to improve later.

**Comment by mygaochunming** [comment]
thanks a lot :)
