### ISSUE TITLE
$t not dispalying text, someone please advise..

### ISSUE THREAD

**Issue by Hajakutbudeen** [kazupon/vue-i18n#931]
ill get json file but $t not display text please advise

js:
const i18n = new VueI18n({
locale: 'en', // set locale
fallbacklocale: 'en',
messages: {
'en': axios.get('app/assets/vue/components/lang/en.json').then((res) => {
return res.data
}),
'ar': axios.get('app/assets/vue/components/lang/ar.json').then((res) => {
return res.data
}),
}
})

php:
{{ $t("welcome") }}

en.json:
{
"welcome": "Welcome"
}

ar.json:
{
"welcome": "...."
}

**Comment by exoego** [comment]
I think `i18n.messages` can not handle Promise value returned by `axios.get`.

You need construct `i18n` with empty messages first, then update  `i18.messages` in the callbacks of Promise.
Example of lazy loading using axios is here:
https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

**Comment by Hajakutbudeen** [comment]
> I think `i18n.messages` can not handle Promise value returned by `axios.get`.
> 
> You need construct `i18n` with empty messages first, then update `i18.messages` in the callbacks of Promise.
> Example of lazy loading using axios is here:
> https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

dear exoego,  ill try like this this is also not working. 

let eng;
let arb;

const i18n = new VueI18n({
  locale: 'en', // set locale
  fallbacklocale: 'en',
  messages
})

async function getJsonData(){
  await axios.get('app/assets/vue/components/lang/en.json').then((res) => {
    //console.log('DATA',res.data); 
    eng = res.data;
    //console.log(eng)
  });
  await axios.get('app/assets/vue/components/lang/ar.json').then((res) => {
    //console.log('DATA',res.data); 
    arb =  res.data;
    //console.log(arb)
  });
  loadLocalMessage()
}

function loadLocalMessage(){
  const messages = {
    en: eng,
    ar: arb,
  }
  console.log('TEST',messages);
  return JSON.stringify(messages);
}

**Comment by exoego** [comment]
It does not work because i18n is constructed with undefined eng/arb, and it defensively clone the values, so updating eng/arg wont affect i18n.messages.

I think i18n.message should be explicitly updated in callback function as so in example.

**Comment by Hajakutbudeen** [comment]
> It does not work because i18n is constructed with undefined eng/arb, and it defensively clone the values, so updating eng/arg wont affect i18n.messages.
> 
> I think i18n.message should be explicitly updated in callback function as so in example.

ok exoego thanks for your kind reply, ill try to fix if you know any example please let me know. Thank you

**Comment by Hajakutbudeen** [comment]
Dear Exoego, ill fix that, my code will help someone so ill post here, Thanks you Exoego 

let langData = {
  en:{},
  ar:{},
}

const i18n = new VueI18n({
  locale: 'en', // set locale
  fallbacklocale: 'en',
  messages: langData
})

$(document).ready(async function(){
  const messages = {
    en: await axios.get('app/assets/vue/components/lang/en.json').then(res => {
      return res.data;
    }),
    ar: await axios.get('app/assets/vue/components/lang/ar.json').then(res => {
      return res.data;
    }),
  }
  langData.en = messages.en;
  langData.ar = messages.ar;
})

**Comment by exoego** [comment]
Thanks for posting the code example that resolve the issue :+1:
I hope it help others facing same issue.

So, let me close this issue as resolved.
Feel free to reopen if the issue still remains!
