### ISSUE TITLE
Dynamic words

### ISSUE THREAD

**Issue by navidshad** [kazupon/vue-i18n#932]
Hi, I want to define some calibration word in local strings, then replace them with new words when I call the strings. here is an example.

```js
// en.json
{
 "message":"this is your account number [number]"
}
```

```html
<!-- vue component -->
<span>{{ $t('message', {number: 41234} ) }}</span>

<!-- result-->
<!-- this is your account number 41234 -->
```

**Comment by exoego** [comment]
I am afraid to say that what you want to try is a bit unclear for me.

If you want to replace word(s) in message, vue-i18n offers named formatting.
https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting
Does this help?
