### ISSUE TITLE
[Feature request] Add i18n component to vetur autocomplete

### ISSUE THREAD

**Issue by phiter** [kazupon/vue-i18n#941]
Hi!

I have a feature request which is very simple to implement, I might even add a PR for this.

Vetur has a system to add components and attributes to its autocomplete, it's quite simple to add it.

I think vue-i18n users would benefit from having `<i18n>` component show up in autocomplete, as well as its attributes.

Here's the documentation for this functionality: https://vuejs.github.io/vetur/framework.html#custom-tags-attributes

**Comment by exoego** [comment]
Thanks !!
This sounds great DX enhancement for VS code users.

> I might even add a PR for this.

Awaiting for that 🙏
