### ISSUE TITLE
i18n in Vue Instance

### ISSUE THREAD

**Issue by Hajakutbudeen** [kazupon/vue-i18n#964]
### vue & vue-i18n version
ex: 2.1.0, 5.0

### What is Expected?

try to change vue-chartjs label text

### What is actually happening?

I am trying to change vue-chartjs label using i18n, i did using computed.

Instance: 
  i18n,
  name: 'dashboard',
  el: '#dashboard',
  data: {
       revenues_vs_expenses:{
       getRevenuesExpensesData:{
       datasets:[{
              label: '',
       }]
  }}

Computed:
 load(){
        this.$set(this.revenues_vs_expenses.getRevenuesExpensesData.datasets, 'label', i18n.t('revenues'));
 }

its update value but didn't display

**Comment by exoego** [comment]
Could you provide repro using JSFiddle or similar? 

> - It is recommended that you make a JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with [this template](https://jsfiddle.net/kazupon/rn724baz/3/) that already includes the latest version of Vue & Vue-i18n.

**Comment by kazupon** [comment]
close due to in-activity
