### ISSUE TITLE
DateTime localization ($d) does not resolve path in key

### ISSUE THREAD

**Issue by dlindenkreuz** [kazupon/vue-i18n#970]
### vue & vue-i18n version
2.6.11, 8.20.0

### Reproduction Link
https://codesandbox.io/s/elegant-dan-dh37b?file=/src/App.vue

### Steps to reproduce
See codesandbox above

### What is Expected?
`$d(value, key)` should behave like `$t(key)`. `$t` resolves `key` as path (example: `a.b.c`) and allows retrieving nested localizations intuitively. Nesting `dateTimeFormats` should be possible just like `messages`.

### What is actually happening?
`$d` does not resolve nested paths in the `key` parameter. Passing a path to `$d` with multiple segments (such as `datePicker.header`) does not yield any output.

This currently requires that `dateTimeFormats` must not be nested, while nesting `messages` is fine.

**Comment by kazupon** [comment]
Thank you for reporting!
sorry, my lately response.

datetimeFormats` and `numberFormats`, like the `messages` used in `$t`, are not allowed to use keys in the hierarchy.
This is expected behaivor.
https://github.com/kazupon/vue-i18n/blob/b3e1895c2cd1c338f41bacc7e7837210d576d468/types/index.d.ts#L42

Thanks!
