### ISSUE TITLE
single file component render less than sign

### ISSUE THREAD

**Issue by delcon** [kazupon/vue-i18n#977]
### vue & vue-i18n version
ex: 2.1.0, 5.0

### Steps to reproduce
in you component:
```
<i18n>
{
   "en" : {
         "key": "value should be < 25"
}
</i18n>
```
### What is Expected?
render:  "value should be < 25"

### What is actually happening?
eslint error "invalid-first-character-of-tag"
disabling eslint gives a webpack error

**Comment by matthew-white** [comment]
I've encountered this ESLint error as well. To avoid the ESLint error, I've been using `\u003c` instead of `<`. For example:

```
{
  "key": "value should be \u003c 25"
}
```

I'm not sure, but I think this issue is also related: https://github.com/intlify/eslint-plugin-vue-i18n/issues/107

**Comment by exoego** [comment]
Let me close this issue as out-of-scope.
This sounds more like issue in eslint and its plugin.

As @matthew-white described, there is an workaround and open issues in eslint ecosystem.

**Comment by delcon** [comment]
@exoego The error goes beyond eslint, disabling eslint gives a webpack error.
