### ISSUE TITLE
Changing fonts on language change isn't possible.

### ISSUE THREAD

**Issue by onurusluca** [kazupon/vue-i18n#978]
This is not an issue but a request. I can't change fonts based on the language which is very impractical considering for example Latin fonts and Japanese fonts are different.
Is there a way to do this? I have been searching for hours. 
Thanks!

**Comment by exoego** [comment]
How about adding `lang-(en|ja)` class to `body` element on locale change, and changes fonts per such classes on CSS ? 

I think this may be a common UI issue, but is off-topic for vue-i18n.

**Comment by exoego** [comment]
Let me close this issue as out-of-scope of this repo.
You may find help in other Vue forums.
Feel free to leave any ideas on how to change fonts based on the languages.
