### ISSUE TITLE
[feature request] Add new translation to an already loaded language

### ISSUE THREAD

**Issue by xmorell** [kazupon/vue-i18n#981]
I think it would be good to have some way to add a new translation via JS

something like:

i18n.addTranslation("en", "code-of-translation", "Text of the translation in English");

That would allow to have labels in a .json file and also in the database and only load the ones from the database if those are required depending on his navigation on the webpage.

**Comment by kazupon** [comment]
you can use `mergeLocaleMessage`.
https://kazupon.github.io/vue-i18n/api/#mergelocalemessage-locale-message
