### ISSUE TITLE
When does vue-i18n support vue3.0.x(vue-next)?

### ISSUE THREAD

**Issue by abelit** [kazupon/vue-i18n#982]
### vue & vue-i18n version
ex: 2.1.0, 5.0

**Comment by exoego** [comment]
Stay tuned.
Next major version of vu-i18n is developed in https://github.com/intlify/vue-i18n-next

**Comment by abelit** [comment]
> Stay tuned.
> Next major version of vu-i18n is developed in https://github.com/intlify/vue-i18n-next

Thanks!
